### ISSUE TITLE
Seg fault with logic QF_LRA

### ISSUE THREAD

**Issue by franck44** [Z3Prover/z3#1021]
Hi,
I am running z3 4.5.1 (master from this repo), compiled with clang OSX and gcc on Ubuntu.

When I run the program z3-seg-fault.smt2 below, I get a seg fault:

```
(set-option :print-success true)
(set-logic QF_LRA)
(check-sat)
(exit)
```

```
franck:~/tmp $ z3 -smt2 z3-seg-fault.smt2
success
success
Segmentation fault: 11
```

I just upgraded from z3 4.4.2 and in 4.4.2 there was no seg fault for the same program.
The problem manifests on the version compiled for OSX with clang and on Linux with gcc.

**Comment by NikolajBjorner** [comment]
So far I haven't been able to repro it. The QF_LRA changed significantly early last week.

**Comment by NikolajBjorner** [comment]
We have tried on Windows, Ubuntu gcc, and OSX. No repro so far.

**Comment by franck44** [comment]
thanks Nikolaj for looking into this issue.
I have updated my devtools on OSX, fetched the latest z3 master, and re-compiled.
I still have the same issue.
If I set another logic the issue does not manifest.

If I am the only one to experience this problem, and if you cannot repro it, I guess there is not much to investigate.

FYI here is the clang version I am running on OSX:
```
z3/build [master]$ clang++ --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Note that the same problem manifested on a Linux (VM) machine, Ubuntu, running gcc (this machine is a minion I am using for CI of a project of mine).  I need to change my build setup to collect more information about the version of gcc and the configuration of the machine.

As a fix, I am now using a logic which is higher in the hierarchy (there is no seg fault for any of the logic above QF_LRA. [SMTLIB hierarchy](http://smtlib.cs.uiowa.edu/logics.shtml)

Thanks again for your help and if manage to narrow down the problem I'll update this thread.

**Comment by delcypher** [comment]
@franck44 
To help the developers track this down it would help if you provided a backtrace (for all threads) when the crash occurs. You can do this by running `z3` under a debugger.

For example

```
gdb --args /path/to/z3 your_file.smt2
```

If you're using gdb as your debugger see [this](http://stackoverflow.com/questions/18391808/getting-the-backtrace-for-all-the-threads-in-gdb). If you're using lldb as your debugger see [this](https://lldb.llvm.org/lldb-gdb.html) (I think the command is `bt all`). Note with gdb there is [convenient functionality to log all output to a file](https://sourceware.org/gdb/onlinedocs/gdb/Logging-Output.html).

If the bug is not obvious you may wish to compile Z3 with AddressSanitizer to look for memory access related bugs.

**Comment by delcypher** [comment]
@franck44 Another thing. You didn't mention how you built Z3. Did you use a fresh build tree? The python/Makefile build system has some bugs in it which means that it sometimes doesn't rebuild things properly.

**Comment by jamesbornholt** [comment]
I was able to reproduce this, on a fresh repo clone, on a Mac (10.12.4, Xcode 8.3, Apple LLVM version 8.1.0 (clang-802.0.42)). I also have a (potential?) fix.

Here's a backtrace from LLDB:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x0000000100619b41 z3`lean::lar_solver::lar_solver() + 49
    frame #1: 0x0000000100619865 z3`smt::theory_lra::imp::init_solver() + 85
    frame #2: 0x000000010042e59e z3`smt::context::register_plugin(smt::theory*) + 94
    frame #3: 0x000000010047d2f1 z3`smt::setup::setup_QF_LRA(static_features const&) + 865
    frame #4: 0x000000010047a8eb z3`smt::setup::setup_auto_config() + 1531
    frame #5: 0x0000000100438157 z3`smt::context::setup_context(bool) + 55
    frame #6: 0x0000000100437b39 z3`smt::context::setup_and_check(bool) + 137
    frame #7: 0x00000001003b6069 z3`smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) + 937
    frame #8: 0x0000000100a07d13 z3`exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) + 67
    frame #9: 0x0000000100a07fb2 z3`check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 290
    frame #10: 0x00000001008e474e z3`tactic2solver::check_sat_core(unsigned int, expr* const*) + 638
    frame #11: 0x00000001008e3bf5 z3`solver_na2as::check_sat(unsigned int, expr* const*) + 133
    frame #12: 0x00000001008dd4b0 z3`combined_solver::check_sat(unsigned int, expr* const*) + 944
    frame #13: 0x000000010082c3fa z3`cmd_context::check_sat(unsigned int, expr* const*) + 490
    frame #14: 0x0000000100802ca1 z3`smt2::parser::parse_check_sat() + 433
    frame #15: 0x000000010080001d z3`smt2::parser::operator()() + 109
    frame #16: 0x00000001007fff65 z3`parse_smt2_commands(cmd_context&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool, params_ref const&, char const*) + 69
    frame #17: 0x000000010001adda z3`read_smtlib2_commands(char const*) + 586
    frame #18: 0x0000000100017ff9 z3`main + 665
    frame #19: 0x00007fffaa6f1235 libdyld.dylib`start + 1
    frame #20: 0x00007fffaa6f1235 libdyld.dylib`start + 1
```

and the (start of the) disassembly:

```
z3`lean::lar_solver::lar_solver:
    0x100619b10 <+0>:    pushq  %rbp
    0x100619b11 <+1>:    pushq  %r15
    0x100619b13 <+3>:    pushq  %r14
    0x100619b15 <+5>:    pushq  %r13
    0x100619b17 <+7>:    pushq  %r12
    0x100619b19 <+9>:    pushq  %rbx
    0x100619b1a <+10>:   subq   $0x38, %rsp
    0x100619b1e <+14>:   movq   %rdi, %rbx
    0x100619b21 <+17>:   leaq   0x8(%rbx), %r14
    0x100619b25 <+21>:   leaq   0xa8f4e4(%rip), %rax      ; vtable for lean::lp_settings::default_lp_resource_limit + 16
    0x100619b2c <+28>:   movd   %rax, %xmm0
    0x100619b31 <+33>:   leaq   0xa9cbe0(%rip), %rax      ; vtable for lean::lar_solver + 16
    0x100619b38 <+40>:   movd   %rax, %xmm1
    0x100619b3d <+45>:   punpcklqdq %xmm0, %xmm1              ; xmm1 = xmm1[0],xmm0[0] 
->  0x100619b41 <+49>:   movdqa %xmm1, (%rbx)
    0x100619b45 <+53>:   movq   %r14, 0x10(%rbx)
    0x100619b49 <+57>:   callq  0x100d11f30               ; lean::get_millisecond_count()
```

and lldb says that `rbx = 0x00000001018c8e08`.

It looks like the `this` allocation is misaligned; it requires 16-byte alignment on the Mac because the `m_column_type_function` field (a `std::function`) is 16-byte aligned. The compiler exploited this to generate `movdqa` instead of `movdqu` (which is what my Linux box compiles). UBSan also flagged this.

I couldn't find any uses of `m_column_type_function`, so to test I simply removed it and its initialization. This example no longer crashes, and now `std::alignment_of<lean::lar_solver>::value` reports 8-byte alignment on the Mac too. So removing that field is a potential fix.

**Comment by NikolajBjorner** [comment]
at least the unused field has to go away.

**Comment by jamesbornholt** [comment]
4069e76 fixes the segfault for me.

**Comment by franck44** [comment]
yes this commit fixes the problem for me too.
Thanks James and Nikolaj.

**Comment by NikolajBjorner** [comment]
Thank you both for reporting with a simple repro and figuring out what was going on.
