### ISSUE TITLE
Unknown expression when using tseitin-cnf Tactic

### ISSUE THREAD

**Issue by LostBenjamin** [Z3Prover/z3#1023]
I am using Z3py to convert some expression to Conjunctive Norm Form and below is my code:
```python
from z3 import *

g = Goal()
path = Function('path', StringSort(), StringSort(), BoolSort())
edge = Function('edge', StringSort(), StringSort(), BoolSort())
oneway = Function('oneway', StringSort(), StringSort(), BoolSort())
_var0_edge = String('_var0_edge')
_var1_edge = String('_var1_edge')
_var0_path = String('_var0_path')
_var1_path = String('_var1_path')
g.add(And(oneway(StringVal("R1"), StringVal("R2")), Not(edge(StringVal("R1"), StringVal("R2"))), Not(And(Or(Not(And(_var0_path == StringVal("R1"), _var1_path == StringVal("R2"))), path(_var0_path, _var1_path)), Or(And(_var0_path == StringVal("R1"), _var1_path == StringVal("R2")), Not(path(_var0_path, _var1_path)))))))
describe_tactics()
t = Tactic('tseitin-cnf')
print(t(g))
```

I tested the code on macOS 10.12.4 and Ubuntu 14.04. The results of `print(t(g))` are the same:
```
[[oneway("R1", "R2"),
  Not(edge("R1", "R2")),
  Or(_var0_path == "R1", k!0),
  Or(_var1_path == "R2", k!0),
  Or(Not(_var0_path == "R1"),
     Not(_var1_path == "R2"),
     Not(k!0)),
  Or(Not(path(_var0_path, _var1_path)), k!0),
  Or(_var0_path == "R1", path(_var0_path, _var1_path)),
  Or(_var1_path == "R2", path(_var0_path, _var1_path))]]
```

The are several `k!0`s in the result. Since I am a beginner of Z3py, I don't know where the `k!0`s comes from. Did I misuse the API or is it a bug?

**Comment by krypt-n** [comment]
`k!0` is an auxillary variable that was introduced by the `tseitin-cnf` tactic. Introducing new variables during conversion to CNF results in significantly shorter CNF formulas and the tactic is making use of that.

**Comment by LostBenjamin** [comment]
Thanks for your info, krypt-n! Another question is how to recover the original CNF form (i.e. the none without the auxillary variables)?

**Comment by NikolajBjorner** [comment]
There is no tactic to produce a CNF without auxiliary variables. It is generally exponential in size of the original formula so not a good idea and therefore not part of Z3's tactics.

**Comment by LostBenjamin** [comment]
Or is there a way to find what expression the auxiliary variables are?

**Comment by krypt-n** [comment]
I am not exactly sure what you are asking for. The formula `tseitin-cnf` generates for you restricts `k!0` to be eqal to `Not(And(_var0_path == "R1", _var1_path == "R2"))`, but that's contained in the formula (clauses 3, 4 and 5). You generally don't need to know what the auxillary variables are used for.

**Comment by LostBenjamin** [comment]
I want to perform conversion for the predicates in CNF (e.g. after converting the expression in the example to CNF, I want to convert `path` predicate into another predicate). If I don't know whether `k!0` contains `path` predicate, it is unlikely to perform the conversion.

**Comment by krypt-n** [comment]
`k!0` does not contain anything (in the subexpression sense). All information about it is in the CNF formula. Substituting the predicates (that were treated as black boxes by the tseitin transformation), does not affect `k!0` in any way.

**Comment by LostBenjamin** [comment]
Yes. In this case, `k!0` does not contain anything. How about the general case?

**Comment by arey0pushpa** [comment]
Hi @krypt-n @NikolajBjorner . Lets assume we start from a formula [fml] not in cnf form. If i'm correct the new formula [Exists_k!0 (new_cnf_fml_with_k!0)]  will be equivalent to that of old formula [fml]?  My question is this new variable can be treated as existence quantifier on the leftmost side ? Or is there other way to state the fact (cause there might be already a few quantifiers present at leftmost side in the initial formula).

**Comment by krypt-n** [comment]
I don't know how the Z3 implementation of tseitin encoding deals with first-order logic. The usual definition just covers simple combinatorical logic. Intuitively I'd assume that the added variables cannot be quantified existentially at the outermost level since they may need to take different values depending on universally quantified variables. Existential quantification at the innermost level seems like a safe choice for the additional variables.

**Comment by NikolajBjorner** [comment]
The cnf conversions apply Tseitsin transformations and also Skolemization. Tseitsin introduces skolem constants on its own in order to represent sub-formulas. Skolemization introduces Skolem constants and Skolem functions that replace existential force quantifiers with free constants or functions. 
In both cases, you can treat Skolem functions/constants as if they are existentially quantified at the outermost or leftmost level as you say.

In general, Tseitsin transformations preserve satisfiability, and the original formula is equivalent to the existential closure of the new formula with respect to the new constants:

       F <=> exists AuxVars . tseitsin(F)

Similarly for Skolemization, which is used when the formulas contain quantifiers.
The wikipedia page on Skolemization contains relevant definitions.

**Comment by arey0pushpa** [comment]
Thanks. Another interesting question is: how to check which new auxiliary variables are introduced?
One direct way i can think of is making a list of formula in original formula nd matching against it. Is there a better way to check which additional auxiliary variables are introduced? Is there any intrinsic difference between original variables(/constants) and new introduced one.
