### ISSUE TITLE
Unexpected huge performance difference between solver using "default" tactic, Z3_mk_solver() and Z3_mk_simple_solver()

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1035]
I'm currently investigating queries that Z3 is taking a very long time to solve in my tool and I ran into one that Z3 is handling in a surprising way.

This is the query

```
(declare-fun f_ackermann!0 () (_ BitVec 64))
(assert
 (not (fp.isNaN ((_ to_fp 11 53) f_ackermann!0))))
(assert
 (let ((?x8 ((_ to_fp 11 53) f_ackermann!0)))
(let ((?x18 (fp.sqrt roundNearestTiesToEven (fp.mul roundNearestTiesToEven ?x8 ?x8))))
(let ((?x24 (fp.mul roundNearestTiesToEven ?x18 ((_ to_fp 11 53) (_ bv4607092346807469998 64)))))
(let ((?x11 (fp.abs ?x8)))
(let (($x20 (or (fp.isNaN (fp.mul roundNearestTiesToEven ?x11 ((_ to_fp 11 53) (_ bv4607092346807469998 64)))) (fp.isNaN ?x18))))
(let (($x22 (or $x20 (fp.gt (fp.mul roundNearestTiesToEven ?x11 ((_ to_fp 11 53) (_ bv4607092346807469998 64))) ?x18))))
(not (or $x22 (or (or (fp.isNaN ?x11) (fp.isNaN ?x24)) (fp.lt ?x11 ?x24)))))))))))
(check-sat)
```

In my tool libz3 is taking ~1679 seconds to solve this. When I give this query to the Z3 binary it is solving the query in ~2 seconds.

I started digging into this and by making my tool increase libz3's verbosity it looks like the slow `smt` tactic is being used when my tool uses libz3.

```
(smt.searching)
(smt.simplifying-clause-set :num-deleted-clauses 4)
(smt.searching)
(smt.simplifying-clause-set :num-deleted-clauses 30)
...
```

but when Z3 binary solves the query a different tactic is being used.

```
(sat.sat-solver)
(sat.simplify)
(sat-restart :conflicts 202 :decisions 677 :restarts 1 :clauses 185638 :learned 159 :gc-clause 0 :memory 46.75 :time 1.35)
(sat-restart :conflicts 303 :decisions 1100 :restarts 2 :clauses 185638 :learned 246 :gc-clause 0 :memory 46.75 :time 1.36)
...
```

In my tool I use the `Z3_mk_simple_solver()` to create the solver which I expected (maybe this is my mistake?) to have the same performance as the Z3 binary if no explicit tactic is requested and no logic is set. However it seems this is not the case at all.

To investigate some more I tried creating the Z3 solver instance in two different ways in my tool

* replacing `Z3_mk_simple_solver()` with `Z3_mk_solver()`
* Explicitly create the `default` tactic and make a solver from that, i.e. like this
```c++
    theTactic = Z3_mk_tactic(builder->ctx, "default");
    Z3_tactic_inc_ref(builder->ctx, theTactic);
    theSolver = Z3_mk_solver_from_tactic(builder->ctx, theTactic);
```

In both cases these changes to my tool caused performance to improve dramatically on these queries. Looking at the verbose output it seems when I instantiate Z3's solver this way it looks like the much faster `sat.sat-solver` tactic gets used.

So why is this happening? I would have expected `Z3_mk_simple_solver()` to behave like the Z3 binary does when no logic is provided and no tactic is supplied.

To help you reproduce this I'm attaching [z3_interaction.zip](https://github.com/Z3Prover/z3/files/1018519/z3_interaction.zip) (Z3 interaction log) and 
[solver-queries.core_solver.aa.smt2.txt](https://github.com/Z3Prover/z3/files/1018523/solver-queries.core_solver.aa.smt2.txt) (also a log of queries issued to Z3 in SMT-LIBv2.5 format).

Warning the interaction log has
* Multiple contexts. One is used for solving, the other is just used for logging queries to a text file.
* Sets verbosity to 0

**CC:** @ccadar @danielschemmel

**Comment by delcypher** [comment]
I forgot to mention.

Z3 revision: b782ec35ccaf59cac1294b7bb2f7714dd9854ac2

**Comment by wintersteiger** [comment]
Usually, Z3 will try to detect the logic ([here](https://github.com/Z3Prover/z3/blob/master/src/tactic/portfolio/default_tactic.cpp)) and then run a specialized tactic for the problem. This is what happens when the `default` tactic is used (declared [here](https://github.com/Z3Prover/z3/blob/master/src/tactic/portfolio/default_tactic.h#L29)). If none of those logic checks succeed, it will call the `smt` tactic ([here](https://github.com/Z3Prover/z3/blob/master/src/tactic/portfolio/default_tactic.cpp#L48)). On this particular problem, the `fpa2bv` and `bit-blaster` tactics are executed (among others) before handing the problem to the SAT solver. This is "eager", everything is translated into SAT and we use a SAT solver to decide the problem. 

However, when the `smt` tactic is used the approach is "lazy": nothing is done up front and only during the search, when things become relevant, they are translated (for the case of the FP logic, see [here](https://github.com/Z3Prover/z3/blob/master/src/smt/theory_fpa.cpp)) or otherwise instantiated. This is what the "simple" solver does; it provides a direct path to the SMT solver without any tactics being involved. 

The solver obtained via `mk_solver` is a much more complicated one ([here](https://github.com/Z3Prover/z3/blob/master/src/tactic/portfolio/smt_strategic_solver.cpp)); it constructs a `combined_solver` that switches to the SMT solver if it sees incremental commands, otherwise it uses tactics (which may finally also result in running the SMT solver). Setting the verbosity to `-v:15` should print lines beginning with `(combined-solver ...` to tell you which one of them is used. 

Usually, we would expect that specialized tactics are better at solving their respective problems, but that's of course not always true. 

In this particular case, you should also see that Z3 switches to the SMT solver when one of the FP operations requires uninterpreted functions (e.g., `fp.to_ubv` when `hi_fp_unspecified=false`, default setting may change depending on upcoming modifications to the SMT FP standard). In this case, the goal will still contain uninterpreted functions after fpa2bv and bit-blaster have translated everything they can translate, and so we can't use the SAT solver. (In this case, that check is [here](https://github.com/Z3Prover/z3/blob/master/src/tactic/fpa/qffp_tactic.cpp#L95) and there are similar ones in other tactics.)

A minor note: the "default" tactic tries to detect the logic _after_ running the simplifier (see [here](https://github.com/Z3Prover/z3/blob/master/src/tactic/portfolio/default_tactic.cpp#L36)). So, when it doesn't detect a matching logic, it will run the "smt" tactic on the _simplified_ goal; so in these cases the actual tactic that gets executed is `(then simplify smt)` instead of just `smt`.

**Comment by delcypher** [comment]
@wintersteiger Thanks for the detailed response.

> However, when the smt tactic is used the approach is "lazy": nothing is done up front and only during the search, when things become relevant, they are translated (for the case of the FP logic, see here) or otherwise instantiated. This is what the "simple" solver does; it provides a direct path to the SMT solver without any tactics being involved.

Is the `smt` tactic an implementation of what's described in "
Simplification by Cooperating Decision Procedures" by Nelson and Oppen? Sorry if this is a dumb question. I don't know that much about how SMT solvers are actually implemented. 

I didn't realise this is what the "simple" solver did. I thought it was just like `Z3_mk_solver()` except that the simplifier tactic was applied first.

I think the doxygen documentation on `Z3_mk_solver()` and `Z3_mk_simple_solver()` could be greatly improved. Your description of what these functions actually do does not seem to match the current documentation.

Currently the docs say

```c++
/**
       \brief Create a new (incremental) solver. This solver also uses a
       set of builtin tactics for handling the first check-sat command, and
       check-sat commands that take more than a given number of milliseconds to be solved.

       \remark User must use #Z3_solver_inc_ref and #Z3_solver_dec_ref to manage solver objects.
       Even if the context was created using #Z3_mk_context instead of #Z3_mk_context_rc.

       def_API('Z3_mk_solver', SOLVER, (_in(CONTEXT),))
    */
    Z3_solver Z3_API Z3_mk_solver(Z3_context c);

    /**
       \brief Create a new (incremental) solver.

       The function #Z3_solver_get_model retrieves a model if the
       assertions is satisfiable (i.e., the result is \c
       Z3_L_TRUE) and model construction is enabled.
       The function #Z3_solver_get_model can also be used even
       if the result is \c Z3_L_UNDEF, but the returned model
       is not guaranteed to satisfy quantified assertions.

       \remark User must use #Z3_solver_inc_ref and #Z3_solver_dec_ref to manage solver objects.
       Even if the context was created using #Z3_mk_context instead of #Z3_mk_context_rc.

       def_API('Z3_mk_simple_solver', SOLVER, (_in(CONTEXT),))
    */
    Z3_solver Z3_API Z3_mk_simple_solver(Z3_context c);
```

* The docs say that `Z3_mk_solver()` gives an incremental solver but this doesn't seem to always be the case.
* The docs don't say what `Z3_mk_simple_solver()` does.

Fixing the descriptions here would hopefully prevent others from making my mistake.

**Comment by delcypher** [comment]
@wintersteiger 
Based on your description it sounds like using either the `default` tactic or using `Z3_mk_solver()` would be suitable for my use case. I don't use Z3 in an incremental manner so it looks like `Z3_mk_solver()` would end up using the `default` tactic because it doesn't pass a logic to `mk_smt_strategic_solver_factory()`.

**Comment by delcypher** [comment]
@wintersteiger If you'd like me to have a go at rewriting the documentation for `Z3_mk_solver()` and `Z3_mk_simple_solver()` based on this discussion let me know and I'll have a go.

**Comment by wintersteiger** [comment]
Sure! We should definitely add a better definition of "simple" :-)

**Comment by delcypher** [comment]
@wintersteiger Okay. I'm pretty busy right now but when I have some free time I'll tackle this.

**Comment by rainoftime** [comment]
@delcypher  From my own experience, the `qfbv_tactic`(eager encoding to sat, z3/src/tactic/smtlogics/qfbv_tactic.cpp) based solver(what Z3_mk_solver() returns in your case) is usually faster than the `smt_tactic`(DPLL(T)-style lazy approach) based solver.

**Comment by rainoftime** [comment]
@delcypher  Another tactic z3 uses to solver QF_BV constraint is called `inc_sat_solver`(see `src\sat\sat_solver\inc_sat_solver.cpp`), which is same as qfbv_tactic, but has simpler preprocessings.

**Comment by wintersteiger** [comment]
Can we close this issue or is there still something remaining to do?

**Comment by delcypher** [comment]
There's nothing else to do. Closing.
