### ISSUE TITLE
Saving the “state” of a Z3 solver in SMT2 format

### ISSUE THREAD

**Issue by AndreaCallia** [Z3Prover/z3#1044]
Dear Z3 developers,

is it possible, using the Z3 API (e.g. the Python API), to save the current state of a solver, including what the solver has learned (in SAT solving we would say the "learned clauses") in a file in SMT2 format?

Because I would like to be able to save the state of the solver in a temporary file in order to resume solving later, in order to have some time to understand what further queries I should make to it.

Many thanks in advance...

**Comment by NikolajBjorner** [comment]
The state of the solver isn't fully serializable to SMT2 format.
You can print the solver to smt2 format based on the current assertions, 
but not learned clauses/units using the sexpr() method on the Solver object.

**Comment by AndreaCallia** [comment]
Many thanks for this kind reply Nikolaj... then, for example, there is no way to "pause" the solver dumping its state to the disk and reloading it later to resume it and to make further queries? Not even in other formats? You said that the state isn't "fully"serializable, this means that there is something which can still be printed or dumped in any format? Many thanks for your help again...

**Comment by NikolajBjorner** [comment]
We don't expose ways to print internal state. You could perhaps interrupt the solver, then clone it using the "translate" methods and access the translated solver state using internal print utilities. You would have to change the code a bit to get to this state.
The print features on solvers don't access the internal state of any of the solvers, instead they look at the asserted formulas and print them.
I don't translate learned lemmas. For example, the code in smt_context.cpp line 176 is disabled because it didn't help with any performance enhancements. Similarly, the copy code in sat_solver does not copy learned clauses even though it retains unit literals and binary clauses that are learned.

**Comment by AndreaCallia** [comment]
Many thanks for this Nikolaj....
