### ISSUE TITLE
push & pop causes hang

### ISSUE THREAD

**Issue by jakkdu** [Z3Prover/z3#1053]
Hi, I found the constraints cause hang if I use push & pop.
The constraints are 
```
(push)
(declare-fun k!0 () (_ BitVec 8))
(declare-fun k!1 () (_ BitVec 8))
(declare-fun k!2 () (_ BitVec 8))
(declare-fun k!3 () (_ BitVec 8))
(assert (let ((a!1 (concat ((_ extract 31 3)
                     (bvadd #x0000000b (concat k!3 k!2 k!1 k!0)))
                   #b000)))
(let ((a!2 (bvadd #x0804bfff
                  (concat ((_ extract 31 12) (bvadd #x0002100f a!1)) #x000)))
      (a!3 (bvadd #x0804b000
                  (concat ((_ extract 31 12) (bvadd #x0002100f a!1)) #x000))))
  (not (= (concat ((_ extract 31 12) a!2) #x000) a!3)))))
(check-sat)
(pop)
```

However, if I run
```
(declare-fun k!0 () (_ BitVec 8))
(declare-fun k!1 () (_ BitVec 8))
(declare-fun k!2 () (_ BitVec 8))
(declare-fun k!3 () (_ BitVec 8))
(assert (let ((a!1 (concat ((_ extract 31 3)
                     (bvadd #x0000000b (concat k!3 k!2 k!1 k!0)))
                   #b000)))
(let ((a!2 (bvadd #x0804bfff
                  (concat ((_ extract 31 12) (bvadd #x0002100f a!1)) #x000)))
      (a!3 (bvadd #x0804b000
                  (concat ((_ extract 31 12) (bvadd #x0002100f a!1)) #x000))))
  (not (= (concat ((_ extract 31 12) a!2) #x000) a!3)))))
(check-sat)
```
then, it simply returns `unsat`.

From my understanding of push & pop,
it saves contexts, so the first one should be same with the second one.
However, it causes hang. 
Could you let me know why they are different?

I am using the latest z3 wih 32bit version
```sh
$z3 --version
Z3 version 4.5.1 - 32 bit
```

Thanks.

**Comment by delcypher** [comment]
@jakkdu Z3 isn't hanging. In that case it's applying a different strategy which is much slower. You can see what's going on if you pass `-v:10` to Z3.

Without push/pop

```
(simplifier :num-exprs 23 :num-asts 210 :time 0.00 :before-memory 2.56 :after-memory 2.56)
(propagate-values :num-exprs 23 :num-asts 210 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(solve_eqs :num-exprs 23 :num-asts 210 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(elim-uncnstr-vars :num-exprs 16 :num-asts 236 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(:num-elim-apps 3)
(bv-size-reduction :num-exprs 16 :num-asts 236 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(simplifier :num-exprs 16 :num-asts 236 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(simplifier :num-exprs 16 :num-asts 236 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(max-bv-sharing :num-exprs 16 :num-asts 236 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(ackermannize :num-exprs 16 :num-asts 236 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(bit-blaster :num-exprs 2 :num-asts 453 :time 0.00 :before-memory 2.65 :after-memory 2.65)
(simplifier :num-exprs 1 :num-asts 300 :time 0.00 :before-memory 2.65 :after-memory 2.65)
unsat
```

with push/pop

```
(smt.simplifier-done)
(smt.searching)
(smt.simplifying-clause-set :num-deleted-clauses 0)
(smt.restarting :propagations 38 :decisions 129 :conflicts 101 :restart 100 :restart-outer 110 :agility 0)
(smt.restarting :propagations 39 :decisions 246 :conflicts 202 :restart 110 :restart-outer 110 :agility 0)
...
```

The root cause of what you're seeing can seen in https://github.com/Z3Prover/z3/blob/40177f7bac4ab9615a32728154f6fd1fa6c8fcf9/src/tactic/portfolio/smt_strategic_solver.cpp#L123 .

Z3 makes a ["combined solver"](https://github.com/Z3Prover/z3/blob/40177f7bac4ab9615a32728154f6fd1fa6c8fcf9/src/solver/combined_solver.cpp#L44) that is made of two different solvers. If push/pop are detected it uses the second solver, otherwise it uses the first solver.

The first solver from `mk_tactic2solver()` will be using the ["default" tactic](https://github.com/Z3Prover/z3/blob/40177f7bac4ab9615a32728154f6fd1fa6c8fcf9/src/tactic/portfolio/default_tactic.cpp#L36) because you didn't specify a logic. This tactic probes the constraints to determine what the logic is and uses the appropriate tactic if the logic is recognised. In your case the probe will detect the logic is `QF_BV` and will use the `qfbv` tactic.

The second solver from `mk_solver_for_logic()` will make an incremental sat solver (`mk_inc_sat_solver()`) if you specify the logic as `QF_BV` otherwise the solver will be the general SMT solver (`mk_smt_solver()`) which in my experience is frequently slower than the solvers built from a tactic for a particular logic.

So to solve your problem.

* If you need incremental solving specify the logic with `(set-logic QF_BV)` at the beginning of the SMT-LIBv2 query.
* If you don't need incremental solving but don't know what the logic will be up front use `(reset)` to clear the assertion stack and avoid using push/pop.

Hope that helps.

**Comment by jakkdu** [comment]
Thanks a lot. 
It is really helpful for me.
I have limited knowledge of z3 in detail.  
I will close this issue.
Thank you!
