### ISSUE TITLE
Using z3 java library in windows

### ISSUE THREAD

**Issue by Edillower** [Z3Prover/z3#1093]
I'm able to use z3 in OSX by import the jar file (com.microsoft.z3) into my eclipse java project and set its native library location to the folder that contains the libz3java.dylib file. However, problems pop up when I was trying to port my project to windows system. I added all the library files in the bin folder of z3's 4.5.0-x64-win release into the jar's native library location but still got the following error: 

**Exception in thread "main" java.lang.UnsatisfiedLinkError: ...\libz3java.dll: Can't find dependent libraries**

According to Dependency Walker, it seems that many system libraries (name starts with API-MS-WIN-CORE or EXT-MS-WIN-GDI) are missing.

I also tried adding the directory containing libz3.dll and libz3java.dll to my system's PATH instead of java.library.path as @wintersteiger suggested in issue #1064 but it didn't work.

I'm not sure what to do. Am I supposed to manually find all those missing DLL in my system and add them to the java.library.path? Thanks for your help in advance.

**Comment by wintersteiger** [comment]
No, you're not supposed to collect all of them manually! One problem may be that the Z3 DLLs were compiled for 64-bit architectures, but your Java is 32-bit (or vice versa). In that case Java will not report a useful error message (just "can't load" and similar), so make sure all parts have matching bitness. Also, when you set PATHs and classpaths `-cp` remember to use `;` instead of `:` on Windows.

**Comment by Edillower** [comment]
Setting PATH is actually the solution to this problem. 
I guess it didn’t work yesterday because I hadn't restart my computer or eclipse.
