### ISSUE TITLE
Problems with Z3 Simplex Optimization

### ISSUE THREAD

**Issue by duduRodrigues** [Z3Prover/z3#1124]
I am trying to use Z3 to solve a maximization problem. The problem is described as follow:

Maximize p = (1/2)x + 3y + z + 4w subject to
x + y + z + w <= 40
2x + y - z - w >= 10
w - y >= 10

And it's Optimal Solution is: p = 115; x = 10, y = 10, z = 0, w = 20
I created a optimizer using Z3 but it still saying that the problem goes to infinite.
Here is my Z3 Code:

![code](https://user-images.githubusercontent.com/10099698/27745431-af2f9588-5d99-11e7-82e9-c303cd5e7219.png)

And this is the output of my code:

![output](https://user-images.githubusercontent.com/10099698/27745467-d0c78b74-5d99-11e7-8a9f-964c0122169b.png)

Someone know where is my mistake? Also, someone know how to get the variables separately, I am printing the entire model to see the variables values :P 
Thank you, Guys.

**Comment by krypt-n** [comment]
One thing I noticed reading your code is that `(1/2)` is probably evaluated in C++ and thus equal to `0`. I don't think that's the cause of you problem though.

**Comment by duduRodrigues** [comment]
I changed (1/2) to 0.5 but it keeps Maximizing to infinity. :/

**Comment by NikolajBjorner** [comment]
why would the problem be bounded? In SMT2 I can assert arbitrary lower bounds:

(declare-const x Real)
(declare-const y Real)
(declare-const z Real)
(declare-const w Real)

(assert (<= (+ x y z w) 40))
(assert (>= (+ (* 2 x) y (- z) (- w)) 10))
(assert (>= (- w y) 10))
;(maximize (+ (* 0.5 x) (* 3.0 y) z (* 4.0 w)))
(assert (>= (+ (* 0.5 x) (* 3.0 y) z (* 4.0 w)) 1000000099999000))
(set-option :opt.priority pareto)
(check-sat)
(get-model)
(eval (+ x y z w))
(eval (+ (* 2 x) y (- z) (- w)))
(eval (- w y))
;(get-objectives)

**Comment by duduRodrigues** [comment]
@NikolajBjorner i dont get what you do. The result keeps going to infinity.

I've change my code a little and now it looks like this:

![code2](https://user-images.githubusercontent.com/10099698/27751026-c39b25ac-5db0-11e7-8898-ccb5442af1ee.png)

And when I put the restrictions to the variables be positive, I get the exoected output:

![output](https://user-images.githubusercontent.com/10099698/27751048-d77588b0-5db0-11e7-8a07-4fdb377dfc27.png)


But I do not want to force the variables to be positive. Someone can explain why this is happening/find out the solution?

**Comment by duduRodrigues** [comment]
@NikolajBjorner Sorry to keep bothering you, but I run your code on rise4fun and what I've got was not the maximization of the function. The following image shows the code ant it's result:

![rise4fun](https://user-images.githubusercontent.com/10099698/27753061-791eef0e-5dba-11e7-84d1-3d589a9a1187.png)

I'm saying that the 61.666666667 output isn't the optimal solution because it isn't consistent with the simplex tableau output. Here is an image of my tableau: 

![tableau](https://user-images.githubusercontent.com/10099698/27753124-d0b485bc-5dba-11e7-840a-b048fc203bff.png)

Is z3 capable of solve this kind of problem or am I using it wrong?

**Comment by NikolajBjorner** [comment]
Some tableau formulations assume that all variables are non-negative. They introduce dual copies or compensation variables to solve also for negative solutions. So I guess you are solving a system where variables are assumed to be non-negative. 
When you declare a variable to be real in Z3 it ranges over all real numbers. You can, as you correctly did, assert that variables are non-negative by adding inequalities. 

To see that the problem is unbounded for arbitrary reals you can do the following:

solve for w in: w - y >= 10, which is w = 10 + y, so the rest of the system is:
x + y + z + 10 + y <= 40,
2x + y - z - 10 - y <= 10

Then solve for z in the last inequality: z = 2x - 20, and substitute the solution in the remaining:

x + 2y + 2x - 20 + 10 <= 40
which simplifies to

2x + 2y <= 60

Go back to your objective function:

    1/2)x + 3y + z + 4w
then you see that it rewrites to:

     1/2*x + 3y + 2x - 20 + 40+4y

So the coefficient to y is larger than the coefficient to x, thus, you can always set x = -y and make y as large as possible.

**Comment by duduRodrigues** [comment]
Wow, now I get it!!!! Thank you so much, @NikolajBjorner ! That was really helpful!
