### ISSUE TITLE
(+ (- 1) str.len) instead of (- 1 str.len) make problem very slow to execute

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#1140]
When testing the problem

(declare-fun q () String)
(assert (let ((a!1 (re.++ (re.++ (re.++ (str.to.re "") (str.to.re "-")) (str.to.re "-"))
                  (re.+ (re.union (re.range "\x00" "\x09") (re.range "\v" "y"))))))
(let ((a!2 (re.++ (re.* (re.union (re.range "\x00" "\x09") (re.range "\v" "y")))
                  (re.++ a!1 (str.to.re "=")))))
  (str.in.re q a!2))))
  
(assert (let ((a!1 (= (str.at q  (+ (- 1) (str.len q))) "=")))
  (not a!1)))

(check-sat)
(get-model)

I get a timeout / really long exec time on http://rise4fun.com/z3

Substituting  (+ (- 1) (str.len q)) for (- 1 (str.len q)) makes the problem execute really quickly. Why is this & is there anyway to rewrite to avoid this (The query is automatically generated by symbolic engine)

**Comment by LeventErkok** [comment]
Just wanted to point out that `(+ (- 1) str.len)` means `str.len - 1`, while `(- 1 str.len)` means `1 - str.len`. So, the latter probably causes z3 to recognize the string can be at most 1 character long before that index becomes negative, and thus it can easily exhaust the cases; while the former would be a much harder problem as the proof would be over a much larger search space. That would explain the performance difference, as the problems are significantly different. Was that intentional in your encoding?

**Comment by jawline** [comment]
Ah, that makes sense. Thanks
