### ISSUE TITLE
Triggering lemma learning to reduce quantifier instantiations in incremental mode

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#1151]
Heads up: this is basically a feature request, but for a feature that [we](http://viper.ethz.ch) expect to be useful for many users and that we hope won't be too difficult to implement.

A bit of context: we use Z3 as the back-end of a symbolic-execution-based program verifier, and while exploring a program path we push more and more assumptions to Z3 and we repeatedly check if certain conditions are guaranteed to hold. I.e. we use Z3 in incremental mode with lots of (nested) push-pop blocks and we typically get the following program structure:

```
; Verification preamble:
;   - declaring sorts and functions
;   - axiomatising theories via quantifiers
;   - ...

(push)
  (assert ...)
  ...
  (push)
    (assert ...)
    ...
    (push)
      (assert (not P))
      (check-sat) ;;; unsat --> P holds
    (pop)
    ...
    (push)
      (assert (not Q))
      (check-sat) ; unsat --> Q holds
    (pop)
    ...
  (pop)
(pop)
```

As is "common knowledge", the first property checks (`P`) causes Z3 to learn lots of lemmas, e.g. by instantiating quantifiers (we don't use MBQI), but these lemmas are forgotten upon pop and thus need to be relearned during the second property check (`Q`).

However, lots of the learned lemmas are independent of the checked properties, e.g. they could already be learned right after the verification preamble. Indeed, some lemmas appear to be learned upon first `push`: our understanding is that Z3 performs some kind of cursory lemma learning whenever a new push-pop block is entered.  
Adding a `check-sat` *right after* (but curiously, not *before*) the first `push` seems to make Z3 learn even more lemmas — this seems to be an easy way to reduce the number of lemmas Z3 will have to learn again and again.

Attached SMT file [state_saturation.smt2.txt](https://github.com/Z3Prover/z3/files/1156328/state_saturation.smt2.txt) — the interesting (and short) bit starts on line 919 — illustrates the above, including the positive effect of an initial `check-sat`. The file is a cut-down version of an example generated by our symbolic execution engine; for the original file, the initial `check-sat` reduces Z3's runtime from 14 to 3 seconds.

However, it is unclear to us how "hard" Z3 tries to learn lemmas upon such additional `check-sat`s. After all, Z3 could probably be lucky and conclude `sat` right away, or it could give up immediately and conclude `unknown`, without having learned many lemmas.

It might thus be helpful to have a command that forces Z3 to learn as many lemmas as possible (modulo quantifier triggering, etc.) in a given amount of time (i.e. until a user-provided timeout is reached). 

Does all of this sound reasonable? Do you think such a command would be useful?

**Comment by wintersteiger** [comment]
I'm afraid there's a bit too many variables left in this request. Z3 doesn't know how to learn "hard" or "soft", it will resolve whatever conflict it hits, which depends on the variable and phase selection heuristics (and more). Or, in other words, it already learns as "hard" as possible every time and it will never give up because it can't "learn hard enough".

The differences in performance that you're seeing are most likely due to the order of quantifier instantiation. Sometimes Z3 is lucky and it picks just about the right instance for the crucial quantifier, and at other times it will instantiate a thousand irrelevant quantifiers until it finally hits the right one. Simply changing the order of assertions, variable declarations, or the random seed, frequently makes the difference. (Shameless plug: [this](https://github.com/Wintersteiger/z3/commits/quant-exp) branch is able to record an SMT2-format, readable, and replayable quantifier instantiation log that you can play around with. Set `smt.search_log=filename.smt2` and replace `(check-sat)` with `(replay "filename.smt2")`. Then remove all the irrelevant ones... )

Obviously, those are all undesirable properties for many applications. Suggestions and new ideas that maintain performance while improving predictability are most welcome though!

Also note that lots of "independent" lemmas also clog up the memory, so you don't necessarily want to collect and keep all irrelevant lemmas (or quantifier instances) forever. 

(Since your example file contains `(set-option :timeout 0)`: Combining timeouts with a search algorithm makes everything non-deterministic, so now you don't even have to change the random seed to make it fail! Use rlimits (`(set-option :rlimit <n>)` and similar) for a deterministic way of resource bounding.)

**Comment by mschwerhoff** [comment]
Thank you very much for all the information, @wintersteiger! As far as I am concerned, the fact that Z3 already tries "as hard as possible" upon `check-sat` is good to know and good enough for us (at least for now). I'll close the issue, but I might reopen it again if I have more concrete ideas or suggestions.

Regarding timeouts: I looked at Z3's help (`-pd`) but couldn't find out much about `rlimit`. I filed a [Stackoverflow post with questions](https://stackoverflow.com/questions/45457131) because I thought it would be more appropriate than asking them here.
