### ISSUE TITLE
Failed to run Z3 unit test test-z3.exe from master branch revision a0a8bc2

### ISSUE THREAD

**Issue by KarenHuang2016** [Z3Prover/z3#1159]
We tried to build Z3 and run its unit tests on Windows. The unit test test-z3.exe failed to run from master branch revision [a0a8bc2](https://github.com/Z3Prover/z3/commit/a0a8bc2a628274965d995c3fb8db6dba6ff7ee02#diff-49d45889919896b3e21acf88e1a47826). Could you please take a look at this? Thanks in advance!

**Environment:** Windows Server 2016 + VS2017 Update 2
**Reproduce steps:**
1. git clone https://github.com/Z3Prover/z3 D:\Z3\src
2. Open a VS 2017 x86 command prompt and browse to D:\Z3\src
3. python contrib\cmake\bootstrap.py create
4. cd D:\Z3
5. mkdir build_x86 && pushd build_x86
6. cmake -G "Visual Studio 15" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src
7. msbuild Z3.sln /p:Configuration=Release;Platform=Win32 /t:Rebuild /m /p:BuildInParallel=true
8. .\Release\test-z3.exe /a

**Actual result:**
[Z3_x86_test.txt](https://github.com/Z3Prover/z3/files/1172493/Z3_x86_test.txt)
failed to run test-z3.exe due to the following error:
attempting to parse spec1...
(error "line 3 column 57: smtlib 2.6 parametric datatype sorts are not supported")
(error "line 4 column 21: unknown sort 'list'")
(error "line 5 column 24: unknown sort 'list'")
(error "line 6 column 19: unknown sort 'list'")
(error "line 7 column 19: unknown sort 'list'")
(error "line 8 column 19: unknown sort 'list'")
(error "line 10 column 17: unknown sort 'list'")
(error "line 12 column 12: unknown constant l")
Error: parser error

**Comment by delcypher** [comment]
@KarenHuang2016 

Just to note you don't need to run `python contrib\cmake\bootstrap.py create` anymore. That script doesn't do anything anymore.

Also if you want fast parallel builds (and you don't need to do development work in Visual Studio) consider using [Ninja](https://ninja-build.org/) as the CMake generator rather than Visual Studio.

**Comment by delcypher** [comment]
@NikolajBjorner Looks like I've been running the unit tests incorrectly in CI. I just ran

```
./test-z3
```

Presumably I should be doing

```
./test-z3 /a
```

instead?

**Comment by NikolajBjorner** [comment]
yes

**Comment by delcypher** [comment]
@NikolajBjorner I just took a look and there are some very odd things here.

* The tests seem rely on `SASSERT()`. Isn't that a no-op in non debug builds? That doesn't seem like a great idea because that means we don't know if the checks actual pass on a release build.
* `src/test/hashtable.cpp` seems to redefine `SASSERT()` and that implementation isn't particularly good because it doesn't halt execution with a non zero exit code which means we'll easily miss any failures here.
* Several of the tests have `#ifdef _WINDOWS`  (e.g. `src/test/api.cpp`) guarding them with no obvious reason why.

**Comment by NikolajBjorner** [comment]
yes, much of this unit test code has been used for various purposes over time so isn't as rigorous as the rest of the code base.

**Comment by KarenHuang2016** [comment]
@delcypher, thanks for your information. I will not run "python contrib\cmake\bootstrap.py create"  anymore. Actually we're testing VC++ compiler, so I need to use VS to build. :)

**Comment by KarenHuang2016** [comment]
test-z3.exe run successfully with master branch revision 9d6be28. Close this issue.

**Comment by delcypher** [comment]
@KarenHuang2016 
> Actually we're testing VC++ compiler, so I need to use VS to build. :)

You can use MSVC (same as VC++ compiler as far as I know) and Ninja together on Windows. You don't have to use MSBuild/Visual Studio.
