### ISSUE TITLE
How to let double variable do bit operations in Z3?

### ISSUE THREAD

**Issue by freyaZhou** [Z3Prover/z3#1164]
I use Z3 to solve the expression `d < (x&1)`, where `d` is real const type, `x` is a bv_const. It got `Assertion failed: (false), function operator<, file /usr/local/include/z3++.h, line 1187.
`. 
I use the code below:
```
#include "z3++.h"
#include "z3_api.h"
using namespace z3;

void z3_example() {
  context c;
  expr d = c.real_const("d");
  expr x = c.bv_const("x", 32);
  solver s(c);
  
  s.add(d < (x&1));
  std::cout << s.check() <<"\n"; 
}

int main() {
  z3_example();
  return 0;
}
```
Help, I don't know to solve this expression using Z3.

**Comment by wintersteiger** [comment]
The `<` operator is only defined for arguments of the same type, you can't mix bit-vectors and reals. You'll have to convert one of them to the other type first (see the various conversion functions called `Z3_mk_real2int`, `Z3_mk_int2real`, `Z3_mk_bv2int`, `Z3_mk_int2bv`). However, it's very likely that Z3 will not be able to produce results for this type of problem, because those translation are effectively treated as uninterpreted (`Z3_mk_bv2int`) or the result is horribly non-linear (`Z3_mk_real2int`). So, if there is a way, you should avoid those conversions.
