### ISSUE TITLE
Assertion violation in theory_arith_inv.h

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#1197]
Running Z3 revision `05c4ea8` on [this SMT file](https://github.com/Z3Prover/z3/files/1199726/repro.smt2.txt) I *non-deterministically* get the following output:

    Failed to verify: m_util.is_numeral(rhs, _k)

When using a debug build of Z3 I (also non-deterministically) get the following assertion violation:

    ASSERTION VIOLATION
    File: D:\Develop\z3\src\smt/theory_arith_inv.h
    Line: 97
    !it->m_coeff.is_zero()

Let me know if there is anything else I can do to help.

**Comment by NikolajBjorner** [comment]
Thanks for the repro I can get the assertion violation after a few tries.
The repro is non-deterministic because it relies on timeouts that you are setting in the file.
We can use the rlimit to get determistic repros. It will require printing statistics, retrieving the rlimit counts and deltas and set the rlimit instead of timeout. At this point I can see that quantifier instantiation somehow does not produce atomic formulas in normal form, which is expected by the arithmetic module. It should be an invariant that instantiated atoms are simplified. Either the arithmetic solver has to assume less about simplification or we have to locate where the missing simplification can be fixed.

**Comment by mschwerhoff** [comment]
I tried what you suggested and [this SMT file](https://github.com/Z3Prover/z3/files/1203010/repro-det.smt2.txt) yields `Failed to verify: m_util.is_numeral` every time I execute Z3 on it. I hope it works for you as well.

**Comment by NikolajBjorner** [comment]
The updated repro somehow didn't hit the problem, so my version could have drifted with respect to how resource limits are incremented. But it was very helpful to stage a version where I could search for random pertubations of the rlimit setttings and identify a couple of places that could be fixed. I currently don't produce crashes in my runs (debug/release), so I hope we have addressed the issues you found.

**Comment by NikolajBjorner** [comment]
@mschwerhoff  can we close this?

**Comment by mschwerhoff** [comment]
@NikolajBjorner I currently can't run the (previously) failing tests, but I'll rerun them as soon as I can and then I'll either update or close the issue.

**Comment by mschwerhoff** [comment]
@NikolajBjorner I couldn't reproduce the error, so I assume it's fixed. Thank you for resolving it so quickly, Nikolaj!
