### ISSUE TITLE
deprecate VS 2012?

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#1210]
Commit 2473c6967921ce4c22ffecc2b3d74c37f7dc0130 broke the VS 2012 build. 
It turns out that the C++11 feature used there isn't supported down to 2012.
The change was required to enable strict alias analysis to aid compiler optimizations.
Are there any compelling reasons at this point to maintain VC 2012 support?

**Comment by wintersteiger** [comment]
Sorry, but this is completely unnecessary. What is the motivation for this and why would we make this change at this point in time? This can easily wait until January, when we switch to VS2013.

Also, the errors that VS2012 throws are trivial to fix (just keep pointers instead of symbol/rational just like they used to be). A union with pointers will probably prevent compiler optimizations, but this part of the code has been user-optimized with intent. So, if we give that up, I want to see at least some evidence of an increase in performance on our usual benchmarks.

**Comment by delcypher** [comment]
> Sorry, but this is completely unnecessary. What is the motivation for this and why would we make this change at this point in time? This can easily wait until January, when we switch to VS2013.

I don't use Windows much so this doesn't really affect me too much but why would you need to support a 5 year old compiler, when much newer versions are easily available and usable? Perhaps you have projects that **only** build against the older MSVC and also depend on Z3? If so that might be a legitimate reason to maintain MSVC 2012 support. However at some point those projects will have to upgrade or face (eventually) becoming irrelevant.

Without context it is difficult for me to say whether I think the change is "completely unnecessary". I personally think it's a good thing to drop a compiler like MSVC 2012 so that the ability to use more C++11 features is available.

Just my 2c.

**Comment by NikolajBjorner** [comment]
If we drop support in January, then that seems like the approach. A tradeoff is to deal with inadvert regressions and setup that takes time from other priorities.

**Comment by wintersteiger** [comment]
@delcypher Z3 is not a new project, we have lots of users that use older systems. So far 5 years back was my limit, which is a "usual" timeframe for a PhD. Also, remember the VS is not free (or most of it wasn't, until recently), some universities may not have licenses for the latest cutting-edge VS, and some users can't upgrade because of other project dependencies, or because the upgrade would take too much testing effort (e.g. one MSFT product group that ships three different versions of libz3.dll for different sub-projects...). And yes, those projects will have to face becoming irrelevant, but that is not our call. 

@NikolajBjorner Yes, that when it's 5 years. What sort of inadvert regressions are you hinting at?

In general, my attitude is to maintain backwards compatibility if it's free and this is one of those cases (or at least it is until someone has run some benchmarks...). There is no point in breaking something and interrupting other people's work, just for the sake of pretending to be "cool" by using the latest crazy language features and similar.

**Comment by NikolajBjorner** [comment]
> What sort of inadvert regressions are you hinting at
For example, we would have to change optional.h to use a pointer. Bugs could easily sneak in and then we spend another day or two fixing build problems. Speaking of which, the OSX build is mysteriously broken...

**Comment by wintersteiger** [comment]
Hadn't seen that one yet, but my Visual Studio claims optional<...> is used in only 2 places (one of which is mine via array_map.h). Candidate for cleanup?

Yes, the benefits of cutting edge software are well understood. Also, many of the downsides are known. Pick a new/better rule for backwards compatibility then, so far there were far more complaints than proposals...
