### ISSUE TITLE
OCaml API for String/Sequence/RegExp

### ISSUE THREAD

**Issue by johnduck** [Z3Prover/z3#1214]
I'm trying to use Z3 OCaml binding for my project.

However, I could not find any support for string/sequence/regexp in [z3.mli](https://github.com/Z3Prover/z3/blob/master/src/api/ml/z3.mli), and it has not been updated about a year.

Is there a plan for supporting these features in OCaml api? I only found that there are some interfaces for string/sequence/regexp in `z3native`, but I don't know what issues would happen when I use it blindly.

**Comment by wintersteiger** [comment]
Yes, the plan is to support those features in all APIs, but so far nobody has had time to add them to the OCaml API. The lower level (raw OCaml-to-C) interface in `z3native` is automatically generated and already contains all the relevant functions. Theoretically you can use those, but it would be a bit of a pain as you'd have to deal with the C pointers hidden in OCaml objects, reference counting, etc.

That said, if you happen to have time to add the higher level modules/functions, you're most welcome! (The modules would look very much like the `FloatingPoint` module, except with fewer functions of different names.) 

Otherwise, @martin-neuhaeusser would be my next port of call :-)

**Comment by NikolajBjorner** [comment]
API functions for seq/re/strings have now been added.
