### ISSUE TITLE
Is there a performance advantage if you use Z3_mk_solver_for_logic?

### ISSUE THREAD

**Issue by bennofs** [Z3Prover/z3#1239]
This is not an issue, just a question:

Is there a performance advantage to using `Z3_mk_solver_for_logic` instead of `Z3_mk_solver`? I am asking because I've read somewhere that z3 only applies a reduced set of preprocessing if the logic is unknown, but that information could be outdated (it is very hard to find up-to-date information on Z3 performance characteristics).

**Comment by rainoftime** [comment]
`Z3_mk_solver_for_logic` will create a solver based on the tactic corresponding to the "logic" you pass to 

`Z3_mk_solver` will attempt to probe the logic used by the assertions and will apply a specialized tactic(such as `qflia_tacitc` for linear integer arithmetic) if one is supported, otherwise it will use the `smt_tactic`.

**Comment by rainoftime** [comment]
You can check the new documentation about `Z3_mk_solver` here https://github.com/Z3Prover/z3/pull/1069/files

**Comment by bennofs** [comment]
Thanks for the thorough answer! This answers my question.
