### ISSUE TITLE
Z3 can't prove power property when (set-option :produce-proofs true)

### ISSUE THREAD

**Issue by j123123** [Z3Prover/z3#1240]
This sample
````SMT
(assert
  (forall ((a1 Real))
    (= (^ a1 4.0) (* (^ a1 2.0) (^ a1 2.0)) )
    )
)
(check-sat)
(exit)
````
It says ``sat``, but if add (set-option :produce-proofs true) at the beginning, it says ``unknown
``
http://rise4fun.com/Z3/0vNgJ

**Comment by j123123** [comment]
Another testcace
````SMT
(assert
  (forall ((a1 Real))
    (= (^ a1 2.0) (* a1 a1))
   )
)
````

**Comment by NikolajBjorner** [comment]
Z3 uses a complete method for satisfiability of quantified formulas over non-linear reals. It does not produce proofs. In fact, proof producing quantified non-linear solving is a topic that someone keen on proof production can take on (corresponding results for QBF exist and involve extracting Skolem and Herbrand functions). So instead of pretending to generate a "trust me" certificate Z3 simply doesn't enable this strategy when proofs are turned on.

**Comment by j123123** [comment]
>So instead of pretending to generate a "trust me" certificate Z3 simply doesn't enable this strategy when proofs are turned on.

Why?

Here we get ``sat`` and ``Z3(9, 10): ERROR: proof is not available``:
```SMT
(set-option :produce-proofs true)

(assert
  (forall ((a1 Real))
    (= (+ a1 a1) (* a1 2))
  )
)
(check-sat)
(get-proof)
(exit)
```

Here we get ``unknown`` and ``Z3(9, 10): ERROR: proof is not available``:
```SMT
(set-option :produce-proofs true)

(assert
  (forall ((a1 Real))
    (= (^ a1 2.0) (* a1 a1))
   )
)
(check-sat)
(get-proof)
(exit)
```

If we remove ``(set-option :produce-proofs true)`` and ``(get-proof)`` we get ``sat``.

This is inconsistent behaviour.
