### ISSUE TITLE
Overflow encountered when expanding vector

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1251]
Likely related to #864 #455  and reading those descriptions it sounds like a memory limit issue.

When running the latest Z3 master (1d6f53c31026ea80679cccc12932f8ba986d7f7b) and using Z3's C API in our application we receive an error to our Z3 error handler. The associated error message with the error is `Overflow encountered when expanding vector`.

This is an error I noticed quite a while ago but hadn't got round to reporting because I hadn't tested on the latest Z3 master.

Attached is a [compressed API interaction log](https://github.com/Z3Prover/z3/files/1288376/z3api.log.zip). If you need anything else from me to reproduce then let me know.

**Comment by NikolajBjorner** [comment]
How long does it take you to produce this overflow based on the log? This seems to run for a long time with modest memory consumption.

**Comment by delcypher** [comment]
@NikolajBjorner It's approximately 15 minutes. I just tried replaying the log and I don't seem to get same behaviour as we do in our too. I'm assuming an API error would cause the replay to halt. Does it?.

This is likely going to require more digging on my part.

**Comment by NikolajBjorner** [comment]
I added rather many changes since your log was generated and only tried replaying against the newest bits. In the newest bits, the legacy simplifier is gone. If the overflow happened there for whatever reason, then it is not going to come back in that form. We have special vector classes that allow 64 bit indexing, so if your bug identifies a useful place to allow more memory it is one option to address this.

**Comment by NikolajBjorner** [comment]
This bug is so old that the relevant code has changed significantly
