### ISSUE TITLE
Homebrew package for OCaml bindings

### ISSUE THREAD

**Issue by btj** [Z3Prover/z3#1329]
There is a Homebrew `z3` package, but it does not include the OCaml bindings. It would be useful for me if there was a Homebrew package called e.g. `z3-ocaml` with the OCaml bindings.

BTW: It seems that it would be easier to create such a package if it were possible to build the Z3 OCaml bindings without having to build Z3 itself. That is, it would be nice if there was a way to build the Z3 OCaml bindings against an installed Z3 DLL instead of against a just-built Z3 DLL. (Unlike the Debian package manager, Homebrew does not seem to support generating multiple binary packages from the same build.)

**Comment by btj** [comment]
Note: I just discovered that the [Homebrew documentation](https://docs.brew.sh/Acceptable-Formulae.html) frowns on formulae (= Homebrew packages) that are just bindings; they prefer that the bindings be included in the main formula. However, given that that would add a build-time dependency on OCaml to the Z3 formula, I assume that in this case they would agree that it is preferable to have a separate formula.

**Comment by delcypher** [comment]
> BTW: It seems that it would be easier to create such a package if it were possible to build the Z3 OCaml bindings without having to build Z3 itself. That is, it would be nice if there was a way to build the Z3 OCaml bindings against an installed Z3 DLL instead of against a just-built Z3 DLL. 

That isn't likely to happen right now. The build of the bindings is coupled with the build system. The new CMake build system could be architected to allow it to be possible to build any of the bindings against a pre-built libz3, however it isn't architected that way right now. The CMake build system doesn't actually support the OCaml bindings yet. It's on my TODO list but its a lot of work and I haven't found time to do it.

To be honest though I'm not a fan of allowing the bindings to be built separately from libz3 itself. This opens up a whole new world of problems due to API/ABI mismatches. I'm also not a fan of making build system architecture decisions based on behaviour of just one package manager.

In the case of homebrew I recall that formulas can have options so I think that's the better way to go. The  [current Z3 formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/z3.rb) already has an option to disable the python bindings. A similar option could be added to enable/disable the OCaml bindings.

**Comment by btj** [comment]
> formulas can have options

Good point; yes, that's probably the way to go. Thanks!

Just so that I understand, though:

> API/ABI mismatches

Would there be any difference in this respect between the bindings and any other client of `libz3`?

**Comment by delcypher** [comment]
@btj 
> Would there be any difference in this respect between the bindings and any other client of libz3?

I don't think so.

**Comment by NikolajBjorner** [comment]
Regarding clients of libz3 and package managers. There are occasional asks for supporting package managers out of the box and I have to resist this as the setup complications, dependencies and moving parts would drag down main efforts. Having the build environment do end-to-end builds ensures that what comes out fits together. Sometimes Python and Java users have a stale libz3.dll somewhere and update their API bindings and they run into trouble. This generates GitHub issues, that call for attention.

There is another obstacle wrt OCaml from my point of view: it isn't well supported on Windows other than under Cygwin, which has its own barriers of entry for non-rudimentary uses. An Ubuntu shell is an option for me, but it is a separate setup cost whenever moving between machines (or reimaging them).

**Comment by btj** [comment]
FYI: I'm trying to make it easier to set up the build environment for [VeriFast](https://github.com/verifast/verifast) on all supported platforms (Windows, Linux, macOS); more specifically, right now I'm trying to make it easier to set up the Z3 OCaml bindings, which are an optional dependency of VeriFast.

For macOS, I'm already using Homebrew for the other dependencies, so my current plan is to extend the `z3` formula with an option for building the OCaml bindings, as suggested by @delcypher above. As a prerequisite to that, I'm investigating creating a formula for Findlib, the package that provides the `ocamlfind` command, which is used by the Z3 install script for installing the OCaml bindings.

For Windows, we're currently using Cygwin but I'm investigating whether it wouldn't be better to switch to MSYS2.
