### ISSUE TITLE
API doc build

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#1350]
@delcypher: which command failed [here](https://travis-ci.org/Z3Prover/z3/jobs/299638876) and where should libz3.so be found? I already added the build directory to the PATH just in case, but that didn't help. It works fine on my personal Ubuntu though.

**Comment by delcypher** [comment]
@wintersteiger I can reproduce this. Something is going wrong when `pydoc.writedoc()` is called. When this happen the code in `z3core.py` fails to find `libz3.so`.

The problem is the paths being searched for in `z3core.py`. I hacked `z3core.py` to print out the directories that are checked for `z3core.py`.

```
XXX: trying "/home/dan/.gem/ruby/2.4.0/bin"
XXX: trying "/home/dan/dev/llvm/bin/bin"
XXX: trying "/home/dan/dev/iscp"
XXX: trying "/home/dan/dev/unrarall"
XXX: trying "/usr/local/sbin"
XXX: trying "/usr/local/bin"
XXX: trying "/usr/bin"
XXX: trying "/usr/lib/jvm/default/bin"
XXX: trying "/usr/bin/site_perl"
XXX: trying "/usr/bin/vendor_perl"
XXX: trying "/usr/bin/core_perl"
XXX: trying "/home/dan/path"
XXX: trying "/home/dan/dev/rubber/bin"
XXX: trying "."
XXX: trying "/home/dan/dev/z3/build/python/z3"
XXX: trying "/home/dan/dev/z3/build/python/z3/lib"
XXX: trying "/usr/lib"
XXX: trying "None"
```

None of them match. There are several problems here.

* Currently `libz3.so` is next to the `z3` package directory (i.e. `/home/dan/dev/z3/build/python/`) on my system. Therefore checking `os.path.dirname(os.path.abspath(__file__))` is wrong. Instead it should be checking one directory above.
* Checking `pkg_resources.resource_filename('z3', 'lib')` doesn't make sense as we don't copy the library into `/home/dan/dev/z3/build/python/z3/lib`.
* The paths in `PATH` probably shouldn't be checked before paths like `.`. This will cause us to pick up the wrong `libz3` if the user just so happens to already have a copy of Z3 installed.

**Comment by delcypher** [comment]
@wintersteiger I've created #1351 which does the bare minimum to fix TravisCI.

> It works fine on my personal Ubuntu though.
The fact that it works for you is likely a fluke. You should check which `libz3` is being loaded. Likely you have a copy of libz3 installed somewhere or it's being picked up in `PATH`.

**Comment by delcypher** [comment]
@wintersteiger Looking at this, I don't understand why so many different paths are being searched for `libz3`. This will lead to all sorts of horrible issues when trying to use z3 from the build directory when another copy of z3 is also installed.

We **know** the `libz3` binary we want to use can only be in one of two possible locations

* In the build tree, next to the `z3` python package directory.
* In the install tree. We can compute this path at run time relative to the python package directory so that the install is portable.

We shouldn't really be considering **any other paths**. 

* Checking `PATH` is **wrong**. This is for binaries, not libraries.
* Checking `Z3_LIBRARY_PATH` is probably okay as this is a custom Z3 specific environment variable but I would still heavily discourage this because it can easily lead to some shooting themselves in the foot. I see no reason to support this environment variable.
* Checking `builtins.Z3_LIB_DIRS`... is this even legal?? I don't see why anyone would ever need this.
* Checking the current working directory seems pretty nasty and super fragile. This caused me to miss the fact that the z3 python package in the build tree **ONLY works if the current working directory is the `python` directory in the build tree**.

**Comment by wintersteiger** [comment]
The search paths are set up so that it finds the .dll/.so correctly for most users. I've recently changed z3core.py and cleaned up that part. We're still searching the same directories as always, albeit in a different order. The last resort is to ask the system to find it (`_lib = ctypes.CDLL('libz3.%s' % _ext)`). Searching the PATH is correct on Windows. `.builtins` is legal and recommended as a quick and dirty hack   for similar problems. I'm not considering any changes to this as I don't have time to re-fix all the problems Python users had with this in the past.

More to the point: why is pydoc trying to load libz3.dll?!

**Comment by wintersteiger** [comment]
Ah! I think I figured it out. All the paths are fine. In the past, the library was loaded upon the first use of a Z3 function, but after my recent changes it is loaded upon `import z3`. Pydoc likely runs the import, but then never uses any of the imported functions.

**Comment by wintersteiger** [comment]
From the [Python docs](https://docs.python.org/3.6/library/pydoc.html): 

> Note In order to find objects and their documentation, pydoc imports the module(s) to be documented. Therefore, any code on module level will be executed on that occasion. 

@delcypher could you add the build directory to the call to mk_api_docs.py via CMake? It already has the `-b` option, but it looks like it's not being set right.

**Comment by delcypher** [comment]
@wintersteiger 
>@delcypher could you add the build directory to the call to mk_api_docs.py via CMake? It already has the -b option, but it looks like it's not being set right.

#1355 makes the change you requested. The build directory was never passed previously because it was not needed.

**Comment by delcypher** [comment]
@wintersteiger 

>The search paths are set up so that it finds the .dll/.so correctly for most users.

If you have the time I'd like you clarify exactly what use cases you are expecting the Z3 python bindings to be used in. The current solution is neither simple (IMHO) nor correct.

As I said earlier, I expect the libz3 library (at least from the build system perspective) to only reside in two possible places, in the build tree, and in the install tree. There might be an additional location if for some reason binary distributions that you make are packaged differently.

> I've recently changed z3core.py and cleaned up that part. We're still searching the same directories as always, albeit in a different order.

The current order is **wrong** and is missing a path. For the CMake build system you **need** PR #1351 and for the order to be changed so that the bindings in the build directory use the correct libz3. Right now if there's an installed copy that will be used in instead which is non-intuitive if you're trying to use the Z3 bindings that were just built.

> The last resort is to ask the system to find it (_lib = ctypes.CDLL('libz3.%s' % _ext)).

> Searching the PATH is correct on Windows.

Ah I see [Windows does this](https://msdn.microsoft.com/en-us/library/7d83bc18.aspx). Yuck. Windows is not the only operating system out there so `PATH` should not be used on non-windows platforms.

> .builtins is legal and recommended as a quick and dirty hack for similar problems.

After a bit of googling I eventually found https://stackoverflow.com/a/28389678/635367 . I wouldn't
say this counts as "recommended", do you have another source that's a bit more official?

Dirty hack aside, why do we even need this? I am not seeing a compelling use case here. Why would you ever want to load a different libz3 to the one that the bindings were explicitly built to use.

> I'm not considering any changes to this as I don't have time to re-fix all the problems Python users had with this in the past.

Granted maintenance time is a consideration here. However if these use cases are so important why not have some sort of regression test for them? If we don't have tests for these use cases either

* Development will be by hindered by us being unwilling to make code changes due to fear of breaking untested configurations.
OR
* The code will be changed anyway and this will likely eventually break these use cases without us realising.

**Comment by wintersteiger** [comment]
There is no correct or incorrect here. Different people will copy the files into different directories, sometimes manually, sometimes via package managers. It's fine to add a missing path if it helps you, but it would only create unnecessary trouble to remove paths. 

Users copy files around manually, they don't use CMake to build or to install, so we have to have a way to let them tell us exactly where they expect the library. In the past that was done via `init(...)`, but I removed that because it created a bunch of trouble with the garbage collector (_lib being collected at the wrong time), plus I'm not aware of any users re-initializing via `init(...)`. Most recent example of usage of `init(...)` is #1348, where the user wants to use libraries from a binary/nightly release without building or installing anything.

In general, mk_api_doc.py does not need to be in the CI runs. It's used one per year by myself, and everybody else goes to the webpage. So, I'd rather dirty-hack it instead of spending hours to fix it. 

If you have time to spend on this, feel free to propose a solution that fixes all of this without breaking any existing or future installations, but it will be a rough ride with lots of bug requests to answer soon after it gets merged...

**Comment by delcypher** [comment]
> There is no correct or incorrect here. Different people will copy the files into different directories, sometimes manually, sometimes via package managers. It's fine to add a missing path if it helps you, but it would only create unnecessary trouble to remove paths.

I would argue that freshly built Z3 bindings (i.e. in the build tree) using a completely different libz3 by default is incorrect. That is what happens right now.

> Users copy files around manually, they don't use CMake to build or to install, so we have to have a way to let them tell us exactly where they expect the library.

Sure, users don't have to use CMake or run the `install` target. However this does not stop us from mandating where `libz3` resides. It would simplify things greatly if the path to `libz3` is just computed relative to where the Z3 python bindings live. This is portable and greatly reduces the number of paths to consider.


> In the past that was done via init(...), but I removed that because it created a bunch of trouble with the garbage collector (_lib being collected at the wrong time), plus I'm not aware of any users re-initializing via init(...). Most recent example of usage of init(...) is #1348, where the user wants to use libraries from a binary/nightly release without building or installing anything.

My proposal still works in that case.

> In general, mk_api_doc.py does not need to be in the CI runs. It's used one per year by myself, and everybody else goes to the webpage. So, I'd rather dirty-hack it instead of spending hours to fix it.

I think it's good that `mk_api_doc.py` is run in CI. Doing so caught an issue exactly as I intended it to.
At some point I'd like to have the result of this build uploaded to GitHub so the generated docs are up-to-date but I've not found time to do this yet.

> If you have time to spend on this, feel free to propose a solution that fixes all of this without breaking any existing or future installations, but it will be a rough ride with lots of bug requests to answer soon after it gets merged...

I don't have much time right now but when I have time I can create a PR.

**Comment by NikolajBjorner** [comment]
API doc is built by nightly.yaml
