### ISSUE TITLE
Java API Set methods, the return type is to general

### ISSUE THREAD

**Issue by bmaderbacher** [Z3Prover/z3#137]
In the Java API all set factory methods from `Context` return a simple `Expr`. Even `mkSetMembership` or `mkSetSubset`, which should return `BoolExpr`. 

If you now want to use this expressions as parameters for e.g. `mkAnd` - a method that expects `BoolExpr` as parameters - you need an explicit down cast. This makes the API usage look unsafe in Java.

I'm currently using wrapper functions that to the casting for me, but I think this should done right in the official API. 
It might also be a good idea to change all parameters and return types to `ArrayExpr`, but as sets are mostly used in set expressions this doesn't bother me that much.

The problem doen't exist in the C API, because there is only a single expression type.

**Comment by wintersteiger** [comment]
Yes, the return value for those functions should indeed be changed. Since we have SetSort, I guess we could also add SetExpr, but that may pose some challenges as they are internally represented by ArrayExprs, so we may not be able to determine the right type in all cases.

Note to self: this applies to the Python, .NET, and Java APIs.

Currently super busy with other stuff, it might be another week until I can fix that, so for now keep the casts on your code's side.

**Comment by wintersteiger** [comment]
This is now fixed. I've adjusted the return types to ArrayExpr as that is what they are represented as internally.
