### ISSUE TITLE
CMake cleanliness check

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#1384]
CMake says 

```
CMake Error at src/util/CMakeLists.txt:2 (message):
  "F:/dev/z3-cruanes/src/util/version.h" should not exist and is polluting
```

@delcypher: I need both build systems, how do I tell cmake not to worry?

**Comment by NikolajBjorner** [comment]
Run git clean -fx src

**Comment by delcypher** [comment]
@wintersteiger This was a deliberate design decision on my part. This is designed to avoid "shooting yourself in the foot". Build systems in general shouldn't emit build tree files into the source tree because
that prevents the same source tree from being used by multiple used for multiple different build configurations.

The bigger concern here though is I didn't want the generated build files from the python build system screwing up the CMake build. `version.h` is one such file. If we allowed this file to exist the `version.h` file generated by the python build system would end being up in the CMake build, which is completely wrong. This isn't so bad for `version.h` but there are other more important files generated by the build system which would cause havoc.

I deliberately included **NO CONVENIENT WAY TO DISABLE** the behaviour you're seeing because allowing the user to continue is simply too dangerous. If "you know what you're doing"(tm) the CMake code can be modified to remove those checks.

The full error message should be something like...

```
  " F:/dev/z3-cruanes/src/util/version.h should not exist and is polluting the source tree."
  " It is likely that this file came from the Python build system which"
  " generates files inside the source tree. This is bad practice and the CMake"
  " build system is setup to make sure that the source tree is clean during"
  " its configure step. If you are using git you can remove all untracked files"
  " using ``git clean -fx``. Be careful when doing this. You should probably use"
  " this with ``-n`` first to check which file(s) would be removed."
)
```

As the code suggests you can run `git clean -fx` to remove the files generated by the Python build system.

Another way to do this is use the git's worktree feature.

```
git worktree add ../path branch_name
```

`../path` will be contain a the Z3 repo in a new branch named "branch_name".

Using git worktrees may be more trouble that its worth though.

**Comment by wintersteiger** [comment]
Sorry, git clean is not an option for me. I have all kinds of files around that aren't checked into the repository. I usually manage quite well without a nanny.

**Comment by delcypher** [comment]
@wintersteiger Another way to handle this (which is what I did when the CMake build system was first being developed) is to simply have the Z3 repository cloned twice. I exchanged changes between the copies by adding a local remote.

```
# Make two copies
$ git clone git@github.com:Z3Prover/z3.git copy1
# Reference is just to save disk space. You can omit it if you want
$ git clone git@github.com:Z3Prover/z3.git --reference ./copy1 copy2

# Add a remote named "copy2" to the "copy1" repo so it can fetch/pull from it
$ cd copy1
$ git remote add copy2 $(realpath ../copy2)
$ git remote -v
copy2	/home/dan/dev/z3/XXX/copy2 (fetch)
copy2	/home/dan/dev/z3/XXX/copy2 (push)
origin	git@github.com:Z3Prover/z3.git (fetch)
origin	git@github.com:Z3Prover/z3.git (push)
# We can now do `git fetch copy2` and `git pull copy2 <branch_name>`


# Add a remote named "copy1" to the "copy2" repo so it can fetch/pull from it
$ cd ../copy2
$ git remote add copy1 $(realpath ../copy1)
copy1	/home/dan/dev/z3/XXX/copy1 (fetch)
copy1	/home/dan/dev/z3/XXX/copy1 (push)
origin	git@github.com:Z3Prover/z3.git (fetch)
origin	git@github.com:Z3Prover/z3.git (push)
# We can now do `git fetch copy1` and `git pull copy1 <branch_name>`
```

Note you can't push to "copy1" or "copy2" but you can fetch from it. This is useful if you want to keep local only changes sync'ed between the repositories.

**Comment by NikolajBjorner** [comment]
The legacy build configurator mixes input and outputs of the compiler in the same directories. I can't think of a real benefit to this, while having the output in designated folders has benefits, such as very easy cleaning and separation of builds. The cmake system does not prevent auxiliary files, other than ones where the include paths would cause ambiguities. The legacy build configurator isn't compelling compared to cmake, which supports a very flexible set of back-end build systems and it will be awesome  when we can properly sunset those parts of the legacy configurator that deal with build configuration.

**Comment by NikolajBjorner** [comment]
I don't see a reason to address this issue given that one can git clone separately if building for cmake vs. building for the legacy build system.
