### ISSUE TITLE
Strange behavior with string equality and inequality

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1389]
Hi, I have a simple query that **gets solved just fine**:

    (set-logic QF_S)
    (declare-const sj String)
    (declare-const si String)
    (declare-const sk String)
    (declare-const i     Int)
    (declare-const j     Int)
    (declare-const k     Int)
    
    (assert (= i  (str.indexof si "#"    0)))
    (assert (= j  (str.indexof si "$"    0)))
    (assert (= k  (str.indexof si "@"    0)))
    (assert (= -1 (str.indexof si "\x00" 0)))
    (assert (< 3 i))
    (assert (< i j))
    (assert (< j k))
    (assert (= (= sj "TT8G") true))
    
    (check-sat)
    (get-value (sj si i j k))

Here is the output:

    sat
    ((sj "TT8G")
     (si "aaaaaaaaa4#aaaaaaaam$@aaaaa\x06#@aaaaaaaay$aam")
     (i 10)
     (j 20)
     (k 21))

However, **when I change the constraint on sj**,
and make it different than "TT8G", **Z3 is stuck**:

    (set-logic QF_S)
    (declare-const sj String)
    (declare-const si String)
    (declare-const sk String)
    (declare-const i     Int)
    (declare-const j     Int)
    (declare-const k     Int)
    
    (assert (= i  (str.indexof si "#"    0)))
    (assert (= j  (str.indexof si "$"    0)))
    (assert (= k  (str.indexof si "@"    0)))
    (assert (= -1 (str.indexof si "\x00" 0)))
    (assert (< 3 i))
    (assert (< i j))
    (assert (< j k))
    (assert (= (= sj "TT8G") false))
    
    (check-sat)
    (get-value (sj si i j k))

**Comment by NikolajBjorner** [comment]
@mtrberzi set-logic QF_S invokes z3str3.

**Comment by mtrberzi** [comment]
I compiled the latest Z3 as a debug binary and got an assertion violation on the first instance (which should be solved). I'm investigating.

**Comment by mtrberzi** [comment]
The assertion violation is related to a known issue involving binary search length testing in z3str3. I think I'm going to disable that temporarily until I have time to resolve it properly (there's a theoretical issue that needs to be thought about, and I don't know when I will have time to address it).

Otherwise the latest build using z3str3 is able to solve both versions of the instance quickly.

**Comment by NikolajBjorner** [comment]
@mtrberzi There seems to be a regression in z3str3. It throws a stack-overflow during model generation in when commenting out the last assert.

**Comment by mtrberzi** [comment]
I'll look into this today.

**Comment by mtrberzi** [comment]
I can't reproduce a stack overflow, but I did find an issue where the wrong answer is being returned for the unmodified instance. The first bad commit seems to be 54b00f35. I'm investigating further.

**Comment by mtrberzi** [comment]
I found something else weird when replacing the last assert with similar terms: using the form `(assert (= (= sj "TT8G") true))` causes problems, but the equivalent `(assert (= sj "TT8G"))` does not. Is it possible that the core solver isn't properly sending this equality to theory_str?

(I can't confirm this for myself, because I can't reproduce the defect in debug/trace builds...)

**Comment by mtrberzi** [comment]
Fixed! The new model construction algorithm clears up the assertion violation.
