### ISSUE TITLE
Compiling Z3 with ocaml-bindings does not work anymore

### ISSUE THREAD

**Issue by mthark** [Z3Prover/z3#1393]
Dear Z3 developers,
Since the beginning of this week I can not compile Z3 with ocaml-bindings anymore. I get the following error:
ocamlc  -I api/ml -o api/ml/z3.cmi -c api/ml/z3.mli
ocamlc  -I api/ml -o api/ml/z3.cmo -c ../src/api/ml/z3.ml
File "../src/api/ml/z3.ml", line 1986, characters 6-34:
Error: Unbound value Z3native.parse_smtlib_string
Hint: Did you mean parse_smtlib2_string?
I tried to install Z3 via this git-repository and via opam and got the same error in each case. How can I resolve this error?
Thank you for your help.

**Comment by NikolajBjorner** [comment]
Could you remove the parse_smtlib references and add a pull request that builds. I don't have a good way of testing the ocaml bindings.

**Comment by delcypher** [comment]
@mthark Ah this will be the recent changes in #1381 that removed the support for parsing the SMT-LIB v1 files.

This wasn't caught because the continuous integration (CI) I implemented doesn't test the OCaml bindings. This is because the CI uses CMake exclusively which doesn't support building the OCaml bindings (yet).

Perhaps this is the motivation I need to finally implement this...

**Comment by NikolajBjorner** [comment]
Note: I have now removed the deprecated functions, but cannot check locally check it with my current setup.

**Comment by mthark** [comment]
Thank you for your help, it works now.
