### ISSUE TITLE
Prefix for MSYS2

### ISSUE THREAD

**Issue by eactor** [Z3Prover/z3#1403]
MSYS2 should have a prefix option, if you agree I will try to provide a pull request.

**Comment by wintersteiger** [comment]
Not sure I understand what you mean. Doesn't the existing installation prefix work for MSYS2?

**Comment by eactor** [comment]
os.name returns 'nt' using mingw-w64-x86_64-python on a  MingW64 shell. 

The prefix is working or at least it is a more general problem, but discovered it during the --help message of the python script  where the prefix option is not shown if the "wrong" python is used. 
Depending on the python used the script fails to determine the right system type.

Two distingt python versions:

pacman -S mingw-w64-x86_64-python
vs.
pacman -S python

Depending on which shell is used on or the other python will be found in the Path.

One could explicitly use /usr/bin/python to start the MSYS Python while running a MINGW64 shell, unsure if that has other consequences.

**Comment by wintersteiger** [comment]
All this business is a huge mess and I'm inclined not to support anything but the most basic default-installation. 

The `--prefix` option is definitely shown in `--help` on every platform except Windows. If it didn't show for you and if os.name returns `nt`, the problem is that you're using a Windows-Python in the MSYS+friends shells. The right versions return `MSYS_NT` or `MINGW` (which the scripts detect correctly). 

Clearly, we can't support the cross product of Pythons and MSYS/MinGW setups, the user will just have to run the "right" Python. We could try to emit warning messages when we detect some non-trivial combination of tools, but I'm not sure it's worth the effort.

**Comment by eactor** [comment]
I agree that the msys world with mingw is a mess, but I think the point is asking python for os.name is the wrong thing to destinguish between windows and linux. 

"most basic defaul-installation" isn't that easy, **installation is for all the same**, after that it totally depends on which shell is started and out of my experience this would be the MINGW64 shell. 

Cmake  for example has build in variables MINGW and WIN32 where only one can be true.

**Comment by eactor** [comment]
How about 
os.name('NT') and (NOT os.environ['MSYSTEM'].startswith('M') )

MSYS sets this varialbe to MSYS or MINGW64 depending on the shell.

**Comment by eactor** [comment]
@26b1f25

Python Documentation: 
     os.uname() -> Availability: recent flavors of Unix.
     platform.uname() -> Fairly portable uname interface.  Note that unlike the os.uname() function this also returns possible processor information as additional tuple entry.

To destiguish between Windows and MingW64 i would suggest the MSYSTEM enviroment variable os.environ[]

**Comment by wintersteiger** [comment]
All of those are currently or have been used for platform detection in the past.  I would recommend not to touch any pieces of the scripts that depend on `nt`, otherwise some or all Windows builds will break. In my opinion we should start by simply issuing a warning message when we think that the user uses a Windows-Python (`nt`) in an MSYS/MinGW shell. 

Note that all changes to the scripts have to work and be tested using Python 2.x and 3.x too, so that may put another level of complication on top of the platform detection.

**Comment by NikolajBjorner** [comment]
seems obsolete
