### ISSUE TITLE
spurious (push) makes z3 return unknown instead of unsat

### ISSUE THREAD

**Issue by ciobaca** [Z3Prover/z3#1406]
The following code returns unknown because of the "(push)" command.

Removing the (push), which is not used anyway, makes the code return unsat.

I would expect z3 to return unsat even in the presence of the push.

```
(declare-const x Int)
(declare-const y Int)
(declare-const z Int)

(push)
(assert (
		 and 
				(exists ((xp Int)) (= x (* 2 xp))) 
				(not (exists ((xp Int)) (= y (* 2 xp))))
				(= z (+ x y))  
				(exists ((xp Int)) (= z (* 2 xp)))
			 
		)
)

(check-sat)
;;(pop)

```

**Comment by wintersteiger** [comment]
This is a frequently reported issue; the problem is that the first occurrence of a push/pop makes Z3 switch to a completely different solver that supports incrementality. Before that, Z3 assumes that it won't need those features and it can thus run different, non-incremental algorithms. If you need the incremental features, you can add a (push) into every file you emit, thus you will always experience the performance of the incremental solver during development. Obviously, if you don't need those features, don't use them :-)
