### ISSUE TITLE
Question about finding all possible solution of simple equation using Z3 in Windows 10, VS2013

### ISSUE THREAD

**Issue by leesanghun910701** [Z3Prover/z3#1409]
Dear all,

I am sorry to again upload this one,

but I made some progress on my previous question based on what wintersteiger advised.

Again, here is the problem set that I want to solve.

** problem set: what is the possible combination of a, b, c that satisfies a + 2b + 3*c = 7?

So I made below C code, based on the C code example of Z3,

![capture1](https://user-images.githubusercontent.com/32499009/34125895-ca3861d2-e405-11e7-92b0-9b34876d6e62.PNG)

The result of running the code is as follows:

![capture2](https://user-images.githubusercontent.com/32499009/34125906-d4556462-e405-11e7-8488-598ccd5a690e.PNG)

However, it seems that the C code I wrote does not consider the case of
[a = 1, b= 0, c = 2] or [a = 1, b = 3, c = 0] and so on.

Can you give any advice on how to revise my Z3 code?

I'm sorry for you to spend so much of your valuable time on this issue.

Thank you very much in advance.

For your information, here is the code:

`
void example()
{
	Z3_context ctx = mk_context();
	Z3_solver  s = mk_solver(ctx);
	Z3_model m = 0;
	Z3_ast a, b, c, b_mul_two, c_mul_three, zero, two, three, seven, sum;
	Z3_ast args2[2], args3[3];
	Z3_ast c1, c2, new_constraint[3], new_constraint_and;
	Z3_ast a_new, b_new, c_new, a_eq_new, b_eq_new, c_eq_new;
	unsigned num_constants, i, iter;

	a = mk_int_var(ctx, "a");
	b = mk_int_var(ctx, "b");
	c = mk_int_var(ctx, "c");
	
	zero = mk_int(ctx, 0);
	two = mk_int(ctx, 2);
	three = mk_int(ctx, 3);
	seven = mk_int(ctx, 7);
	
	args2[0] = b;
	args2[1] = two;
	b_mul_two = Z3_mk_mul(ctx, 2, args2);
	
	args2[0] = c;
	args2[1] = three;
	c_mul_three = Z3_mk_mul(ctx, 2, args2);

	args3[0] = a;
	args3[1] = b_mul_two;
	args3[2] = c_mul_three;
	sum = Z3_mk_add(ctx, 3, args3);

	c1 = Z3_mk_eq(ctx, sum, seven);
	Z3_solver_assert(ctx, s, c1);

	c2 = Z3_mk_ge(ctx, a, zero);
	Z3_solver_assert(ctx, s, c2);

	c2 = Z3_mk_ge(ctx, b, zero);
	Z3_solver_assert(ctx, s, c2);

	c2 = Z3_mk_ge(ctx, c, zero);
	Z3_solver_assert(ctx, s, c2);

	iter = 0;
	while (Z3_solver_check(ctx, s) == Z3_L_TRUE){
		
		// find solution for the model
		m = Z3_solver_get_model(ctx, s);
		printf("model for: a + 2*b + 3*c = 7 (loop: %d)\n", iter);
		printf("%s\n", Z3_model_to_string(ctx, m));

		
		// Create the finded solution as new constraints to the model
		// (for each variable a, b, c)
		num_constants = Z3_model_get_num_consts(ctx, m);

		for (i = 0; i < num_constants; i++) {
			Z3_symbol name;
			Z3_func_decl cnst = Z3_model_get_const_decl(ctx, m, i);
			Z3_ast k, v;
			Z3_bool ok;

			name = Z3_get_decl_name(ctx, cnst);
			Z3_string str = Z3_get_symbol_string(ctx, name);
			
			char* var_name = (char*)*str;

			k = Z3_mk_app(ctx, cnst, 0, 0);
			v = k;
			ok = Z3_model_eval(ctx, m, k, 1, &v);
			Z3_string val = Z3_get_numeral_string(ctx, v);

			int var_val;
			var_val = (int)*val - '0';
			
			if (strcmp(&var_name, "a") == 0){
				a_new = mk_int(ctx, var_val);
			}
			else if (strcmp(&var_name, "b") == 0){
				b_new = mk_int(ctx, var_val);
			}
			else if (strcmp(&var_name, "c") == 0){
				c_new = mk_int(ctx, var_val);
			}
			else{
			}
		}

		a_eq_new = Z3_mk_eq(ctx, a, a_new);
		b_eq_new = Z3_mk_eq(ctx, b, b_new);
		c_eq_new = Z3_mk_eq(ctx, c, c_new);

		new_constraint[0] = Z3_mk_not(ctx, a_eq_new);
		new_constraint[1] = Z3_mk_not(ctx, b_eq_new);
		new_constraint[2] = Z3_mk_not(ctx, c_eq_new);

		new_constraint_and = Z3_mk_and(ctx, 3, new_constraint);
		
		// Add a new contraint to the existing model(?)
		Z3_solver_assert(ctx, s, new_constraint_and);

		iter++;
	}

	del_solver(ctx, s);
	Z3_del_context(ctx);
}

int main() {
#ifdef LOG_Z3_CALLS
    Z3_open_log("z3.log");
#endif
    example();
    return 0;
}
`

**Comment by NikolajBjorner** [comment]
Sorry, Ihave 0 bandwidth for providing feedback at this level. 
Also, really don't use the C API for applications. It is for low level interfacing with Z3.

**Comment by leesanghun910701** [comment]
Thank you very much for your reply.

Can you tell me anyone who can help me on this issue,

or at least open this issue for future help?

Thank you.

**Comment by NikolajBjorner** [comment]
There is already a stackoverflow question on this from you and StackOverflow is the right place for questions like these. It isn't a Z3 bug/issue.

**Comment by wintersteiger** [comment]
You're very close to a working solution! The bits around `var_val` seem unnecessarily complicated; you already have the numeral in the variable `v` and you can use that as is, no string conversions are needed, e.g. `a_new = v` should do just fine. Also, instead of the `*_new` variables you could just keep a single `Z3_ast` and then, in each iteration, just `Z3_mk_and(...)` the new inequality. 

In general, when working with the C API, you are responsible for the reference counting of expressions, i.e., every time Z3 returns a Z3_ast (and many of the other Z3_* object types), you have to call `Z3_inc_ref` on it and once your code is done with an expression, you have to call `Z3_dec_ref` on it. This is not optional. Without that, you will get segfaults and incorrect results very often, so fix this first. Or, use one of the higher-level APIs for prototyping (e.g. the C++ API has the `expr` class that takes care of this for you).

**Comment by wintersteiger** [comment]
As for the unexpected early termination: instead of sat/unsat, Z3 can also return unknown, which would be the case if there is any problem with the current expressions you are using and this is likely what's happening here. So, perhaps it's best to save (and print) the return value of `Z3_solver_check` to make sure that's not a problem.
