### ISSUE TITLE
C++ API: z3::expr to int: conversion operator to int different than output to stream

### ISSUE THREAD

**Issue by daniel-j-h** [Z3Prover/z3#141]
Once I have a model, I want to get an assignment for a constant back into the C++ world, e.g. into an int. I took a look at 

* [the example.cpp file and](https://github.com/Z3Prover/z3/blob/31643a8f20a60ac8d9b6fef471a50b8602a595d3/examples/c%2B%2B/example.cpp#L57-L62)
* [this StackOverflow answer](http://stackoverflow.com/a/24263605)

but at least in this small self-contained test case the conversion to int is always 1:

https://gist.github.com/daniel-j-h/33d49c7f51dd74ea0cbc

What does work is the following:

    int out;
    Z3_get_numeral_int(context, model.get_const_interp(model.get_const_decl(i)), &out);

I'm not sure why the conversion operator comes up with this, as it should basically be the same, right?

I'm on branch qsat @31643a8. By the way, what happened to the opt branch which contained nuZ? I'm using the qsat branch because it has the optimizing feature in it. What is the qsat branch all about?

**Comment by daniel-j-h** [comment]
I'm not sure how to feel about this, but `Z3_get_numeral_int64` also does not work with `int64_t`:

> error: invalid conversion from ‘int64_t* {aka long int*}’ to ‘long long int*’ [-fpermissive]

That is, `long long int` works, but `int64_t` does not, although the function even has 64 in its name.

**Comment by NikolajBjorner** [comment]
Use unstable branch. Opt is fully merged with unstable. Qsat is for new module on quantiers, not ready for general use.

**Comment by NikolajBjorner** [comment]
int64_t requires additional includes that we don't have by default.
I will be adding helper functions that use __int64 and leave it to caller create additional wrappers for additional types.

**Comment by daniel-j-h** [comment]
Same issue on unstable branch at @f29d828 with the small self-contained example from above.

* output is 16 for the operator>> into ostream conversion.
* output is 1 for the operator int overload.

Conceptually this should always return the same, no matter if I'm piping it into std::cout or using the implicit to-int conversion, right?

**Comment by wintersteiger** [comment]
The example contains

    int x = model.get_const_interp(decl);

This is not how models work. A model assigns an `expr` to every constant (and other things), and the automatic cast from `expr` to `int` is misleading; there exists an automatic conversion to `bool` (see `ast::operator bool`) and then another one from `bool` to `int` (in the C++ standard/compiler), which is why it returns `1` (non-zero pointer casted to bool 1 then casted to int 1). In this case, a warning or error message would be helpful, but I'm not sure we can do that and at the same time keep `ast::operator bool`.

The output of `get_const_interp(...)` will usually be a numeral (can be checked via `.is_numeral()`) and we need to get the `int` out of the numeral `expr`, for instance like so

    z3::expr x = model.get_const_interp(decl);
    std::cout << x << std::endl; // OK, 16.

    int xi;
    Z3_get_numeral_int(x.ctx(), x, &xi);
    std:: cout << xi << std::endl; // Now xi is also 16.

**Comment by daniel-j-h** [comment]
Thanks for the implicit conversion clarification. This is indeed a bit misleading, as similar functions do quite different things (toStream vs toInt). I settled for the `Z3_get_numeral_int64` solution!
