### ISSUE TITLE
java use z3 ,only use your example?how use this in a java project?

### ISSUE THREAD

**Issue by GOGJIAN** [Z3Prover/z3#1422]
please help me ,thank you

**Comment by wintersteiger** [comment]
See [Java Example Readme](https://github.com/Z3Prover/z3/blob/master/examples/java/README). You need to add com.microsoft.z3.jar to your classpath and at runtime your system needs to be able to find a suitable libz3.dll/.so/.dylib and libz3java.dll/.so/.dylib, i.e., set up your PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH as instructed in the Readme. Make sure all .dll/.so/.dylib files are of the same bitness (32/64 bit) as your Java installation, otherwise the error message may report "can't load dll" without further clarification.
