### ISSUE TITLE
Generating Expr using the same context functions throws Context mismatch error

### ISSUE THREAD

**Issue by ionuttamas** [Z3Prover/z3#1490]
Using the NET Z3 library:

    using (var context = new Context())
    {
          var left = context.MkConst("left", context.RealSort);
          var right = context.MkNumeral("40", context.RealSort);
          var  result = context.MkLt((ArithExpr)left, (ArithExpr)right);  =>ERROR thrown: Context mismatch
       }

Checking the NativeObject for left and right variables, shows indeed diferent values.
How can this be solved?

**Comment by NikolajBjorner** [comment]
Can you provide a complete example?

The following works just fine:

     using Microsoft.Z3;

     class Program {
       public static void Main() {
   	using (var context = new Context()) { 
	var left = context.MkConst("left", context.RealSort); 
	var right = context.MkNumeral("40", context.RealSort); 
	var result = context.MkLt((ArithExpr)left, (ArithExpr)right); 
	System.Console.WriteLine($"{result}");
     }}}

**Comment by ionuttamas** [comment]
Is a more convoluted example, but the source code can be found here: https://github.com/ionuttamas/Prometheus. 
Running the _ReferenceProverTests/ReferenceProver_For_NestedIfElse_And_SatisfiableCounterpart_TracksCorrectly_ test (using NUnit) always yields that error, even though I am using the same context when creating the instances.

**Comment by NikolajBjorner** [comment]
Sorry, there are too many hoops in order to get this functional (hard-coded file paths, test over nunit that goes away after I change the project to x64/Debug). Stand-alone self-contained repros or even pointing out what is wrong with the API would be required. I reviewed the code in the API that is called in your example. In this case I cannot determine any bug. I don't see anything unusual about the way you use Z3 from .NET and other similar uses do not have issues with the contracts.

**Comment by ionuttamas** [comment]
The issue was due to a faulty usage of the Context: I have created multiple contexts and tried to combine the resulting Expr made by different contexts together.

**Comment by NikolajBjorner** [comment]
Good, then the contact did precisely what it was supposed to do.
