### ISSUE TITLE
Possible bug in int.to.str

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#1500]
Hi,
We are experimenting a little with the semantics of **int.to.str**, and we found this **weird behavior** that **looks like a bug**. Here is the first query that works OK:

    (declare-const s String)
    (declare-const i    Int)
    
    (assert (< i -2))
    
    (assert (= s (int.to.str i)))
    (assert (< 0 (str.len s   )))
    
    (check-sat)
    (get-value (s i))

And the result:

    sat
    ((s "-11")
     (i (- 11)))

When I change the '<' sign to '=' I get an unsat response:

    (declare-const s String)
    (declare-const i    Int)
    
    (assert (= i -2))
    
    (assert (= s (int.to.str i)))
    (assert (< 0 (str.len s   )))
    
    (check-sat)
    (get-value (s i))

Here is the result I get:

    unsat
    (error "line 10 column 16: model is not available")

Am I missing something here? Thanks!

**Comment by NikolajBjorner** [comment]
thanks yes this was a bug

**Comment by NikolajBjorner** [comment]
Both examples should be unsat. 

The (draft?) semantics has the "int.to.str" of a negative number is the empty string.
Thus, we have the axiom 

       (forall ((x Int)) (=> (< x 0) (= "" (int.to.str x)))

In previous oversions, Z3 would convert negative numbers to a signed string representation. 
As you can observe, several bugs were introduced in Z3 when adapting the semantics where
negative numbers don't produce strings. 

Quoting from the draft spec that Cesare prepared very carefully a while ago (the name str.from-int was later changed to int.to.str):

;---------------------------
; Maps to and from integers
;---------------------------

 :fun (
  ; Digit check
  ; (is-digit s) is true iff s has length 1 and its character is a decimal digit.
  ; Total
  (is-digit String Bool)

  ; Conversion to integers.
  ; (str.to-int s) with s consisting of digits is the corresponding natural number.
  ; Otherwise, it is -1. 
  ; Total
  (str.to-int String Int)

  ; Conversion from integers.
  ; (str.from-int n) with n non-negative is the corresponding string in decimal
  ; notation. Otherwise, it is the empty string. 
  ; Total
  (str.from-int Int String)
 )
