### ISSUE TITLE
Conflicting assertions over lists come out as satisfiable

### ISSUE THREAD

**Issue by vimuel** [Z3Prover/z3#1515]
Is this a bug or am I missing something?

```lisp
(declare-const blah (List Int))
(assert (= (head blah) 1))
(assert (= blah nil))
(check-sat)
sat
```

**Comment by NikolajBjorner** [comment]
Accessor functions on matching constructors are defined as you would expect, so a head of a cons(x,y) returns x. But accessor functions on non-matching constructors, e.g., head(nil) are _underspecified_, in other words their meaning is not fixed by the theory. So it is possible to have head(nil) be 1 or 2 (but not both).

**Comment by vimuel** [comment]
This is strange and unexpected:
```lisp
(declare-datatypes ((X 0)) (((A) (B) (C))))
(declare-const blah (List X))
(assert (= (head blah) A))
(check-sat)
(eval blah)
nil ; !?
```
 In CVC4 I get the expected singleton list.

**Comment by NikolajBjorner** [comment]
still, this is consistent with the semantics that accessors on non-matching constructors are uninterpreted. The model is legal.

**Comment by vimuel** [comment]
So to ensure this doesn't happen, I always need to `(assert (> (length blah) 0))`?

It might be useful to add this information to the documentation. Do you accept pull requests for the documentation?

**Comment by NikolajBjorner** [comment]
Sure, but it follows SMT-LIB2.6, http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf, page 77.

**Comment by vimuel** [comment]
Thank you for the clarification.
