### ISSUE TITLE
Assigning a value to function based on that function value gives unexpected results.

### ISSUE THREAD

**Issue by SMTStuck** [Z3Prover/z3#1524]
A bit of a mouthful title, and truth be told I'm unsure if this is a bug in the program or a bug in my thinking.

```
(declare-fun Temp () Int)
(assert(= Temp (ite (= Temp 0) 1 Temp)))
(check-sat)
(get-model)
(exit)
```

Initially:
> (-INF < Temp < INF)

So, I would expect the evaluation of 
> (= Temp 0)

To come first, and as it is true, the assertion used is:
> (assert(= Temp 1 ))

Instead, it would seem Temp is being assigned any value (albeit a constant one on each run of the program), which would lead me to believe that the assertion that is being applied is:
> (assert(= Temp Temp))

However, if using bools instead of Int:

```
(declare-fun Temp () Bool)
(assert(= Temp (ite (= Temp false) true Temp)))
(check-sat)
(get-model)
(exit)
```

Does give the correct result and Temp can only be true.

What is the cause of this?

**Comment by OrenGitHub** [comment]
@SMTStuck , any Temp value other than 0 will satisfy your query ... you're simply telling the solve that if Temp is zero, flip it to one, and otherwise don't change it. So clearly, **Temp = ..., -5, -4, -3, -2, -1, 1, 2, 3, 4, ... will solve it**. Since Bool is either true or false, you'll have **just Temp=true** satisfying the query ...

**Comment by SMTStuck** [comment]
Bug in my thinking.... I was under the impression that (= Temp 0) would be true initially (as Temp is unconstrained), and so would then be constrained to 0...
