### ISSUE TITLE
Deprecation notices

### ISSUE THREAD

**Issue by waywardmonkeys** [Z3Prover/z3#1525]
In the C API, some functions are marked as deprecated:

* `Z3_mk_config`
* `Z3_del_config`
* `Z3_set_param_value`
* `Z3_mk_context`
* `Z3_update_param_value`

Notably, `Z3_mk_context_rc` is not deprecated.

But there's no way to create a `Z3_context` without creating a `Z3_config` object that I've seen.

The docs don't make it clear what the successor to these functions might be in all cases.

It might help to use compiler attributes to mark these functions as deprecated rather than only having it in the documentation comments as well?

I'm happy to submit a pull request for any of the above things, I just need to know what is best to do.

**Comment by NikolajBjorner** [comment]
they are in fact not deprecated and I don't see a reason to deprecate them given how they are used.
Z3_mk_context was introduced when we did not have solver objects, then reference counting was handled internally and based on user scopes. It remains useful to apply Z3_mk_context for basic uses of the C API, because reference counting is so error prone when done manually.
Z3_update_param_value seems redundant given there is Z3_global_param_set.
The other API methods are used in many places and don't have replacements.

**Comment by waywardmonkeys** [comment]
Okay, so a patch that removes the `\deprecated` marker from the API doc comments would be fine?

Should `Z3_set_param_value` and `Z3_update_param_value` remain deprecated?

**Comment by NikolajBjorner** [comment]
I updated the comment as I was not recalling the facts correctly
