### ISSUE TITLE
problems with solving linear equations

### ISSUE THREAD

**Issue by moliam** [Z3Prover/z3#1536]
First, I am new to Z3.... 
I did a test with Z3.  I have 50 linear equations with 50 variables to be solved, and it  is quick for Z3 to give the answer. However, if I give 49 linear euqations with 50 variables(just remove one from the 50 equations), the solving time increases significantly. Why ?  
I know that mathematically there are actually infinite number of solutions to the latter situation,  is this the reason ?     When solving a set of constraints, would Z3 find as many as possible the satisfiable solutions or just find one of them ?

**Comment by NikolajBjorner** [comment]
Sometimes solutions or proofs of non-solutions to combinatorial problems can be very difficult to find. 
For example, if you encoding the following problem into propositional satisfiability: 

             fit N pigeons into M holes, no hole may contain two pigeons.

Alternatively, you have a shoe closet and your shoes are very fashionable, so you are only willing to fit one shoe per shelf in the closet. You ahve N shoes and M shelves. 

If you set N = M + 1, the problem is unsolvable. If you have N <= M, the problem is solvable.
The time taking to find solutions for N <= M tends to be really quick. 
The time taking to find solutions for N > M, especially for N = M + 1, can be extremely high for SAT solvers.

Similarly, the integer solver may struggle when seemingly similar problem are easy. 
This holds particularly for problems that you create using a random problem. Z3 is not at all a solver for randomly generated problems.
