### ISSUE TITLE
Z3 answers a question with a question.

### ISSUE THREAD

**Issue by bj2015** [Z3Prover/z3#1550]
I stumbeled upon the following phaenomenon quite by accident:

I wanted to ask Z3 the following question:

question.smt2:
```
(set-option :produce-models true)

(declare-const b Bool)

(assert (= b (not (exists ((A Bool) (B Bool)) (= A B)))))

(check-sat)

(get-value (b))

(exit)
```

However, `z3 -smt2 question.smt2` yields the following output:
```
sat
((b (not (exists ((A Bool) (B Bool)) (= A B)))))
```

which is, in essence, not an answer, but my question. According to the SMTLIB specification, get-value is supposed to return a "value-term" for each given expression. For a boolean variable (b), I would have expected the result to be either "true" or "false", but not a formula, especially not one that contains quantifiers...

Could someone please help me figure out what is going on?

I am using Z3 version 4.6.0 - 64 bit on macOS Sierra Version 10.12.6 (16G1212).

**Comment by NikolajBjorner** [comment]
It uses a pre-processing pass to solve equalities. You can disable the pre-processing by adding a (push) or you can replace the check-sat call with (check-sat-using smt), which disables the part that solves for b.

**Comment by bj2015** [comment]
Thanks, yes that seems to work.

Just out of curiosity: Is it not possible to check whether or not the preprocessing succeeded to derive proper values for the boolean variables? (IMHO both quantifiers and variables on the RHS should indicate failure in that respect)

**Comment by NikolajBjorner** [comment]
Seems to a question of what defines a certificate for satisfiability. It isn't a constructive certificate in that only one possible value of b is possible in this case, but it is a certificate because the RHS has some value, and whatever value it is, becomes the value of b. In the case this isn't workable for an application, one approach is to introduce a configuration option that prevents the solve-eqs tactic from solving equalities that have right-sides with quantifiers.

**Comment by bj2015** [comment]
Agreed.

Such a configuration option would definitely be a solution. Until it is availlable, I will use the workarounds you mentioned earlier. Thanks!
