### ISSUE TITLE
Persist (define-fun ...) definitions between Z3_solver_from_string calls

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#1593]
When calling the following method using the solver fromString method the (define-fun ...) instances do not persist (Can't be used in later fromString methods or using mkFunc). Is there any way to persist these between calls?

`/** Set up trim methods **/
 this.slv.fromString( 
            "(define-fun isWhite ((c String)) Bool (or (= c \" \") (= c \"\t\")))\n" +
            "(define-fun-rec whiteLeft ((s String) (i Int)) Int (if (isWhite (str.at s i)) (whiteLeft s (+ i 1)) i))\n" +
            "(define-fun str.trimLeft ((s String)) String (str.substr s (whiteLeft s 0) (- (str.len s) (whiteLeft s 0))))\n" +
            "(define-fun-rec whiteRight ((s String) (i Int)) Int (if (isWhite (str.at s i)) (whiteRight s (- i 1)) i))\n" +
            "(define-fun str.trimRight ((s String)) String (str.substr s 0 (+ (whiteRight s (- (str.len s) 1)) 1)))\n" +
            "(define-fun str.trim ((s String)) String (str.trimRight (str.trimLeft s)))\n");`

**Comment by NikolajBjorner** [comment]
This is not a supported scenario for the fromString method.  You can add relevant declarations to the string. You can just use (declare-fun ...) instead of (declare-fun-rec ...) to ensure the declaration is available. 

With appropriate helper functions you should be able to define everything from expression builders. For recursive functions you are creating quantified axioms with the :recfun quantifier id.

**Comment by jawline** [comment]
Ok, thanks.
