### ISSUE TITLE
sort mismatch: expected Bool got Bool.

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#165]
Hi,

I am getting this error message from Z3, which seems to indicate a bug.

```
WARNING: invalid function application for and, sort mismatch on argument at position 2, expected Bool but given Bool
WARNING: (declare-fun and (Bool Bool) Bool) applied to: 
true of sort Bool
(and (not (<= __ADDRESS_OF_main::sum 0::Int)) (= main::p __ADDRESS_OF_main::sum)) of sort Bool

Error: type error (Z3NativeApi.mk_and, SEVERE)
```

I am not sure how to give reproducible details... I'm having trouble locating the offending statement in my code, and Z3 logging feature does not seem to do much good for this case (when I try to replay the log, it just dies with "invalid pointer" somewhere near the very start).

**Comment by cheshire** [comment]
Actually, sorry, my bad, two formulas were from different contexts. The error message is still wrong though.

**Comment by wintersteiger** [comment]
Indeed, mixing contexts will throw unexpected error messages. At the level of the C API we can't check for that, because AST are just pointers, they do not come with an associated context pointer. In the higher level APIs like in C# we can and do check for such errors, e.g., Context.MkAnd(...) calls CheckContextMatch(...). Which API did you get this error from?

**Comment by cheshire** [comment]
Good point, I was using C API.
It could be still possible to make the error message more understandable (e.g. check whether sorts are compatible, and if they are, deduce that the context must be different).

**Comment by NikolajBjorner** [comment]
The C++ API is more suitable for this. 
It checks context compatibility and uses data-structures where contexts are embedded to avoid confusion.
