### ISSUE TITLE
windows.h could not be found

### ISSUE THREAD

**Issue by nasmdh** [Z3Prover/z3#1742]
Hello,
@ashalatha-0504
I am encountering the following error. Can someone help?
![image](https://user-images.githubusercontent.com/15107340/42454879-02f148d8-8391-11e8-9f28-b08238686ed4.png)

I already included the file path in the file, but it is complaining with other files. I am building the program on windows 10 x64 Intel Visual C++ 2015 x64 Native...

thank you

**Comment by NikolajBjorner** [comment]
Perhaps you need to run under the VS dev environment first.
You should set up a development shell for either x86 or x64. 
There should be a folder in your VS distribution with some pre-cooked scripts to set this up, otherwise, search for development prompts on the web, e.g., 
https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs

**Comment by nasmdh** [comment]
Thank you Nikolaj, I appreciate for the quick response.
I will try it out.

Best Regards,
Nesredin
