### ISSUE TITLE
Bit-vector regression

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#1754]
The following query took about 13 seconds on my Mac, using z3 built about a week ago, correctly answering `unsat`. A fresh build of z3 seem to go on it forever:

```
(set-option :produce-models true)
(set-logic ALL)
(declare-fun s0 () Int)
(define-fun s2 () Bool (<= 0 s0))
(define-fun s4 () Bool (< s0 256))
(define-fun s5 () Bool (and s2 s4))
(define-fun s6 () Bool (not s5))
(define-fun s7 () (_ BitVec 8) (let ((__a (mod s0 256))) (let ((__a0 (ite (= (mod __a 2) 0) #b0 #b1)) (__a1 (ite (= (mod (div __a 2) 2) 0) #b0 #b1)) (__a2 (ite (= (mod (div __a 4) 2) 0) #b0 #b1)) (__a3 (ite (= (mod (div __a 8) 2) 0) #b0 #b1)) (__a4 (ite (= (mod (div __a 16) 2) 0) #b0 #b1)) (__a5 (ite (= (mod (div __a 32) 2) 0) #b0 #b1)) (__a6 (ite (= (mod (div __a 64) 2) 0) #b0 #b1)) (__a7 (ite (= (mod (div __a 128) 2) 0) #b0 #b1))) (concat __a7 (concat __a6 (concat __a5 (concat __a4 (concat __a3 (concat __a2 (concat __a1 __a0))))))))))
(define-fun s8 () Int (+ (ite (= ((_ extract 0 0) s7) #b1) 1 0) (ite (= ((_ extract 1 1) s7) #b1) 2 0) (ite (= ((_ extract 2 2) s7) #b1) 4 0) (ite (= ((_ extract 3 3) s7) #b1) 8 0) (ite (= ((_ extract 4 4) s7) #b1) 16 0) (ite (= ((_ extract 5 5) s7) #b1) 32 0) (ite (= ((_ extract 6 6) s7) #b1) 64 0) (ite (= ((_ extract 7 7) s7) #b1) 128 0)))
(define-fun s9 () Bool (= s0 s8))
(define-fun s10 () Bool (or s6 s9))
(assert (not s10))
(check-sat)
```

I'm pretty sure this got broken in the last few days; based on Travis CI output.

The benchmark is essentially proving that any integer between @0@ and @255@ can be converted to an 8-bit vector and back using the obvious translation. (Repeated division to obtain the bits, and then add the powers per each blasted one bit.)

**Comment by NikolajBjorner** [comment]
@levnach can you take a look? After simplification, there are no bit-vectors and the problem is pure QF_LIA with mod/div operations. It uses the theory_lra.

**Comment by levnach** [comment]
I cannot reproduce it anymore.

I ran this benchmark on my Surface Pro 4 with smt.random_seed = 0 to 30. All instances were solved and none took more than 21 second. Most went faster than that.

**Comment by LeventErkok** [comment]
@levnach 

I've just done a fresh build on my Mac, and neither directly calling `z3`, not providing `smt.random_seed` helps; this benchmark still seems to run forever. I can post the output of "-v:10" if you like. (Or any other command line invocation, let me know.)

I know that it doesn't converge on Travic CI's Linux machines either.

(I haven't tried on Windows, I don't have easy access.)

**Comment by NikolajBjorner** [comment]
It runs forever on my end. The example exposes some other issues around how Z3 selects default tactics, but fixing this doesn't change the runtime behavior once we get to the main SMT solver. It is also a bit slow on the legacy arithmetic solver. It takes 30 seconds, and generally the ILP solver has to figure out various congruence and divisibility constraints for moduli 2, 8, up to 256.

**Comment by LeventErkok** [comment]
If it helps: I have a 2011 Mac; definitely not top of the line or anything, and z3 compiled on Jun26 goes through it in about 12 seconds:

```
$ time /usr/local/bin/z3_Jun26_2018 a.smt2
unsat
/usr/local/bin/z3_Jun26_2018 a.smt2  11.64s user 0.03s system 97% cpu 11.970 total
```

**Comment by levnach** [comment]
Ahh, sorry, I was running Z3Prover/z3, but branch "lev" .

**Comment by levnach** [comment]
I fixed a performance bug in lar_solver.h at line 115 where I returned an array by copy instead of reference, but it does not solve the problem. If I look at the statistics I see that in the current branch 
 :arith-max-columns              1613
 :arith-max-rows                 1551


This means that the matrix for the LP solver becomes much bigger comparing with about 400 X 300 matrices in the previous runs. Could it be a blowup in the amount of added terms?
I will debug more later.

**Comment by levnach** [comment]
My tests with going to the past with git show that at commit 2dfb8f53b62b2f72cfed0a536dbeabaa599d9e77 it worked. The next commit e0e893b791ce661e68d0a9943b2ac1614637a79f e0e893b79 ("fix in hnf for the lower bounds", 2018-07-11) it stopped working. It does make sense since a bug was fixed where the ILP solver was generating too strong cuts, so luckily producing "unsat". At this point I am not sure how to fix it since even disabling HNF cuts did not help.

**Comment by LeventErkok** [comment]
@levnach 

Out of curiosity, I just let it run and it finished in 22 minutes. At least it does eventually converge; but the performance hit is quite significant.

**Comment by levnach** [comment]
I investigated some more and maybe have found the reason of this behavior. I noticed that while solving this problem free variables are created in lar_solver. In the legacy solver before calculating a Gomory cut we would constrain all free variables by calling "constrain_free_vars()". I did not port this functionality and the current solver defaults to a branch instead of creating a cut when a free variable is found in the row. Nikolaj, what are your thoughts on it?

**Comment by LeventErkok** [comment]
@levnach @NikolajBjorner 

In case it helps: I'd be happy to run my test-suite on it, if you make the change and put it on a branch.

**Comment by levnach** [comment]
@NikolajBjorner, sure, it is my fork, the branch is "gomory". It gives me an assert currently.

**Comment by LeventErkok** [comment]
@levnach I was referring to your comment: 

> In the legacy solver before calculating a Gomory cut we would constrain all free variables by calling "constrain_free_vars()". I did not port this functionality and the current solver defaults to a branch instead of creating a cut when a free variable is found in the row. 

If you want to make that change in a branch and give it a test run, I'd be happy to do that. Does your branch already have this idea implemented?

**Comment by levnach** [comment]
Sorry, the fix is not here yet.

**Comment by LeventErkok** [comment]
@levnach Looks like the latest build has fixed this one! Thanks.

Unfortunately, I ran into another similar problem. Will open a new ticket.

**Comment by LeventErkok** [comment]
This is now working just fine! Thanks.
