### ISSUE TITLE
Making Z3 determenistic (using random seed)

### ISSUE THREAD

**Issue by jenny1234567890** [Z3Prover/z3#1821]
Hi,

I am using z3py to solve a Scheduling problem. I would like to run this script on my build server as a regression test but I am experiencing a problem: the execution times of each run differ sometimes by a lot. In some cases I even have to kill the query and restart the solver again (often it then produces a result within seconds...). 

This unpredictable behavior is kinda preventing me so far to fully integrate my tool in our build process. I have heard that using "random_seed" it is possible to enforce a more deterministic behavior of the solver. 

So I was doing something like: z3.set_params(random_seed=2) but it doesnt feel like my situation got better. 

So what I am doing is: I am using the z3.Optimize() solver instance. I was wondering, whether that is a problem.

Also I was wondering whether "strategies/tactics" can be of any help in my situation. I didnt find too much info on this topic though (especially when it comes to the question: which tactic should I use).

**Comment by NikolajBjorner** [comment]
The behavior of calls under z3.Optimize should be deterministic for the same query. 
If you change the query/formula slightly the runtimes may be drastically different.
If you observe inconsistent timing behavior with optimization queries it may be due to a bug in Z3, but it has been a while since I encountered such bugs (mainly due to uninitialized memory reads). 
The best would be if you can post a repro where performance is inconsistent.

**Comment by jenny1234567890** [comment]
Hi Nikolaj,

thanks a lot for your response. I can't really post the problem here but maybe you can tell me which version has this bug?
print("version: {}".format(z3.get_version()))
return: version: (4, 8, 0, 0)

When I run the same problem several times in a row and at least 1 out of 10 runs it takes instead of 1-2 seconds a long time.
