### ISSUE TITLE
OCaml API...

### ISSUE THREAD

**Issue by DennisYurichev** [Z3Prover/z3#1868]
I'm trying to use ml_example.ml as a base...
https://pastebin.com/vzFaLUqu
Line 27 causing error: "Z3 EXCEPTION: operator is applied to arguments of the wrong sort".
i misunderstanding something probably...

**Comment by juliannagele** [comment]
Because the last open statement at the top is `open Z3.BitVector` the `mk_add` used in line 27 is the one from `BitVector` but its arguments are declared to be integers, hence the sort error.
You can just use `Arithmetic.mk_add` instead (which has type `Z3.context -> Z3.Expr.expr list -> Z3.Expr.expr` so you'll need to pass `[a; b]` as argument). Overall I would advise to get rid of (most of) the open statements at the beginning altogether to avoid this kind of problem. You could also implement your own version of `mk_add` that picks the correct module based on the sorts of its arguments, i.e., something like:
```OCaml
let mk_add ctxt x y =
  match Sort.get_sort_kind (Expr.get_sort x), Sort.get_sort_kind (Expr.get_sort y) with
  | BV_SORT, BV_SORT -> BitVector.mk_add ctxt x y
  | INT_SORT, INT_SORT -> Arithmetic.mk_add ctxt [x; y]
  | _, _ -> raise (Z3.Error "sort mismatch")
```

**Comment by DennisYurichev** [comment]
Thanks!
