### ISSUE TITLE
Can Z3 deduce automatically?

### ISSUE THREAD

**Issue by nuppt** [Z3Prover/z3#202]
In general, we can use Z3 to check our assertions is sat/unsat by some search strategies based on theories.
But I want to know whether Z3 is able to deduce automatically.
Let me use a sample to explain it:
![2015-08-24 10 44 28](https://cloud.githubusercontent.com/assets/8719521/9431960/23af979e-4a4d-11e5-9175-d2a918b3db56.png)

Now I have a precondition (forall z,  z > y) and a postcondition (exists x, x > y) in implication expression. Obviously, if I (check-sat), Z3 can return sat for me. Furthermore, if I (get-model), Z3 can return a interpreted model for me. 
![2015-08-24 10 53 46](https://cloud.githubusercontent.com/assets/8719521/9432035/6d8b5c6c-4a4e-11e5-9372-b43f5e62c061.png)

But what I want to know, is there any approach to reason out a strong property of that existential quantifier x in postcondition:   `x >= z`, not just a interpretation of x by get-model.

**Comment by NikolajBjorner** [comment]
You could apply a tactic to transform the current assertions into "simplified" form. For example, there is a tactic called "qe" that performs quantifier elimination. For your example, you have:

    (declare-const z Int)
    (declare-const y Int)

    (assert (=> (> z y) (exists ((x Int)) (> x y))))
    (apply qe)
    (apply (and-then qe simplify))

The results are not what you are expecting in the question because (exists ((x Int)) (> x y)) is equivalent to "true". Z3 produces the output:

    (goals
    (goal
      (=> (> z y) true)
      :precision precise :depth 1)
    )
    (goals
    (goal
      :precision precise :depth 2)
    )

The second set of subgoals contains no formulas, it is equivalent to "true".
