### ISSUE TITLE
[Question] Updated NuGet release supporting .NET Core on Linux

### ISSUE THREAD

**Issue by tawalke** [Z3Prover/z3#2036]
I see that the CMake list was updated last week that seems to support .NET Core bindings which means the lib is available to run on Linux.  Has Z3 been successfully update to support .NET Core 2.x and if so is this version or will this version be available on NuGet.

**Comment by NikolajBjorner** [comment]
It is currently in the works. I am not sure the CMake based build is ready, but we are using the python build for now. Yesterday's update included an ESRP sign pass which has now to be tested so that the packages can be published.

To create nuget packages we will use a script in https://github.com/Z3Prover/z3/blob/master/scripts/mk_nuget_release.py.
@msoeken is currently testing the output of that script. It would create a combined .Net platform 1.4 package that includes native binaries for ubuntu 64, MacOs, and Windows (either just x64 or including x86 if this works too). 

The script can of course be run by anybody because it just downloads the latest release and creates a nuget package. So you are of course welcome to try it and make pull requests with any adjustments. 

@helwer noticed that the current release 4.8.3 dlls are not even (delay) signed. This will be fixed with new builds.

**Comment by sequenze** [comment]
Hi guys.

Any ETA on the nuget package for .NET core?

**Comment by NikolajBjorner** [comment]
4.8.4 with .net core for Windows, Ubuntu, Debian, MacOs x64 was pushed to nuget.org yesterday.
The package is called Microsoft.Z3.x64 for now, until we get Microsoft.Z3 namespace back from someone who authored a package some years ago under that namespace.
We (@ahelwer , @msoeken ) did our best to test the package on the various platforms. For Windows it should be possible to use both Framework 4.5+ and Standard 1.4+. Other platforms are Standard 1.4+. These should be low denominators.
