### ISSUE TITLE
Consider using PhantomReference instead of finalizers for Java interface

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#205]
Hi All,

Z3 uses the `finalize()` method to add the objects to the queue, on which `dec_ref` needs to be eventually called.
While using finalizers feels natural, in our experience (while developing CPAchecker), we have found them to cause rather severe performance issues, both with time and memory (those are outlined in Effective Java, also a relevant article is http://resources.ej-technologies.com/jprofiler/help/doc/index.html).
In addition, because finalizers run on the other thread, such approach requires locking.

We have found that it is much more safe to use `PhantomReference` instead: a special reference, which does not increase the reference count of the object for GC purposes, but gets added to the queue once the referenced object is released by the GC.
An example of such usage is https://github.com/dbeyer/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/util/predicates/bdd/JavaBDDRegionManager.java: note the `ReferenceQueue`, and the map used to retrieve the stored pointer.
The `#poll` method is used on the map, which does not lock until the data is available (it does lock then, but for a very short period of time).

What would be your thoughts on the proposal?
I can do the pull request for the migration.

We currently do not have benchmarks data for phantom references vs. finalizers for Z3 specifically, but it did help tremendously in similar circumstances (native objects which required explicit free-ing).

**Comment by wintersteiger** [comment]
Sure, that sounds like a good idea. The Java API hasn't seen a lot of benchmarking or optimization yet, so there may well be bottlenecks that we shold get rid of. 

Note however that those finalizers have second purpose: The Context object needs to know when all other Z3Objects created from that context have disappeared, because only then is it safe to delete the context (See m_`ctx.m_refCount--;` in `Z3Object::dispose()`). Once `m_ctx.refCount` is down to 0, the API will call `Native.delContext(m_ctx)`, which is done in `Context::finalize()`. The current implementation is only sound for non-concurrent GCs, because I couldn't figure out how to re-queue something for finalization in Java, so this might need a bit more work. 

I don't know PhantomReferences at all, but I can imagine that we wouldn't be able to keep those counters up to date, which might mean that we need a major rewrite of the API, or that we accept memory leaks from Context objects.

**Comment by cheshire** [comment]
Personally I would accept the memory leaks from the context objects, but that's only because all uses I have seen use one context.
But that maybe me --- does the "empty" context take a lot of memory?

> The current implementation is only sound for non-concurrent GCs

But that's quite bad, since Java GC is concurrent by default?.. I'm not even aware of a flag to make it non-concurrent.

**Comment by wintersteiger** [comment]
Yes, most users use only one context, but some already started using multiple, some of them even in parallel, so in the API we need to cater for that too. 

As far as I know, Oracle Java comes with at least 4 different garbage collectors. Of those Java 8 (again only Oracle) versions I have on my machine, only the 64-bit "server" VMs have the -XX:+UseParallelGC flag enabled by default, the others don't. In general, we should indeed support all of them, but so far I haven't found an easy way to do that, because Java doesn't give you access to the finalization queue. Ultimately, we might have to spin up our own thread that tries to collect Contexts from time to time.

**Comment by cheshire** [comment]
I use OpenJDK7 on 64 bit linux machine (is there any difference now in Oracle JDK vs. OpenJDK apart from some minor graphics issues? I think OpenJDK is _the_ reference implementation now), and it definitely uses quite a lot of threads for GC.

> because Java doesn't give you access to the finalization queue
Exactly, that's one of the finalizers problems. AFAIK it's not even on the GC thread, but on some separate one.

**Comment by cheshire** [comment]
One possible approach would be for each class which knows which kinds of native object it handles (e.g. Tactic, AST) have a map `PhantomReference -> native pointer`. Then the constructor would populate the relevant `ReferenceQueue`, and after that we would see whether we can get rid of objects pending deletion in that queue.

Since AFAIK the default for Java is to run multiple GC threads I think the current solution for garbage-collecting contexts does more harm then good.
As for deleting context objects (if that is really necessary), can't we store the pointer to the context in each object, and then rely on GC to mark the context is unreachable (or phantom-reachable, if we use the garbage collection method described above), and then get rid of it in the same way as other objects?..

**Comment by wintersteiger** [comment]
I don't know about Java, but in .NET this doesn't work because the context may be unreachable before all objects containing references to it are destroyed, e.g., think of a large set of ASTs, each of which has a reference to the Context, but the whole set of them has just become unreachable. Frequently the GC will now try to finalize the Context, and only after that it will handle the ASTs. It will crash because the Context, and the underlying native Z3_Context, are not there anymore. This is why we count the number of ASTs and if there is an attempt to finalize the Context while the counter is still greater than zero, then the Context is put back onto the finalization queue. 

Since we can't requeue objects onto the finalization queue, I think the only real solution would be to implement our own finalization queue (one way or another), because we can't teach the GC that there are also dependencies between the underlying native objects.

**Comment by cheshire** [comment]
I see. Yet with the phantom references solution we have a `ReferenceQueue` which we have some control over, and the associated map to get the data required for cleaning a given `PhantomReference`.
What if our map is `PhantomReference<AST> -> (Context, AST native pointer)`?
That way `Context` will become unreachable only after all the associated ASTs are no longer phantom-reachable.

Also, how much RAM is leaked if we just leave contexts around? Is it just one pointer, or the whole associated datastructure?

**Comment by wintersteiger** [comment]
There can be a lot of data that stays in memory, we definitely can't leave that around. Also, in some applications, many context objects are used, so even if each of them is small, it adds up to a lot. 

Your suggestion of a queue and mapping is quite similar to what's implemented right now; we call them DecRefQueues and they collect the native pointers when a non-native Z3Object like an AST is destroyed. The queue is kept until someone can dec-ref them (concurrently, so the queues have locks). In the current implementation, every Context has a number of DecRefQueues for different types of objects.

It's true that keeping the reference count at 1 while an AST is alive, is sufficient under the right assumptions, but I can't imagine that this is a major performance issue for the typical applications. Do you have any numbers on that?

**Comment by NikolajBjorner** [comment]
To my understanding using phantom references will not work well with multiple contexts in different threads and GC and the current bug-fixes listed above address main issues raised.

**Comment by cheshire** [comment]
Hi Nikolaj,

> To my understanding using phantom references will not work well with multiple contexts
Why? Everything achievable with finalizers is achievable with phantom references, they just give you a more fine-grained control.

We will have performance data shortly for Z3 tests cases for different configurations (finalizers vs. phantom references vs. leaking memory).

And there is another message complaining about the same issue, namely, performance issues associated with finalizers usage:
http://swig.10945.n7.nabble.com/Java-Finalizer-Alternatives-td10181.html
