### ISSUE TITLE
Z3 Solver's timeout isn't working properly

### ISSUE THREAD

**Issue by norhh** [Z3Prover/z3#2080]
## Description
The timeout seems to work for low timeouts, but when the timeout is increased then z3 doesn't respond for quite an amount of time.
## Example
```
from z3 import *

a = BitVec('a', 256)
b = BitVec('b', 256)
c = BitVec('c', 256)
s = Solver()
s.add(BVMulNoOverflow(a, b, False))
s.add(b + c < 100000000000)
s.add(a * c > 100000000000)
s.set("timeout", 50000)
print(s.check())
```
This code doesn't finish in 50s(or even 1 minute). had to kill it after 2-3 minutes

**Comment by NikolajBjorner** [comment]
It is fixed.

**Comment by jannicklange** [comment]
Hello Nikolaj,

I'm currently working on the integration of the new NuGet package of Z3 into OPTANO Modeling.
When we're trying to solve a (non-trivial) MIP, Z3 does not seem to respond to the configured timeout.

We're setting the parameter in the following way on a "Z3.Optimize" solver object:
```csharp
  var parameters = this.context.MkParams();
  parameters.Add("timeout", (uint)(this.Configuration.TimeLimit * 1000));
  this.solver.Parameters = parameters;
```

When the timeout expires (after ~90 seconds), we can observe some sort of timeout exception that is thrown and caught/handled within the Z3 solver.
The solver then continues to calculate (or is doing something else). Either way, it still has some CPU usage and the `solver.Check()` method is not left.

It seems to me as though the model size might play a role here. The MPS file is ~40MB and the model contains about 400k constraints and 300k variables.

When testing on a smaller model, the optimization is interrupted as expected - even though we cannot extract a meaningful (intermediate) solution, since the Z3Status is `UNKNOWN`, so that we're not sure whether the model is feasible or infeasible.

Do you have a clue on what might be going on internally, when a large optimization shall be interrupted?

Best Regards
Jannick
