### ISSUE TITLE
Why the unspecified operation for fp.to_*bv has been eliminated from the latest version of z3?

### ISSUE THREAD

**Issue by Phat3** [Z3Prover/z3#2085]
Hi,

I'm one of the developers of [angr](https://github.com/angr). I was trying to update the version of z3 we are using to solve collected contraints from version 4.5.1.0 to version 4.8.5. 
During this process I noticed that some of the test cases fails because we use the unspecified version of the function fp.to_ieeebv which is no more available in the latest version of z3 (as specified in [this commit](https://github.com/Z3Prover/z3/commit/31cfca0444d2df3f231e0a8b92e80a8fa531f7c1).

It is not very clear to me why this functionality has been removed,  is it because the theory behind it not correct in some way? Are there any workaround that I'm not aware of?

Thanks in advance!

**Comment by LeventErkok** [comment]
If I may chime in; as I had this same issue a while back myself.

SMTLib doesn't define `fp.to_ieeebv` because it's partial: The `NaN` value has no fixed bit-pattern that you can map to. (As opposed to SMTLib notion of a "single" `NaN`, IEEE754 has many bit-patterns that correspond to it.)

The workaround I found is rather crude, but it does work so long as you never inspect the bits of a `NaN` value. The idea is to allocate a 32-bit-vector (or 64), and use the ` ((_ to_fp eb sb) (_ BitVec m) (_ FloatingPoint eb sb))` function which is supported: (http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml), and assert that the converted float is equal to the one you wanted to convert in the first place. Then you use the bit-vector you declared as your value.

It's kind of roundabout, and it doesn't handle IEEE754 `NaN` payloads at all, but otherwise, I found this conversion trick to work just fine in practice.

**Comment by wintersteiger** [comment]
That particular commit only removed the extraneous functions for the _unspecified_ cases of those functions, not for the functions themselves, just as a clean-up of the API. After that commit, the unspecified bits are integrated into the function interpretations provided in models. I don't think `fp.to_ieeebv` has been removed, but I'll have to check whether someone else removed it. As @LeventErkok said, this is a non-standard (neither IEEE nor SMT) and you should avoid using this function if at all possible.

**Comment by wintersteiger** [comment]
(I checked, `fp.to_ieeebv` is still there and works.)
