### ISSUE TITLE
Implementing lastIndexOf for strings

### ISSUE THREAD

**Issue by jawline** [Z3Prover/z3#2089]
Is there any function like Z3_mk_seq_index that can be used to return the last index a string occurs at in another string rather than the first?

**Comment by NikolajBjorner** [comment]
Because of "rfind" vs "lfind"? I lost track of how many bugs I had to fix in implementing mk_seq_index so even though it is symmetric I wonder how to limit feature creep. What other library functions are missing?

Note that the implementation of mk_seq_index is by equi-satisfiable reduction to equalities and negated containment. 

Modulo copy-paste errors: 
Given occurrence of "indexof(t, s, offset)" we produce the following axioms, where
"i" is shorthand for indexof(t, s, offset)" and x, y, s1 are skolem functions of t, s, offset.

  |t| = 0 => |s| = 0 or indexof(t,s,offset) = -1
  contains(t,s) or indexof(t,s,offset) = -1
  offset >= len(t) => |s| = 0 or i = -1  
  len(t) != 0 & !contains(t, s) => i = -1
  offset = 0 & len(t) != 0 & contains(t, s) => t = xsy & i = len(x)
  0 <= offset < len(t) => xy = t &
                          len(x) = offset &
                          (-1 = indexof(y, s, 0) => -1 = i) &
                          (indexof(y, s, 0) >= 0 => indexof(t, s, 0) + offset = i)
  offset < 0 => i = -1

For indexof(s, t, 0) there is a specialized definition:
        |t| = 0 => |s| = 0 or indexof(t,s,0) = -1
        |s| = 0 => indexof(t,s,0) = 0
        contains(t, s) or indexof(t,s,0) = -1
        contains(t, s) => |s| = 0 or (t = xsy & indexof(t,s,0) = |x|)
        |s| = 0 or (s = s1(unit c) & !contains(xs1, s))

**Comment by NikolajBjorner** [comment]
added
