### ISSUE TITLE
Z3 NuGet Package update

### ISSUE THREAD

**Issue by GennadyGS** [Z3Prover/z3#2090]
Official nuget package contains version 4.8.1, however a few more versions have been released, which contain important bug fixes.
Are there any plans to update nuget package to current version?

P.S. Thanks a lot for amazing library!

**Comment by NikolajBjorner** [comment]
The new build release process signs the Windows dlls with strong keys (Microsoft publisher).
We also moved to .Net platform 1.7 since 4.8.1.
And we would like a process that includes unmanaged libraries for all platforms, which is currently provided by the scripts/mk_nuget_package.py script (anybody can run this script to create local packages).

The remaining piece is resolving whether MaxOS binaries are strong-signed and whether we can publish this over nuget in the capacity similar to 4.8.1.

@helwer initiated and handled the entire process for releasing 4.8.1. It took quite a while because various pieces had to get aligned. Some of these process issues have been automated, so hopefully it will be less of an overhead.

**Comment by AceHack** [comment]
Yes, I would like to see a 4.8.4 package too.  Thanks.

**Comment by NikolajBjorner** [comment]
There is an updated package with Ubuntu, Debian and MacOs, and win64: https://www.nuget.org/packages/Microsoft.Z3.x64/

**Comment by GennadyGS** [comment]
Thank you!
