### ISSUE TITLE
Ubuntu Cosmic (18.04) still uses libz3-dev 4.4

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2097]
Hi there,

I've learned today that Ubuntu Cosmic 18.04 still uses libz3-dev 4.4.
https://packages.ubuntu.com/cosmic/libz3-dev
Do you know how package maintenance is going?
For example, on Arch Linux libz3 is already 4.8.

Thanks!

**Comment by NikolajBjorner** [comment]
I don't know. It says Michael Tautschnig is original maintainer, 
but maybe he switched jobs since doing this. I can't/don't keep 
track of what people do with Z3 outside of this repository. 
The license lets you do pretty much what you want, but nowhere can I promise to support whatever gets sprinkled around. There seem to be two pip packages, and don't use the "z3" pip package because it has nothing to do with z3. pull request that streamline pushing such publications are accepted. I am preparing one for nuget packages, though it doesn't include the last step that pushes the package to nuget.org.

**Comment by leonardoalt** [comment]
Sure, thanks for the quick reply. I asked directly on launchpad if there are update plans (https://answers.launchpad.net/ubuntu/+source/z3/+question/677999).
