### ISSUE TITLE
Will Z3 ever "collapse" model entries in v2 format?

### ISSUE THREAD

**Issue by jonkirsch** [Z3Prover/z3#214]
Consider the following simple input file:

```
(set-option :produce-models true)
(declare-fun myfun ( Int ) Int)
(assert (! (= (myfun 1) 1)))
(assert (! (= (myfun 2) 2)))
(assert (! (= (myfun 3) 1)))
(check-sat)
(get-model)
```
When I run this through Z3 using the "model.v2=true" option, I get the following output:
```
sat
"myfun -> {
  1 -> 1
  2 -> 2
  3 -> 1
  else -> 1
}"
```
In this case, Z3 did not "collapse" the two entries that yield the value 1; every application of the function to a unique set of arguments is explicitly listed.  Is this guaranteed to always be the case, or can there be cases where collapsing can occur?

Thanks!

**Comment by wintersteiger** [comment]
Yes, there are some cases functions can be collapsed, e.g., if you use macros, the macro finder will keep the macro as a model instead of building if-then-else terms. For complex functions however, there is no guarantee that it will always (or never) collapse, so you'll have to expect both. 

Closing this as answered, please open a new issue if there are follow-up questions.
