### ISSUE TITLE
feature request: platform independent step limit

### ISSUE THREAD

**Issue by florianschanda** [Z3Prover/z3#216]
Hi,

We notice the step limit (using memory_max_alloc_count=BLAH) seems to be platform dependent. In particular we have a VC that solves on OSX with a given step-limit, but not on 64-bit Linux.

Limiting the number of allocations always struck me as slight low-level, are there any plans to have something more platform independent like CVC4's --rlimit feature? It doesn't need to be the same for two different revisions of Z3; but ideally its the same no matter the architecture.

The VC in question can be easily provided if you're interested.

Thanks,

   Florian

**Comment by wintersteiger** [comment]
See also [resource limit in addition to time limit](https://github.com/Z3Prover/z3/issues/56).

CVC's documentation says that their rlimit feature is roughly the number of SAT conflicts. Z3 also has that option, but it was invisible, I've now made that visible in unstable; on the commandline use `smt.max_conflicts=<n>`. Note that Z3 does not necessarily produce any conflicts at all and that the number of conflicts needed to reach a conclusion is stricly speaking non-deterministic, because many tactics contain timers that abort a sub-tactic after some timeout, which of course isn't always precise. But you can build your own custom tactics that don't use timers, but instead use memory_max_alloc_count to cancel them deterministically.

**Comment by florianschanda** [comment]
Ok - I have re-read the thread from Johannes and Yannick. It contains many useful explanations on both sides, so thank you for that. I start to understand how Z3 works in that regard, and why it was done this way. To summarize, the main issue is that tactics use time-outs.

Looking at a bit of code in tactical.h, how does this idea sound? Imagine some "deterministic mode" that you can enable at command-line, you then have a resource number somewhere. Some things (like sat conflicts) increase this by 1.

You seem to have a single time dependent tactic, try_for; the second argument to it gives a time in milisecond. Instead of using it as time, you can use the milliseconds argument relative to the current resource count: the timer would "expire" when the resource_pool >= starting_resource + milliseconds.

That way we should get something that is entirely deterministic no matter the platform or speed of the computer you're on, with not too much change. In particular, any of the existing tactics would need no modification.


CVC4 has slightly more complex counting now, many things (not just SAT conflicts) increase this resource pool, and there are command-line options to fine-tune them. (For example a rewrite step might consume 0 resource, where a sat conflict consumes 10, etc.)


The issues noted by Johannes and Yannick are still relevant - a deterministic step is something we would require to enable the general purpose use of Z3, since we are seeing issues where we have repeatable but divergent results across different platforms.

**Comment by NikolajBjorner** [comment]
I started adding an rlimit feature. 
Example usage
           z3 <file.smt2> /st rlimit=21045

**Comment by florianschanda** [comment]
Ok, great, thanks! I look forwards to trying it.
