### ISSUE TITLE
the "!=' seems not work in z3Str

### ISSUE THREAD

**Issue by MatrixLing** [Z3Prover/z3#2169]
```
#!/usr/bin/python3
from z3 import *
print (z3.get_version_string())
s = Solver()
x = String('x')
s.add(x[0] != StringVal('\x00'))
s.add(x[1] == StringVal('a'))

s.set('timeout', 5000)
if s.check() == z3.sat:
    print (s.model())
else:
    print ('unsat')
```
the output is:
```
4.8.5
[x = \x00a]
```
it seem `s.add(x[0] != StringVal('\x00'))` not work. Is there something wrong with the way I use z3?

**Comment by LeventErkok** [comment]
Looks like this is an issue with the Python layer, and not z3 itself. If you add:

    print s.sexpr()

to your program it prints out:

     (assert (distinct (str.at x 0) ""))

Clearly, this is not what the Python tried to say.

There were a few previous issues with how strings are marshalled back-and-forth between Python and Z3, but looks to me like this somehow escaped.

**Comment by LeventErkok** [comment]
Looking a bit further into this, it appears z3 ends up calling:

```python
def StringVal(s, ctx=None):
    """create a string expression"""
    ctx = _get_ctx(ctx)
    return SeqRef(Z3_mk_string(ctx.ref(), s), ctx)
```

And there's the rub: This ends up calling a C function to convert the string, at it gets fooled because it thinks the string is of length 0 since it has a null (0-value) terminator. The null-terminated string idiom of C strikes again.

Note that this would have the same issue if you had a null-byte anywhere in a string literal at the Python layer.

One of those annoying things: There's simply no way to write a string literal that has a 0-byte in it. (Unless @NikolajBjorner comes up with some magic!)

**Comment by NikolajBjorner** [comment]
the magic is that strings are just sequences of 8-bit bit-vectors. So instead create a concatenation of such unit characters.

**Comment by LeventErkok** [comment]
Another idea might be to fix the `StringVal` function so it actually does produce a string that's parseable by SMTLib. (i.e., fix `Z3_mk_string` function to understand the 0 bytes etc. and spit out the correct escape sequences.) Incidentally, that's what I do in my Haskell library, instead of creating a concatenation of sequences.

**Comment by MatrixLing** [comment]
I solve it by modify the StringVal function, is this correct?
original code:
```
def StringVal(s, ctx=None):
    """create a string expression"""
    ctx = _get_ctx(ctx)
    return SeqRef(Z3_mk_string(ctx.ref(), s), ctx)
```
patched code:
```
def StringVal(s, ctx=None):
    """create a string expression"""
    ctx = _get_ctx(ctx)
    return SeqRef(Z3_mk_string(ctx.ref(), s.replace('\x00', '\\x00')), ctx)
```

**Comment by LeventErkok** [comment]
@MatrixLing 

No that wouldn't work, since you'd be changing the meaning of the string. The following should do it:

```python
def MyStringVal(s):
    if '\x00' not in s:
        return StringVal(s)
    elif s == '\x00': # Need to explicitly handle this since Concat needs at least two elts
        return Unit(BitVecVal(0, 8))
    else:
        return Concat(*[Unit(BitVecVal(ord(i), 8)) for i in s])
```

You can use `MyStringVal` in your code till Nikolaj replaces the z3's version with the above, or with something better.

Note that z3 still prints the models incorrectly in the presence of 0 bytes:

```python
#!/usr/bin/python3
from z3 import *

def MyStringVal(s):
    if '\x00' not in s:
        return StringVal(s)
    elif s == '\x00':    # Need to explicitly handle this since Concat needs at least two elts
        return Unit(BitVecVal(0, 8))
    else:
        return Concat(*[Unit(BitVecVal(ord(i), 8)) for i in s])

print (z3.get_version_string())
s = Solver()
x = String('x')
s.add(Length(x) == 2)
s.add(x[0] != MyStringVal('\x00'))
s.add(x[1] == MyStringVal('a'))

print s.sexpr()

s.set('timeout', 5000)
if s.check() == z3.sat:
    print (s.model())
else:
    print ('unsat')
```

this prints:

```
4.8.5
(declare-fun x () String)
(assert (= (str.len x) 2))
(assert (distinct (str.at x 0) (seq.unit #x00)))
(assert (= (str.at x 1) "a"))

[x = a]
```

which is very confusing since the sequence printer has a similar bug as well; but that's a different question!

**Comment by MatrixLing** [comment]
@LeventErkok 
I use python3, and the output is normal.
```
4.8.5
(declare-fun x () String)
(assert (= (str.len x) 2))
(assert (distinct (str.at x 0) (seq.unit #x00)))
(assert (= (str.at x 1) "a"))

[x = \x04a]
```

Next, I will say my paches.
in z3 C level, It convert the string to zstring class.
```
zstring::zstring(char const* s, encoding enc): m_encoding(enc) {
    unsigned mask = 0xFF; // TBD for UTF
    while (*s) {
        unsigned ch;
        if (is_escape_char(s, ch)) {
            m_buffer.push_back(ch & mask);
        }
        else {
            m_buffer.push_back(*s & mask);
            ++s;
        }
    }
}
```

the is_escape_char will convert the `"\\x00"`(length=4) to `"\x00"`(length=1).
so if in python level, we use `"\\x00"`, in z3 internel, It will treat it as string `'\x00'`.

```
from z3 import *
print (z3.get_version_string())
s = Solver()
x = String('x')
s.add(Length(x) == 2)
s.add(x[0] != StringVal('\\x00'))
s.add(x[1] == StringVal('a'))

print (s.sexpr())

s.set('timeout', 5000)
if s.check() == z3.sat:
    print (s.model())
else:
    print ('unsat')
```
this is the output as I expected.
```
4.8.5
(declare-fun x () String)
(assert (= (str.len x) 2))
(assert (distinct (str.at x 0) "\x00"))
(assert (= (str.at x 1) "a"))

[x = \x04a]
```

so I think can modify StringVal throuth s.replace('\x00', '\\x00')

**Comment by LeventErkok** [comment]
@MatrixLing I'll let @NikolajBjorner decide on how (also if!) this should be fixed. But I think he alluded to conversion directly at the Python layer by converting to sequences of 8-bit values, and that's what my code does. Obviously, there might be other ways to fix the same.

Other APIs (most likely the C API) probably suffers from the same problem, but again this is best handled by the z3 HQ..

**Comment by NikolajBjorner** [comment]
will be able to look at this in earnest by mid-week, sorry.
