### ISSUE TITLE
can not combine tuple an array sorts

### ISSUE THREAD

**Issue by wysiib** [Z3Prover/z3#221]
The code in https://gist.github.com/wysiib/fcc40987115bc8856b45 shows that tuple sorts behave differently if combined with array sorts than if combined with other sorts.

If the array sort is used instead of the integer sort, an exception is thrown:

z3exception Sort mismatch at argument #2 for function (declare-fun the_tuple (Int the_tuple) the_tuple) supplied sort is (Array Int Int).

I assume the constructed function should be (declare-fun the_tuple (Int (Array Int Int) the_tuple).

If the integer sort is used, the function is created as (declare-fun the_tuple (Int Int) the_tuple) as expected.

Tested with latest Z3 nightly build on OS X.

If you need further input let me know!

**Comment by NikolajBjorner** [comment]
This is a bug in the user code that is related to how objects have to be reference counted.
The line:

       proj_sorts[1] = c.array_sort(c.int_sort(),c.int_sort());

Is problematic because the reference count to the newly created array sort gets lost.
Instead consider the following:

       z3::sort aSort = c.array_sort(c.int_sort(),c.int_sort());
       proj_sorts[1] = aSort;

In this way, the reference count to the array sort is maintained during the scope of the body of 'main'.
You can also re-use aSort later on in the code.
The C++ wrappers ensure that reference counts to Z3 objects are kept as long as the wrapper objects are live. For example z3::sort is an object that maintains a reference count to the sort.
