### ISSUE TITLE
z3 incremental solving clarification

### ISSUE THREAD

**Issue by muqsitazeem148** [Z3Prover/z3#2220]
I am using python binding of Z3 (version 4.8.4) under 64bit Linux.

When we execute solver.push(), z3 reuses previously learned clauses.

Can z3 reuse the previous learned clauses across the sessions? i.e. Will it be possible to reuse the analysis done by z3 in the previous solution that it has obtained in an almost similar problem?

**Comment by NikolajBjorner** [comment]
You can save the solver state. It contains the current set of clauses. They may be simplified relative to learned clauses and may contain some learned clauses that are not going to be garbage collected.
So if it learns a unit clause "p", then the other clauses would not contain "p" (unless you are pushing and popping scopes). 

You typically need the old solver state in order to convert a model from the new set of assertions into a model of the original assertions. The Z3_import_model_converter function is used for this purpose.

**Comment by YuanbinCN** [comment]
@NikolajBjorner Is it possible to give an example on how to use Z3_import_model_converter function. I am not able to find the API for python. Thanks for your help.
