### ISSUE TITLE
segfault when using z3str3 and sequences together

### ISSUE THREAD

**Issue by joelburget** [Z3Prover/z3#2223]
Running this script causes a segfault (tested with the latest nightly). However, removing the first line results in `sat`. Note that there are actually no strings in this example.

```
(set-option :smt.string_solver z3str3)

(define-fun zero-one-two () (Seq Int) (seq.++ (seq.unit 0) (seq.unit 1) (seq.unit 2)))

(declare-fun ix () Int)
(declare-fun free-var () Int)

(assert (= (seq.unit free-var) (seq.extract zero-one-two ix 1)))
(check-sat)
```

Possibly related to #2110.

**Comment by NikolajBjorner** [comment]
z3str3 only supports strings. This is not a supported scenario.

**Comment by mtrberzi** [comment]
I'll look into this, this shouldn't be a segfault (I would prefer to exit gracefully with an error message) but as mentioned Z3str3 is not a solver for the theory of sequences, only the theory of strings, so it does not support this usage.

**Comment by mtrberzi** [comment]
Opened #2600

**Comment by embg** [comment]
Since z3str3 only supports strings, is there a performance advantage from mapping a sequence to a string before using methods like indexof? Specifically, I have a sequence `s` of Bool and need to find `(seq.indexof s true)`. Would there be an advantage to converting `s` to a string `t` consisting of `\x00` and `\x01` characters and then using `(str.indexof t "\x01")`?
