### ISSUE TITLE
When should I internalize an expression?

### ISSUE THREAD

**Issue by guluchen** [Z3Prover/z3#2228]
I am trying to write a custom string theory for z3. One problem I encountered is the concept of internalization in z3.

If I do not internalize an expression (or literal) before I add it as an axiom, sometimes I got an exception, but sometimes not.

For example, in the following code from theory_seq.cpp

    VERIFY(m_util.str.is_index(i, t, s) ||
           m_util.str.is_index(i, t, s, offset));
    expr_ref minus_one(m_autil.mk_int(-1), m);

    literal cnt = mk_literal(m_util.str.mk_contains(t, s));
    literal i_eq_m1 = mk_eq(i, minus_one, false);
    add_axiom(cnt,  i_eq_m1);
It does not internalize i_eq_m1 and it seems to work fine.

But if I do not internalize any expression (e.g. remove all calls to ctx.internalize(e, false)), I will get some exception.

Are there any principle that I should follow when I create a new expression?

**Comment by NikolajBjorner** [comment]
* In theory_seq.cpp, mk_literal and mk_eq already make sure to internalize expressions.
* yes, otherwise, when accessing enode objects and Boolean variables that are associated with expressions it is required that they be internalized first. The smt_context layer maintains Boolean variables for atomic predicates and it maintains enodes (equality nodes where union-find information is captured) on top of expressions. In order to ensure that the smt_context knows about what enode is associated with an expression and what Boolean variable is associated with a Boolean expression it is necessary to internalize the expressions.

**Comment by guluchen** [comment]
Many thanks for the explanation. I have a follow up question. 

For a bool expression constructed from some already internalized expressions. Should I still always internalize it before adding it as an axiom.

**Comment by NikolajBjorner** [comment]
I take the answer is yes, though the question is very high level. 
I think there are plenty of examples of how to use internalization in the various theories.
