### ISSUE TITLE
UNKNOWN result (Bad definition?)

### ISSUE THREAD

**Issue by Progress1** [Z3Prover/z3#225]
Hi, maybe it's not bug, maybe i do something wrong (some definition etc) ... I try run this simple script http://pastebin.com/9myuJaYV and Z3 can't find solution. Any ideas what is wrong? Thank you.

**Comment by wintersteiger** [comment]
This is because there is an error in the encoding and the corresponding error message isn’t reported by the (slightly outdated) version of Z3 on rise4fun, but it’s already been fixed in unstable:

Line 21:  (ite (= N 0) T0
(error "line 21 column 13: Sorts (_ BitVec 8) and Int are incompatible")

“0” is not a bit-vector but an integer, it should be (_ bv0 8)
