### ISSUE TITLE
Does Z3 have randomness by default?

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2260]
Hi, I am using OCaml Z3 (v. 4.8.4), especially bitvector modules. Z3 4.8.4 seems to produce different results for each running (i.e., whenever satisfiable, produces different SAT models with different running time, for the same formulas).

Does Z3 have randomness by default? Can I disable this randomness?
I am not sure whether my memory is correct, but I haven't experienced such phenomenon with the previous versions (e.g., 4.7.1).

**Comment by NikolajBjorner** [comment]
1. Default tactics use some probing that is time dependent. This could cause different behavior. Use verbose output at level 10 or above to see if it tries different tactics.
2. Reference counts on terms are managed by the OCaml GC. This may cause randomness.
3. Otherwise, Z3 isn't supposed to be random. Self-contained repros using files would then be possible to produce in case of, say, uninitialized memory.
