### ISSUE TITLE
setup.py does not include linked libraries in Windows package

### ISSUE THREAD

**Issue by LordAro** [Z3Prover/z3#2265]
The packaged versions of z3-solver on pypi (4.5.1.0.post2) don't include the additional libraries that it's built against in the package - 

```
 > objdump.exe -p python/Lib/site-packages/z3/lib/libz3.dll | grep DLL
        DLL
 vma:            Hint    Time      Forward  DLL       First
        DLL Name: VCOMP140.DLL
        DLL Name: MSVCP140.dll
        DLL Name: KERNEL32.dll
        DLL Name: VCRUNTIME140.dll
```

Now kernel32.dll is obviously unnecessary, but the other 3 aren't necessarily installed on the system, particularly if you don't have Visual Studio installed.

Looks like the issue is centred here:
https://github.com/Z3Prover/z3/blob/16af728fbe0cb3fd7583d921fea9b545f42591b8/src/api/python/setup.py#L111

I don't have the issue personally, but looking at the Linux version, the only "possible to not have installed" library it's linked against is libgomp.so.1 (OpenMP), might want to include that as well

Incidentally, the pypi situation is a bit of a mess - the latest precompiled Windows version is 4.5.1, and the Linux version is 4.8.0, neither of which are particularly up to date. Would be really great if these could be updated...

I can probably put together a PR (for Windows & Linux, at least) that fixes the issue, but I can't do anything about the existing pypi releases

**Comment by NikolajBjorner** [comment]
scripts\mk_win_dist.py contains some code to find the redistributables. 
It can be pushed to mk_util.py or somewhere else for reuse.

**Comment by rhelmot** [comment]
I'm the one that does the pypi distributions for now. I've just pushed out a 4.8.5 release, though none of the dynamic library problems have been resolved.

imo, (and maybe I just don't understand the dynamics of software distribution on windows) if we need to distribute our dynamic libs along with our binaries, we should just be statically linking?

for linux, I've been maintaining a project that depends on z3's python distribution for a while, and it's been at least 4 years since I heard someone complaining about errors with linking libgomp. These were very common back when ubuntu 12.04 was in use...

**Comment by LordAro** [comment]
Thanks for doing that, should be helpful. It occurs to me there may be an additional issue with distributing the runtime binaries - licensing. If I recall correctly, you can't link these statically either

**Comment by LordAro** [comment]
And I'm not I've not really looked into libgomp at all - just noticed that it was required, and wasn't part of libc or some other core library

**Comment by NikolajBjorner** [comment]
I have only seen libgomp as an issue on bare bones docker containers.
Visual studio redistributables are dynamic linked (only). They are there to 
support derivatives produced by Visual Studio. They can be found in free 
versions of VS and are routinely included in other distributions.

**Comment by NikolajBjorner** [comment]
added a first attempt. Nightly build should kick in and help establishing if this is the right direction.

**Comment by NikolajBjorner** [comment]
first attempt was miss-guided. mk_win_dist.cmd should be doing the job of copying over the dlls and the nightly.yml script should be copying those dlls over to bin. But, the wheels on pypi.org appear to not include those redistributables.

**Comment by rhelmot** [comment]
If we actually want the windows wheels to contain the necessary dlls we need to figure out where they should actually live in the python package directories. My suggestion for how this should work is that setup.py should copy the dlls into the same `python/z3/lib` folder as the main dll during the build phase (the `LIBS_DIR` variable in setup.py). They will be automatically be distributed, which is different from the `bin` folder we put the executable in, where you have to be explicit about every file that is distributed. (sorry about that. setuptools magic.) Then we can add code in the python end that will try to manually load the dependency dlls from the special folder before it loads the z3 core from that same folder.

**Comment by NikolajBjorner** [comment]
I think I am slowly getting it.

       shutil.copy(os.path.join(BUILD_DIR, LIBRARY_FILE), LIBS_DIR)

only copies z3lib.dll
Adding something like

       shutil.copy(os.path.join(BUILD_DIR, "msvcp*"), LIBS_DIR)
       shutil.copy(os.path.join(BUILD_DIR, "vcomp*"), LIBS_DIR)

could do the trick, but be ugly as ...

**Comment by rhelmot** [comment]
I think that's not too ugly! The only thing wrong with the code you posted is that `shutil.copy` will not respect glob patterns - you want:

```python
for filepath in glob.glob(os.path.join(BUILD_DIR, "msvcp*")) + glob.glob(os.path.join(BUILD_DIR, "vcomp*")):
    shutil.copy(filepath, LIBS_DIR)
```

**Comment by NikolajBjorner** [comment]
That seems to do it:

copying z3/lib/msvcp140.dll -> build/lib.linux-x86_64-2.7/z3/lib
copying z3/lib/libz3.dll -> build/lib.linux-x86_64-2.7/z3/lib
copying z3/lib/vcomp140.dll -> build/lib.linux-x86_64-2.7/z3/lib
copying z3/lib/msvcp140_2.dll -> build/lib.linux-x86_64-2.7/z3/lib
copying z3/lib/msvcp140_1.dll -> build/lib.linux-x86_64-2.7/z3/lib

**Comment by JamieShelley** [comment]
Heyo do you mind providing a complete setup.py example - there's so many potential conflicting options that I'm worried the other shtuff I have in mine is interfering with it.
I did fix it by copying over manually so am I to assume this copy can be a post build command bundled into the bdist installer somehow. Not Entirely sure...
Any advice helpful thanks!

**Comment by rhelmot** [comment]
`python setup.py bdist` should create a wheel file which is a zip archive containing the z3 binaries, headers, python bindings, and dependency libraries. It can also use the `PACKAGE_FROM_RELEASE` environment variable, which should point to the unzipped folder of a z3 release and will use the binaries/headers from that instead of the current build tree, in addition to setting the platform metadata to match the release.

`python setup.py sdist` should create a source release which is an archive containing all the z3 source and headers in addition to the python bindings.

This is the full manual for maintainers to use setup.py. If you're not a maintainer, you should install z3 via pip, either just using installing the distributions from pypi (i.e. `pip install z3-solver`) or installing the built working tree (`pip install .`)

**Comment by rhelmot** [comment]
(also this issue is fixed and can be closed, right?)

**Comment by NikolajBjorner** [comment]
right, with next release, the redist should be included. The nightly wheels should contain them as well.

**Comment by rhelmot** [comment]
the current release ([4.8.7.0](https://pypi.org/project/z3-solver/4.8.7.0/#files)) definitely has the libs included, I just checked!

**Comment by NikolajBjorner** [comment]
OK, thanks, then closing this one. 
The Mac wheels are for next release though
