### ISSUE TITLE
 prove" (y>=z && y>x) => (y>=z)" very slow

### ISSUE THREAD

**Issue by LH-413x** [Z3Prover/z3#2266]
I want to prove: (y>=z && y>x) => (y>=z), but following code run really really slow, is there some way to make this proving quickly?

from z3 import *

x, y, z = Ints('x y z')
f1 = Function('f1',IntSort(),IntSort(),IntSort(),BoolSort())
f2 = Function('f2',IntSort(),IntSort(),IntSort(),BoolSort())

e=ForAll(
        [x,y,z],
        And(f1(x,y,z)== And(y >= z, y > x),
            f2(x,y,z)== And(y >= z),
            Implies(f1(x,y,z),f2(x,y,z)
                    )
            )
    )

print(e)
s = Solver()
s.add(e)
print(s.check()==sat)

**Comment by NikolajBjorner** [comment]
To prove a formula F, amounts to checking that "not F" is unsatisfiable. You should instead check that "not F" is unsat. Instead of creating uninterpeted functions for definitions you can just use a Python function for f1, respectively, f2. The resulting formula is then quantifier-free and much easier to deal with.

**Comment by LH-413x** [comment]
Thanks ! ! ! !
