### ISSUE TITLE
Z3str3 unsat answer for sat formula with indexOf

### ISSUE THREAD

**Issue by alebugariu** [Z3Prover/z3#2301]
For the following formula, z3str3 returns unsat (version 4.8.4 and also the current master):
```(set-option :random-seed 0)
(set-option :produce-models true)
(set-info :status sat)
(declare-fun tmp_int2 () Int)
(assert
 (= (str.indexof "" "" tmp_int2) (- 1)))
(check-sat)
(get-value (tmp_int2))
```
 
If we set the smt.string_solver option to seq, then the result is sat (as expected) and a correct model is generated (tmp_int2 = -2).

**Comment by OrenGitHub** [comment]
I get the following result with master (pulled today)

    sat
    ((tmp_int2 (- 2)))

Though I'm not sure how a negative offset (`tmp_int2`) makes sense.
And what's the meaning of looking for the empty string?
The [documentation from cvc4](http://cvc4.cs.stanford.edu/wiki/Strings) says (emphasis mine):

> (str.indexof s t i) where s is a string, **t is a non-empty string** and **i is a non-negative integer**. This function returns the position of the first occurrence of the specified value t in the string s after the index i. It returns -1 if the value to search for does not occur.

**Comment by NikolajBjorner** [comment]
tmp_int2 makes sense: it serves the role of "i" in the documentation. The documentation doesn't say that you can't pass in a negative number to the function str.indexof. After all the function is total.
The documentaiton implies that "i" is expected to be non-negative for the function to returns some meaningful position. Otherwise it is free to produce the value -1.

**Comment by mtrberzi** [comment]
Thanks for the bug report - opened #2538
