### ISSUE TITLE
C++ error using OCaml API

### ISSUE THREAD

**Issue by giltho** [Z3Prover/z3#2305]
Hello,
We've been using z3 for a while, and it has been working properly. Recently, the opam version was updated to include static linking, but supposedly the version of z3 didn't change. However, since that update, we started getting the following error :
```
libc++abi.dylib: terminating with uncaught exception of type is_non_propositional_predicate::found
```
We've had to add `(c_library_flags -lstdc++)` to the dune file, maybe we're doing something wrong with regard to linking z3 ?

**Comment by NikolajBjorner** [comment]
Maybe #2294 fixes this?

**Comment by arbipher** [comment]
Hi @giltho , if you are a Mac Mojave user, this may work for you
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

**Comment by giltho** [comment]
Hi,
@NikolajBjorner sorry I didn't answer earlier, I don't really know yet sorry. I don't have a lot of time right now, and we are using the opam version of Z3, meaning, to incorporate your fix I would need to package Z3 myself or make a PR to opam-repository, which I don't have time for right now. I will keep you posted if that works, thank you for your answer !

@arbipher Thank you for your answer. Unfortunately, I get `The file /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg does not exist.`. I do not even have a `Packages` folder in my `CommandLineTools` folder :/ I tried `xcode-select --install` but it is already installed and up to date.

**Comment by arbipher** [comment]
@giltho 
Here is what I guess and I hope it could help.
The library `stdc++` is a kind of C++ standard library, which should be located in some default system paths. Then Z3 or other packages can depend on them.

The problem which we share is Z3 works before but it doesn't work now is caused by Mac moved the C++ standard library. It is stated [here](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes). 
`macOS_SDK_headers_for_macOS_10.14.pkg` is mentioned in the notes. Then I guess could you update your Xcode then the file may be there?

**Comment by giltho** [comment]
@arbipher
Thank your for your answer, it makes it much clearer ! I think that might be the issue indeed, since whenever I compile I also get this message :
```ld: warning: building for macOS, but linking in object file (/path/to/menhir/menhirLib/menhirLib.o) built for ```
And I think the program ends before the message is entirely flushed because I don't have the rest of the message.

I guess it's trying to tell me that it is building with an older version of the `std++` library or something like that. I will try to find the latest version ! 
Thank you very much

**Comment by NikolajBjorner** [comment]
seems resolved

**Comment by jnfoster** [comment]
I am seeing the same issue with this environment:
```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G84
> opam switch
#  switch  compiler                    description
   4.06.1  ocaml-base-compiler.4.06.1  4.06.1
   4.07.0  ocaml-base-compiler.4.07.0  base-bigarray.base base-threads.base
                                       base-unix.base
                                       ocaml-base-compiler.4.07.0
→  4.07.1  ocaml-base-compiler.4.07.1  4.07.1
   system  ocaml-system.4.07.1
> opam list z3
# Packages matching: (installed | available) & name-match(z3)
# Package # Installed # Synopsis
z3.4.6    4.8.4       Z3 solver
z3.4.7.1  4.8.4       Z3 solver
z3.4.8.1  4.8.4       Z3 solver
z3.4.8.4  4.8.4       Z3 solver
```

I also installed the SDK headers as suggested above, reinstalled `z3` via OPAM, and I still see the error.

Any advice for what to try? I haven't tried futzing with Dune incantations.

**Comment by giltho** [comment]
@jnfoster Unfortunately, the version on opam seems to have issues. It is not maintained by the Z3 team at microsoft but by the people at Aesthetic Integration. In particular, they did some black magic with respect to static linking (which is really a push in the right direction for OCaml developers), but it doesn't work on my end, and it doesn't seem to be working on yours. This might be because we're using some feature of Z3 they aren't using.

So 2 solutions :
 - You might try to propose a PR to update to the actual latest version of Z3 and see if that changes anything. (It's on my to do list but I don't have time right now :/)
 - You can take my solution which is forcing z3 back to version 4.8.1. Hope it will work for you too, and that there's nothing that you really need that has been introduced between 4.8.1 and 4.8.4.

**Comment by jnfoster** [comment]
Thanks!

@c-cube, as maintainer of the z3 OPAM package, you might want to look at this thread?

**Comment by jnfoster** [comment]
Downgrading to 4.8.1 worked for me. Thanks again @giltho!

**Comment by c-cube** [comment]
We don't use all the features at AI, and your problem seems caused by some mac OS specific change, but I'm not on a mac. I'm really not sure I can help, sorry :s

**Comment by mgree** [comment]
Bumping the thread because I ran into this same issue; downgrading to 4.8.1 worked for me, too. I'm not using any particularly fancy features of Z3 (though I suppose that's in the eye of the beholder).

I have _some_ experience debugging OCaml linking issues on macOS, and I'd be game to look into this issue if I could be pointed in the right direction.

**Comment by NikolajBjorner** [comment]
I have _no_ experience on opam*mac. We have three build machines that continuously build and test Mac configurations. If there are additional configurations we can add to the build I am all for it.
The hosted build images are listed here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
We currently use macOS-10.14 as specified in 
https://github.com/Z3Prover/z3/blob/master/azure-pipelines.yml.
(e.g., we are not exercising Catalina FWIW).
The Travis builds can presumably also be configured in various ways.

In theory you would submit your build scripts (with how you use opam) as a pipeline task to 
azure-pipelines.yml and the pull request gets built (or not if it errors).
This would establish more baselines for portability across environments.

The main differences from 4.8.1 are:

- we got rid of OpenMP dependencies, using c++11 threads everywhere.
- the libraries for Z and Q (big-nums) have been updated from the previous deprecated implementations to the current implementations.

**Comment by mgree** [comment]
The OPAM CI suite is testing against Linux (many distros) and macOS, so I'm surprised they didn't catch this issue the last time the OPAM file was bumped. It may be that this linker issue particularly bites people who have computers that were configured pre-`SDKROOT` and then upgraded into the new regime.

**Comment by c-cube** [comment]
the problem with the opam CI here is that there's no test for *linking* z3, only for building it (which succeeds).

**Comment by mgree** [comment]
Ah, of course. It's a particular problem with OPAM that the test scripts need to be run before installation, so you can't test things as others will see them. (An issue I ran into recently in [libdash](https://github.com/mgree/libdash). I just [created an issue](https://github.com/ocaml/opam/issues/4099) on the OPAM repo.)

At this point I can say that merely making sure that `-cclib -lstdc++` is in the compiler arguments is not enough to avoid this issue. Looking more closely at the error, why do we suspect that this is a linker issue at all, and not some breaking API change?

**Comment by mgree** [comment]
Looking more closely at the code, I'm a little surprised to be seeing this exception escaping at all. It comes up in [probe.cpp](https://github.com/Z3Prover/z3/blob/238ff78374368317d349c75422ec993f74356748/src/tactic/probe.cpp#L307), where the general idiom is to use [test from goal.h](https://github.com/Z3Prover/z3/blob/238ff78374368317d349c75422ec993f74356748/src/tactic/goal.h#L190-L202) to catch an exception indicating that the probe has found something outside of the logical fragment being probed for.

I suspect https://github.com/Z3Prover/z3/commit/cfd048658278c7079e52a41e9ec34fa2b4ed1abc is the guilty commit. Now, _why_ that is, I'm not sure. Perhaps an assumption the C++ compiler is making about how exceptions are treated is being violated when we link with OCaml?

**Comment by NikolajBjorner** [comment]
The API functions should catch all internal C++ exceptions. No internal C++ exceptions should ever escape. It would point to a flaw in the internal code or some build issue with exceptions.
The API functions catch all exceptions of type z3_exception. 
The exceptions from probe.cpp are not subclasses of z3_exception, but as you point out 
should have been caught by the test function template.

**Comment by mgree** [comment]
Hmm... that seems plausible on my local system, but the [failed macOS build](https://travis-ci.com/mgree/kmt/builds/150398115) of my Z3 client software doesn't (or, at least, very much shouldn't!) have that issue.

**Comment by NikolajBjorner** [comment]
I see both gcc and clang in the log. I hope they are not mixed :-)

**Comment by NikolajBjorner** [comment]
I see that you have "-package z3", which I guess is thanks to @c-cube. 
If there is any chance of mixed-mode debugging from ocaml (sorry I am out of touch on this) it would be possible to make progress on pinning the exception stack.

**Comment by mgree** [comment]
`gcc` on macOS _is_ clang... for better or worse.

**Comment by NikolajBjorner** [comment]
I learned something new today

**Comment by mgree** [comment]
I've created [z3canary](https://github.com/mgree/z3canary), which is just a few simple tests exercising the OCaml interface of Z3. I haven't yet been able to get these tests to [work in CI](https://travis-ci.com/mgree/z3canary), though it works fine on my machine. I'll keep pushing, but at this point I'm pretty confused about what's going wrong here... the tests fail even with 4.8.1, even though I have other projects succeeding. (A dune problem, maybe? I'm a novice with dune.)

**Comment by arbipher** [comment]
I read the [log](https://travis-ci.com/mgree/z3canary/jobs/290802313) of @mgree's work in CI.
The problem is the same as when I install 4.8.1 for my project - the dynamic library isn't in the path.

See line 1991
> ./basic.exe: error while loading shared libraries: libz3.so: cannot open shared object file: No such file or directory

The solution is either
1. the not-so-smart way, copy them (works both in mac and ubuntu)
```shell
cp `opam config var z3:lib`/libz3.dylib .
cp libz3.dylib _build/default
```
2. config path
`export LD_LIBRARY_PATH=~/.opam/4.07.1/lib/z3` (this works in Linux but I don't find the solution in mac

**Comment by mgree** [comment]
Thanks for looking at this. NB that [Linux has the same issue (with `libz3.so`)](https://travis-ci.com/mgree/z3canary/jobs/290802313#L1988-L1995).

Baffling! Why do we need the dynamic library at all if things are meant to be statically linked?

The solution here may be to have the build manually set the RUNPATH to find the shared libraries in the OPAM directory.

**Comment by giltho** [comment]
I've use solution 1 and solution 2 manually for a while, but one elegant solution that I ended up adopting is an esy-packaging of z3 (see git@github.com:giltho/esy-z3.git). If you are a [esy](https://esy.sh) user, it builds z3 for you and exports the right variables in the library path.

If whatever you're developing is not meant to end up on opam, in the end, it works quite well.
Using this solution, I managed to bump my z3 version to 4.8.7 without the issues that the opam version has. 

It could be a nice solution for z3canary for example. I also have github actions stuff for caching esy projects if needed

**Comment by arbipher** [comment]
I have another working solution, which is simply creating a soft link for z3, a.k.a
```shell
# mac
ln -s `opam config var z3:lib`/libz3.dylib /usr/local/lib/libz3.dylib
# ubuntu
sudo ln -s `opam config var z3:lib`/dllz3ml /usr/local/lib/dllz3ml
```
Just put `z3` into the default place for dynamic libraries.

@mgree 
> Why do we need the dynamic library at all if things are meant to be statically linked?
(unclear 1) I don't know whether opam can install dynamic library 
(unclear 2) or z3 intends to work as a static library , then why do we have shared library

I checked z3 package on opam and found in all opam file (from [4.6](https://github.com/ocaml/opam-repository/blob/master/packages/z3/z3.4.6/opam) to [4.8.7](https://github.com/ocaml/opam-repository/blob/master/packages/z3/z3.4.8.7/opam) ), it specifies `-nodll`

```
install: [
  [ "sh" "-c" "ocamlfind install z3 build/api/ml/META -nodll build/api/ml/*" ]
]
```

It seems there must be some conflicts here if I literally understand `-nodll`.
As long as opam can build z3 and we can fix the PATH, the building process is correct and the problem is in installing (or the building our client project)

**Comment by mgree** [comment]
It's important for me that things work out of the box from OPAM, whether the project is itself an OPAM library or an application.

OPAM can definitely install dynamic libraries. They'll typically go in `.opam/<switch>/lib/stublibs`, but they can also appear in `.opam/<switch>/lib/<library>`.

The global soft link is, I think, a nonstarter. OPAM will never allow it, since such global changes undermine the very point of OPAM.

The `-nodll` flag is telling `ocamlfind` to put any `.so` files in `build/api/ml/*` in `.opam/<switch>/lib/z3` as opposed to stublibs. The flag should be read as "don't treat these files as shared libraries destined for stublibs".

Discussion above seems to indicate that Z3 is _supposed_ to be linking statically. That isn't what's happening, though.

One possible solution is to tell the Z3 OCaml package to ensure that `.opam/<switch>/lib/z3` is in the runtime load path (i.e., `RPATH` or `RUNPATH`), which can be achived using `-dllpath <path>` flags for bytecode or `-ccopt -W,l -ccopt <path>` for native code. I'll try building a version of Z3 that sets the RUNPATH for its `cmxa` and `cma` appropriately.

**Comment by mgree** [comment]
My z3canary's [current status](https://travis-ci.com/github/mgree/z3canary/builds/157574660):

- On macOS and Linux, you need to set `LD_LIBRARY_PATH` to include `$(opam var lib)/z3`.
- On macOS everything works, though you need to set `DYLD_FALLBACK_LIBRARY_PATH` to include that same path when using Z3 4.8.1 (but not for later, statically linked versions).
- On Linux, all version of Z3 fail with OCaml 4.10 due to some issue with the C bindings and the new OCaml runtime.

I've discussed the Linux/OCaml 4.10 bug on the [OCaml discord](https://discuss.ocaml.org/t/trouble-with-z3-on-ocaml-4-10-on-linux-and-ocaml-4-x-on-macos/5418), but here's the [error](https://travis-ci.com/github/mgree/z3canary/jobs/311587222#L513-L527):
```
$ opam config exec -- dune build src/main.exe
(cd _build/default && /home/travis/.opam/ocaml-base-compiler.4.10.0/bin/ocamlopt.opt -thread -cclib -lstdc++ -g -o src/main.exe /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml/nums.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3/z3ml.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3 /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml/unix.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml/bigarray.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml/str.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml/threads/threads.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ocaml /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/batteries/batteries.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/batteries/batteriesThread.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ANSITerminal/ANSITerminal.cmxa -I /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ANSITerminal /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/stdlib-shims/stdlib_shims.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/fmt/fmt.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/cmdliner/cmdliner.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/fmt/fmt_cli.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/fmt/fmt_tty.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/astring/astring.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/uuidm/uuidm.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/re/re.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/alcotest/alcotest.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/logs/logs.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/logs/logs_fmt.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/logs/logs_cli.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/result/result.cmxa /home/travis/.opam/ocaml-base-compiler.4.10.0/lib/ppx_deriving/runtime/ppx_deriving_runtime.cmxa src/kmt.cmxa src/.main.eobjs/native/main.cmx)
/home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3/libz3ml.a(z3native_stubs.o): In function `n_context_of_ast':
z3native_stubs.c:(.text+0x133a): undefined reference to `caml_local_roots'
/home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3/libz3ml.a(z3native_stubs.o): In function `n_mk_null_ast':
z3native_stubs.c:(.text+0x142a): undefined reference to `caml_local_roots'
/home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3/libz3ml.a(z3native_stubs.o): In function `n_context_of_symbol':
z3native_stubs.c:(.text+0x153a): undefined reference to `caml_local_roots'
/home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3/libz3ml.a(z3native_stubs.o): In function `n_mk_null_symbol':
z3native_stubs.c:(.text+0x162a): undefined reference to `caml_local_roots'
/home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3/libz3ml.a(z3native_stubs.o): In function `n_context_of_constructor':
z3native_stubs.c:(.text+0x173a): undefined reference to `caml_local_roots'
/home/travis/.opam/ocaml-base-compiler.4.10.0/lib/z3/libz3ml.a(z3native_stubs.o):z3native_stubs.c:(.text+0x182a): more undefined references to `caml_local_roots' follow
collect2: error: ld returned 1 exit status

File "caml_startup", line 1:
Error: Error during linking
```
It's a vexing bug, because the phrase `local_roots` doesn't appear at all in the Z3 repo... so what's going on here?!

My current plan is to set up z3canary with a branch for each version of Z3 with (a) a submodule of the appropriate release of Z3 and (b) the OPAM file for that version. The install script will pin the local version into OPAM, install it, and then try to build and run a client of the z3 library.

Long term, [OPAM will eventually support post-install tests](https://github.com/ocaml/opam/issues/4099), which are critical for making sure that a library is _usable_. When that feature is available, I hope we can use it here.

**Comment by NikolajBjorner** [comment]
in my installation on ubuntu (  OCaml version 4.05.0 so maybe dated)
caml_local_roots are defined in header files /usr/include/caml/memory.h and compatibility.h

**Comment by mgree** [comment]
Yes: it changed in 4.10. (See, e.g., https://github.com/ocaml/ocaml/issues/9179.)

**Comment by jormal** [comment]
> I have another working solution, which is simply creating a soft link for z3, a.k.a
> 
> ```shell
> # mac
> ln -s `opam config var z3:lib`/libz3.dylib /usr/local/lib/libz3.dylib
> # ubuntu
> sudo ln -s `opam config var z3:lib`/dllz3ml /usr/local/lib/dllz3ml
> ```
> 
> Just put `z3` into the default place for dynamic libraries.
> 
> @mgree
> 
> > Why do we need the dynamic library at all if things are meant to be statically linked?
> 
> (unclear 1) I don't know whether opam can install dynamic library
> (unclear 2) or z3 intends to work as a static library , then why do we have shared library
> 
> I checked z3 package on opam and found in all opam file (from [4.6](https://github.com/ocaml/opam-repository/blob/master/packages/z3/z3.4.6/opam) to [4.8.7](https://github.com/ocaml/opam-repository/blob/master/packages/z3/z3.4.8.7/opam) ), it specifies `-nodll`
> 
> ```
> install: [
>   [ "sh" "-c" "ocamlfind install z3 build/api/ml/META -nodll build/api/ml/*" ]
> ]
> ```
> 
> It seems there must be some conflicts here if I literally understand `-nodll`.
> As long as opam can build z3 and we can fix the PATH, the building process is correct and the problem is in installing (or the building our client project)


I solved my proble with this suggestion like,
``` bash
#ubuntu
$sudo ln -s $OPAM_SWITCH_PREFIX/lib/libz3.so /usr/local/lib/libz3.so
#mac
$sudo ln -s $OPAM_SWITCH_PREFIX/lib/libz3.dylib /usr/local/lib/libz3.dylib
```

More detail, I observed those.
`ocamlc` wants to just set `LD_LIBRARY_PATH` on Linux `DYLD_LIBRARY_PATH` on macOS to the `$OPAM_SWITCH_PREFIX/lib` with
``` bash
#linux
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OPAM_SWITCH_PREFIX/lib
#mac
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$OPAM_SWITCH_PREFIX/lib
```
But, `ocamlopt` wants to place dynamic library to `usr/local/lib`.

Anyway Thx :)

**Comment by mgree** [comment]
These are helpful tricks for users who are willing to do whatever is necessary to get z3... but setting global environment variables or putting in global symlinks should be a non-starter for OPAM packages. Both of these approaches go directly against the very idea of OPAM, and having to do either of those things means the package is broken. (The former is non-compositional. The latter won't work if I'm not root and will break when I upgrade my OPAM switch.)
