### ISSUE TITLE
Model validation and unspecified values

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#237]
Suppose the follwing input. 

    (set-option :rewriter.hi_div0 false)    
    (declare-fun x () (_ BitVec 32))
    (assert (= x (bvudiv (_ bv1 32) (_ bv0 32))))
    ; (push)
    (check-sat)
    (get-value(x))

Currently this produces

    ((x (bvudiv0 #x00000001)))

and all is well. Now switch to incremental mode by uncommenting the `(push)`. It then produces

    ((x #xffffffff))

and the model validation (`model_validate=true`) fails. Adding 

    (set-option :old_simplify.bv.hi_div0 false)

doesn't fix it either, but it does change the result to 

    ((x #x00000000))

and again, model validation fails.

**Comment by wintersteiger** [comment]
Incremental check (with push) still produces a model that can't be validated.

**Comment by NikolajBjorner** [comment]
Non-incremental mode eliminates x and creates a model x = bvudiv0(1). 
Incremental mode invokes the theory_bv and treats bvudiv0 as uninterepreted (as it should), but
since bvudiv0 is a built-in symbol, no entry is generated for it during model construction, so when the
model evaluator picks up (bvudiv 1 0) and rewrites it first to (bvdiv0 1) it is unable to evaluate it further.
So it is unable to validate that the interpretation that sets (bvdiv0 1) to 0 is legal.

**Comment by wintersteiger** [comment]
Yes, that's correct. I was hoping you would fix it so I can copy the fix into theory_fpa :)

**Comment by NikolajBjorner** [comment]
I think we got there now.
