### ISSUE TITLE
Z3 reports  unknown on unsatisfiable formula

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#2384]
The following easy formula is unsatisfiable according to the SMTLIB spec on Reals http://smtlib.cs.uiowa.edu/theories-Reals.shtml
```
(assert (not (exists ((f Real))
    (= (/ f 0) 0)
)))
(check-sat)
```
z3 reports `unknown` for this formula. Z3 stable (v4.8.5) hangs on this case.
Removing `(not` helps, it gives the correct result which is SAT in that case. 

OS: Ubuntu 18.04
Revision: 6d244ed2aa311d07e8c8aaca9051308d0107ce03

**Comment by NikolajBjorner** [comment]
actually, it is satisfiable, not unsat.
The specification is that (/ f 0) is uninterpreted, so it is the same as:

    (not (exists ((f Real)) (= (dummy-divides f) 0)))

with a model where dummy-divides-0 is 1 for every value f, the formula is true.

I had to take out elimination of / that applies to bound variables because it was incorrect, so Z3 falls back to incomplete procedures for such formulas.
