### ISSUE TITLE
Spacer generates weird counterexample

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#2430]
I'm encoding some code into Horn clauses creating https://pastebin.com/e71Dyr8D.
For context, the original code is
```
		uint i = 0;
		uint m = 0;
		while (i < 5) {
			if (_a[i] > m)
				m = _a[i];
			++i;
		}
		assert(m > _a[0]);
```
The assertion is clearly wrong, for the case where `m == _a[0]`. If I change it to `>=` it works, as expected.

However, the given counterexample is
```
(and (loop_35_0!slice!1 (store ((as const (Array Int Int)) 0) 4 39) 5 39)
     (loop_35_0!slice!1 (store ((as const (Array Int Int)) 0) 4 39) 4 0)
     (loop_35_0!slice!1 (store ((as const (Array Int Int)) 0) 4 39) 3 0)
     (loop_35_0!slice!1 (store ((as const (Array Int Int)) 0) 4 39) 2 0)
     (loop_35_0!slice!1 (store ((as const (Array Int Int)) 0) 4 39) 1 0)
     (loop_35_0!slice!1 (store ((as const (Array Int Int)) 0) 4 39) 0 0))

```
The way I read this counterexample is an array with all 0s except `_a[4] == 39`. After 5 loop iterations, it correctly sees that `m == 39`, but `m > _a[0]` should still hold.

Am I reading it wrong? Any possible explanation here?

**Comment by agurfinkel** [comment]
Your interpretation is correct. There might be a bug in cex generation (but not in the solver). I am looking into it. For now, you might get better results by disabling inlining (and maybe slicing):
```
 fp.xform.slice=true fp.xform.inline_linear=false fp.xform.inline_eager=false
```

Unfortunately, the combination of pre-processing and counterexamples is not well handled at the moment.

**Comment by leonardoalt** [comment]
Ah ok, thanks! Those parameters did help.
Not sure whether you want to keep the issue open to track the bug, I'm fine with closing.

**Comment by agurfinkel** [comment]
I hope I can fix it instead of ignoring it :)

**Comment by agurfinkel** [comment]
I've submitted a PR to fix the problem. Please try it when the PR is merged.

Note that cex certificates are only computed / defined for linear CHC. We do not have a good format for the general case. Internally, a cex is represented by a hyper-resolution refutation. I can dump that. It contains all the information (including the rules) you might need. Unfortunately, since it includes all the rules it is quite large and not visually pleasing.

**Comment by leonardoalt** [comment]
I can test it locally and let you know. I found a couple other examples of buggy cex that worked with the flags you mentioned above.

**Comment by leonardoalt** [comment]
I confirm that the branch fixes the first issue posted here.
However, for this example: https://pastebin.com/KVLqtSGq
```
11:48 $ z3 c.smt2 
sat
(and (interface_SimpleCrowdsale_108_0 1 1 1)
     (interface_SimpleCrowdsale_108_0 1 0 1))
```
This cex is wrong since the first argument of `interface_SimpleCrowdsale_108_0` should start with 0 (unless there's a bug in my encoding itself).

```
11:48 $ z3 fp.xform.slice=true fp.xform.inline_linear=false fp.xform.inline_eager=false c.smt2 
sat
(and error_1
     (function_finalize_107_0 1 1 1)
     (interface_SimpleCrowdsale_108_0 1 1 1)
     (fallback_85_0 1 0 1 0)
     (interface_SimpleCrowdsale_108_0 1 0 1)
     (function_setCap_42_0 0 0 0 1)
     (interface_SimpleCrowdsale_108_0 0 0 0))
```
This cex looks correct to me.

**Comment by agurfinkel** [comment]
I would argue that if the bottom cex looks ok then the top should be ok as well. The top counterexample is produced after inlining. Hence, it is expected to be a sub-sequence of the bottom one. The bottom cex has three applications of `interface_SimpleCrowdsale_108_0`. The top cex matches the last two application. The last (i.e., first in cex order) application must have been inlined.

**Comment by leonardoalt** [comment]
But shouldn't it anyway be a complete path from a fact to the error predicate?

**Comment by agurfinkel** [comment]
The problem is that the counterexample is produced on the system after inlining. By the time the system gets to spacer, it is rewritten so that the first few steps are merged into a single rule. 
I've checked the result of inlining and sure that it is correct.

A proper fix is for inliner to justify the new rules that it is inserting using original rules and resolution. Then, the counterexample can be lifted up through the inliner. This, however, is not easy and has been on my todo list for a while.

Most users of spacer disable inliner in the front-end in favor of pre-processing and inlining in the domain specific way. For example, seahorn inlines at the compiler level and has its own domain specific tricks to lift counterexamples through inlining.

If this is a significant issue for you, let me know. Anything that is a showstopper for active users will get higher priority :)

**Comment by leonardoalt** [comment]
Ok, thanks for the explanation!

For now I haven't implemented getting counterexamples back to the user yet, I need to experiment a bit more. Maybe disabling inlining would be the way to go.

I definitely need the second counterexample to be given to the user, since that one tells exactly which function to call with which parameters to break the assertion. The `interface` predicate is an artificial one that I created as sugar for the encoding, so the first counterexample doesn't tell much from the programer's point of view.

Thanks for the discussion, I'll close the issue since the branch with the fix works.
