### ISSUE TITLE
enumerate models

### ISSUE THREAD

**Issue by arademaker** [Z3Prover/z3#2532]
Is there any option to enumerate all possible models for a propositional problem?

**Comment by NikolajBjorner** [comment]
Not directly. 
A good model enumeration technique could be as follows: 
run a SAT solver without backjumping and restart.
It would identify don't cares from a complete assignment by identifying a 
prime implicate from the assignment and then backtrack to the next branch. 
A version of CaDiCaL might have this approach available or use model counting as a proxy.
From outside of Z3 you are left with blocking each model by creating a clause from the negated literals. Eventually this takes a toll on space because the clauses are not garbage collected.
For some domain specific needs you can identify products of don't cares and represent models very succinctly. Alternative use a BDD package to enumerate models.
