### ISSUE TITLE
Asserting at 0-scope-level

### ISSUE THREAD

**Issue by diepbp** [Z3Prover/z3#2588]
Hello,

We are implementing string theory inside Z3, called Z3-Trau. The implementation is mostly completed. Now we focus on improving its performance, and later contribute the work to Z3 so it gets closer to general users. I have two following questions:

1. Assume at `final_check_eh` (scope_level = x, x > 0), I add an assertion `assert c1`. The constraint c1 does not depend on the context and is always satisfiable. However, after `final_check_eh`, Z3 can pop, therefore `c1` will be popped. Then I need to  `assert c1` again. It turns out that `c1` can be re-asserted many times.

Is there a solution to `assert c1`at scope_level = 0, so that `c1` will not be popped when Z3 pops?

2. What are requirements/processes of a theory to become a part of Z3? 
We hope that our work [Z3-Trau](https://github.com/guluchen/z3/tree/new_trau) will reach more people in the future by being a part of Z3. About the progress of our work, we are testing Z3-Trau and comparing it with most of string solvers, including Z3seq, Z3str3, and CVC4, on all benchmarks we know. Results of solvers are at http://trauc.iis.sinica.edu.tw/. Note that, each solver will be cloned from its latest commit, then reinstalled, and retested a few times a week, so the results are dynamic and updated.
According to the tester, Z3-Trau works quite well on the benchmarks.

Best,
Diep

**Comment by NikolajBjorner** [comment]
theory_seq uses a replay stack to ensure axioms of value are re-inserted during backtracking.

     class replay_axiom : public apply {
            expr_ref m_e;
        public:
            replay_axiom(ast_manager& m, expr* e) : m_e(e, m) {}
            ~replay_axiom() override {}
            void operator()(theory_seq& th) override {
                th.enque_axiom(m_e);
                m_e.reset();
            }
        };

2. Contributions are extremely welcome. The consequence is that users start exercising the procedures in ways they weren't originally tested. The ask is that bugs (GitHub issues) get fixed in a timely manner. If code lies around and isn't being fixed I will end up deleting it to limit the liability that is involved. This happened to the interpolation and duality engine as the code wasn't being maintained and GitHub issues accumulated. It will happen to other code, whether my own or others if it is buggy of low quality and the bugs don't get fixed.

Regardless of code quality, another requirement is about dependencies. Z3 itself has minimal dependencies and I am not willing to add code (to master branch) that introduces a deluge of dependencies.
If it makes sense, we can create a different fork, say call it Z*, that admits dependencies.

**Comment by diepbp** [comment]
Thanks for giving me the pointer. I will use it for my implementation. 
Could you briefly explain to me the idea of `m_trail_stack` in `theory_seq`, or `trail_stack` in general?

> Contributions are extremely welcome. The consequence is that users start exercising the procedures in ways they weren't originally tested. The ask is that bugs (GitHub issues) get fixed in a timely manner. If code lies around and isn't being fixed I will end up deleting it to limit the liability that is involved. This happened to the interpolation and duality engine as the code wasn't being maintained and GitHub issues accumulated. It will happen to other code, whether my own or others if it is buggy of low quality and the bugs don't get fixed.
I fully understand it.

> Regardless of code quality, another requirement is about dependencies. Z3 itself has minimal dependencies and I am not willing to add code (to master branch) that introduces a deluge of dependencies.
> If it makes sense, we can create a different fork, say call it Z*, that admits dependencies.
Do dependencies mean dependencies on external libraries, or dependencies between theories inside Z3. My string theory does not use external libraries; but often makes queries to `theory_arith` to get string lengths, string length upper/lower bounds (even the returned upper bound info is mostly useless) and, sometimes query `theory_array`. Hope they are not too much.

**Comment by NikolajBjorner** [comment]
The idea with trail stacks is that one can push an action that gets called during a pop that backtracks from the current scope. 

Dependencies = external libraries (external code). 
Internal depdencies are typically fine, especially if they follow the inclusion specified in scripts/mk_project.py.

**Comment by NikolajBjorner** [comment]
Some comments:

Based on https://github.com/guluchen/z3/blob/new_trau/src/smt/theory_trau.cpp and header file, it seems there are no external dependencies.
overall code seems of fine quality (there is a lot).

The use of std::set and std::map are not good because they end up using pointer-equality, which changes on runtime. We have obj_map for some of the cases you use and obj_hashtable. 
Some places uses std::list<..> or std::map<..> without & in function declarations. Typically you want to call by reference. 

The code doesn't support "unit" and "nth" operators and generally seems only focused on strings:
        if (!(m.get_sort(n->get_owner()) == u.str.mk_string_sort())) {
This is going to bound the use cases.

For code like this:

        } else if (u.str.is_concat(n)) {
            // recursively call this function on each argument
            SASSERT(n->get_num_args() == 2);
            expr * a0 = n->get_arg(0);
            expr * a1 = n->get_arg(1);

I end up adding recognizers in src/ast/seq_decl_plugin.h that returns a0, a1 without relying on the next 3 lines.

**Comment by diepbp** [comment]
> The use of std::set and std::map are not good because they end up using pointer-equality, which changes on runtime. We have obj_map for some of the cases you use and obj_hashtable.
Some places uses std::list<..> or std::map<..> without & in function declarations. Typically you want to call by reference.

Thank you. I will clean the code to use replace container libraries like set, map by built-in data structures. The code still looks messy right now and need much effort to clean. 

> The code doesn't support "unit" and "nth" operators and generally seems only focused on strings.

Yes, you are correct. They are not supported yet. We currently focus on strings and regular expression. Recently, we focus more on string-int conversion, which has been not supported well on some string solvers. Both z3seq and z3str can answer incorrectly in some tests. I might create another issue to report that bug soon. I hope to do "unit" and "nth" when the current code is stable and clean.
