### ISSUE TITLE
set time limit for interpolant

### ISSUE THREAD

**Issue by cgcgbcbc** [Z3Prover/z3#260]
now according to #249 , try-for can't be used in interpolant solving, how could I set time limit for interpolant API?

**Comment by kenmcmil** [comment]
I am setting it up so you can pass a timeout parameter to Z3_compute_interpolant. However, this won't be very useful since there's no way to detect whether the "unknown" result occurred because of a timeout or because of an incompleteness in the solver. I would recommend instead to use the Z3_get_interpolant call. You first set up your assertions in a solver, and check satisfiability. If unsat, you call Z3_get_interpolant. If the solver says "unknown" you can query it to determine the reason for the unknown result.

**Comment by kenmcmil** [comment]
Timeout is now implemented in Z3_compute_interpolant. You can specify the "timeout" parameter either as a global option or in the "params" argument of Z3_compute_interpolant. If the solver times out, a value of Z3_L_UNDEF will be returned, and the "model" return parameter will be null.
