### ISSUE TITLE
regarding unsigned division in bitvector module

### ISSUE THREAD

**Issue by SunBeomSo** [Z3Prover/z3#2843]
## Expected Behavior
OCaml API states:
>   (** Unsigned division.
      It is defined as the floor of [t1/t2] if \c t2 is
      different from zero. If [t2] is zero, then the result
      is undefined.
      The arguments must have the same bit-vector sort. *)

So I expect that, when checking satisfiability, Z3 does not produce any satisfying assignment for the formula below, because the condition ``d==0`` and thus ``UDiv(c, d)`` is undefined:
```
And(a == 100, d == 0, b == UDiv(c, d), Not(UGE(a + b, a)))
```
 where the syntax for Z3 api is written in Python for readability.

My intention was to inspect whether ``a+b>=a`` can be violated or not for the code below. Assuming division-by-zero as undefined behavior, the assertion cannot be violated (so I expected "unsatisfiable"):
```
a := 100
d := 0
b := c/d
assert (a+b >= a)
```

## Actual Behavior
But Z3 produces a following satisfying assignment:
```
[b = 115792089237316195423570985008687907853269984665640564039457584007913129639935,
 d = 0,
 a = 100]
```

Could you explain whether it is a normal behavior or not?
How do I provide a constraint to make it work as expected?

## Setting
I tested with z3 4.8.4 on macOS 10.15.1 . Here is the full Python code that I used:
```
from z3 import *

bit = 256
a = BitVec ('a', bit)
b = BitVec ('b', bit)
c = BitVec ('c', bit)
d = BitVec ('d', bit)

f = And (a == 100, d==0, b == UDiv (c,d), Not (UGE (a+b, a)))

solve (f)
```

**Comment by NikolajBjorner** [comment]
The issue is what was meant by "undefined". The proper wording is perhaps "underspecified".
All functions and predicates are total. They have some value. Also UDiv(x, 0) has some value, but it isn't specified what it should be. The solver is at liberty to find some interpretation of UDiv(x, 0) that satisfies the constraints where it is used. You can think of UDiv as follows: 
It is defined as UDiv(x, y) == if y == 0 then UDiv0(x) else MachineUDiv(x, y).
Where UDiv0 is some uninterpreted function and MachineUDiv is the machine semantics of unsigned division that has meaning for all values of x, y, but here only used when y != 0.
