### ISSUE TITLE
Contributors Guide

### ISSUE THREAD

**Issue by zv** [Z3Prover/z3#290]
When I submitted my pull request @NikolajBjorner made some significant changes to my code and effectively made a patch and squashed my commits under his username.

In the future, I would love to ease the merge process for @NikolajBjorner, @wintersteiger et al. Z3 is also a large codebase and so familiarizing yourself with it is time consuming, all of this (and more) could be accomplished by the creation of a GNU "CONTRIBUTE"-style guidelines document, covering preferred code style; high level details such as the 'architecture' of the core functions of the AST, the standard how (and when) of parsing module options and simple but helpful classes like `eval_cmd`, `cmd_context`, etc.

Thoughts?

**Comment by NikolajBjorner** [comment]
When it comes to me, I am rather rudimentary user of git features. 

Regarding pull request to add line: IF_VERBOSE(1, error("unsupported symbol"););
I reviewed the request, but thought the appropriate way to fix it was to add line information to the "unsupported" feedback that gets printed anyhow. This required several changes and didn't include your line. I probably forgot to add a reference in the commit comment, which I often do. Christoph sometimes comes with the broom, adding appropriate cross-references.

**Comment by wintersteiger** [comment]
Sure, the usernames should be in the commit messages, either in the original commit, or at the very least in the comments. This is also important for license issues, because external contributions might look like internal ones, so this is not just courtesy but hard requirement. 

When reviewing a pull request that needs changes, my recommendation is to _always_ create a new branch in which the PR is imported and _after_ that start making modifications, in the worst case removing all the PR code and overwriting it in a new commit. That way the history will always contain both parts. 

Our [Contribution Guidelines](https://github.com/Z3Prover/z3/wiki/Contribution-Guidelines) outline general issues, but there is no "documentation" of high level architecture or any of that. But, we would very happily merge contributions that get us closer to that goal!
