### ISSUE TITLE
z3py stops while performing quantifier elimination in a loop

### ISSUE THREAD

**Issue by zganjei** [Z3Prover/z3#2969]
I try to apply the following quantifier elimination in Python. In the third iteration, z3 does not return and gets stuck. I use Python 2.7.17 and Ubuntu 18.04.4.

```
for i in range(0,10) :
      n,X_0_, X_1_= Ints('n X_0_ X_1_')
      R_0_0, R__0, R_1_0, R__1= Ints('R_0_0 R__0 R_1_0 R__1')
      all=[n >= 3, X_0_ + X_1_ == n,X_0_ >= 0,R_0_0 <= X_0_, R_0_0 >= 0]
      all.extend([R_0_0 <= R__0, X_1_ >= 0, R_1_0 <= X_1_, R_1_0 >= 0, R_1_0 <= R__0, R_0_0 + R_1_0 == R__0])
      all.extend([3*R__0 > 2*n, R_1_0 > R_0_0, 3*R_1_0 <= 2*n, 3*R__1 <= 2*n])
      expr = And(*all)
      expr = Exists([R_0_0, R__0, R_1_0, R__1],expr)
      print "before:",expr
      tactic = Then(Tactic('qe'),Tactic('simplify'),Tactic('solve-eqs'))     
      expr=tactic(expr).as_expr()
      print "after:",expr
      print i
```

What am I missing? Should I for instance free some memory, etc?

**Comment by zganjei** [comment]
I noticed that when I change the order of variables in Exists, it doesn't get stuck! In particular, R_0_0 should not be the first variable in the list. I don't know why...

**Comment by NikolajBjorner** [comment]
A few comments:

1. You typically want to simplify before calling quantifier elimination. So change the order of arguments to the tactic, or add simplification before the qe step.

2. It also helps to use qe-light, which eliminates quantifiers by solving equations and identifies some cases where variables can be eliminated without incurring overhead.
An SMT file with your example is then (and translating back to Python should be direct):

```
(declare-fun n () Int)
(declare-fun X_1_ () Int)
(declare-fun X_0_ () Int)
(assert (exists ((R_0_0 Int) (R__0 Int) (R_1_0 Int) (R__1 Int))
  (and (>= n 3)
       (= (+ X_0_ X_1_) n)
       (>= X_0_ 0)
       (<= R_0_0 X_0_)
       (>= R_0_0 0)
       (<= R_0_0 R__0)
       (>= X_1_ 0)
       (<= R_1_0 X_1_)
       (>= R_1_0 0)
       (<= R_1_0 R__0)
       (= (+ R_0_0 R_1_0) R__0)
       (> (* 3 R__0) (* 2 n))
       (> R_1_0 R_0_0)
       (<= (* 3 R_1_0) (* 2 n))
       (<= (* 3 R__1) (* 2 n)))))
(apply (and-then simplify qe-light solve-eqs qe))
```

3. The qe2 tactic seems to do much better on this example than qe. It is not always the case, so I keep both around. The qe tactic gets stuck solving feasibility queries for some branches. This is the wrong tradeoff for your example because the feasibility check turns out to be rather expensive. The qe2 tactic also uses feasibility checks, but in a way that is better tuned. Overall, such a small formula has a small quantifier-free counter-part that can be computed without feasibility checks, but z3 doesn't give you that option.

**Comment by zganjei** [comment]
Great! Thanks!
