### ISSUE TITLE
qflia assertion violation at ../src/smt/smt_context.cpp Line: 2463

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#2980]
Hi,
For this formula,
```
(declare-sort T 0)
(declare-fun b (Int T) T)
(declare-fun c (T) Int)
(declare-fun e (Int T) T)
(assert (forall ((d Int) (g T)) (= (c (b d g)) (/ 1 (c g)))))
(assert (forall ((f Int) (g T)) (=> (<= f 0) (= (e f g) (e 0 (b 1 g))))))
(assert
 (forall ((f Int))
  (and (<= f 0)
   (exists ((g T)) (distinct (e f (b 1 g)) (b 1 (e f g))))
   (forall ((g T)) (distinct (e 0 (b 1 g)) (b 1 (e (+ f 1) g)))))))
(check-sat-using qflia)
```
z3 throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/smt/smt_context.cpp
Line: 2463
UNREACHABLE CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Commit: 4f33c12

**Comment by NikolajBjorner** [comment]
sorry, seems abusive: qflia is for quantifier-free formulas.

**Comment by NikolajBjorner** [comment]
alas, it is triggered by a case that could happen without uflia

**Comment by NikolajBjorner** [comment]
BTW, this bug was timing dependent. It was applying a tactic that timed out in a region where z3 can't deal with exceptions. Many bugs can be triggered by cancelling Z3 in bad places. There is a deterministic way to cancel Z3, it is by using the "rlimit" option. A typical bug appears when z3 is canceled on one query and continued on another afterwards. Several such bugs were reported by Imandra, but they use an ocaml interface, timeouts, and repros are super hard. But a fuzz tool can tinker with adequate values of rlimit and adequate combinations of queries. The upshot is that there will almost for sure be more bugs than it is possible to fix. For resilient applications, I would say one may as well redo the entire state after a cancelation. Nevertheless, many users torture z3 using rlimits so it is not an entirely unreasonable check.
