### ISSUE TITLE
format of model generated by z3

### ISSUE THREAD

**Issue by susmitj** [Z3Prover/z3#31]
Hi,

Is there a documented  grammar specification for the model generated by z3 on a satisfying instance ? 

And thanks for releasing z3 under MIT license - its a great service to the community ! 

--Susmit

**Comment by wintersteiger** [comment]
No, there's no such document. Currently there is no standard format for models from SMT solvers in the SMT standard, but this is being discussed. Note that this is non-trivial, because SMT is open to addition of new logics, meaning that new operators can be added in the future, so new (interpreted) function symbols and sorts might show up. For Z3, the model is usually a numeral assigned to each constant, where the shape of numerals is defined in the corresponding SMT logic. Exceptions to this are when arrays are used (there are additional function definitions) or user-defined sorts (there are additional universe definitions).

**Comment by wintersteiger** [comment]
Closing this issue, all questions answered. Feel free to re-open it if more questions come up.
