### ISSUE TITLE
How to set the "opt.priority" to be "box" in ocaml workspace for Z3-opt(Ocaml version)?

### ISSUE THREAD

**Issue by gingeredder** [Z3Prover/z3#312]
Thanks for the last reply for #308 . 
Now I want to solve optimization problem of multiple objects in Ocaml workspace.
And I don't know how to set the "opt.priority" to be "box" like in OCaml version.
I have tried this Ocaml interfaces:
Z3.Params.update_param_value ctx "opt.priority" "box"
But it doesn't work.
Could you tell me that how to set the "opt.priority" to be "box" with OCaml interface of Z3-opt?
By Jiahong Jiang

**Comment by gingeredder** [comment]
The Optimize module has the interface "val set_parameters : optimize -> Params.params -> unit", but I don't know how to update the "Params.params" to make the "opt.priority to be box".

**Comment by NikolajBjorner** [comment]
Since you are configuring the parameter locally on the opt object, you should not need the prefix "opt."
For example, from Python you can configure box mode as follows:


from z3 import *

opt = Optimize()
x, y = Ints('x y')
opt.add(Or(x <= y - 3, y <= x - 1))
opt.add(Or(y <= 10, y <= x-1))
opt.add(x <= 10)
opt.add(y <= 10)

h1 = opt.maximize(x)
h2 = opt.maximize(y)
opt.set('priority','box')
is_sat = opt.check()
print h1.value()
print h2.value()
