### ISSUE TITLE
alternative pattern annotations for forall quantifiers are sometimes ignored by Z3

### ISSUE THREAD

**Issue by alexanderjsummers** [Z3Prover/z3#316]
When a forall quantifier is provided with multiple alternative patterns, it seems that Z3 sometimes doesn't use anything but the first pattern. The behaviour seems quite sensitive to the kind of example, but I've managed to cut down one to a fairly reasonable Boogie input (and corresponding smt file). 

Here is the Boogie input:
[Z3_repro.bpl.txt](https://github.com/Z3Prover/z3/files/35442/Z3_repro.bpl.txt)

The axiom starting on line 31 exhibits the problematic behaviour. Uncommenting the alternative version of this axiom below it (or just removing its first trigger annotation in this particular example) will make the file verify. Similarly, one can remove the first pattern annotation from the corresponding quantifier in the smt file, at line 184:
[triggering_repro.smt2.txt](https://github.com/Z3Prover/z3/files/35441/triggering_repro.smt2.txt)

This could be related to the following (old) stack overflow question, where Leonardo confirmed and fixed a bug with [very similar symptoms.](http://stackoverflow.com/questions/11649305/triggering-problems-in-z3)

**Comment by NikolajBjorner** [comment]
This is subtle, but not an accident.
The example uses several multi-patterns, which can become quite expensive.
The default behavior of Z3 is to limit the instantiation of multi-patterns. 

z3 unk.smt2
unknown
(:reason-unknown (incomplete quantifiers))

You can overwrite the default by controlling parameters. 
One parameter that lets Z3 use (more) multi-patterns directly is called smt.qe.max_multi_patterns. 
There is also an internal parameter that isn't exposed that controls the number of rounds admitted for lazy pattern instantiation. It is set at 2. Increasing this number should allow Z3 to also find the match, but as it seems not really exposed at this point I would recommend trying the smt.qe.max_multi_patterns value. 

z3 unk.smt2 smt.qi.max_multi_patterns=3
unsat
(:reason-unknown ok)

**Comment by alexanderjsummers** [comment]
Hi Nikolaj,

Thanks for the information! Is there a way to disable this limit? For example, does 0 mean 0 or any, for this option?

More generally, I'm a bit puzzled about this behaviour. Does Z3 effectively discard multi-patterns from the input? Or will they sometimes be used again later in the run?

Are multi-patterns more expensive than duplicating the axiom, with single patterns? I typically use multi-patterns as a short-hand for this.
It seems that a user writing a multi-pattern would also normally need the pattern to be used in their encoding.

By the way, I'm happy to move this to stack overflow if that would be more appropriate.

Thanks for your help,
Alex

**Comment by NikolajBjorner** [comment]
1. 0 means 0 (not any). What it means is that the first multi-pattern 
gets instantiated eagerly (the first in your list of patterns). The others are not.
2. So yes, you could write the same quantifier with different multi-patterns 
and Z3 would act as if it works eagerly with an unlimited number of multi-patterns. This is so as pointed out in 1: Z3 treats the first pattern in the list of patterns more prominently as other multi-patterns that occur later.
3. Note that a multi-pattern is a :pattern directive with more than one term in the list. It is not the same as multiple :pattern directives. In your example, you have two multi-patterns, each of them contain two terms. So when you say "duplicating" axiom, it does not eliminate what I call a multi-pattern. It eliminates the use of several patterns (or say, multi*ple* patterns).  

Multi-patterns are generally expensive. The reason is that the number of potential matches grows exponentially with the number of terms in the pattern. For example if we have the multi-pattern:

      ( (edge x y) (edge y z) (edge z u) (edge u v))

Then the number of matches grows (potentially exponentially) with the number of different possible paths.

For your purpose I suggest to simply increase the number from 0 to the maximal number of multi-patterns that you use. In this way, Z3 would treat all patterns the same.

**Comment by alexanderjsummers** [comment]
Hi Nikolaj,

Thanks a lot for the extra information, and sorry for my slow reply. I was indeed confusing multi-patterns with multiple ones - thanks for clarifying this!

Is it the case that the additional multi-patterns (above the set threshold) are guaranteed never to be used? Or are there situations in which the behaviour might change?

One reason that getting this threshold to the right level isn't entirely trivial for us is that we have code which generates patterns for quantifiers automatically. It's likely that cases with loads of different multi-patterns are rare, but we'd have to at least try to spot/count them to take this approach. Or I guess we could just set the parameter to something like 1000.

I like your edge example, but if I understand it correctly, this would be problematic even with just one multi-pattern. I guess in the end the number of multi-patterns doesn't determine whether one has the potential for bad triggering behaviour in a particular axiomatisation.

I totally agree that one probably doesn't want the patterns with this behaviour. But having them silently ignored is, I think, very hard for the user to understand. We are also working on tools which help with debugging problematic performance (due to triggering) in these cases, but we need the "full" behaviour of such examples in order to really analyse them.

More generally, I'd find any such situations much easier to debug if Z3 took all of the patterns and then gave us bad performance. I was lucky in this particular instance that a student managed to produce a test case which was quite easy to reduce, but in general it is really hard to detect that patterns written in the input file are not actually being used by the prover. It would be great to get a warning if this occurs in the default case.

It would also be nice to have an option to switch off this threshold. I would personally say that could be the default behaviour - a user writing "too many" multi-patterns will ultimately need to learn what the underlying problem in the encoding is, if they're going to get predictable results.
