### ISSUE TITLE
Feature request: expose finite sorts to the Java API

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#318]
There's currently no way to create finite sorts from Java, so all finite types must be encoded as bitvectors sorts of some size, and constants must be arbitrary bitvector constants.  Since this is already implemented at the C++ level, it would be great if this was exposed to Java.

**Comment by wintersteiger** [comment]
The Java API has EnumSort and FiniteDomainSort and there are examples in JavaExample.java that use them. Is there something that is missing from those two interfaces?

**Comment by seanmcl** [comment]
Ah, my mistake.  I was looking only in the Fixedpoint code.  Thanks.

**Comment by seanmcl** [comment]
Thanks.  That works!  It is not obvious to me how to get the value back out now.  The signature has a bunch of toX and getX.  The getX that return Int are getIndex (only works for bound vars) and getId which  is an implementation detail.  How can I get the int back out of a numeral?   (I tried casting to a BitVecNum, which does have a '.getInt', but that didn't work.)

**Comment by wintersteiger** [comment]
Good question, I'll reopen this issue so we don't forget to answer your question.

**Comment by wintersteiger** [comment]
I just fixed a bug related to finite domain numerals and also added FiniteDomainExpr and FiniteDomainNum objects so that these expressions are easier to work with (in the .NET, Java, and Python APIs). I've also updated the example to illustrate how to use them (see updated [FiniteDomainExample](https://github.com/Z3Prover/z3/blob/master/examples/java/JavaExample.java#L2159)). In Java, the gist is:

    FiniteDomainSort s = ctx.mkFiniteDomainSort("S", 10);
    FiniteDomainNum n = (FiniteDomainNum)ctx.mkNumeral(1, s); // Creates an FD numeral
    int inx = n.getInt(); // Gets the index out of the numeral
