### ISSUE TITLE
Bug, rational produced where an integer is expected.

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#32]
Malte Schwerhoff has previously reported a bug on stackoverflow: 

http://stackoverflow.com/questions/28088487/unexpected-error-message-reproduction-apparently-very-fragile-bug

Internally a rational is produced where an integer is expected.

**Comment by Drup** [comment]
I also saw a similar problem, and for me it was usually an issue of promotion between heterogeneous operands. for `i` and `f` integers and floats, `f + i` was a float and `i + f` an integer, or something like that.

I just added manual promotions everywhere and rolled with it.

**Comment by wintersteiger** [comment]
I can't reproduce this problem with the latest unstable branch anymore, but I suspect the problem is just hidden now, because this file is significantly faster (and with less unknowns) than before. Does either of you still see this problem?

**Comment by NikolajBjorner** [comment]
Issue fix for #161 deals with the case where the arithmetic solver returns l_undef (due to for example non-linear arithmetic). In this case models could still be extracted even though no assurance that the model would satisfy the formula. To ensure that integers are returned during this model construction phase, the arithmetic module truncates non-integer solutions to integer variables. It is reasonable to assume this is the core of also this issue.
