### ISSUE TITLE
Access defining polynomial of algebraic number via C/C++ API

### ISSUE THREAD

**Issue by ahumenberger** [Z3Prover/z3#3245]
Is there a way of accessing the defining components of an algebraic number via the C/C++ API?
That is, I want to get the expressions for `(+ (* 20 (^ x 2)) (* 50 x) 29)` and `1` from `(root-obj (+ (* 20 (^ x 2)) (* 50 x) 29) 1)`.

**Comment by wintersteiger** [comment]
I don't really know, but doesn't `Z3_rcf_get_numerator_denominator` in `z3_rcf.h` allow you to do that?

**Comment by ahumenberger** [comment]
I'm not very familiar with the types in Z3. My situation is the following: I'm using the C++ API, and there I'm getting an object of type `expr` which encapsulates an algebraic number. The `expr` is basically a `Z3_ast`, but how would I turn this into an `Z3_rcf_num`?

**Comment by wintersteiger** [comment]
Good question; there doesn't seem to be an easy way. I suspect that it would work just fine if you cast the `Z3_ast` to a `Z3_rcf_num`, but if it were that easy, it probably wouldn't have been a to-do item in the Python API since 2013 [(here)](https://github.com/Z3Prover/z3/blob/d9c09dcdf94411b70bc23f817b67bf526a17724b/src/api/python/z3/z3rcf.py#L55).

**Comment by NikolajBjorner** [comment]
does it work for you to have the approximations exposed (and not the root polynomials)?

**Comment by NikolajBjorner** [comment]
I think it is dealt with now given the merge. Thanks
