### ISSUE TITLE
Debug branch: soundness issue cased by rewriter.arith_ineq_lhs and nlsat.reorder

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3327]
Hi, for the following formula,
z3 debug branch (Commit 3ac9dbd) returns sat and gives an invalide mode
~~~~
(set-logic NRA)
(set-option :model_validate true)
(set-option :rewriter.arith_ineq_lhs true)
(set-option :nlsat.reorder false)
(declare-const r1 Real)
(declare-const r2 Real)
(declare-const r4 Real)
(declare-const r5 Real)
(declare-const r6 Real)
(declare-const r7 Real)
(assert (exists ((q0 Real) (q1 Bool) (q2 Real) (q3 Bool)) (= (- (* r4 r2 r1 r2)) (* r5 r6 0.7044 r1 r7))))
(assert (<= 0.0 0.0 0.0 r1 r2))
(check-sat)
~~~~

**Comment by NikolajBjorner** [comment]
same as #3303

**Comment by NikolajBjorner** [comment]
The way to see that it is a false positive is by running with -v:10 (verbosity set to 10 or above).
It will then display the sub-formula that didn't pass the model validator.
In this case there is an atomic formula that evaluates to some equality/inequality using root objects instead of "true" (or false). The normal behavior of the model validator is to expect true/false here, but the change of configuration parameter breaks this. The model validator is already a debug option, so somehow tricking the debug facility astray is not a bug that I see worth addressing.
