### ISSUE TITLE
Assertion violation at src/math/lp/emonics.cpp: 527

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3340]
Hi,
For this formula:
```
(set-option :smt.random_seed 1) 
(declare-fun x1uscore3dollarskuscore425 () Real) 
(declare-fun v1 () Real) (declare-fun A ( ) Real ) 
(declare-fun B () Real ) 
(declare-fun v2 () Real) (declare-fun I1 () Real) 
(declare-fun I2 () Real )   
(declare-fun t2721uscore0 () Real) (declare-fun x1 ( ) Real ) 
(declare-fun I1uscore3dollarskuscore632 () Real) 
(declare-fun xI1 ( ) Real ) 
(declare-fun I2uscore3dollarskuscore632 () Real) 
(declare-fun xI2 () Real ) 
(declare-fun V () Real ) 
(declare-fun ep () Real) 
(declare-fun v1uscore3dollarskuscore632 () Real ) 
(assert (not (exists ( (ts2721uscore0 Real)) (let ( ( ?v_0 ( * 
(mod A ts2721uscore0) v1uscore3dollarskuscore632 ) ) ( ?v_1 0 ) ) 
(=> (and (and (and  (>= A 36)) (> V 0 )) (> ep 114 )) 
(=> (>= t2721uscore0 0) (=> (xor (and (<= 0 ts2721uscore0 ) 
( <= ts2721uscore0 t2721uscore0 ) ) (and ( and ( and ( and ( >= ?v_0 0 ) 
(<= ?v_0 V ))) (<= ?v_1 V ) ) (<= ( mod ts2721uscore0 152 ) ep ))) 
( or ( = 2 8 )  ) ) ) ) ) ) ) ) (check-sat) 
```
Z3  throws out an assertion violation. It takes up to 17s on my machine until it triggers.
```
ASSERTION VIOLATION
File: ../src/math/lp/emonics.cpp
Line: 527
found
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB

```

OS: Ubuntu 18.04
Commit: 6ad261e

**Comment by NikolajBjorner** [comment]
dup

**Comment by levnach** [comment]
Reopening for awareness. The snapshot-regression suite in [Z3Prover/bench](https://github.com/Z3Prover/bench) detected that the benchmark(s) derived from this issue regressed to a **timeout** (per-file 20s budget) with the latest Nightly `z3-4.17.0-x64-glibc-2.39`, where a definite result was recorded before:

- `inputs/issues/iss-3340/bug-1.smt2`: `unknown` -> **timeout**

Run: https://github.com/Z3Prover/bench/actions/runs/27527718378

This looks like a possible performance regression rather than a different-but-valid answer, so the snapshot oracle was left unchanged.

**Comment by levnach** [comment]
This looks benign.
