### ISSUE TITLE
Debug and master branches: Assertion violation lp_primal_core_solver_def.h:1299

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3344]
Hi, for the following instance,
[lp1299.txt](https://github.com/Z3Prover/z3/files/4335753/lp1299.txt)

z3 debug branch (Commit 3ac9dbd7d)
throws an assertion violation
~~~~
File: . lp_primal_core_solver_def.h
Line: 1299
!this->use_tableau()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

**Comment by rainoftime** [comment]
Master branch 6ad261e also has the issue

**Comment by NikolajBjorner** [comment]
@levnach; perhaps the assert is spurious. The code is called from a routine called solve_with_tableau, in line 165.

        case lp_status::UNBOUNDED:
            if (this->current_x_is_infeasible()) {
                init_reduced_costs();
                this->set_status(lp_status::UNKNOWN);
            }
            break;
So it would be odd that the function called from here has this assert.
Either way, seems conceptually simple corner case.

**Comment by levnach** [comment]
I fixed some inconsistencies it the tableau optimizations.
I am seeing that the optimization happens when lar_solver is in UNKNOWN state. The stack in below.

Here is the stack. #1  0x0000000000cad250 in lp::lar_solver::get_model (this=0x291c8a8, variable_values=std::unordered_map with 0 elements) at ../../src/math/lp/lar_solver.cpp:1202
#2  0x000000000165e946 in smt::theory_lra::imp::init_variable_values (this=0x291c538) at ../../src/smt/theory_lra.cpp:1547
#3  0x0000000001632610 in smt::theory_lra::imp::init_model (this=0x291c538, mg=...) at ../../src/smt/theory_lra.cpp:3317
#4  0x000000000162e761 in smt::theory_lra::init_model (this=0x291a2b8, m=...) at ../../src/smt/theory_lra.cpp:3915
#5  0x000000000134971d in smt::model_generator::init_model (this=0x28bed38) at ../../src/smt/smt_model_generator.cpp:67
#6  0x000000000134f523 in smt::model_generator::mk_model (this=0x28bed38) at ../../src/smt/smt_model_generator.cpp:497
#7  0x00000000012ba7fc in smt::context::mk_proto_model (this=0x28cbf58) at ../../src/smt/smt_context.cpp:4486
#8  0x00000000012b68ac in smt::context::get_model (this=0x28cbf58, m=...) at ../../src/smt/smt_context.cpp:4509
#9  0x000000000130188d in smt::kernel::imp::get_model (this=0x28cbf58, m=...) at ../../src/smt/smt_kernel.cpp:136
#10 0x0000000001300c60 in smt::kernel::get_model (this=0x28cbec0, m=...) at ../../src/smt/smt_kernel.cpp:319
#11 0x0000000001db399e in opt::opt_solver::get_model_core (this=0x28cbb78, m=...) at ../../src/opt/opt_solver.cpp:317
#12 0x0000000000eefc83 in check_sat_result::get_model (this=0x28cbb78, m=...) at ../../src/solver/check_sat_result.h:58
#13 0x0000000001db19cd in opt::opt_solver::maximize_objective (this=0x28cbb78, i=5, blocker=...) at ../../src/opt/opt_solver.cpp:238
#14 0x0000000001dabd83 in opt::optsmt::update_lower_lex (this=0x28c8880, idx=0, v=..., is_maximize=false) at ../../src/opt/optsmt.cpp:377
#15 0x0000000001daa91e in opt::optsmt::geometric_lex (this=0x28c8880, obj_index=0, is_maximize=false) at ../../src/opt/optsmt.cpp:203
#16 0x0000000001dae7c9 in opt::optsmt::lex (this=0x28c8880, obj_index=0, is_maximize=false) at ../../src/opt/optsmt.cpp:515
#17 0x0000000001d8b629 in opt::context::execute_min_max (this=0x28c87c8, index=0, committed=true, scoped=true, is_max=false) at ../../src/opt/opt_context.cpp:409
#18 0x0000000001d8a951 in opt::context::execute (this=0x28c87c8, obj=..., committed=true, scoped=true) at ../../src/opt/opt_context.cpp:436
#19 0x0000000001d8ab42 in opt::context::execute_lex (this=0x28c87c8) at ../../src/opt/opt_context.cpp:464
#20 0x0000000001d89a0b in opt::context::optimize (this=0x28c87c8, _asms=...) at ../../src/opt/opt_context.cpp:344
#21 0x000000000103e30f in cmd_context::check_sat (this=0x7fffffffe248, num_assumptions=0, assumptions=0x28bf2e0) at ../../src/cmd_context/cmd_context.cpp:1557
#22 0x0000000001088b16 in smt2::parser::parse_check_sat (this=0x7fffffffd710) at ../../src/parsers/smt2/smt2parser.cpp:2596
#23 0x000000000108732f in smt2::parser::parse_cmd (this=0x7fffffffd710) at ../../src/parsers/smt2/smt2parser.cpp:2938
#24 0x0000000001084e44 in smt2::parser::operator() (this=0x7fffffffd710) at ../../src/parsers/smt2/smt2parser.cpp:3130
#25 0x00000000010840bb in parse_smt2_commands (ctx=..., is=..., interactive=false, ps=..., filename=0x0) at ../../src/parsers/smt2/smt2parser.cpp:3179
#26 0x0000000001e9707e in read_smtlib2_commands (file_name=0x7fffffffea3b "/home/lev/Dropbox/smts/3344.smt2") at ../../src/shell/smtlib_frontend.cpp:89
#27 0x0000000001e94c29 in main (argc=2, argv=0x7fffffffe708) at ../../src/shell/main.cpp:352
(gdb) r
Starting program: /home/lev/dev/z3/build/debug/z3 /home/lev/Dropbox/smts/3344.smt2
[Switching to thread 1 (process 11751)](running)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000429d23 in invoke_gdb () at ../../src/util/debug.cpp:91
91	            *x = 0;
(gdb) bt
#0  0x0000000000429d23 in invoke_gdb () at ../../src/util/debug.cpp:91
#1  0x0000000000cad250 in lp::lar_solver::get_model (this=0x291c8a8, variable_values=std::unordered_map with 0 elements) at ../../src/math/lp/lar_solver.cpp:1202
#2  0x000000000165e946 in smt::theory_lra::imp::init_variable_values (this=0x291c538) at ../../src/smt/theory_lra.cpp:1547
#3  0x0000000001632610 in smt::theory_lra::imp::init_model (this=0x291c538, mg=...) at ../../src/smt/theory_lra.cpp:3317
#4  0x000000000162e761 in smt::theory_lra::init_model (this=0x291a2b8, m=...) at ../../src/smt/theory_lra.cpp:3915
#5  0x000000000134971d in smt::model_generator::init_model (this=0x28bed38) at ../../src/smt/smt_model_generator.cpp:67
#6  0x000000000134f523 in smt::model_generator::mk_model (this=0x28bed38) at ../../src/smt/smt_model_generator.cpp:497
#7  0x00000000012ba7fc in smt::context::mk_proto_model (this=0x28cbf58) at ../../src/smt/smt_context.cpp:4486
#8  0x00000000012b68ac in smt::context::get_model (this=0x28cbf58, m=...) at ../../src/smt/smt_context.cpp:4509
#9  0x000000000130188d in smt::kernel::imp::get_model (this=0x28cbf58, m=...) at ../../src/smt/smt_kernel.cpp:136
#10 0x0000000001300c60 in smt::kernel::get_model (this=0x28cbec0, m=...) at ../../src/smt/smt_kernel.cpp:319
#11 0x0000000001db399e in opt::opt_solver::get_model_core (this=0x28cbb78, m=...) at ../../src/opt/opt_solver.cpp:317
#12 0x0000000000eefc83 in check_sat_result::get_model (this=0x28cbb78, m=...) at ../../src/solver/check_sat_result.h:58
#13 0x0000000001db19cd in opt::opt_solver::maximize_objective (this=0x28cbb78, i=5, blocker=...) at ../../src/opt/opt_solver.cpp:238
#14 0x0000000001dabd83 in opt::optsmt::update_lower_lex (this=0x28c8880, idx=0, v=..., is_maximize=false) at ../../src/opt/optsmt.cpp:377
#15 0x0000000001daa91e in opt::optsmt::geometric_lex (this=0x28c8880, obj_index=0, is_maximize=false) at ../../src/opt/optsmt.cpp:203
#16 0x0000000001dae7c9 in opt::optsmt::lex (this=0x28c8880, obj_index=0, is_maximize=false) at ../../src/opt/optsmt.cpp:515
#17 0x0000000001d8b629 in opt::context::execute_min_max (this=0x28c87c8, index=0, committed=true, scoped=true, is_max=false) at ../../src/opt/opt_context.cpp:409
#18 0x0000000001d8a951 in opt::context::execute (this=0x28c87c8, obj=..., committed=true, scoped=true) at ../../src/opt/opt_context.cpp:436
#19 0x0000000001d8ab42 in opt::context::execute_lex (this=0x28c87c8) at ../../src/opt/opt_context.cpp:464
#20 0x0000000001d89a0b in opt::context::optimize (this=0x28c87c8, _asms=...) at ../../src/opt/opt_context.cpp:344
#21 0x000000000103e30f in cmd_context::check_sat (this=0x7fffffffe248, num_assumptions=0, assumptions=0x28bf2e0) at ../../src/cmd_context/cmd_context.cpp:1557
#22 0x0000000001088b16 in smt2::parser::parse_check_sat (this=0x7fffffffd710) at ../../src/parsers/smt2/smt2parser.cpp:2596
#23 0x000000000108732f in smt2::parser::parse_cmd (this=0x7fffffffd710) at ../../src/parsers/smt2/smt2parser.cpp:2938
#24 0x0000000001084e44 in smt2::parser::operator() (this=0x7fffffffd710) at ../../src/parsers/smt2/smt2parser.cpp:3130

**Comment by NikolajBjorner** [comment]
looks like the bug that was fixed in master. Better to address opt specific bugs only in master and avoid redundant work.
