### ISSUE TITLE
Thinking about changes to the build scripts

### ISSUE THREAD

**Issue by zv** [Z3Prover/z3#336]
As a matter of personal interest, I have started developing JavaScript bindings for Z3, extensively referencing the python API generation code. Although @leodemoura has given fair warning in the headers of the build scripts, warning that they are hacks that have 'gone too far', the binding generation code has gotten somewhat hairy over time!

I have made some changes to help make it easier for me to write these JavaScript bindings but I don't want to duplicate work if @wintersteiger, @NikolajBjorner or @leodemoura are already rewriting or refactoring the binding generation / scripts. 

(Another great benefit is generating an up to date list of syntax 'keywords' / 'symbols' for the syntax highlighting of `z3-mode` - which a rewrite of the scripts code could make much easier as well)

**Comment by NikolajBjorner** [comment]
We aren't refactoring the bindings right now. I removed a bunch of deprecated APIs last week but they were not referenced. Suggestions and changes on the python side are welcome. I can see there are some python specific pull requests that are lingering (for the build scripts, not the auto-generation). One adds a path variable multiple places, so it seems to better refactor this before taking it, but otherwise contributions are welcome.

**Comment by wintersteiger** [comment]
I totally agree with Nikolaj, this is definitely welcome and nobody is working on it as far as I know.

The existing scripts are already sort of modular in that their stubs generation code is very similar. It would be great if we could have just one script for all APIs to plug in to, so that only the "simple" things like syntax have to be implemented to add new APIs. Also, the current scripts generate a bunch of files in the src directory, ideally we should move all of that to the build directory, and move the stubs generation code into src/api/language. .

**Comment by NikolajBjorner** [comment]
@zv Should we integrate your javascript bindings or can we close this as an issue?

**Comment by zv** [comment]
I am squashing commits now! I will have a PR for you by Friday.

**Comment by delcypher** [comment]
@zv When doing this if possible please consider the CMake build system too if you  have time.

**Comment by NikolajBjorner** [comment]
Yes, my take is that the cmake system, thanks to Dan, is the way forward so I would prioritize making features work with it for new features.
