### ISSUE TITLE
Reducing memory consumption

### ISSUE THREAD

**Issue by SweetVishnya** [Z3Prover/z3#3400]
Hi!

I am trying to solve a path predicate for a program which reads a big input file. The solver process crashes due to "Out of memory".
I create a single symbolic variable &mdash; bit-vector of an enormous size. The bit-vector represents an input file. Will z3 solving use less memory if I split this bit-vector into multiple bit-vectors (create multiple symbolic variables)?
Also, is there any way to limit memory consumption for z3 solving process?

**Comment by SweetVishnya** [comment]
I use C API and `Z3_model_eval`.

**Comment by NikolajBjorner** [comment]
It makes no difference if you use one or more bit-vectors. In the end, all bits, regardless of where they come from, are represented as Boolean predicates.
If you have a file that is, say 1GB, you end up having 1Billion Boolean predicates using the bit-vector representation used. 
Z3 blasts all bits into Boolean predicates because this is what with current approaches works best for mainstream applications. If you end up creating bit-vectors with hundreds or thousands of bits, this representation isn't good. There are potentially other ways to handle bitvectors of large bit-width, but they are not available (in Z3). 

You can try starting with different representations, though.
For example, a predicate P(idx) that takes one argument idx can encode a bit-vector of arbitrary size, or whatever size the domain of idx is. Similarly, a predicate P(b1, b2, b3, b4, .., b20), can represent a bit-vector of size 1M, where b1, b2, ..., b20 are Boolean arguments.
The adequacy of using representations, such as these mentioned above, are completely dependent on the application characteristics. 
For fuzzing applications, it is perhaps not a change in representation, but a change in slicing by the tool calling the solver, that makes better sense to pursue.

**Comment by SweetVishnya** [comment]
Thank you for the answer. I will try getting model only for the part of the file. And I suppose we should implement slicing for comprehensive examples.
