### ISSUE TITLE
opt: non-deterministic assertion violation at model_based_opt.cpp:183

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3412]
A related issue that was fixed before https://github.com/Z3Prover/z3/issues/3131

-----

Hi, for the following instance,  z3 master branch (Commit e075f38) nondeterminstically throws out an assertion violation:
[nondet.txt](https://github.com/Z3Prover/z3/files/4354036/nondet.txt)

~~~~
ASSERTION VIOLATION
File: ../src/math/simplex/model_based_opt.cpp
Line: 183
index == 0 || r.m_type != t_le || !r.m_value.is_pos()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~
The timeout should be around 10seconds.

For the same instance, sometimes, z3 crashed at the other program point
~~~~
File: ../src/qe/qe_arith.cpp
Line: 345
UNREACHABLE CODE WAS REACHED
~~~~

**Comment by NikolajBjorner** [comment]
This doesn't reproduce, however, the use of timeouts indicates it happens during cancelation. 
I have added some stopgaps to bail out the code that relies on model_based_opt during cancelation. 
Otherwise this seems low priority. It is possible that the cancelation path is incorrect, but in this case I suspect it isn't because cancellation is already checked above in the stack.
