### ISSUE TITLE
Z3 internals: simulating (declare-const) from inside a theory plugin

### ISSUE THREAD

**Issue by mtrberzi** [Z3Prover/z3#348]
One of the reduction steps in the theory plugin (for strings) I'm working on involves creating a fresh string variable and then asserting some facts about it. I couldn't find any other theory plugins that need to do something like this, so I guessed that the best approach would be to simulate what `smt2parser` does when it encounters a `(declare-const)` expression. To this end I have the following code:

```
app * theory_str::mk_str_var(std::string name) {
	context & ctx = get_context();
	ast_manager & m = get_manager();

	sort * string_sort = m.mk_sort(m_strutil.get_family_id(), STRING_SORT);
	char * new_buffer = alloc_svect(char, name.length() + 1);
	strcpy(new_buffer, name.c_str());
	symbol sym(new_buffer);

	app * a = m.mk_const(m.mk_const_decl(sym, string_sort));

	ctx.internalize(a, false);
	SASSERT(ctx.get_enode(a) != NULL);
	SASSERT(ctx.e_internalized(a));
	m_basicstr_axiom_todo.push_back(ctx.get_enode(a));

        // some internal stuff I have to keep track of
	variable_set.insert(a);
	internal_variable_set.insert(a);
	track_variable_scope(a);

	return a;
}
```

It seems that this method works sometimes and fails other times. In particular, in one test case I'm working with, I create a temporary variable and make some assertions with it, then the solver pops the context (deallocating that variable in the process), and then later I create a second temporary variable (with a different name). The first variable successfully has the assertions applied; the second one fails the assertion `get_id() >= c_first_decl_id` in `ast/ast.h:547`. This is very strange, and inspecting the object in the debugger seems to suggest that some of its fields don't point to valid memory.

It's definitely not the case that the fresh variable goes out of context before I try to use it. The context doesn't push or pop before this assertion failure; the variable is created and then immediately used in the same method without returning control to the solver.

If it matters, I'm doing all of this inside `final_check_eh()`.

The other strange factor is that code similar to this worked in a previous version of this string solver (Z3str2, built against Z3 4.1.1) with the code:

```
Z3_ast mk_var(Z3_context ctx, const char * name, Z3_sort ty) {
  Z3_symbol s = Z3_mk_string_symbol(ctx, name);
  return Z3_mk_const(ctx, s, ty);
}
```

and `Z3_mk_const()` doing almost exactly what I'm doing here except also calling the function `save_ast_trail()` which I cannot seem to access from the new API.

I would appreciate any assistance you can provide with respect to how to generate fresh theory variables / constants from inside my theory plugin.

**Comment by NikolajBjorner** [comment]
I suggest to maintain a trail object in the theory solver that ensures that locally created ast objects have a lifetime of the solver. There are several examples in the code where we use "m_trail" of type expr_ref_vector to pin expressions. 
The other suggestion is that you can simplify 

    char * new_buffer = alloc_svect(char, name.length() + 1);
    strcpy(new_buffer, name.c_str());
    symbol sym(new_buffer);

to just 
    symbol sym(name.c_str());

The symbol objects are persistent (don't get de-allocated).

**Comment by NikolajBjorner** [comment]
Some other suggestions:

1. Avoid alloc_svect in higher-level code. Use instead the svector or buffer classes. This also solves memory leaks down the road.
2. Avoid std::map and in particular don't use this for heap-allocated pointers because behavior will not reproduce between calls. Use obj_map, which uses the identifiers of objects, such as expressions for indexing. Generally, Z3 does not use std::map and instead uses the custom hash tables. This also ensures that all memory allocations use the shared allocator and that memory pressure, allocation counts get detected as a realistic measure.
3. Use the ast_manager::mk_fresh_func_decl/mk_fresh_... routines when creating fresh function symbols/constants. You don't have to maintain your own name space or counters then.
4. Use expr_ref and expr_ref_vector when accumulating intermediary expresssions. Don't use alloc_svect to allocate a raw array and populate it with expression pointers. ast/ast_util.h contains a few utilities for taking expr_ref_vectors into conjunctions and disjunctions. More shorthands can be added by request.

**Comment by mtrberzi** [comment]
Thanks very much for the advice -- this is extremely useful. I'll look over my code and incorporate these suggestions, and follow up if I continue to experience any issues.

**Comment by NikolajBjorner** [comment]
I hope it will help. Many things that have to do with using internal Z3 features can be simplified.
To give an example, you can write:

app * theory_str::mk_internal_xor_var() { 
       app * a = get_manager().mk_fresh_const("xor", m_autil.mk_int());
       m_trail.push_back(a);
       return a;
}

instead of the 15 line version I can see in "develop". Let me know if/when you can use a code review
(especially after changing tab to 4 spaces in your editor :-)).

**Comment by NikolajBjorner** [comment]
Here is another idea: 
In class str_recognizers add methods:
   bool is_concat(app* e) const { return is_app_of(m_fid, OP_CONCAT); }
   bool is_concat(expr* e) const { return is_app(e) && is_concat(to_app(e)); }
and also 
   MATCH_BINARY(is_concat);
The second function returns the two arguments of concatenation if the match succeeds, and you can use this to shorten a lot of tedious matching code.

**Comment by NikolajBjorner** [comment]
Regarding the last comment on utilities. I added some basic support for a signature of strings in the master branch. I hope you can leverage this. Strings are really a special case of sequences, so the features are added to seq_decl_plugin.h. This also allows parsing benchmarks that use strings. You would have to pull the latest master into your branch, which is a bit of a merge.

**Comment by mtrberzi** [comment]
Yes, that will be some work to merge but I'll make a note of it for later. Probably what I will end up doing is coming back to `seq_decl_plugin.h` once I am ready to open a pull request with this code (since then I will only need to sort out the merge one time :-) )

For the immediate future I am focusing on reaching backwards compatibility with Z3str2 (as well as testing and benchmarking of course).

**Comment by NikolajBjorner** [comment]
I suggest you take a look at the latest master branch where a lot of native support for strings, sequences and regular expressions has been added. Hopefully you can leverage this.

**Comment by mtrberzi** [comment]
Cool, I will definitely review that, hopefully we will be able to integrate the Z3str2 work with the native solver.
