### ISSUE TITLE
Debug branch: smt Assertion violation at ../src/math/lp/emonics.cpp Line: 346

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3482]
Hi,
For this formula:
```
(declare-fun a () Real)   
(declare-fun b () Real) 
(declare-fun c () Real)  
(declare-fun d () Real) 
(declare-fun h () Real) 
(declare-fun e () Real) 
(declare-fun f () Real) 
(declare-fun i () Real) 
(assert (not (exists ((g Real)) (and (or (< 0.0 (* a c))) (<= (- (* d g)) e))))) 
(assert (= b (+ d i))) 
(assert (= c (/ h f f))) 
(check-sat-using smt)    
```
Z3 debug branch  throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/math/lp/emonics.cpp
Line: 346
invariant()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Commit: 8d39694

**Comment by 5hadowblad3** [comment]
I think it is duplicate with #3480

**Comment by zhendongsu** [comment]
Looks like you don't reduce your reported test formulas ...  but this one is cleanly minimized --- test minimization takes effort, but, in general, could also save folks like Nikolaj's valuable time.  In fact, I wish he had consistently insisted on every test to be minimized before being reported.  @NikolajBjorner

**Comment by zhendongsu** [comment]
The CVC4 folks, for example, have been more adamant in having reduced tests, Nikolaj :)  @NikolajBjorner

**Comment by rainoftime** [comment]
Here is a reduced test from issue 3480.
Perhaps the root cause might be different (since the two tests use different theories and different tactics)
~~~~
(set-logic NIA)
(declare-const i0 Int)
(declare-const i1 Int)
(assert (exists ((q0 Bool) (q1 Int)) (=> (<= i0 i1) (not q0))))
(assert (forall ((q12 Int) (q13 Int)) (not (<= q12 (mod 535 (- 248 (abs i1) 38 i1 (abs i1)))))))
(assert (or (distinct 38 (div (abs i1) 412))))
(check-sat-using (then ctx-solver-simplify smt))
~~~~
