### ISSUE TITLE
Spurious model validation error

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3516]
```
$bin/z3-145ec8f model_validate=true bug.smt2
sat
(error "line 2 column 10: an invalid model was generated")
(model 
)
$cat bug.smt2 
(assert (= (seq.indexof (seq.unit 0) (seq.unit 0)) 0))
(check-sat)
(get-model)
```
OS: Ubuntu 18.04
Commit: 145ec8f

**Comment by NikolajBjorner** [comment]
it is essentially a false positive. You can inspect false positives by running with verbose set to 10.
Then model validation prints the expected value vs obtained value. The expected value is true, the obtained value is something that is not reduced. This is because the rewriter does not necessarily ground normalize indexof on general sequences. I have added a slight heuristic to increase simplification coverage, but generally it cannot be a requirement that the simplifier be complete when the use case is the model validator.
