### ISSUE TITLE
support for smt-lib standard version 2.5

### ISSUE THREAD

**Issue by PierreVDL** [Z3Prover/z3#352]
Since June 28, 2015 the new smt-lib standard version 2.5 is available.
See e.g. http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.5-r2015-06-28.pdf
Z3 should support this version as well.

**Comment by wintersteiger** [comment]
Some of the new features have already been added (see #351). Could you perhaps add a list of features that are still missing to this issue here, so we can keep track of what's missing?

**Comment by PierreVDL** [comment]
Probably my list of missing features is far too limited, but at least I miss:
* Recursive functions (see page 58 of standard)
* single string escape character: "" only (see page 22 of the standard)
* explicit support Logic DT (Z3 supports datatypes but doesn't require DT in the logic name)
* parsing of all 2.5 features (possibly generating warning on not yet supported features)

**Comment by NikolajBjorner** [comment]
- You can enter recursive functions. We print a warning message at this point as there is no special handling other than asserting the straight-forward axioms. Additional support will have to depend on use cases. Since you can reason about recursive functions by generating Horn clauses in Z3, we do already offer ways to deal with theorems about recursive functions. It does require the front ends to be aware of such encodings, but this amply described in several papers and is essentially just a way to symbolically write down Hoare logic assertions with placeholders (my home page contains some introductory material and papers by Andrey Rybalchenko). Just asserting recursive equations invokes engines that are currently not tuned specifically for checking satisfiability in the context of recursive definitions. 
- simple string characters are supported.
- Not sure where is DT described. Is it really important or is it a matter of nit?
- Specifically, what other features are not parsed?

**Comment by NikolajBjorner** [comment]
1. The available features for sequences is now described on http://rise4fun.com/Z3/tutorial/sequences
2. define-rec-fun and define-rec-funs now use a special quantifier instantiation mechanism that allows establishing satisfiability. Z3 assumes silently that the recursive function definitions are well-founded.
