### ISSUE TITLE
":named" annotation ignored by solver.from_string() in Z3Py

### ISSUE THREAD

**Issue by drlagos** [Z3Prover/z3#3537]
I'm not sure if this is intended behavior but it bit me today so I thought it would be worth checking out.

I have a piece of code that generates an smt-lib string where all the added constraints are annotated with a name, the point being that I can get a "requirement conflict" out of it in the unsat case.
A simple example would be:

(set-logic QF_LIA)
(declare-const x Int)
(assert (! (> x 0) :named $x_gt_0))
(assert (! (< x 0) :named $x_lt_0))
(check-sat)

I feed this to Z3 with:
solver.from_string(example)

The named annotations are parsed but are apparently ignored. 
If I do solver.to_smt() there are no new variables in the model, nor are there any named annotations.

With assert_and_track we have to add new variables ourselves and with those it works correctly. 
New variables and implications are added to the model and unsat-cores are correctly generated.
I can change my code rather easily to do that but it was surprising to see this behavior.

**Comment by NikolajBjorner** [comment]
It is correct that it would ignore named assumptions.
I have changed the behavior so that the parsed solver state now includes the assumptions
(as implications, which is their default representation). 
It is still subtle to get it to work because you have to enable unsat_core explicitly to get the tracking assumptions. Without unsat cores set it ignores assumptions.


```
from z3 import *

lia = """
(set-option :unsat-core true)
(set-logic QF_LIA)
(declare-const x Int)
(assert (! (> x 0) :named $x_gt_0))
(assert (! (< x 0) :named $x_lt_0))
(check-sat)
"""

s = Solver()
s.from_string(lia)
print(s.sexpr())

```

**Comment by drlagos** [comment]
Awesome, thank you!
