### ISSUE TITLE
Python installation

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#361]
The Python installation (make install) needs a little bit more work. @delcypher and @NikolajBjorner are interested. 

After the latest fixes, there are these issues remaining:
- Currently, we install a separate copy or symlink of libz3.so/.dylib in the Python site-/dist- packages directory. We should change that to use the system-wide installation of libz3.\* in expectation of system and Python packages being installed separately, or at least check whether there is already a libz3.\* and only install a new one if none is found.
- The warning messages on OSX should be 'softened' a bit as discussed in #357 
- Currently, the same warning messages about installation outside of the prefix are also thrown during _un_installation. Perhaps we should change that into warnings about the system package potentially being broken?

**Comment by delcypher** [comment]
> Currently, we install a separate copy or symlink of libz3.so/.dylib in the Python site-/dist- packages directory. We should change that to use the system-wide installation of libz3.* in expectation of system and Python packages being installed separately, or at least check whether there is already a libz3.* and only install a new one if none is found.

I see code in ``z3core.py`` for this. Looks like it'll just try ``libz3.so`` first it'll pick up if ``libz3.so`` is installed properly. What is the reasoning for copying/sym-linking ``libz3.so`` to the Python package directory? It looks completely unnecessary because

* If ``libz3.so`` is installed properly that will be used
* You tell users to set up their ``LD_LIBRARY_PATH`` already.

I would be in favour of not installing a copy/symlink of ``libz3.so`` in the python package directory at all (perhaps it's needed on Windows though?).

I also noticed for Python 3 the building system copies over the ``__pycache__`` directory, is there a reason for doing this?

> The warning messages on OSX should be 'softened' a bit as discussed in #357

I don't think we actually discussed softening the warnings from what they are now.
What is wrong with how they are now.

> Currently, the same warning messages about installation outside of the prefix are also thrown during _un_installation. Perhaps we should change that into warnings about the system package potentially being broken?

The message currently makes sense in both the install/uninstall case when you read the makefile. It isn't quite so useful if you don't know the commands being run during ``install`` and ``uninstall``.

I'm happy enough with the messages as they are but If you feel you really need to change them I (probably) won't object.

**Comment by wintersteiger** [comment]
Yes there is a reason for the __pycache__ copy. At some point we had trouble with students having installed a different version of Python (3.x, pre 3.5.0) than us and it produced different errors, the quick fix for that was to pre-compile packages for them that contained the compiled python files (*.pyc or __pycache__). At the moment, this shouldn't hurt anybody, so I think we can keep it. 

#357 said "warning, installing outside..." while the current code says "... broken installation ..." which is too aggressive, on OSX this is "normal" not "broken"

During uninstallation we get exactly the same message as during installation which is '... is not in the install prefix. This will likely lead to a broken installation.' But there is no 'installation' being performed at that point. We should either not warn at all, or warn them that this might break their system-package-managed installation of Z3 if that was in the same directory.

**Comment by delcypher** [comment]
The last two points, i.e.

> * The warning messages on OSX should be 'softened' a bit as discussed in #357
>
> * Currently, the same warning messages about installation outside of the prefix are also thrown during _un_installation. Perhaps we should change that into warnings about the system package potentially being broken?

Are addressed by #374

**Comment by delcypher** [comment]
@wintersteiger 
Regarding this point

> Currently, we install a separate copy or symlink of libz3.so/.dylib in the Python site-/dist- packages directory. We should change that to use the system-wide installation of libz3.* in expectation of system and Python packages being installed separately, or at least check whether there is already a libz3.* and only install a new one if none is found.

I think all we need to do is

* Remove the ``install/uninstall`` step for the copy/symlink of libz3 in the ``site-packages`` directory
* Change the logic in ``z3core.py`` to not look in the ``site-packages`` directory for libz3

This simplifies install/uninstall (I can rip out the symlink logic which is a bit complicated) and the logic in ``z3core.py``. Given that we tell Linux and OSX users that the library directory used for install needs to be in ``LD_LIBRARY_PATH`` or ``DYLD_LIBRARY_PATH`` this seems fine.

However I'm not sure about Windows because it doesn't have a global location for libraries and also has the convention of looking for dynamic libraries in the current directory. Do we need to do something special here?

**Comment by wintersteiger** [comment]
Sounds good. I can't find a point in the code that tries to find files in the site-config dir. `lib()` in z3core.py just adds the current directory as far as I can tell. We may have explicitly add a lookup in LD_LIBRARY_PATH though. 

Windows should be alright. There is no install target for Windows, the Makefile just tells the user to add the build directory to PYTHONPATH. We may want to add that it also has to be added to PATH so libz3.dll is found.

**Comment by wintersteiger** [comment]
The Windows build was broken since #357 but that was hidden by other (unrelated) problems until now. Should be fixed in two different ways now (see previous two commits), but it may be worth taking another look at it as there may well be more similar problems. 

Also, we may want to keep an install target for installing the Python API only if the user wants to install it into their 'global' package directory. (Without libz3.dll, or perhaps optionally also adding that if the user asks for it).

**Comment by NikolajBjorner** [comment]
The pip package is now a supported way to install Z3 (Linux and Windows). I would therefore down-prioritize fiddling with self-installs.
