### ISSUE TITLE
Invalid model with Seq 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3665]
Hi,
For this formula:
```
(declare-fun a () (Seq Int)) 
(declare-fun b () Int) 
(declare-fun c () Int) 
(define-fun d () Int b) 
(define-fun j () Bool (distinct c d)) 
(define-fun e () Bool j) 
(define-fun f () Bool (not e)) 
(define-fun g () (Seq Int) (seq.unit c)) 
(define-fun h () Int (seq.indexof a g)) 
(define-fun i () Bool (> h b)) 
(define-fun k () Bool (or f i)) 
(assert k) 
(check-sat)
```
Z3  gives an invalid model:
```
$ ./z3/build/z3 model_validate=true small.smt2 
sat
(error "line 13 column 10: an invalid model was generated")
$ cat small.smt2 
(declare-fun a () (Seq Int)) 
(declare-fun b () Int) 
(declare-fun c () Int) 
(define-fun d () Int b) 
(define-fun j () Bool (distinct c d)) 
(define-fun e () Bool j) 
(define-fun f () Bool (not e)) 
(define-fun g () (Seq Int) (seq.unit c)) 
(define-fun h () Int (seq.indexof a g)) 
(define-fun i () Bool (> h b)) 
(define-fun k () Bool (or f i)) 
(assert k) 
(check-sat)
```

OS: Ubuntu 18.04
Commit: 65b2037

**Comment by zhendongsu** [comment]
The generated model seems to be correct when it is fed to the formula, but -v:10 still complains that "model check failed on: ...". 

Interestingly, on the original unreduced test, z3 complains about an invalid model, but z3 smt.arith.solver=6 does not (on this reduced test, both complain).

**Comment by NikolajBjorner** [comment]
we have seen this false positive before.

model check failed on:  (or (not (distinct c b)) (> (seq.indexof a (seq.unit c)) b))
expected value: true
#31: (or #26 #30) (not (<= (seq.indexof (as seq.empty (Seq Int)) (seq.unit 38) 0) (- 2)))

indexof isn't rewritten to a value even as the arguments are ground.
Since model-validate is best effort and seq rewriting too it is a won't fix.
