### ISSUE TITLE
Invalid model on QF_FP formula

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3776]
Related: #3462, #3496
```
[846] % z3 model_validate=true small.smt2
sat
(error "line 6 column 10: an invalid model was generated")
[847] % 
[847] % cat small.smt2
(define-sort FPN () (_ FloatingPoint 50 100))
(declare-fun x () FPN)
(declare-fun b () FPN)
(declare-fun c () FPN)
(assert (= (fp.sub roundTowardNegative x b) c))
(check-sat)
[848] %
```
OS: Ubuntu 18.04
Commit: 550852b

**Comment by wintersteiger** [comment]
This is another case of the bug report not being reproducible because the models have changed since it was submitted. Please always include a printout of the invalid model for this type of bug report. 

I was able to find a different model after playing around with it for a while and there was indeed a bug in the FP rounding algorithm, which only manifested itself when huge exponents are used.

**Comment by wintered** [comment]
> This is another case of the bug report not being reproducible because the models have changed since it was submitted. Please always include a printout of the invalid model for this type of bug report.

Thank you for fixing this bug @wintersteiger. We will certainly include the invalid model next time.
