### ISSUE TITLE
java API error in MacOSX

### ISSUE THREAD

**Issue by levilucio** [Z3Prover/z3#384]
The problem shown up on MacOSX Yosemite 10.10.4 where I'm getting a C error outside the Java VM, apparently some dynamic memory allocation problem, that crashes my whole application. The problem has been reported on stackoverflow here:

http://stackoverflow.com/questions/14707790/segmentation-fault-in-java-using-z3

here's what I get on my Eclipse console:

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x0000000146db15c8, pid=2139, tid=45827

 JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
 Problematic frame:
 [thread 54063 also had an error]
C  [libz3.dylib+0xb9b5c8]  _ZN11mpz_managerILb1EE7big_setER3mpzRKS1_+0x48

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /Applications/eclipse_Kepler/Eclipse.app/Contents/MacOS/hs_err_pid2139.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by wintersteiger** [comment]
Can you clarify what you are trying to do? That stackoverflow post was about java bindings different from our own, so if that breaks we would need to talk to their author first. If you are using our own, something like Z3Object ... = new ... is incorrect usage, but the compiler might not warn about it (and our private/public declarations may be wrong, cant check right now).

**Comment by levilucio** [comment]
Here is the method where I instantiate Z3 objects:

	public static boolean isSatisfiableZ3(IRestrictionTerm r) {

		// context for the Z3 solver
		Map<String, String> solverSettings = new HashMap<String, String>();
		solverSettings.put("unsat_core", "false");
		solverSettings.put("timeout", Integer.toString(Z3Timeout * 1000));

		Context context = null;
		context = new Context(solverSettings);

		// Z3 Solver
		Optimize solver;

		// empty restriction term
		if(r == null) {
			return true;
		}

		BoolExpr r_inZ3format = toZ3(context, r);
		solver = context.mkOptimize();
		solver.Add(r_inZ3format);

		Status check = solver.Check();

		if(check == SATISFIABLE)
			return true;

		return false;
	}

The toZ3 method above is used to convert our internal representation of propositional logic formulas into Z3's representation. It uses the mk... methods in the context to build the objects that compose the formula.

I forgot to mention this code runs fine on Windows and Linux (Ubuntu).

Thanks!

**Comment by wintersteiger** [comment]
Looking closer at the trace this may be a simple out-of-memory problem. 

If I'm reading this correctly, the stackoverflow post that you cite has nothing whatsoever to do with the problem you are seeing right now. It just happens to mention Java and segfaults. Is that correct?

mpz_manager::big_set is a very old and well tested function and I wouldn't expect a segfault to originate there. However, it (de-) allocates pieces of memory when numbers get bigger (smaller), so I would expect that either allocation fails or that some part of the memory has been corrupted before (e.g. a double free).

Since OSX does not come with Java: Which version of Java are you using? From the version strings in the crash output, I assume it's Oracle Java 1.8.0_60, but it may well be that some other implementation tries to mimic Oracle Java. 

The Oracle Server VM (which is indicated by the crash output) uses the concurrent garbage collector by default, so there could be a problem that is concurrency related and that you wouldn't see on another OS that perhaps uses the non-server VM by default. Are you using any kind of concurrency/parallelism on your side?

By default, Java VMs are not allowed to use all of the system memory, that requires options and the amount and options may have to be set up differently for different systems or Java implementations. So without further information, I'd guess that the JVM is out of memory but the native code doesn't throw a nice exception (which may or may not be fixable from our side).

**Comment by wintersteiger** [comment]
Since there has not been an update to this in two weeks, can we assume this problem is fixed and close the issue?

**Comment by levilucio** [comment]
Thanks for the comment and sorry for the late answer - I was on vacation and with little internet access.

Yes, the stackoverflow post I cite happens to throw the same error but it could have nothing to do with the real problem.

I am using Oracle Java 1.8.0_60

We are using concurrency in our framework and the code that I showed above is part of a thread that executes periodically to perform consistency checks in the model we are building.

I don't have now the details of the kind of threading that is being used for this as this code has been done by someone else, but I will find them and post them here soon. I will try to play with the memory thread options to see if the problem goes away.

**Comment by levilucio** [comment]
I'd appreciate you don't close the issue yet, I'll post here soon. Thanks.

**Comment by levilucio** [comment]
I checked with the framework developer, but I got the answer that manipulating the threads programmatically from Java is not possible. He suggested I play with the JVM start options.

I played around with the JVM options (e.g. -Djava.awt.headless, -Xmx, -Xss) to try to give more memory to the threads, but couldn't get it to work.

Finally I upgraded my Mac OS to the latest version (El Capitan) as I suspected that might be the issue, but still got the same problem.

Any suggestions are helpful at this point...

**Comment by wintersteiger** [comment]
Before going anywhere, can you make sure that every thread in the system uses its own Context object? Calling mk* on the same context from different threads is not supported and will most definitely throw segfaults and other similar errors. As long as this is not absolutely clear it doesn't make sense to chase any other leads. 

Since it works fine on Windows and Linux, can you find out which versions of JVMs are running there? If you like, you can try different [garbage collectors](http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/gc01/index.html), e.g., `-XX:+UseSerialGC` should be the 'safest' one.

**Comment by levilucio** [comment]
If you mean context objects being passed around between threads then that definitely does not happen.

My colleagues that are running the code on Linux use the Oracle VM too:

Oracle VM:

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

I also ran the code with all other garbage collectors (the ones mentioned in the page you pointed me to) but also no luck.

Finally, to be sure that it's not a freak combination of OS / Java / Eclipse / other in my machine that's causing the problem I asked another colleague with the same configuration I have to run the code. He ran into the same problem.

**Comment by wintersteiger** [comment]
The critical point for this issue is this line here:

    C [libz3.dylib+0xb9b5c8] ZN11mpz_managerILb1EE7big_setER3mpzRKS1+0x48

Does it always crash in exactly this same spot?

Also, can you share your input (large/slow is fine), or an API interaction log (use [Log.open](http://z3prover.github.io/api/html/classcom_1_1microsoft_1_1z3_1_1_log.html#ad57f9410a40ded1858176a544ee0944d) before any other intraction with Z3).

**Comment by levilucio** [comment]
I have some more information: it turns out that the error also happens under Linux. I tried installing the whole project under Ubuntu and, although it did not crash with the same code as running under Mac, the moment I added another verification task using Z3 (launched from different thread), it threw the same error. So it seems that this is indeed a problem with threads and not OS dependent.

I'll send you the data you asked for tomorrow.

**Comment by wintersteiger** [comment]
Great, that's a good bit more information! If it's really a threading/concurrency problem it will definitely break at many different points in the code if you try it under slightly different conditions, e.g., when other CPU intense processes are running in the background, etc.

**Comment by levilucio** [comment]
So here is some more information:

>Does it always crash in exactly this same spot?

No, here's a few places where it has crashed while I was launching the application:

`# C  [libz3.dylib+0xb9b5c8]  mpz_manager<true>::big_set(mpz&, mpz const&)+0x48`
`# C  [libc++.1.dylib+0xbf62]  _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE5flushEv+0x4c`
`# C  [libsystem_malloc.dylib+0x3813]  tiny_malloc_from_free_list+0x147`
`# C  [libc++.1.dylib+0x1097e]  _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE6sentryC2ERS3_+0x10`

I send attached the logs you have asked. A bit of information on how to parse the files:

* I have logged errors with two setups of the system: 
  *  *allchecks* meaning multiple z3 checks are ran.
  *  *onecheck* meaning only one z3 check is ran. This is a more minimal run, in the sense that less verification tasks are ran through z3. I'm not sure how useful this will be for you because the number of threads seems to be the same for both, but is maybe useful in some manner.
* For each setup I ran the application several times. Sometimes the application actually starts, so in that case I called the dir with the logs *run_ok*.
* The names of the log files mean the following: they start with the "z3" prefix, then after the first underscore comes the thread number, and after the second underscore comes the time of the system when the log was created.
* Since z3 is called from the kernel of our framework via several threads, I have only logged each particular call to z3 which creates a new context, fills it with assertions and checks for satisfaction. This is always the same chunk of code in one single class (runs across 2 methods of the class).

Finally, I still tried something else as I thought the problem might come from my code: the class and the method where the z3 context was created and used were static. I thought this might have something to do with what you said about threads sharing the same z3 context. I turned everything non-static but it still did not work.
[z3logs.zip](https://github.com/Z3Prover/z3/files/99133/z3logs.zip)

**Comment by levilucio** [comment]
I forgot to mention, the OS also generates sometimes a report of the crash. It is attached here, maybe is useful.

[os_report.txt](https://github.com/Z3Prover/z3/files/99135/os_report.txt)

**Comment by wintersteiger** [comment]
Before we get lost in the concurrency jungle, could you try to make absolutely sure that there is only 1 thread running (also use the sequently garbage collector), so we can see whether it crashes single-threaded as well?

Also, I understand that there is some piece of code/library/someone else's program between your code and Z3. Can you please make absolutely sure that these pieces of the code are also using only a single thread during that time? 

As long as we can't exclude the possibility that this is a concurrency issue there is no point in chasing up those points at which it crashes, because it will always be very likely that a crash happens in places were memory is being managed. 

Perhaps you could also load it up in the debugger and set breakpoints on various Z3 functions to see whether that is hit multiple times with different thread IDs.

**Comment by NikolajBjorner** [comment]
This thread has gone nowhere. The calls to Z3 seems to happen just in the same thread.
Then I noticed that you use context.mkOptimize() but the query is a standard SAT query, you don't pass any objectives to maximize/minimize. So maybe it is more reasonable to use:

        solver = context.mkSolver();

It is OK to use context.mkOptimize without objectives, but not really how it was intended.

**Comment by levilucio** [comment]
For internal reasons we have reverted to our previous API code (with no changes, still using mkOptimize), and with the most recent version of the Z3 libraries the error does not appear anymore.
