### ISSUE TITLE
Invalid model for QF_LRA formula (unsat_core)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3979]
Hi, for the following formula,
~~~~
(set-logic QF_LRA)
(declare-fun _substvar_38_ () Real)
(set-option :model_validate true)
(set-option :unsat_core true)
(declare-const r4 Real)
(declare-const v4 Bool)
(declare-const v44 Bool)
(assert (! (< (* (/ 0.0 0.0) _substvar_38_) (/ r4 0.0)) :named IP_67))
(check-sat-assuming ((! (or v4 v44 v44) :named IP_1) (! (or v4 v44) :named IP_2)))
~~~~
z3 (commit dde0c514fa) gives an invalid model

**Comment by zhendongsu** [comment]
See Nikolaj's comment for https://github.com/Z3Prover/z3/issues/3902

**Comment by rainoftime** [comment]
@zhendongsu  :lblpos and :named are different. The former one Is introduced by Boogie,
but :name is general in smt-lib2 (also supported by CVC4, OpenSMT, etc)

**Comment by rainoftime** [comment]
There is a document http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.0-r12.09.09.pdf 
(Page 25)

**Comment by zhendongsu** [comment]
Okay, I see; thanks.  Let's see what Nikolaj says about Z3's support regarding this.

**Comment by NikolajBjorner** [comment]
the bug was not directly tied to named assumptions, but perhaps not too easy to trigger because it required that the variable used in division wasn't used elsewhere in arithmetical context.

**Comment by NikolajBjorner** [comment]
The construct :named is supported for the standard.

The constructs :lblpos :lblneg is a "Rustan" feature. It was added in 2007 and never really touched. They may have sound denotational meanings, but the implementation is very narrowly tuned to Boogie use case. I am not willing to risk breaking Boogie uses because the z3 implementation of lblpos/lblneg is highly operational.
