### ISSUE TITLE
Invalid model for String formula (unsat_core, rewriter.elim_and, rewriter.local_ctx, smt.phase_selection)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3980]
Hi, for the following formula,
~~~~
(set-option :model_validate true)
(set-option :unsat_core true)
(set-option :rewriter.elim_and true)
(set-option :rewriter.local_ctx true)
(set-option :smt.phase_selection 0)
(declare-const Str9 String)
(declare-const Str19 String)
(declare-const i7 Int)
(assert (>= (str.len Str9) i7))
(assert (>= (str.len (str.++ "" "fnmahu" Str19 (int.to.str (+ 884 518 796 0 i7)))) 38))
(assert (! true :named IP_2))
(check-sat)
~~~~
z3 (commit dde0c51) gives an invalid model

**Comment by zhendongsu** [comment]
I guess the same here -- see Nikolaj's comment for https://github.com/Z3Prover/z3/issues/3902

**Comment by rainoftime** [comment]
lblpos and :named are different. The former one is introduced by Boogie,
but :name is general in smt-lib2 (also supported by CVC4, OpenSMT, etc)

**Comment by rainoftime** [comment]
Fixed

**Comment by levnach** [comment]
Reopening for awareness. The snapshot-regression suite in [Z3Prover/bench](https://github.com/Z3Prover/bench) detected that the benchmark(s) derived from this issue regressed to a **timeout** (per-file 20s budget) with the latest Nightly `z3-4.17.0-x64-glibc-2.39`, where a definite result was recorded before:

- `inputs/issues/iss-3980/bug-1.smt2`: `sat` -> **timeout**

Run: https://github.com/Z3Prover/bench/actions/runs/27527718378

This looks like a possible performance regression rather than a different-but-valid answer, so the snapshot oracle was left unchanged.

**Comment by levnach** [comment]
The divergence in tests was benign.
