### ISSUE TITLE
Using quantifier body

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#402]
Hi,

After I have obtained a quantifier body using `get_quantifier_body`, can I do anything with it?
E.g. replacing "exists" by "forall" or vice versa?

I've tried giving the obtained body to `mk_forall` (while supplying no patterns or bound variables),
and that dies with a segfault.
What would be the proper way to do this?

**Comment by wintersteiger** [comment]
Segfaults are of course not expected. Do you have a small test case that triggers this?

Normally the body of a quantifier is an expression just like any other expressions, except that it may contain indexed variables for the bound variables. If there are no bound variables in your call to `mk_forall`, but there are such variables in the body, then I can imagine that there could somewhere be something that doesn't expect such a mismatch, but I wouldn't have expected it.

**Comment by cheshire** [comment]
Yes:

In `blah.py`:

```
from z3 import *

s = Solver()
b = Bool('b')
constr = ForAll([b], b)
body = constr.body()

constr2 = ForAll([], body)
s.add(constr2)
s.check()
```

Then:

```
python -O blah.py
```

The `-O` flag is important, as otherwise `__debug__` is set to `True` and `ForAll` with no constants or bound variables explicitly passed is not allowed.

**Comment by wintersteiger** [comment]
Thanks for the quick test case, that helps a lot!

The actual problem here is not the creation of the quantifier, but the addition of formula to the solver while it still contains unbound variables. That can't be checked during construction, but should probably be checked somewhere within `s.add(constr2)` or `s.check()`.

**Comment by cheshire** [comment]
Right. Funny enough, I can't print `constr2` without an error, even though I can add it to the solver.

How can I use the obtained formula `body` though? Can I re-create the original for-all node without having the reference to `constr` or `b`? Can I change for-all to exists?

**Comment by wintersteiger** [comment]
Confirmed, it crashes during conversion to strings when it tries to look up the name of variable #0 (which isn't there). 

Yes you can re-use the bodies, but you need to be careful about the variables and their indexes. If they don't match up (by your construction) then any result obtained later won't be right; either unexpected or even a segfault like in this case. But, for instance, traversing the body to find the largest index shouldn't be a problem.

Assuming that you see at some point in time the original, correct quantified expression, you can extract names/sorts/etc by using the functions called `Z3_get_quantifier_*`, e.g., `Z3_get_quantifier_num_bound`, which will tell you how many bound variables there are. Depending on your setting, you may have to save that information somewhere so that it can be access later even if you don't have the original quantified expression anymore

**Comment by NikolajBjorner** [comment]
The example suggests to update the python API to handle empty lists of bound variables as no-op, and furthermore have the underlying API reject empty lists of bound variables.

**Comment by wintersteiger** [comment]
The general problem of having partially quantified constraints would still remain. I think it would be nice if all add/assert functions would check for closedness, but that might be a bit more expensive in terms of runtime and implementation effort.

**Comment by cheshire** [comment]
Hi @wintersteiger @NikolajBjorner 

Thank you for replies!
I'm still quite confused: if I want to take the body out of the quantifier, and, say, replace EXISTS by FORALL, how should I do that? I can get the list of bound variables, but if I want to call `mk_bound` I need to know the de-Bruijn index which I don't (well, unless I print the value and parse string representation, but I don't want to do that).

**Comment by NikolajBjorner** [comment]
You can use "substitute_vars" to convert the free variables back to constants.

     from z3 import *

     s = Solver()
     a, b = Bools('a b')
     constr = ForAll([a, b], And(a, b)) 
     body = constr.body()
     body = substitute_vars(body, b, a)
     constr2 = Exists([a,b], body)
     s.add(constr2)
     print s.check()
     print s

**Comment by cheshire** [comment]
@NikolajBjorner Thanks a lot for a very fast reply!

How do I know indexes of `a` and `b` though? E.g. whether I should call `substitute_vars(body, b, a)` or `substitute_vars(body, a, b)`?

You have used the former, but e.g. I would mistakenly use the latter first.

**Comment by NikolajBjorner** [comment]
Variables are always bound in the same order, so just use the same order as the example.

**Comment by taegyunkim** [comment]
> You can use "substitute_vars" to convert the free variables back to constants.
> 
> ```
>  from z3 import *
> 
>  s = Solver()
>  a, b = Bools('a b')
>  constr = ForAll([a, b], And(a, b)) 
>  body = constr.body()
>  body = substitute_vars(body, b, a)
>  constr2 = Exists([a,b], body)
>  s.add(constr2)
>  print s.check()
>  print s
> ```

Are you saying that I need to simply use the reversed list of variables?
