### ISSUE TITLE
Incomplete theory arithmetic as soon as mod gets introduced

### ISSUE THREAD

**Issue by zvonimir** [Z3Prover/z3#4172]
This is a long story, but Boogie/Corral went through some major updates in the past couple of months, which somewhat changed how VCs get generated. A weird and unexpected side-effect of these changes is that Z3 4.8.7 now reports:
```
unknown
(:reason-unknown "smt tactic failed to show goal to be sat/unsat (incomplete (theory arithmetic))")
```
for it seems any query that Corral makes that involves `mod` operation, even for what I would think are very simple ones such as this one: [mod-test.txt](https://github.com/Z3Prover/z3/files/4561801/mod-test.txt)

This is the Boogie program from which the query got generated:
```
function {:builtin "mod"} smod(i1: int, i2: int) returns (int);

procedure {:entrypoint} main()
{
  var i1: int;
  var i2: int;
  var i3: int;

  i3 := smod(i1, i2);
  assert (i3 > 0);
}
```

What are we missing here?
I find it hard to believe that Z3 cannot handle `mod` even in such simple queries, and in fact before we made the Boogie updates it used to work much better. So I think we are missing something obvious here. Thanks for your help!

**Comment by NikolajBjorner** [comment]
it is sat on the current head. I presume you are using a stable release. Could be that variants remain unknown and then it will be good to know even as generally mod with a non-constant second argument is outside the scope of linear integer arithmetic. The current head is fairly unstable as several fuzz bugs have been filed and fixes are attempted (sometimes causing more bugs and/or heavy revisions). It also sets the default arithmetic solver to a new core so that we can make sure it gets tested. It there are some known regressions in this arithmetic solver that we try to address. For your query, both the old and new arithmetic solver produce sat.

**Comment by zvonimir** [comment]
Got it. We'll just wait for the next release then since this is not super urgent. Thanks!
