### ISSUE TITLE
Performance regression from smt.arith.solver=2 to smt.arith.solver=6 on NIRA formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4211]
Hi,
For this case,  smt.arith.solver=6 hangs on it while smt.arith.solver=2 solves it quickly:
```
[566] % time cvc4 -q small.smt2
unsat
real	0m0.028s
user	0m0.020s
sys	0m0.008s
[567] % time z3release smt.arith.solver=2 small.smt2
unsat
real	0m0.022s
user	0m0.009s
sys	0m0.009s
[568] % timeout -s 9 60 z3release smt.arith.solver=6 small.smt2
Killed
[569] % 
[569] % cat small.smt2
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(assert (forall ((e Real)) (distinct (<= e 0) (= 0 (- d)))))
(assert
 (forall ((f Real))
 (distinct (and (<= 0 (div 3 (to_int a) (to_int b))) (<= 0.0 c 0.0 (- a b)))
  (<= 0.0 (mod 0 0)))))
(check-sat)
[570] %
```

OS: Ubuntu 18.04
Commit: a34c5a9

**Comment by NikolajBjorner** [comment]
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun f () Real)
(declare-fun g () Real)
(declare-fun h () Real)
(declare-fun i () Real)
(declare-fun j () Real)
(declare-fun k () Real)
(assert
 (not
 (exists ((e Real))
  (=> (xor (and (=> (<= e d) (> (/ e g) i)) (= a j) (> a (/ j (/ b k)))) (= f 2))
  (> h i)
  (>= b 0 c 2)))))
(check-sat)

**Comment by NikolajBjorner** [comment]
Hi,
For this case, smt.arith.solver=6 reports unknown after a long time while smt.arith.solver=2 solves it quickly:
```
[733] % time z3release smt.arith.solver=2 small.smt2
sat
real  0m0.331s
user  0m0.317s
sys   0m0.004s
[734] % time z3release smt.arith.solver=6 small.smt2
unknown
real  0m45.052s
user  0m44.577s
sys   0m0.119s
[735] % 
[735] % cat small.smt2
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(assert (forall ((d Real)) (and (< a 0) (> b 0) (=> (> d 0) (>= d b) (= (div d 0) a)) (= c 0))))
(check-sat)
[736] %
```

OS: Ubuntu 18.04
Commit: a34c5a9

**Comment by levnach** [comment]
I am not sure what happens here.
 In the legacy solver, when tracing with -tr:arith, the last lines of trace are 
-------- [arith] mk_clause ../../src/smt/theory_arith_core.h:966 ---------
(>= (if (= #1346 -3) 0 (if #1344 -4 -3)) -3)
(<= (if (= #1346 -3) 0 (if #1344 -4 -3)) -3)
------------------------------------------------
-------- [arith] assert_upper ../../src/smt/theory_arith_core.h:2461 ---------
(<= (if (= #1346 -3) 0 (if #1344 -4 -3)) -3)
v9 <= -3
------------------------------------------------
After that m_to_patch is empty and the problem is solved.

I noticed that theory_lra creates constraints like that
j4 > 7/2 , with the ratio on the right. No such constraints were created in the legacy solver.

**Comment by NikolajBjorner** [comment]
for the last one, MBQI isn't connected with the partial interpretation for (div d 0). 
It is maybe fixable, but connections to a use case is at best non-obvious, so therefore wont-fix.
