### ISSUE TITLE
How to define a datatype like this in OCaml?

### ISSUE THREAD

**Issue by zhaoyonghe** [Z3Prover/z3#4264]
Hi, 
I am confused about how to define a Tree datatype like this in z3 OCaml bindings?
```
Tree = Datatype('Tree')
Tree.declare('Empty')
Tree.declare('Node', ('left', Tree), ('data', Z), ('right', Tree))
Tree = Tree.create()
t = Const('t', Tree)
```
The above code is written by Python, which is clear. But in OCaml bindings, there is a contradiction: if I want to define a datatype, I need to have its constructors list; but to build the constructor 'Node', I need a 'Tree' datatype. I also cannot find a way to first define a "placeholder" Tree datatype and then build its constructors on top of that, just like what it did using Python.
Any hints on that? Thanks! /cc @c-cube

**Comment by NikolajBjorner** [comment]
The python and ml APIs call the same low level C API.
The python wrapper is a bit more user-friendly.
The ml wrapper is closer to the metal: you use a "sort_ref" to refer to the recursive datatype that is being declared. 

The function that creates the constructor is:

    let create (ctx:context) (name:Symbol.symbol) (recognizer:Symbol.symbol) (field_names:Symbol.symbol list) (sorts:Sort.sort option list) (sort_refs:int list) =

For example, you would call:

   let empty = DT.create ctx "empty" "is-empty" [] [] []

and 

   let node = DT.create ctx "node" "is-node" [None; Z; None] [0; 0]

The references 0 is to the 0'th recursive datatype being built.

**Comment by zhaoyonghe** [comment]
Thank you very much! That is very helpful!

**Comment by arbipher** [comment]
> let node = DT.create ctx "node" "is-node" [None; Z; None] [0; 0]

The length of the sort ref list isn't the same as the field list and it will raise an error. maybe it could be `[0; 1; 0]`

I search this issue since I don't figure out how the sort ref list works in the [API document](https://z3prover.github.io/api/html/ml/Z3.Datatype.html) isn't so clear.

`0` is for the recursive sort but what does the non-zero integer mean in the sort ref list?
My test code can always compile and give the solution.
