### ISSUE TITLE
(z3str3) Segmentation fault on QF_S formula with regex

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4344]
Hi,
For this case, Z3  throws out a segmentation fault:
```
[556] % z3release smt.string_solver=z3str3 small.smt2
Segmentation fault
[557] % 
[557] % cat small.smt2
(declare-fun a () String)
(assert (str.in.re a (re.inter (str.to.re a) re.allchar)))
(check-sat)
[558] %
```

OS: Ubuntu 18.04
Commit: b2bfb1f

**Comment by mtrberzi** [comment]
@NikolajBjorner unhandled regex terms in re2automaton with this issue:

```
-------- [seq] re2automaton::re2aut ..\..\..\src\ast\rewriter\seq_rewriter.cpp:367 ---------
not handled (re.inter (str.to_re a) re.allchar)
```

**Comment by NikolajBjorner** [comment]
That is because 'a' is not a string constant. The expression does not correspond to a regular language so we can't create an automaton from the regex. 
Your code should handle this case: that the conversion into a symbolic automaton fails.
It should then produce "unknown", an exception, or maybe gracefully return unknown unless it can establish unsat from other constraints.

**Comment by mtrberzi** [comment]
Good catch. I'm so used to `a` being a constant I did not notice here it was being used as a variable.

We may support this at a later date, however for now I will check for and handle this case.

**Comment by mtrberzi** [comment]
Opened #4384
