### ISSUE TITLE
Z3 returns 'unknown'

### ISSUE THREAD

**Issue by kgoyal40** [Z3Prover/z3#4467]
Hi,

I am working on a problem where I have a non-linear quantifier based constraint. The solver takes a really long time and eventually returns 'unknown'. Following is the quantified constraint that I use. There are a few small non-quantified constraints as well (I am not adding them here).

X1 = RealVector('x1', 10)
W = [[Real('w_{}_{}'.format(i, j)) for i in range((11))] for j in range(3)]
ForAll(X1, Implies(And([And(X1[i] <= 100, X1[i] >= -100) for i in range(10)]),
                                                            Or([And([Sumproduct(X1, W[k]) > 0 if k == i else
                                                                     Sumproduct(X1, W[k]) < 0 for k in range(3)]) for i in
                                                                range(3)])))

My question is, Are there any parameters settings I can change which can help the solver find a solution (sat or unsat)?

**Comment by mschwerhoff** [comment]
I'm not a Z3 dev, but here are some comments:
* Might help to post a minimal but complete SMT file
* Where are the non-linear constraints?
* I always get nervous seeing quantifiers without patterns/triggers 
* What did you try so far? Some experimenting with parameters? See `z3 -pd`.

**Comment by kgoyal40** [comment]
Hi,

The quantified formula is itself non-linear as it consists a multiplication of two variables (X1, W). I have tried some parameters from the parameter list you get from help_simplify() but none worked. The problem is that I am not sure how to even approach these parameters as there is no documentation anywhere. So anything would help.

Thanks
Kshitij

**Comment by NikolajBjorner** [comment]
I don't know of options that would deal with non-linear + uninterpreted functions + quantifiers.
It is logically intractable (not as well known as non-linear integers + uninterpreted functions + quantifiers, but non-linear reals + uninterpreted functions + quantifiers is not really easier because you can define integers using 

    forall x . 0 < x < 1 => not is-int(x) and 
    is-int(0) and 
    forall x . is-int(x) <= > is-int(x+1).
 
so there isn't going to be a singular algorithm that can handle these.
For non-linear (reals) + quantifiers z3 can try the nlqsat tactic. It tries it automatically if the problem is pure non-linear reals + quantifiers (no uninterpreted functions, such as SumProduct.
Thus, z3 is best effort, and for your formula it isn't enough. 
There is of course always something to learn from when best effort isn't enough, 
we try based on user scenarios and benchmark sets.
Generally, though it is useful to temper expectations and seek a reformulation where you
instantiate your universal quantifier on a sufficient set of instances that you compute from your problem domain.
