### ISSUE TITLE
Any way to get incremental solving + soft constraints?

### ISSUE THREAD

**Issue by HalleyYoung** [Z3Prover/z3#4503]
I am working on a SMT satisfiability problem where, using a different SMT solver, I have found that it finds the solutions most quickly if I both solve incrementally and, after solving a portion of the problem, push the model's values as soft constraints.  I am now looking to transition to z3py, but it seems that in z3 there's no way to get incrementality and soft constraints at the same time.

Is this true?  If not, are there tactics I could use to simulate the effect of adding a soft constraint that a partial model captured before additional constraints were added should be kept as much as possible?  

I am only interested in satisfying the entire problem as quickly as possible - right now it seems that the way to do this is via incrementality and soft constraints, but if there are other methods which could have the same effect I'd love to hear about them!

Thanks!

**Comment by NikolajBjorner** [comment]
The max-sat solver isn't incremental because it bakes in preprocessing that uses a global analysis on constraints. Another aspect is that the optimization solver itself ends up adding constraints that would not be valid in an incremental setting (they would have to be retracted). A method that works reasonably well for really hard problems is to perform neighborhood optimization: fix a subset of variables through _hard_ constraints, then solve the simpler optimization problems.

**Comment by HalleyYoung** [comment]
Thank you!
