### ISSUE TITLE
Z3 gets stuck 

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#4513]
Hi, when I run z3 **without** the tr definition everything goes well.
When I add the definition with `forall(sigma,tr(sigma) == ...`
z3 gets stuck even though `tr` is actually never used.
```
void oren_example()
{
	int i;

	// context + solver
        context ctx;
	solver solver(ctx);
	
	// sorts
	sort int_sort     = ctx.int_sort();
	sort seq_int_sort = ctx.seq_sort(int_sort);
	sort bool_sort    = ctx.bool_sort();

	// constants
	expr two   = ctx.int_val(2);
	expr five  = ctx.int_val(5);
	expr four  = ctx.int_val(4);
	expr three = ctx.int_val(3);

	// define State sort
	const char *names[4]={"x","A","b","n"};
	sort sorts[4]={int_sort,seq_int_sort,bool_sort,int_sort};
        func_decl_vector projs(ctx);
	func_decl State = ctx.tuple_sort("State",4,names,sorts,projs);
        sort state_sort = ctx.tuple_sort("State",4,names,sorts,projs).range();

	// define an arbitrary state sigma
	expr sigma = ctx.constant("sigma",state_sort);

	// define some predicate on the state
	func_decl init = function("init",state_sort,bool_sort);
	solver.add(forall(sigma,
		init(sigma) == ctx.bool_val(true)));

	// define transition
	func_decl tr = function("tr",state_sort,state_sort);

	expr_vector values(ctx);
	values.push_back(projs[0](sigma)-five);
	values.push_back(projs[1](sigma));
	values.push_back(!projs[2](sigma));
	values.push_back(projs[3](sigma)+three);

	#ifdef PROBLEMS
	solver.add(forall(sigma, tr(sigma) ==
		ite(
			projs[0](sigma) > projs[3](sigma),
			State(values),
			sigma)));
	#endif
	
	// find an initial state
	solver.add(init(sigma));

	std::cout << solver;

	// check sat + get model
	if (solver.check() == sat)
	{
		assert(0);
        }
}
```

**Comment by NikolajBjorner** [comment]
Instead of adding a predicate tr and then an axiom with a definition for the predicate, you could define tr as a (local) function that returns the body of the definition. In this way, your application controls macro unfolding of tr and does not rely on configuring pre-processing to find the macro.
Without pre-processing, z3's model-based quantifier instantiation (MBQI) approach will not realize that tr is a macro. It will attempt to build a model for tr with a finite range, but the range is really infinite (tr is the identity on most values). This is in a nutshell where the finite model building approach of MBQI alone does not work.

**Comment by OrenGitHub** [comment]
@NikolajBjorner thanks, though I'm not too sure what exactly should I do.
I found [this SO question](https://stackoverflow.com/questions/7740556/equivalent-of-define-fun-in-z3-api) which seems exact, and the first suggestion there is actually what I did.
I didn't understand what the alternatives do.

**Comment by NikolajBjorner** [comment]
You can

```
auto tr = [&](sigma) {
	return
		ite(
			projs[0](sigma) > projs[3](sigma),
			State(values),
			sigma));
};

then wherever you use 'tr' in your formula it is expanded into the ite.

**Comment by OrenGitHub** [comment]
Thanks that works great!
