### ISSUE TITLE
Interpreting spacer sat answer

### ISSUE THREAD

**Issue by OrenGitHub** [Z3Prover/z3#4547]
Hi, I'm trying to figure out how to interpret the results
of a **sat response from spacer**. Here is the example I'm using:
```
(declare-rel Error ())

;;;;;;;;;;;;;;;;;;;;;;;
;                     ;
; [1] state variabels ;
;                     ;
;;;;;;;;;;;;;;;;;;;;;;;
(declare-var i Int)
(declare-var n Int)

;;;;;;;;;;;;
;          ;
; [2] init ;
;          ;
;;;;;;;;;;;;
(rule (Loop 0 n))

;;;;;;;;;;;;;;;;;
;               ;
; [3] iteration ;
;               ;
;;;;;;;;;;;;;;;;;
(rule (=> (and (< i n) (Loop i n)) (Loop (+ i 1) n)))

;;;;;;;;;;;;
;          ;
; [4] spec ;
;          ;
;;;;;;;;;;;;
(rule (=> (and (Loop i n) (> i 7)) Error))

;;;;;;;;;;;;;;;;;;;;;;;;;;
;                        ;
; [5] is Error possible? ;
;                        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;
(query Error)
```
And here is how I invoke spacer:
```
$ z3 -v:1 fp.spacer.ground_pobs=false fp.spacer.q3.use_qgen=true spacer_example.smt
```
When I look at the lines just before the `sat` response this is what I see:
```
...
is-reachable: Loop (2, 0) FAR 2737 T 0.00
is-reachable: Loop (3, 0) FAR 2752 T 0.00
is-reachable: Loop (4, 0) FAR 2682 T 0.00
is-reachable: Loop (5, 0) FAR 2603 T 0.00
is-reachable: Loop (6, 0) FAR 2515 T 0.00
is-reachable: Loop (7, 0) FAR 2408 T 0.00
is-reachable: Loop (8, 0) FAR 210 T 0.01
is-reachable: query!0 (9, 0) FAR 1 T 0.01
(spacer::context::check_reachability :time 0.07 :before-memory 4.99 :after-memory 5.58)
sat
```
I'm a little confused because I was hoping for something like:
```
is-reachable: Loop (0, 9) FAR 2737 T 0.00
is-reachable: Loop (1, 9) FAR 2752 T 0.00
is-reachable: Loop (2, 9) FAR 2682 T 0.00
is-reachable: Loop (3, 9) FAR 2603 T 0.00
is-reachable: Loop (4, 9) FAR 2515 T 0.00
is-reachable: Loop (5, 9) FAR 2408 T 0.00
is-reachable: Loop (6, 9) FAR 210 T 0.01
is-reachable: Loop (7, 9) FAR 210 T 0.01
is-reachable: Loop (8, 9) FAR 210 T 0.01
```
Can you help me understand the sat response?
Thanks!

**Comment by agurfinkel** [comment]
You are looking at debug output. It is not intended to be consumed by the users. If you are interested in getting a proper answer for SAT, there are two interfaces available. The most convenient is `get-proof`. There is an example of how to get it and how to interpret it as a graph (or trace) in here: https://spacerexamples-ariegurfinkel.notebooks.azure.com/j/notebooks/Dagstuhl2019.ipynb . To run the notebook, either clone the space and run on Azure, or install locally. Note that it takes a while for notebook to run on Azure since the first step is installing z3 and the feedback from Azure is a bit delayed. 

Second method is to use `get_ground_sat_answer` from the API. This is what SeaHorn still uses to get traces for linear counter-examples. 

The proof interface is preferred since it provides both the counterexample and the reasoning (i.e., the resolution proof) on how it was constructed.

**Comment by KihongHeo** [comment]
Hi @agurfinkel. I am also trying to use the methods you suggest. But I am wondering how I can use the APIs from the Fixedpoint module (I am using OCaml) since they are in Solver.

I am using Spacer as follows:
```ocaml
  let mk_string_symbol s = Z3.Symbol.mk_string z3ctx s in
  let s = Z3.Fixedpoint.mk_fixedpoint z3ctx in
  let param = Z3.Params.mk_params z3ctx in
  Z3.Params.add_symbol param
     (mk_string_symbol "engine")
     (mk_string_symbol "spacer");
  ...
```
