### ISSUE TITLE
Get bitvector model as a vector of bool

### ISSUE THREAD

**Issue by mikhailramalho** [Z3Prover/z3#4568]
Related to issue #1443.

I'm using `Z3_mk_bv_numeral` to create a bitvector using an array of bools, but is there a way to get its value from the model also as an array of bools? 

Maybe there's an option to return the string returned by `Z3_get_numeral_string` in binary?

**Comment by NikolajBjorner** [comment]
I think this takes care of the issue. The decimal output would require the caller to implement their own bit-vector adder and multiplier by 10. It isn't rocket science, but does add some barrier of entry. The API therefore now exposes a method to display non-negative integer numerals, in particular bit-vectors, as bit sequences.
It uses a string for the sequence because the API already has a way to return strings and it is super simple to walk a string for '0' and '1' characters.
