### ISSUE TITLE
Explanation of comment about used_enodes

### ISSUE THREAD

**Issue by murali24adithya** [Z3Prover/z3#4579]
@NikolajBjorner I am trying to extract causality information between quantifier instantiations (i.e., what term(s) triggered a particular instantiation). It seems to me that the variable used_enodes declared in the interpreter class (mam.cpp) is relevant, but I'm not able to understand the comment explaining what it is on line 1874 in mam.cpp:

>// equalities used for pattern match. The first element of the tuple gives the argument (or null) of some term that was matched against some higher level
>  // structure of the trigger, the second element gives the term that argument is replaced with in order to match the trigger. Used for logging purposes only.

Could you please provide a small example illustrating the comment?

**Comment by NikolajBjorner** [comment]
@Nils-Becker - this field is introduced for tracing by Nils.

**Comment by Nils-Becker** [comment]
Say you have a trigger ``f(g(x))`` (where ``x`` is a quantified variable of the quantifier you are trying to instantiate) and you match it against ``f(h(0))`` using the equality ``h(0) = g(5)``. In that case used_enodes would contain 2 elements: ``(null, f(h(0)))`` and ``(h(0), g(5))``. Because the first element of the first tuple is null that entry indicates that the whole trigger (or one of the triggers in a muli-pattern) was matched against ``f(h(0))``. The second tuple indicates that we have to substitute ``g(5)`` for ``h(0)`` to get a term that structurally matches the trigger.

You may also want to have a look at ``log_add_instantiation`` in smt_quantifier.cpp:202. The part on ll. 216-233 ensures that the information on relevant equalities is up-to-date in the log and the part after that basically just logs the elements of used_enodes. Besides that there is also some information on this in the section on the ``[new-match]`` line in the [LogDocumentation](https://github.com/viperproject/axiom-profiler/tree/master/LogDocumentation) which I have also attached.

[LogDocumentation.pdf](https://github.com/Z3Prover/z3/files/4957828/LogDocumentation.pdf)

**Comment by murali24adithya** [comment]
Thanks, @Nils-Becker I think that pretty much clarifies things. The log documentation also makes a lot of sense in the context of your explanation. If my understanding is correct, then there will always be a pair with null in the first component in used_enodes which corresponds to the actual term that triggered the match (modulo equalities), and everything else (without null in the first component) only serves to instruct the substitution that will result in a structural match.

Am I also correct in assuming that the intention in general behind used_enodes simply tracks the term(s) that triggered the instantiation in question?

**Comment by Nils-Becker** [comment]
Yes, you are correct.
