### ISSUE TITLE
Model returning unknown when solutions exists and should be "easy" to find

### ISSUE THREAD

**Issue by joxeankoret** [Z3Prover/z3#4616]
Hi!

I'm working on pushing a Diophantine equation onto Z3. The equation is the following: a^2 + b^3 = c. The solver I wrote finds most solutions, but fails in many cases that I don't understand. For example, it can find a solution for the case C==414 with no problems:

```py
>>> from z3 import *
>>> 
>>> a, b, c = Ints('a b c')
>>> s = Solver()
>>> s.add(a**2 + b**3 == c)
>>> s.add(c == 414)
>>> s.check()
sat
>>> s.model()
[a = -21, b = -3, c = 414]
```

But fails at finding a solution when c == 1004 (for which the solution is a=2 and b=10):

```py
>>> a, b, c = Ints('a b c')
>>> s = Solver()
>>> s.add(a**2 + b**3 == c)
>>> s.add(c == 1004)
>>> s.check()
unknown
```

The problem seems not to be that C is a big integer, as it can find a solution for C==1016 quickly:

```py
>>> a, b, c = Ints('a b c')
>>> s = Solver()
>>> s.add(a**2 + b**3 == c)
>>> s.add(c==1016)
>>> s.check()
sat
>>> s.model()
[a = -32, b = -2, c = 1016]
```

So, am I doing something wrong or is it a limitation of Z3? Is there anything I can do to push this problem onto Z3?

Thanks in advance!

PS: The whole code of my program to calculate the solution for multiple values, ranges, etc... is available [here](https://pastebin.com/sNWva7E0).

**Comment by NikolajBjorner** [comment]
By default it uses the legacy arithmetic solver together with some time bounded tactic based on solving non-linear real problems.
The newer arithmetic solver is better at these problems but does not understand "powers", that is, it does not understand b**3.
I have augmented the newer solver to understand powers with small exponents. Otherwise you would have to write them as b*b*b. The changes are available in the newest nightly builds.

Then to enable it use:

```
s = SimpleSolver()
s.set("smt.arith.solver",6)
...

```

It should behave better on these kinds of puzzles.
