### ISSUE TITLE
Incorrect solving 

### ISSUE THREAD

**Issue by trsh** [Z3Prover/z3#4630]
```
from z3 import *

p = Int('p')
q = Int('q')

solve(Or(p==1,p==2,p==3), Or(q==1,q==2), Not(p==q), q==1)
```

This should return something like `[p={2,3}, q=1]`, but it just spits `[p = 2, q = 1]`.

**Comment by NikolajBjorner** [comment]
The model contains a single solution, not a representation of all solutions.
Generally, there could be an infinite number of solutions. Finding and enumerating all solutions, even if it is possible in some way (because there is a finite number of solutions or because there is a finite way to describe all solutions in an intuitive way) is beyond the basic solve functionality. "solve" implements SMT satisfiability checking and produces a certificate for satisfiability if the formula is satisfiable.

All-sat or algebraic solving features are not built into Z3.

**Comment by trsh** [comment]
@NikolajBjorner but in my case there are no infinite solutions, only 2. And even if, sympy, for example, solves this elegantly by giving back a an array of range(s) what could be as well [-infinity to +infinity] (if it's all possible numbers).

If Z3 team is not planing to add such features, can You at least provide a workaround for me? I need to know when/if there is more than 1 answer. Because 1 of x possible answers in math is mostly not accounted as an final solution and it's preventing me to build the software I intend.

**Comment by andrewvaughanj** [comment]
If all you need to know is if there is > 1 solution, then you can use what's called a "blocking clause" -- you simply assert the *negation* of the model you obtained the first time and see if Z3 gives SAT again.

If you get SAT after asserting the negated model, then that means that there is at least one other solution.

If you get UNSAT after asserting the negated model, then that means the first model you obtained is the only solution to your formula.
