### ISSUE TITLE
FloatingRoundingMode in C++ API

### ISSUE THREAD

**Issue by 3y3p4tch** [Z3Prover/z3#4678]
I am working on translation validation, and currently handling floating points. I want to simulate floating-point-arithmetic in Z3, but I don't want to specify the rounding-mode. Instead, I want to put it as a constant, and let the SMT figure out the correct rounding mode which makes the statements satisfiable.

In Z3, I can simulate the operation as follows:
```
(declare-const rm RoundingMode)
(declare-fun a () (_ FloatingPoint 8 24))
(declare-fun b () (_ FloatingPoint 8 24))
(declare-fun c () (_ FloatingPoint 8 24))
(assert (fp.eq (fp.mul rm a b) c))
```

But I am unable to simulate a similar program using the C++ API of Z3. The C++ API stores rounding_mode as an enum inside the context object and the function `set_rounding_mode` also takes the enum as argument.

Please suggest how to accomplish the above in C++

**Comment by wintersteiger** [comment]
All of the C API is available in C++ too. You can use the C functions directly, e.g. `Z3_mk_fpa_mul` for multiplication. As long as you remember to put the resulting expressions into `expr` objects immediately, the C++ API will continue to take care of the reference counting for your expressions.

**Comment by 3y3p4tch** [comment]
@wintersteiger Yes, I thought about implementing it that way, but my program does a whole lot of arithmetic at different places which is not limited to floats. Mixing C and C++ APIs for arithmetic would be a maintenance issue as the C++ API also provides `+`, `*`, `-`, `/` operators among other things. I use those operators directly for bit-vector and other arithmetic without checking sorts as the operators provide a great abstraction. If I (or some maintainer after me) accidentally use those operators for float somewhere, the code will silently break without any warnings (as Z3 context also stores a `rounding_mode`).

I was looking for a more cleaner solution, along with the reasoning of developers for using an `enum` in the C++ API instead of SMT constants and constraints for `rounding_mode`

If there's no particular reason for implementing it as an enum, maybe we can make the C++ API more consistent with the C API by changing the implementation of `rounding_mode` from enum to a SMT constant using `Z3_mk_fpa_rounding_mode_sort`?

Thanks

**Comment by wintersteiger** [comment]
If we were to do that, your code would become very complicated very quickly. For instance, it would be hard to see whether two expressions use the same rounding mode constant/expr; even worse if those expressions appear on the same line of code. I really recommend using the C functions, because they give you full control and it's always clear what operation is being performed. If you want, you can add your own abstraction in your own C++ class, but I'm not keen on merging something like that into the public API. We could think about it if you need exactly one rounding mode for the entire problem, but otherwise I think it's better to stick to the C functions.

Also be aware that mixing floats with other kinds of arithmetic will get very complicated very quickly, i.e. expect lots of timeouts and unknowns!

I don't understand your comments about enums. The rounding mode is already an enum, both in C and in C++. Are you saying you want `expr m_rounding_mode;` instead of `rounding_mode m_rounding_mode;`?

**Comment by 3y3p4tch** [comment]
I see. Thanks for your precious time and input @wintersteiger .

Yes, I was exactly talking about having `expr m_rounding_mode;` instead of `rounding_mode m_rounding_mode;`. The main concerns are these three functions below:
```c
inline sort context::fpa_rounding_mode() {
    switch (m_rounding_mode) {
    case RNA: return sort(*this, Z3_mk_fpa_rna(m_ctx));
    case RNE: return sort(*this, Z3_mk_fpa_rne(m_ctx));
    case RTP: return sort(*this, Z3_mk_fpa_rtp(m_ctx));
    case RTN: return sort(*this, Z3_mk_fpa_rtn(m_ctx));
    case RTZ: return sort(*this, Z3_mk_fpa_rtz(m_ctx));
    default: return sort(*this); 
    }
}
```
```c
inline void context::set_rounding_mode(rounding_mode rm) { m_rounding_mode = rm; }
```
```c
inline expr operator+(expr const & a, expr const & b) {
    check_context(a, b);
    Z3_ast r = 0;
    ...
    ...
    else if (a.is_fpa() && b.is_fpa()) {
        r = Z3_mk_fpa_add(a.ctx(), a.ctx().fpa_rounding_mode(), a, b);
    }
    else {
        // operator is not supported by given arguments.
        assert(false);
    }
    a.check_error();
    return expr(a.ctx(), r);
}
```
I was curious if we could replace `rounding_mode m_rounding_mode;` with `expr m_rounding_mode;`? I am not quite familiar with how all this is implemented in the underlying C API, but such a change would allow us to play with the rounding mode more freely. What are your views on this?

**Comment by wintersteiger** [comment]
My view is that there should not be any operator overloading for floats in the first place. Floats behave very differently from other theories and they are usually used in a context where exactly this difference is the critical bit of information, so I don't believe we should make them "look" like other numbers. For instance, addition is not associative, so we really shouldn't even allow users to write "a + b + c" without parentheses. In the same example, what if the rounding modes of each `+` are different?

Also, I believe that `z3::context` should not be abused to keep application state. If we add one `expr` now, tomorrow someone else will ask for an `expr_vector`, or a set of rounding modes, ... Since the default rounding mode is also set to an unusual value, I'm thinking about removing it altogether.

If you want to submit a pull request I'm happy to review it, but I think it's the wrong strategy for the API.

**Comment by 3y3p4tch** [comment]
Oh, I understand and I agree with you. I really look forward to the removal of operator overloading for floats in Z3. I'll close this issue now.

Thanks for your precious insights, I really appreciate it.
