### ISSUE TITLE
Transitive Closure mixed with `push` yields confusing results

### ISSUE THREAD

**Issue by jpdoyle** [Z3Prover/z3#4691]
Inspired by https://stackoverflow.com/questions/56496558/transitive-closure-in-z3-z3py, I tried running:
```py
from z3 import *
print(z3.get_full_version())
B = BoolSort()
S = DeclareSort('S')
a, b, c = Consts('a b c', S)
R = Function('R', S, S, B)
TCR = TransitiveClosure(R)
for push1 in [False,True]:
    for push2 in [False,True]:
        s = Solver()

        s.add(R(a, b) == True)
        if push1:
            s.push()
        s.add(TCR(a, b) == False)
        if push2:
            s.push()

        print("==== {}Push 1, {}Push2 ====="
                .format('' if push1 else 'No ',
                        '' if push2 else 'No '))
        print(s)
        res = s.check()
        print(res)
        if res == sat:
            m = s.model()
            print(m.evaluate(R(a,b)))
            print(m.evaluate(TCR(a,b)))
```

The results I saw were:
```
Z3 4.8.7.0
==== No Push 1, No Push2 =====
[R(a, b) == True, transitive-closure(a, b) == False]
unsat
==== No Push 1, Push2 =====
[R(a, b) == True, transitive-closure(a, b) == False]
unsat
==== Push 1, No Push2 =====
[R(a, b) == True, transitive-closure(a, b) == False]
sat
True
False
==== Push 1, Push2 =====
[R(a, b) == True, transitive-closure(a, b) == False]
sat
True
False
```

The `sat` results seem like a bug, but I'm not sure why `push` would change the meaning of `TransitiveClosure`.

**Comment by NikolajBjorner** [comment]
The transitive closure solver is somewhat non-standard. It is only loaded if the original problem contains TC operators.
If it isn't loaded by the time of the first push it never will. The mainstream solvers do get loaded by default so their behavior is not as weird. Since the TC/special-relations solver is so special case I prefer not to change this behavior in the present core. 
A new core will load solvers on demand, but the architecture of the present core isn't amenable to on-demand solver loading.
