### ISSUE TITLE
Building z3 with NVIDIA's compilers

### ISSUE THREAD

**Issue by woachk** [Z3Prover/z3#4694]
Hello,

This is some notes about building z3 with NVIDIA's compiler (HPC SDK 20.7, formerly known as PGI):

- in src/muz/base/dl_rule_set.h, "void restrict(const item_set & allowed);" has restrict compiled as a keyword, with the build as such failing, renaming the name resolves the issue.

- when building src/muz/base/dl_context.cpp:
```

`Block containing LandingPadInst must be jumped to only by the unwind edge of an invoke.
  %283 = landingpad %astruct.dt64
          cleanup
LLVM ERROR: Broken module found, compilation aborted!`
```

... the compiler breaks down, as such I built just that file with g++...

... but then, when running the testsuite:
```
`****************************************************************************************************
1 3 2
*ASSERTION VIOLATION
File: ../src/test/total_order.cpp
Line: 122
Failed to verify: to.lt(v[k], v[k+1])

Z3 4.8.10.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
`
```

Those tests were done on an AArch64 machine. (NVIDIA Carmel processor)

Thank you,

**Comment by nunoplopes** [comment]
The conclusion is that the compiler you used is badly broken, there's nothing we can do about it. `restrict` is not a keyword in C++. You should report these bugs to NVIDIA instead.
The fact that the code crashes may be because you used 2 compilers and they may be ABI incompatible.

If you really care about this compiler, feel free to submit a PR if you manage to produce a small change that makes Z3 work with that compiler.
