### ISSUE TITLE
proof regressions from 4.8.8 to 4.8.9 and current master

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#4746]
[timeout.zip](https://github.com/Z3Prover/z3/files/5412714/timeout.zip)

Hello,

We have experienced quite important proof regressions after 4.8.8. I attached a zip file with ~230 VCs which were proved (most of them almost immediately) by z3 4.8.8, but are not proved by 4.8.9 nor current master (2f756da294e), with a timeout of 20 seconds. The commandline used to run the tests was just `z3 -st -T:20 <filename>`, with the corresponding z3 put in PATH.

I know it represents a lot of work to look at over 200 VCs, but I don't know what is the best way to address this so I figured I would give you a maximum of material. We can also start by looking at one VC at random in this collection (just pick one you like).

Maybe there is command line switch that would give us the previous proof behavior back? Or is there a common pattern that causes the bad performance of z3 here?

Thanks in advance for your input.

**Comment by NikolajBjorner** [comment]
LKG seems to be 71a32f5bb2db4b124dd785473d74ebd48346441c

A regression according to the first benchmark I tried 
seems to be how ite expressions get lifted or not during pre-processing.

You seem include pure Presburger quantified formulas as assumptions.
I am at a loss to understand the motivation for these formulas.

**Comment by NikolajBjorner** [comment]
You have assumptions of the form:

```
(define-fun min ((x Int) (y Int)) Int (ite (<= x y) x y))

(define-fun max ((x Int) (y Int)) Int (ite (<= x y) y x))

;; Min_r
  (assert (forall ((x Int) (y Int)) (=> (<= y x) (= (min x y) y))))

;; Max_l
  (assert (forall ((x Int) (y Int)) (=> (<= y x) (= (max x y) x))))

;; Min_comm
  (assert (forall ((x Int) (y Int)) (= (min x y) (min y x))))

;; Max_comm
  (assert (forall ((x Int) (y Int)) (= (max x y) (max y x))))

;; Min_assoc
  (assert
  (forall ((x Int) (y Int) (z Int)) (= (min (min x y) z) (min x (min y z)))))

;; Max_assoc
  (assert
  (forall ((x Int) (y Int) (z Int)) (= (max (max x y) z) (max x (max y z)))))
```

**Comment by kanigsson** [comment]
OK thanks. These seem superfluous indeed, I will attempt to remove them.

**Comment by NikolajBjorner** [comment]
You can emulate legacy using a newly exposed configuration option.
```
z3 C:\z3\build\timeout\sparkbench__aalias.adb_34_4_precondition3___00.smt2 /v:10 smt.q.lift_ite=2
```
This is a patch that would allow you to evaluate the newest version of the solver against other benchmarks than the one I tried.

**Comment by kanigsson** [comment]
It seems that most if not all VCs I submitted here are solved when removing those axioms. I will close this ticket.

**Comment by levnach** [comment]
Reopening for awareness. The snapshot-regression suite in [Z3Prover/bench](https://github.com/Z3Prover/bench) detected that the benchmark(s) derived from this issue regressed to a **timeout** (per-file 20s budget) with the latest Nightly `z3-4.17.0-x64-glibc-2.39`, where a definite result was recorded before:

- `inputs/issues/iss-4746/sparkbench__fraction_fixed.adb_66_20_overflow_check3___00.smt2`: `unsat` -> **timeout**
- `inputs/issues/iss-4746/sparkbench__students.adb_54_43_overflow_check3___00.smt2`: `unsat` -> **timeout**

Run: https://github.com/Z3Prover/bench/actions/runs/27527718378

This looks like a possible performance regression rather than a different-but-valid answer, so the snapshot oracle was left unchanged.
