### ISSUE TITLE
Z3_substitute with timer

### ISSUE THREAD

**Issue by aqjune** [Z3Prover/z3#4747]
Hello all,

Does Z3 have an API that is equivalent to `Z3_substitute` but uses a timer?

I see that `Z3_simplify` is using scoped timer to early exit if it takes a long time.
@nunoplopes

**Comment by NikolajBjorner** [comment]
substitution should be a linear operation (does a single pass over the expression DAG, except for quantifiers) and therefore isn't subject to timeout checks. The case where there are shared expressions across quantifiers is not considered worth tuning for. If for some reason you are seeing a perf overhead within substitutions, it would be worth a detailed profile analysis. 

The code used by Z3_substitute is here
https://github.com/Z3Prover/z3/blob/master/src/ast/rewriter/expr_safe_replace.cpp

It uses hash-tables. These could turn out to be an overhead for large expressions, so the alternative is to use arrays that map object identifiers to results. But this optimization should really only be useful within an inner loop. 
Suppose your code uses substitution repeatedly and can share information/allocations across calls, you will be better off with a custom implementation that takes care of the common case. For example, you can use Z3_substitute if you encounter a quantifier and otherwise use custom code.

**Comment by nunoplopes** [comment]
`Z3_substitute` is extremely slow for larger expressions (even without quantifiers). And AST traversal outside of Z3 is also slow since you incur in a lot of function calls back and forth.
It's not easy to optimize that code..

**Comment by nunoplopes** [comment]
In the past I used the trick of using De Bruijn variables for cases where I knew replacement was likely and then replacing those as `Z3_substitute` is way faster with those (as then there are no hastable lookups).

**Comment by aqjune** [comment]
After the patches as well as recent updates in Alive2, I see that Z3_substitute shows less often from the call stack trace.
I'm closing this issue.
