### ISSUE TITLE
hard timeout makes run take longer

### ISSUE THREAD

**Issue by kanigsson** [Z3Prover/z3#4763]
[repr.smt2.txt](https://github.com/Z3Prover/z3/files/5455601/repr.smt2.txt)

On the attached file, z3 answers `unsat` in a few milliseconds, but adding a hard timeout `-T:20` to the commandline makes it take the full 20 seconds. This is with the nightly version `0768040`.

FWIW, I don't think the input file is particularly relevant, but it doesn't happen on all inputs in my experience.

**Comment by nunoplopes** [comment]
This seems to be caused by a weird OS thread scheduling. 
Could you try adding `std::this_thread::yield();` right before `workers.lock();` inside the loop of the patch mentioned above? That should force the OS to cleanup the timer thread.

**Comment by NikolajBjorner** [comment]
thanks for allowing me to try this suggestion

**Comment by NikolajBjorner** [comment]
It even exposes a race condition

D:\a01\_work\2\s\src\vctools\crt\github\stl\src\mutex.cpp(64): mutex destroyed while busy

Seems also you want "work" to be declared volatile?

**Comment by NikolajBjorner** [comment]
The shutdown code is fishy: available_workers is a vector of idle workers, while num_workers counts all workers that have been allocated, both the ones in available_workers and also the active ones. The timer thread is active so it is nowhere to be found in available_workers. The shutdown loop keeps spinning until the timeout triggers.
You seem to want to also track the allocated workers so they get signaled and properly shut down. 
This leads to the next issue: the m_mutex attribute on the state is used with "s->m_mutex.try_lock_until(end)".
The shutdown logic, understandably, does not release the mutex on the active thread (because it is not in available_workers) that would otherwise allow this code to trigger. 
Finally, the state of the mutexes when they are deleted may need to be tracked.

**Comment by NikolajBjorner** [comment]
std seemingly lacks a timer-queue abstraction. The "usual way" should be to use a timer-queue and have a single thread handle dequeuing the threads (or have an OS thread do it, but this is probably not any portable). A timer queue based on a single array with event handlers and their timeouts should suffice for Z3. So something like: 

```

struct timer_queue_state {
    std::vector<std::pair<event_handler*, std::duration>> queue;
    std::mutex   work;
    volatile int work_state;
    std::time    start;

    void run() {        
        work.lock();
        while (true) {
            cv.wait(work, [=] { return work_state > 0; });
            work.unlock();
            dequeue();
            if (work_state == 2)
                return;
        next:
            work.lock();
        }
    }

    void dequeue() {
        // while the queue is non-empty and work_state != 2
        //   wait for the earliest timer to expire
        //   if work_state != 2: 
        //     remove expired timers and invoke their callbacks
    }  
};
```

**Comment by nunoplopes** [comment]
Ok, today with fresh eyes I've fixed the underlying issue. The shell was allocating a scoped_timer and leaking it. This in turn was causing the thread to never exit before the timeout. This probably also caused the error you saw with the mutex being destroyed while locked.
The fix was to not leak the scoped_timer.
Apologies for the regression.

@NikolajBjorner I agree scoped_timer could be implemented with a single thread, but since STL doesn't have any helpful abstraction, it would be a bit of work for no benefit. The overhead of having multiple threads right now is extremely low. We can't measure it anymore on our benchmarks.
