### ISSUE TITLE
AUFBV bug - maybe related to sort (_ BitVec 1)

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#4778]
When applying Z3 https://github.com/Z3Prover/z3/commit/d0d06c288a76236ea6fb32b3858e7414e7d5f4c5 to the following SMT script I get `sat` as response to the check-sat command, but `unsat` would be correct.
[rushingMountaineerBug.smt2.txt](https://github.com/Z3Prover/z3/files/5496134/rushingMountaineerBug.smt2.txt)

My reasoning: Because of the first conjunct the array `a` is `1` at position `0`.
I instantiate the universally quantified array `ax` by `(store a (_ bv0 32) (_ bv0 1))` and both disjuncts of the second conjunct are equialent to false.

The bug is maybe related to the sort `(_ BitVec 1)`. If I use `(_ BitVec 2)` or `Int`, the response of Z3 is `unknown`.
The bug might not be related to the constant array `((as const (Array (_ BitVec 32) (_ BitVec 1))) #b1)`. This is only a script that I obtained from a larger script in which `a` was not restricted, I incorrectly got `sat` and the model `(define-fun a () (Array (_ BitVec 32) (_ BitVec 1)) ((as const (Array (_ BitVec 32) (_ BitVec 1))) #b1))`.

**Comment by nunoplopes** [comment]
Your formula has this `(or .. (distinct (select ax (_ bv0 32)) (_ bv0 1)))`, which is trivially true (the `distinct` operator only has 1 argument).
I recommend you cross check these test cases with another SMT solver before opening a bug report. Thanks!

**Comment by Heizmann** [comment]
But the distinct operator in this script has two arguments namely `(select ax (_ bv0 32))` and `(_ bv0 1)`.

**Comment by nunoplopes** [comment]
My bad, sorry. I minimized the example too much.
The issue is that you are comparing arrays directly instead of asserting that the value at all indexes are equal. Two arrays may be "equal" (in the sense all selects yield the same result), but for SMT they can be different if the the order of stores was different. The comparison is syntactic.

**Comment by Heizmann** [comment]
But the [array theory of SMT-LIB](http://smtlib.cs.uiowa.edu/theories-ArraysEx.shtml) is with extensionality, in the past Z3 supported extensionality and z3's check-sat response on the script below is `unsat`.

```
(set-logic ALL)
(declare-fun a () (Array Int Int))
(declare-fun a12 () (Array Int Int))
(declare-fun a21 () (Array Int Int))
(assert (= a12 (store (store a 1 23) 2 42)))
(assert (= a21 (store (store a 2 42) 1 23)))
(assert (distinct a12 a21))
(check-sat)
```

**Comment by nunoplopes** [comment]
Fair. I've never seen that functionality working well in Z3 though. I'll let @NikolajBjorner decide if he wants to support that or not.
BTW, I manually unrolled your example (just 4 cases..) and I get sat for all of them. It shows the issue is not with the quantifier (modulo a copy-paste mistake on my end 😀).
