### ISSUE TITLE
Best approach to solve an optimization constraint

### ISSUE THREAD

**Issue by mskd12** [Z3Prover/z3#4786]
I am looking for solutions to a boolean formula (mix of AND's and OR's) with the additional constraint that at most `k` literals can be set to true. Following the [optimization tutorial](https://rise4fun.com/Z3/tutorialcontent/optimization), I encoded the optimization constraint in the fashion below:

```
(define-fun bool_to_int ((b Bool)) Int 
	 (ite b 1 0))

(assert (< (+ (bool_to_int x0) (bool_to_int x1) (bool_to_int x2) ... k)))
```

The solver outputs fast results for a problem with around 50 literals but when I try to run it on a bigger problem with 150 literals, it gets stuck for a range of `k` values (I must note that I did not let it run for more than 15 mins). Is that expected behavior and is there anything I could do differently to make the solver run quicker? 

Note: In case it helps, here is some more info about the boolean formulae I am working with: they are of depth 3 and have the structure AND of OR of AND. An example is `((x1 or (x2 and x4)) and (x2 or (x1 and x3)) and (x3 or (x2 and x4)) and (x4 or (x3 and x1)) )`.

**Comment by NikolajBjorner** [comment]
It's always possible that Z3 simply chokes on what you send it. 
Generally, you can use ((_ at-most k) x0 x1 ... ) to force the formulas to be PB constraints.
By default the optimization solver looks for PB patterns and translates them automatically so it is more likely that it already has done this step. You can observe what solvers get invoked by asking for statistics (use the -st flag from the command-line, for example; if you see a lot of "arith" then it is using arithmetic, otherwise, if you see more "pb" or "ba" (boolean algebra) operations, the conversion into cardinality constraint solving is used).
