### ISSUE TITLE
Strange result in datalog computation

### ISSUE THREAD

**Issue by bertram-gil** [Z3Prover/z3#4893]
For the following program for z3 version (7fe829847938627ad880d3781fc81ac8dfd96cb3):
```
Z 64

WWW(A:Z) input
mAqE(A:Z) input
p(A:Z)
y(A:Z)
out(A:Z) printtuples


WWW(18).
WWW(15).
WWW(25).
WWW(16).
mAqE(29).
mAqE(39).

p(g) :- mAqE(x), WWW(g), x < g.
y(d) :- mAqE(a), p(d), !WWW(_).
out(c) :- y(a), WWW(b), WWW(c).
```

I get: 
```
$ ./z3 rules.datalog 
Tuples in out: 
	(A=18(18))
	(A=15(15))
	(A=25(25))
	(A=16(16))
Time: 12ms
Parsing: 0ms, other: 11ms
```

Now if I change the variable in the head of the `out` clause from `c` to `b`

```
Z 64

WWW(A:Z) input
mAqE(A:Z) input
p(A:Z)
y(A:Z)
out(A:Z) printtuples


WWW(18).
WWW(15).
WWW(25).
WWW(16).
mAqE(29).
mAqE(39).

p(g) :- mAqE(x), WWW(g), x < g.
y(d) :- mAqE(a), p(d), !WWW(_).
out(b) :- y(a), WWW(b), WWW(c).   ### c changed to b in head
```
Now I get: 

```
./z3 rules.datalog 
Tuples in out: 
Time: 5ms
Parsing: 0ms, other: 4ms

```

**Comment by bertram-gil** [comment]
With fae9481308040ba84fe0e081e142cb9cd3e86cb9, i get an empty result on both programs.

**Comment by NikolajBjorner** [comment]
You are mixing integers with constant literals (lower case identifiers).
Lower case identifiers are assigned integers during parsing. They can collide with the integers you use.
The parser performs only a single pass and does not take clashes or so into account.
A user friendly way of dealing with this could be to throw an error if the input has this toxic mix.

**Comment by bertram-gil** [comment]
Oh, I did not know this. However, I still get the same result if everything is upper case:
```
Z 64

WWW(A:Z) input
M(A:Z) input
P(A:Z)
Y(A:Z)
OUT(A:Z) printtuples


WWW(18).
WWW(15).
WWW(25).
WWW(16).
M(29).
M(39).

P(G) :- M(X), WWW(G), X < G.
Y(D) :- M(A), P(D), !WWW(_).
OUT(C) :- Y(A), WWW(B), WWW(C).
```

**Comment by NikolajBjorner** [comment]
I would first acknowledge that this is a bug. Also, I don't properly recall the case rules for constants vs. variables. If you use quotes, you get a constant for sure. 
The datalog text front-end has some role to play in the numerals vs symbolic constant issues. It is unambiguous over the C API.
However, I am going to punt on this one based on the following reasoning:

1. The bug uses unsafe negation. It is most likely tied to incorrect assumptions in pre-processing about whether negated literals are safe.
2. There is no indication to me that reasonable applications would use unsafe negation. 
3. The Datalog mode is very far from a mainstream use of Z3. Since it was created in 2010, the main use of the fixed-point features have moved to symbolic solving of Horn clauses, which is a closer fit to SMT solving. The SPACER engine serves this area and is disjoint from the features exercised in this bug.
4. I would have to re-acquire an understanding of what the code does in order to analyze the bug. These are cycles that can be spent better on features there is evidence users would care about.

You are invited to dig into the the code and create fixes. If you have an application that would benefit from a solid Datalog engine, other than BDDBDDB or Soufflé or similar this could be worthwhile. However, for purposes of purely poking holes, it isn't too useful.
