### ISSUE TITLE
fp.min/fp.max/fp.neg Bug with +/- 0.0

### ISSUE THREAD

**Issue by kyledewey** [Z3Prover/z3#492]
On the `master` branch at commit `cef8c67cc0e6b1b024d8e4e0150b2020688de7c7` with a debug + tracing build, consider the following input:

```
(set-logic QF_FP)
(assert (= (_ -zero 2 3)
                (fp.max       ; Point 4
                  (fp.min     ; Point 3
                    (fp.neg   ; Point 2
                      (fp.min ; Point 1
                        (_ -zero 2 3)
                        (_ +zero 2 3)))
                    (_ +zero 2 3))
                  (fp #b1 #b10 #b01))))
(check-sat)
(get-model)
```

If this is saved into `test.smt2` and then run with `z3 -smt2 test.smt2`, Z3 reports `unsat`.  Tracing the logic of this, at `Point 1` +/- 0.0 is possible based on the reasoning in issue #68, and similarly both +/- 0.0 is possible at `Point 2`.  `Point 3` still allows +/- 0.0, either of which is greater than `(fp #b1 #b10 #b01)`, allowing `Point 4` to be +/- 0.0.  Following this reasoning, this input should be `sat` at the comparison to -0.0.

While it might be possible to minimize this further, I found that the `fp.neg` is significant, as are nested uses of `fp.min` and `fp.max`.

This might be a duplicate of the closed issue #68.  I'm reporting it separately here as opposed to reopening #68 as this issue seems intertwined with `fp.neg` in some way, which is distinct from #68.

**Comment by wintersteiger** [comment]
Thanks for reporting this issue! Actually, I think Z3 is right in this case, but it's because of the uninterpreted function for the unspecified cases of (fp.min +-zero +-zero), so it's not quite trivial. My reasoning is as follows:

First, rewrite by naming the sub-expressions thusly:

    (set-logic QF_FP)

    (define-fun nz () (_ FloatingPoint 2 3) (_ -zero 2 3))
    (define-fun pz () (_ FloatingPoint 2 3) (_ +zero 2 3))

    (declare-fun x1 () (_ FloatingPoint 2 3))
    (declare-fun x2 () (_ FloatingPoint 2 3))
    (declare-fun x3 () (_ FloatingPoint 2 3))

    (assert (= x1 (fp.min nz pz)))
    (assert (= x2 (fp.neg x1)))
    (assert (= x3 (fp.min x2 pz)))

    (assert (= nz x3))

    (check-sat)

The `fp.max` around all of that is not necessary; the rewritten problem is unsatisfiable, and it becomes satisfiable if we change `(= nz x3)` into `(= pz x3)`. 

Now, all three variables can only be -zero or +zero (all other cases trivially unsatisfiable); so, let's case-split on x2: 

1) suppose x2 = +zero; then 
    x1 = fp.min -zero +zero
    (+zero = fp.neg x1) => x1 = -zero
    x3 = fp.min +zero +zero = +zero
    => x3 == -zero is false (regardless of x1).

2) suppose x2 = -zero; then
  x1 = fp.min -zero +zero (looks like "your choice of -zero or +zero")
  (x2 = fp.neg x1) => x1 = +zero
  x3 = fp.min -zero +zero (again "your choice of -zero or +zero", but, critically, you have to choose the same result as before for (fp.min -zero +zero)):

  A) suppose (fp.min -zero +zero) = +zero
    x1 = +zero
    x3 = +zero
    => x3 != -zero, contradiction with (= -zero x3).

  B) suppose (fp.min -zero +zero) = -zero
    x1 = -zero
    x3 = -zero
    x2 = (fp.neg x1) => x2 = +zero, contradiction with assumption 2).

Since fp.min has the same inputs, it must also have the same output, but that is impossible here. So, I think that's correct. Did I miss some crucial detail?

**Comment by kyledewey** [comment]
You're absolutely right; I failed to account for the fact that once we are forced to make a choice for the behavior of `min(-0.0, +0.0)` in one location, the behavior must be consistent across all locations.  Closing the issue because it's not a bug.  Thanks for the detailed explanation!
