### ISSUE TITLE
The generated C++ and C API are empty

### ISSUE THREAD

**Issue by ShufengGong** [Z3Prover/z3#4946]
I generated the api docs ''python mk_api_doc.py''
but the C++ and C api are empty.

**Comment by NikolajBjorner** [comment]
Thanks for the notification. Yes, doxygen generation is currently broken.
Doxygen issues a warning: end of file with unbalanced grouping commands for z3_api.h
It is likely related to this warning.
Unfortunately, the error message just points to the last line in the tmp file and does not give further hints so I am not sure how to best debug this.

**Comment by NikolajBjorner** [comment]
I couldn't figure out what has led to group__capi and group__cppapi to be empty. The relevant outputs seem to be in z3__api_8h.html and namespacez3.html, respectively. 
I have updated scripts to have the landing page point to these pages instead of the empty ones.
This is without a doubt a patch and there are many other improvements possible about the documentation. 
I would be open to contributions that overhaul this documentation approach, e.g., exploring documentation generation using https://readthedocs.org/, or appropriate.
