### ISSUE TITLE
Reuse of literals in Z3's sat module?

### ISSUE THREAD

**Issue by guluchen** [Z3Prover/z3#4974]
I try to run z3 with -tr:assign_core to understand better how its SAT solver works.

One thing I observe is that the content of a literal can change during its process.

For instance, in one example, I found 

-------- [assign_core] assign_core /home/alan23273850/z3/src/smt/smt_context.cpp:304 ---------
propagating: p309 (>= (+ 1::Int (str.len #84)) 1::Int) level: 34
justification -1: p307
....
-------- [assign_core] assign_core /home/alan23273850/z3/src/smt/smt_context.cpp:304 ---------
propagating: p309 (>= (str.len (seq.tail[seq.tail] #33 0::Int)) 1::Int) level: 31
justification -1: p307
...

in .z3-trace

The definition of literal p309 has been changed during the execution.

Is that an expected behavior of Z3?

**Comment by alan23273850** [comment]
It still happens when using the latest version...

(Ex1)
-------- [assign_core] assign_core /home/alan23273850/3Z/z3/src/smt/smt_context.cpp:290 ---------
propagating: 166 (let ((a!1 (seq.tail (seq.right (seq.suffix.z (seq.unit #x2e) b)
                                (seq.idx.right b (seq.unit #x2e)))
                     0)))
  (<= (str.len a!1) 0)) 
relevant: 0 level: 12 is atom 1
------------------------------------------------
...
-------- [assign_core] assign_core /home/alan23273850/3Z/z3/src/smt/smt_context.cpp:290 ---------
propagating: 166 (let ((a!1 (str.at (seq.left (seq.suffix.z (seq.unit #x2e) b)
                             (seq.idx.right b (seq.unit #x2e)))
                   0)))
  (>= (str.len a!1) 0)) 
relevant: 1 level: 11 is atom 1
------------------------------------------------
...

(Ex2)
-------- [assign_core] assign_core /home/alan23273850/3Z/z3/src/smt/smt_context.cpp:290 ---------
propagating: 167 (let ((a!1 (str.len (seq.right (seq.suffix.z (seq.unit #x2e) b)
                               (seq.idx.right b (seq.unit #x2e)))))
      (a!2 (seq.tail (seq.right (seq.suffix.z (seq.unit #x2e) b)
                                (seq.idx.right b (seq.unit #x2e)))
                     0)))
  (= a!1 (+ 1 (str.len a!2)))) 
relevant: 0 level: 12 is atom 0
------------------------------------------------
...
-------- [assign_core] assign_core /home/alan23273850/3Z/z3/src/smt/smt_context.cpp:290 ---------
propagating: -167 (not (let ((a!1 (str.len (seq.left (seq.suffix.z (seq.unit #x2e) b)
                              (seq.idx.right b (seq.unit #x2e))))))
  (= a!1 0))) 
relevant: 1 level: 11 is atom 1
------------------------------------------------
...

**Comment by NikolajBjorner** [comment]
That is correct. During search new terms and new atomic formulas can be created in conflict clauses. Some of these terms get garbage collected because the lemmas are unused after backtracking. The variable identifiers get recycled for new literals.
It is a bit tricky to enforce this behavior correctly and there is a bit of infrastructure to support that Boolean variables are garbage collected properly. In principle, it works as follows: the mapping from expressions into E-node and Boolean Variables internal representation follows a strict stack discipline. Nodes that are created in scope 84 are deleted when backtracking below 84. 
When there are lemmas that have to be retained during backtracking, they get re-internalized from their expression representations.
