### ISSUE TITLE
Confusing/unexpected reason-unknown with floats

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#5051]
@wintersteiger 

For this input:

```
(set-logic QF_FP)
(declare-fun x () (_ FloatingPoint 5 4))
(declare-fun y () (_ FloatingPoint 5 4))
(declare-fun z () (_ FloatingPoint 5 4))
(assert (fp.eq z (fp.add roundNearestTiesToEven x y)))
(check-sat)
(get-info :reason-unknown)
```

z3 says:

```
unknown
(:reason-unknown "there is no floating point support for division for representations with non-standard bit representations")
```

Wondering why z3 is not handling this case, perhaps it's really not supported? In that case, the unknown-reason is quite confusing as it refers to "division" but the input has no division operators anywhere.

I noticed that if I replace `fp.add` with `fp.mul` then z3 does indeed produce a model. It sounds unlikely that z3 supports multiplication but not addition, so I'm guessing this is actually a bug somewhere instead of actually being `unknown`.

**Comment by wintersteiger** [comment]
Yes, that error message doesn't make any sense. The real reason is that `ebits > sbits`, which is supported for some operations and not for others.

**Comment by wintersteiger** [comment]
The error messages have been updated a while ago (https://github.com/Z3Prover/z3/commit/12c32663c67e48d4397759bb12c0c20f8e7bde1b), so I'll close this issue. 

Just to explain further: the reason for these types of restrictions is that Z3 converts everything to bit-vectors and then bit-blasts that, which in some cases requires huge bit-vectors. It's not really worth the effort to implement those branches, because we know that the bit-blaster is going to run out of memory anyways, so we just return `unknown` early. That said, I think this particular instance in `fp.add` may be fixable; I'll take another look.
