### ISSUE TITLE
Mixing Integers and Rational in the new Java API

### ISSUE THREAD

**Issue by akreuzer** [Z3Prover/z3#5085]
Hi, this is a question and comment on the new Java API as introduced in #4832 by @VTCAKAVSMoACE 

I saw that one cannot mix values of different sorts in operations anymore as it worked beforehand.
For instance the following is valid in the old API (4.8.9) but does not compile in the new API (4.8.10).
```java
var intNum = ctx.mkInt(-1);
var floatNum = ctx.mkReal(3.14);
var x = ctx.mkMul(intNum, floatNum);
```
What is the intended way of writing something like this in the new API?
(Obviously one could call `ctx.mkInt2Real` but this would shift work from the Z3 to the developer.)

**Comment by akreuzer** [comment]
One way to make this possible would be to introduce some variance into the API for instance
https://github.com/Z3Prover/z3/blob/3c26a965e13c828ddb2bc31313a7540a66527c64/src/api/java/Context.java#L840
could become
```java
public final <R extends ArithSort> ArithExpr<R> mkMul(Expr<? extends R>... t)
```
Then the above code would be valid.

**Comment by NikolajBjorner** [comment]
Arithmetic operators are overloaded so Z3 inserts coercions. Therefore arithmetic operators can generally have a mix of real and integer arguments. This makes especially sense for addition, multiplication, comparison. Z3 does insert coercions for other operators, but the value of overloading them is less so because a user may not expect the coercion. 

Are you willing to add a pull request with the update? Adding an example to the java examples with this overload would also be good.

**Comment by akreuzer** [comment]
Yes I can do a pull request but I would need one or two weeks.
