### ISSUE TITLE
Memory leaks in debug build

### ISSUE THREAD

**Issue by MoodyMoon** [Z3Prover/z3#5095]
Tested on commit e8917a1a9f97db86bdc38c569ddbde7f79b76ce7

Repro
```
#include "z3.h"

int main(void)
{
    Z3_global_param_set("debug_ref_count", "true");
    Z3_config config = Z3_mk_config();
    Z3_context context = Z3_mk_context(config);
    Z3_del_config(config);
    Z3_del_context(context);
}
```
stdout
```
ast_manager LEAKED: 5
Leaked: String
Leaked: Seq
Leaked: Bool
ast_manager LEAKED: 2
Leaked: Unicode
Leaked: k!0
```

**Comment by NikolajBjorner** [comment]
I don't recall why reference counts aren't decremented when you add the debug_ref_count flag. I am now removing the code that disables this. It could lead to crashes if debug_ref_count is used or otherwise some new behavior. However, this flag is a debug option so at best an aid for building applications. You get leak information without this flag in debug mode so the flag isn't too useful.
