### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#510]
PR #498 broke the build on at least Ubuntu x86 and amd64, see [here](https://github.com/Z3Prover/bin/blob/master/nightly/z3-x86-ubuntu-failure-11-03-2016-21-21-14.log) and [there](https://github.com/Z3Prover/bin/blob/master/nightly/z3-x64-ubuntu-failure-11-03-2016-21-23-52.log). @delcypher could you take a look at this?

**Comment by delcypher** [comment]
@wintersteiger Sorry about this. I'm not going to be able to access my development machine for another 12 hours or so. If this is blocking you I think reverting  b3f6a3c4af0d157140a1a537927b9c086bef9b22 might fix this for now. I'll take a proper look in 12 hours or so.

**Comment by cheshire** [comment]
@delcypher Why is `exec` necessary there? I think I have never really seen a valid use case for it in production code.

**Comment by delcypher** [comment]
@cheshire I didn't write that code. PR #498 was just a refactor. I do not like the use of ``exec()``. I consider it to be incredibly dangerous. Currently there are special statements embedded in comments in some of the source files that the pythons scripts parse and then call ``exec()`` on. This is incredibly dangerous because I can basically cause arbitrary python code to be executed (e.g. I could delete the contents of your home directory). However the existing code if quite complicated and refactoring it all in one go seemed like too much work.

**Comment by delcypher** [comment]
#513 attempts to fix this.
