### ISSUE TITLE
bitvector/arithmetic regression

### ISSUE THREAD

**Issue by robdockins** [Z3Prover/z3#5106]
This is minimized slightly from an example generated by the Cryptol test suite.  Versions prior to 4.8.10 would solve this quickly. Glancing through the other issues on here led me to believe that it is related to the arithmetic solver, and that does seem to be the case.

```
$ cat z3regression.smt2
(define-fun s2 () Int 0)
(define-fun s4 () Int 32)
(define-fun s9 () (_ BitVec 32) #x00000020)
(define-fun s11 () (_ BitVec 32) #x00000000)

(declare-fun s0 () (_ BitVec 32))
(declare-fun s1 () Int)
(define-fun s3 () Bool (< s1 s2))
(define-fun s5 () Int (- s1))
(define-fun s6 () Bool (< s4 s5))
(define-fun s7 () Int (ite s6 s4 s5))
(define-fun s8 () (_ BitVec 32) ((_ int2bv 32) s7))
(define-fun s10 () Bool (bvuge s8 s9))
(define-fun s12 () (_ BitVec 32) (bvlshr s0 s8))
(define-fun s13 () (_ BitVec 32) (ite s10 s11 s12))
(define-fun s14 () Bool (< s4 s1))
(define-fun s15 () Int (ite s14 s4 s1))
(define-fun s16 () (_ BitVec 32) ((_ int2bv 32) s15))
(define-fun s17 () Bool (bvuge s16 s9))
(define-fun s18 () (_ BitVec 32) (bvshl s0 s16))
(define-fun s19 () (_ BitVec 32) (ite s17 s11 s18))
(define-fun s20 () (_ BitVec 32) (ite s3 s13 s19))
(define-fun s21 () Bool (< s5 s2))
(define-fun s22 () Int (- s5))
(define-fun s23 () Bool (< s4 s22))
(define-fun s24 () Int (ite s23 s4 s22))
(define-fun s25 () (_ BitVec 32) ((_ int2bv 32) s24))
(define-fun s26 () Bool (bvuge s25 s9))
(define-fun s27 () (_ BitVec 32) (bvshl s0 s25))
(define-fun s28 () (_ BitVec 32) (ite s26 s11 s27))
(define-fun s29 () (_ BitVec 32) (ite s21 s28 s13))
(define-fun s30 () Bool (= s20 s29))
(assert (not s30))
(check-sat)

$ time z3-4.8.10 smt.arith.solver=2 z3regression.smt2
unsat

real    0m0.066s
user    0m0.059s
sys     0m0.005s

$ time z3-4.8.10 smt.arith.solver=6 z3regression.smt2
^Cunknown

real    2m55.096s
user    2m54.166s
sys     0m0.717s
```

**Comment by NikolajBjorner** [comment]
@levnach - would you be able to triage? E.g., log what are the lemmas that the legacy solver identifies and not found in the new solver?

**Comment by levnach** [comment]
I will give it a shot.

**Comment by levnach** [comment]
I added a trace statement in int_gcd_test.cpp: the rows where the gcd conflicts are reported look very similar in both versions: almost all variables are fixed, and many are fixed to zeroes.

**Comment by robdockins** [comment]
FWIW, we have noticed some other problems involving `int2bv` also seem to be having problems, so that function may be implicated here.

**Comment by NikolajBjorner** [comment]
We haven't uncovered the root cause yet. 
The int2bv code is the same regardless of arithmetic solver.
The usual culprits are whether the new solver misses bounds or equality propagations that can help close branches.
Ultimately branches are closed using integer reasoning and also here differences in bounds / equality propagation can have an effect. Bounds propagation is affected by how constraints are compiled to tableau form and how the div/mod axioms are compiled to auxiliary inequalities. It is all a finite exercise, and the example is sufficiently small to give an idea (it could even be cut down by limiting the bit-width, I guess).

**Comment by NikolajBjorner** [comment]
For example, here is a smaller example showing a noticeable difference:

```
(define-fun s2 () Int 0)
(define-fun s4 () Int 32)
(define-fun s9 () (_ BitVec 8) #x20)
(define-fun s11 () (_ BitVec 8) #x00)

(declare-fun s0 () (_ BitVec 8))
(declare-fun s1 () Int)
(define-fun s3 () Bool (< s1 s2))
(define-fun s5 () Int (- s1))
(define-fun s6 () Bool (< s4 s5))
(define-fun s7 () Int (ite s6 s4 s5))
(define-fun s8 () (_ BitVec 8) ((_ int2bv 8) s7))
(define-fun s10 () Bool (bvuge s8 s9))
(define-fun s12 () (_ BitVec 8) (bvlshr s0 s8))
(define-fun s13 () (_ BitVec 8) (ite s10 s11 s12))
(define-fun s14 () Bool (< s4 s1))
(define-fun s15 () Int (ite s14 s4 s1))
(define-fun s16 () (_ BitVec 8) ((_ int2bv 8) s15))
(define-fun s17 () Bool (bvuge s16 s9))
(define-fun s18 () (_ BitVec 8) (bvshl s0 s16))
(define-fun s19 () (_ BitVec 8) (ite s17 s11 s18))
(define-fun s20 () (_ BitVec 8) (ite s3 s13 s19))
(define-fun s21 () Bool (< s5 s2))
(define-fun s22 () Int (- s5))
(define-fun s23 () Bool (< s4 s22))
(define-fun s24 () Int (ite s23 s4 s22))
(define-fun s25 () (_ BitVec 8) ((_ int2bv 8) s24))
(define-fun s26 () Bool (bvuge s25 s9))
(define-fun s27 () (_ BitVec 8) (bvshl s0 s25))
(define-fun s28 () (_ BitVec 8) (ite s26 s11 s27))
(define-fun s29 () (_ BitVec 8) (ite s21 s28 s13))
(define-fun s30 () Bool (= s20 s29))
(assert (not s30))
(check-sat)
```

**Comment by levnach** [comment]
I noticed on the run of the legacy solver on the original problem that the last 30 or so lemmas have the same structure: 
(declare-fun s1 () Int)
(assert (let ((a!1 (mod (div (ite (<= s1 32) s1 32) X) 2)))
  (not (>= a!1 1))))
(assert (let ((a!1 (mod (div (ite (<= s1 32) s1 32) X) 2))
      (a!2 (mod (div (ite (>= s1 (- 32)) (* (- 1) s1) 32) X) 2)))
  (>= (+ a!1 (* (- 1) a!2)) 0)))
(assert (let ((a!1 (mod (div (ite (>= s1 (- 32)) (* (- 1) s1) 32) X) 2)))
  (>= a!1 1)))
(check-sat)

The values of X were [...,128, 64, 32] : X was halved in each next lemma.
  I have not noticed this behavior in the new solver.

**Comment by NikolajBjorner** [comment]
These lemmas are created from
void theory_arith<Ext>::imply_bound_for_all_monomials(row const & r, bool is_lower)
and 
void theory_arith<Ext>::imply_bound_for_monomial(row const & r, int idx, bool is_lower)

It suggests that corresponding functionality, if any, in theory_lra is not comparable.

**Comment by levnach** [comment]
I noticed that the new solver finds a some bounds on variable v6 of theory_lra. However they are discarded by bound_is_interesting(), maybe because v6 corresponds to expression (*(-1) s1). Not sure it is the reason of the divergence, but this is the same s1 that the legacy solver was squeezing.

**Comment by NikolajBjorner** [comment]
I spent some hours Wed and Fri on this. Some observations but slow progress. So far I can see a few places where theory_lra can be improved based on the search behavior. 
An observable difference is that the old solver learns bounds between (mod ..) terms. The new does not. This alone isn't too interesting without explaining why.

**Comment by NikolajBjorner** [comment]
Whether or not your observation solves this problem, there seems to be one useful learning:
A bound (- s1) <= k corresponds to a bound s1 >= -k. Since (* (-1) s1) is a term, compiling inequalities to internal form should convert inequalities with (* (-1) s1) into inequalities that use s1. So the bounds propagation filter is brittle in this case. It could search for literals that use s1 instead of just (* (-1) s1). Recall that bounds propagation only assigns existing literals; it doesn't introduce fresh literals.

**Comment by NikolajBjorner** [comment]
Upon closer inspection, lack of bound propagation on (* (-1) s1) doesn't seem to be important. Neither core propagates bounds for this term.

**Comment by NikolajBjorner** [comment]
OTOH, equality propagation on s1 = 0 and  (* (-1) s1) = 0 are both missing in the new solver and for different reasons. The issues seem to all be in the theory_lra layer. Internalization is also different: the old solver doesn't create interface variables for subterms of mod/div. The new solver adds some interface variables for these and this introduces some minor extra overhead.
Changing this behavior to be compatible with old solver behavior doesn't really address the performance difference.

Overall, the issues include:
- fixed_var_eh is a no-op so it doesn't propagate s1 = 0 when this is detected.
- add_eq doesnot propagate (* (-1) s1) = 0 because it believes 0 is not shared (0 should be treated as shared).
After propagating both s1 = 0 and  (* (-1) s1) = 0, the old solver propagates additional equalities that are missed in the new solver. It would appear that these equalities introduce stronger lemmas.
It is still time consuming to fully uncover what is going on, but with the current information and the ability to drill into precisely where the two versions start diverging it should be solvable and fixing this should help broadly.

**Comment by NikolajBjorner** [comment]
fix is pushed

**Comment by robdockins** [comment]
I can confirm that a fresh build as of c0e74f946b28a83f94becab56a1565c49cb37141 fixes the original issue on my end.  Thanks!
