### ISSUE TITLE
Uncaught exception when parsing recursive list function (OCaml)

### ISSUE THREAD

**Issue by DKLoehr** [Z3Prover/z3#5113]
I'm using the OCaml bindings to run Z3, and I'm trying to add some definitions of simple list functions to my solver. However, when I do so my program terminates with the error 

`libc++abi.dylib: terminating with uncaught exception of type cmd_exception`

I get an identical error when I try to construct one of the list functions manually using `mk_rec_func_decl_s`; there, the error seems to occur during the call to FuncDecl.apply which references the recursive function declaration.

This is the smallest example I've found that triggers this error for me.
`SMT.parse_smtlib2_string (mk_context []) "(define-fun-rec f ((l (List Int))) Bool true)" [] [] [] [] `

**Comment by NikolajBjorner** [comment]
You could catch the exception and print information from it.

The issue would be that "List" is a predefined datatype that isn't declared 
in the environment used by the parser from the top level.
The conditions for pre-loading the declarations for List are somewhat buried away in https://github.com/Z3Prover/z3/blob/a99e75f58fc8308fd6e9805b840bf9c0439e1ed0/src/cmd_context/cmd_context.cpp#L751

A python repro of your issue is:
```
from z3 import *

parse_smt2_string("(define-fun-rec f ((l (List Int))) Bool true)", ctx = Context())
```

The exception stack is here:

```
Traceback (most recent call last):
  File "parse.py", line 3, in <module>
    parse_smt2_string("(define-fun-rec f ((l (List Int))) Bool true)", ctx = Context())
  File "C:\z3\build\python\z3\z3.py", line 8684, in parse_smt2_string
    return AstVector(Z3_parse_smtlib2_string(ctx.ref(), s, ssz, snames, ssorts, dsz, dnames, ddecls), ctx)
  File "C:\z3\build\python\z3\z3core.py", line 3286, in Z3_parse_smtlib2_string
    _elems.Check(a0)
  File "C:\z3\build\python\z3\z3core.py", line 1416, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'(error "line 1 column 24: unknown sort \'List\'")\n'
```

As a fix I have enabled loading lists for the smtlib2 parser calls.
