### ISSUE TITLE
`Model.evaluate(fpToIEEEBV(fpNaN(Float32())))` does not fully evaluate

### ISSUE THREAD

**Issue by 4tXJ7f** [Z3Prover/z3#518]
Should `Model.evaluate()` always fully evaluate the expression passed? Is there a way to force it to fully evaluate the expression?

Example that I had a problem with:
```
>>> s = Solver()
>>> s.check()
sat
>>> m = s.model()
>>> m.evaluate(fpToIEEEBV(fpNaN(Float32())))
Concat(0, Concat(255, Concat(0, 1)))
>>> m.evaluate(m.evaluate(fpToIEEEBV(fpNaN(Float32()))))
2139095041
```

Thanks a lot!

**Comment by wintersteiger** [comment]
In general, no, ` Model.evaluate()` will not always fully evaluate. It's last argument is a Boolean that enables model completion and when that is enabled, it will make up model values for everything that doesn't have a model value.

The particular case of fpToIEEEBV was buggy and I had been working on this since yesterday. You saw this problem because I wasn't done with all my changes yet. Note however that fpToIEEEBV is _not_ a standardized function, and that it has changed semantics _today_, i.e., 

    fpToIEEEBV(fpNaN(Float32()))

is 2139095041 (IEEE-like NaN encoding), _only_ when 

    set_param('rewriter.hi_fp_unspecified', 'true')

This is not SMT-compliant, because it disables all unspecified behaviour for all FP conversion functions (including fp.to_* and to_ieee_bv). Now that the unspecified semantics are implemented I will soon switch that default setting of this option to get SMT-compliant behaviour by default. This means that the conversion of NaN to IEEE BV will return an uninterpreted function with the name `to_ieee_bv_unspecified`. I may further refine that to a partially undefined bit-vector one of the next few days (the exponent bits are supposed to be 1, not undefined. It has the right semantics internally but that's not published via the model evaluation yet).

**Comment by 4tXJ7f** [comment]
Thanks a lot for the fix and the explanation! I am just using fpToIEEEBV to print out counterexamples in hexadecimal encoding in addition to the default string encoding and in the NaN case I don't really care about the encoding :)

**Comment by wintersteiger** [comment]
That's great - in that case it's perfectly safe :)
