### ISSUE TITLE
C# Binding of z3 failed to load the native dylib file on Mac OS Big Sur

### ISSUE THREAD

**Issue by panda2134** [Z3Prover/z3#5206]
Create a new C# Project, declare z3 as a dependency, and try to construct `Microsoft.Z3.Context`. The C# binding failed to find the position of `libz3.dylib`. Further inspection gives that the dynamic library is already located at `'${projectRoot}/bin/x64/Debug/net5.0/runtimes/macos/native'`.

A simple solution is to set `DYLD_LIBRARY_PATH` manually:

```bash
export DYLD_LIBRARY_PATH=./bin/x64/Debug/net5.0/runtimes/macos/native
```

However, it would be better if the C# binding of z3 can locate and load the dylib file automatically on Big Sur, just like on other platforms.

**Comment by panda2134** [comment]
BTW, in the file https://github.com/Z3Prover/z3/blob/21e59f7c6e5033006265fc6bc16e2c9f023db0e8/src/api/dotnet/Microsoft.Z3.csproj.in#L84 I didn't find any reference to the OSX build `libz3.dylib`.

**Comment by NikolajBjorner** [comment]
I am not sure how to approach this. 
- are you directly building on MacOS using cmake, python?
- or are you using the Nuget distribution of Z3?
The file
https://github.com/Z3Prover/z3/blob/21e59f7c6e5033006265fc6bc16e2c9f023db0e8/src/api/dotnet/Microsoft.Z3.csproj.in#L79-L86
is relevant for the cmake build, but is not used for the distribution. Clearly it was never tested or used for MacOS. But it isn't used for the distribution of Z3. I pushed a change where the csproj file contains an extra condition aimed for MacOS but don't have a way to test it. If this takes care of your scenario, then fine. Otherwise, submit a pull request with a patch.
