### ISSUE TITLE
Unreachable code in bv_internalize.cpp

### ISSUE THREAD

**Issue by jad-hamza** [Z3Prover/z3#5207]
```smt
(set-option :produce-unsat-assumptions true)
(declare-fun start!10 () Bool)
(assert start!10)
(declare-fun x!108 () (_ BitVec 32))
(declare-fun y!21 () (_ BitVec 32))

(assert (=> start!10 (and (bvsle #b00000000000000000000000000000000 x!108) (bvsle x!108 #b00000000000000000010011100010000) (bvsle #b00000000000000000000000000000000 y!21) (bvsle y!21 #b00000000000000000010011100010000) (= (bvadd x!108 y!21) (bvadd y!21 x!108)) (not (= x!108 #b00000000000000000000000000000000)) (not (= y!21 (bvsdiv (bvmul x!108 y!21) x!108))))))

(assert (=> start!10 true))
(check-sat)
```

I'm trying the new core on some examples and running `z3 tactic.default_tactic=smt sat.euf=true file.smt2` on this file (on master a52b485d9c27c4c7cd26f47fdf878b264900a0a6) got me this error:

```
(bvsdiv (bvmul x!108 y!21) x!108)
ASSERTION VIOLATION
File: /home/fiber/src/Z3/src/sat/smt/bv_internalize.cpp
Line: 223
UNEXPECTED CODE WAS REACHED.
4.8.11.0
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
```

What do these options mean by the way?

**Comment by NikolajBjorner** [comment]
Thanks for trying this very rough and unfinished part. 
The crash was due to incomplete handling of signed division. 
This is fixed. 

> What do these options mean by the way?

Note though, that tactic.default_tactic=smt sat.euf=true should be considered highly unstable.
The options ensures that Z3 uses a new backend for CDCL(T) solving. 
The new backend contains fresh implementations of theory solvers.

Though, as the perpetual fuzz bugs have subsided slightly now it is perhaps time to open the fuzz flood gates on this new code.
For example on very targeted SMT logics: QF_UFLIRA, QF_UFBV, QF_UFA, QF_ABV, QF_DT.

**Comment by jad-hamza** [comment]
Thanks for the quick fix! Are both options required for the new backend?
