### ISSUE TITLE
AVX instruction causes crash in libz3.dll on older CPUs

### ISSUE THREAD

**Issue by brechtsanders** [Z3Prover/z3#5248]
I have built z3 from source as part of the http://winlibs.com/ compiler builds for Windows.
Multiple users experience crashes in libz3.dll when running clang.exe which depends on it, see https://github.com/brechtsanders/winlibs_mingw/issues/39
The reason seems to be and AVX instruction while these users have a CPU that doesn't have the AVX instruction set.

How can I build z3 so it works on these CPUs aswell?

**Comment by andrewvaughanj** [comment]
What compiler are using to compile `libz3.dll`? GCC, clang, MSVC? What compiler flags are you specifying when building the DLL?

For sure, Z3 has some code in `src/util/hwf.cpp` that is guarded with `defined(__AVX__)`, so maybe you're compiling `libz3.dll` with a "too modern" CPU architecture specified for your compiler?

**Comment by brechtsanders** [comment]
I use GCC, in this case GCC 11.1.0 wiith the following cmake flags: `-DZ3_USE_LIB_GMP:BOOL=ON -DSINGLE_THREADED:BOOL=OFF -DPYTHON_EXECUTABLE=$PYDIR/python.exe -DZ3_BUILD_PYTHON_BINDINGS:BOOL=OFF -DZ3_BUILD_DOTNET_BINDINGS:BOOL=OFF -DZ3_BUILD_JAVA_BINDINGS:BOOL=OFF -DZ3_INCLUDE_GIT_DESCRIBE:BOOL=OFF -DZ3_INCLUDE_GIT_HASH:BOOL=OFF -DZ3_ENABLE_EXAMPLE_TARGETS:BOOL=OFF -DZ3_BUILD_DOCUMENTATION:BOOL=OFF`.

I added no other compiler flags manually, but my build system does have a recent CPU (AMD Ryzen 9 5950X 16-Core).

Is there a way to tell the z3 build not to use all the latest features of my own CPU so the code will run on older or more low-end CPUs?

Or should I look in the code for `defined(__AVX__)` and change that so it doesn't include the AVX instructions?

**Comment by wintersteiger** [comment]
CMake and your compiler, by default, assume that you want to build everything for the system you're running the build on, but you can tell it to build for other architectures, e.g. by adding `-march=i386`. CMake can pass that through, I believe via `-DCMAKE_CXX_FLAGS="-march=i386"` or similar. GCC supports a huge set of x86-flavour architectures to pick from, see https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#x86-Options. On architectures that don't support AVX, the `__AVX__` macro should not be be defined, so there's no need to manually modify anything.

**Comment by andrewvaughanj** [comment]
If you're driving this via `cmake`, you should look at setting `CFLAGS` and/or `CXXFLAGS` and then the `-mtune`/`march` option (probably).

**Comment by brechtsanders** [comment]
The `-march` and `-mtune` didn't quite resolve the issue (at least not for Windows 64-bit).
After quite a bit of trial and error the solution was to change the `CMakeLists.txt` line `if (HAS_SSE2)` to `if (HAS_SSE2 AND NOT MINGW)`.
This is probably a dirty solution, but apparently if it is detected the compiler supports SSE2 it always uses this and somehow some AVX instruction(s) too.
Maybe there should be a cmake flag to allow falling back to more basic/common CPU options (I guess SSE2 should be fine, but not everybody has AVX).

**Comment by andrewvaughanj** [comment]
Yeah, it looks like Z3 does something like this:

```
set(SSE_FLAGS "-mfpmath=sse" "-msse" "-msse2")
CHECK_CXX_COMPILER_FLAG("${SSE_FLAGS}" HAS_SSE2)
```

which then sets `HAS_SSE2` to `TRUE` because your compiler _does_ support those flags (but just not the architecture you're compiling for). My guess is that `-msse`/`-msse2` "wins" over having `-march`/`-mtune` on `CFLAGS`/`CXXFLAGS`.

If you really wanted to solve this, you could build a GCC cross-compiler from Win64 to Win64 that disallows stuff like this, but that's probably overkill for what you're trying to do.

Maybe you could create a Z3 PR that allows to disable the above with a CMake option? I wouldn't rely on `NOT MINGW` because, as you've seen, Z3 _does_ work MinGW and if you opened a PR for that change, you'd then be disabling (e.g.,) AXV for users on Windows who _do_ have it.

**Comment by wintersteiger** [comment]
Those particular options are for sound floating point behavior, if they were removed, they need to be replaced by the corresponding flags for the target architecture (i.e. use x87 instead of SSE2), otherwise the compiler (especially MSVC) will chose fast approximations over IEEE754-compliance. I'm have no idea whether the current CMake scripts make that easy or hard, but the older Python build system supports both.

**Comment by brechtsanders** [comment]
I myself wasn't able to reproduce issue on my systems - I was depending in the people who reported this to me in https://github.com/brechtsanders/winlibs_mingw/issues/39
They used gdb on a system without AVX to pinpoint the issue.
