### ISSUE TITLE
adding an include path

### ISSUE THREAD

**Issue by levnach** [Z3Prover/z3#533]
Suppose we want relative paths in the includes. How can we instrument cmake to make sure that the include path includes src?
 Something like:
      list(APPEND Z3_COMPONENT_EXTRA_INCLUDE_DIRS "src")

(which does not work)
 ?

**Comment by agurfinkel** [comment]
Try ${CMAKE_SOURCE_DIR}/src  instead of src.

**Comment by delcypher** [comment]
@levnach @agurfinkel is correct. If you really want to add ``src`` as an include path you could do

```cmake
list(APPEND Z3_COMPONENT_EXTRA_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/src")
```

What you are asking to do make me slightly worried though. What are you trying to achieve? Currently the CMake build system mimics the Python build system and declares dependencies between components. This has two purposes

* Declaring that component ``A`` has a  dependency on say a component ``B`` means that the ``B`` component (and all it's dependencies) will be built before ``A``. This is necessary because some of the components generate their header files at build time and so those header files need to exist before other components try to use them.

* Adding include directories. If a component ``A`` declares a dependency on component ``B`` then ``A`` will have the source and build directory of component ``B`` (and the source and build directory of its dependencies) added to the include paths for component ``A``. I'm not a huge fan of this. I think it would be much simpler if all ``#include``s were written relative to ``src/`` i.e. ``#include "ast/fpa/fpa2bv_converter.h"`` rather than ``#include "fpa2bv_converter.h"``. Then we would only need to specify two include paths (i.e. ``${CMAKE_SOURCE_DIR}/src`` and ``${CMAKE_BINARY_DIR}/src``). However Z3's includes aren't written this way currently and I haven't found the time to go in and fix this.

Anyway the point is the fact you are trying to add include directories makes me think you might be trying to subvert the dependencies between components. So if that's what you're doing don't do it because it will break the build in unpredictable ways.

**Comment by NikolajBjorner** [comment]
There is no attempt to subvert dependencies. 
Dependencies are unchanged.
Lev's code uses paths relative to src and it is not going to be 
sustainable to make them relative to the dependencies.

**Comment by delcypher** [comment]
Okay just to note there are also a few other ways to set the include directories apart from appending to ``Z3_COMPONENT_EXTRA_INCLUDE_DIRS``.

You can do it on a per-target basis (the recommended way)

```cmake
target_include_directories(util PRIVATE "${CMAKE_SOURCE_DIR}/src")
```

or globally (not recommended)

```cmake
include_directories("${CMAKE_SOURCE_DIR}/src")
```
@levnach Do all these responses answer your question? By the way thanks for taking an interest in the CMake build system.

**Comment by levnach** [comment]
Thank you. You answered my questions.

For the time being this trick works for me 

list(APPEND Z3_COMPONENT_EXTRA_INCLUDE_DIRS "../..")

**Comment by NikolajBjorner** [comment]
.... of course to be replaced by the appropriate way later :-)

**Comment by delcypher** [comment]
@levnach 
```cmake
list(APPEND Z3_COMPONENT_EXTRA_INCLUDE_DIRS "../..")
```

that will certainly lead to problems later on. At a guess that path will probably refer to the ``src/`` folder in the build directory (depending on which component is being built) which will contain generated header files. So my guess is what you actually want is this instead:

```cmake
list(APPEND Z3_COMPONENT_EXTRA_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/src")
list(APPEND Z3_COMPONENT_EXTRA_INCLUDE_DIRS "${CMAKE_BINARY_DIR}/src")
```

**Comment by wintersteiger** [comment]
Looks like this problem has been resolved, can we close this issue?
