### ISSUE TITLE
model_eval returns identity on "don't cares"

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#536]
Hi,

The C API documentation for `model_eval` specifies that setting `model_completion` to `false` would let the caller identify the identities.
I have (somehow naively) assumed that for don't-cares Z3 would not write anything into the given pointer, or write `null`.
Turns out it instead writes the same AST node it got as an input.
Is it a bug or a feature?
If latter, could it be documented?

**Comment by cheshire** [comment]
Identity is really not helpful, as it makes it very hard to identify don't-cares.
E.g. I would expect that `model.evaluate(1)` stays `1`, yet it interferes with the fact that `model.evaluate(x) = x` signals that `x` is irrelevant.

**Comment by NikolajBjorner** [comment]
It's a feature, but I think I see the inconsistency: models given by lookup-tables may have undetermined default cases when model completion is off and it may have resulted in null in a distant past. 
The behavior is that model completion=false is that sub-expressions are only converted into values when the current model specifies a value. Otherwise, sub-expressions are retained. Model evaluation in both cases performs rewriting to do constant folding if the expression you are evaluating corresponds to a compound expression.

Models expose tables for constants and functions. You can query these tables to determine if a constant is a don't care. You can use the function tables to also evaluate (on your own) if a function application is handled by the current cases.

**Comment by cheshire** [comment]
@NikolajBjorner I can, but I think it would be very tricky with function applications, especially nested ones, and wouldn't it be easier for a model to give me a boolean flag indicating whether the value is relevant?
I assume you mean something like (in bad pseudocode):

```
val = model.evaluate(input);
if (input == val && val not in model) {
    return DONT_CARE;
} else {
   return val;
}
```

right? The only handling I can think of for function applications is to recursively evaluate the argument checking it's relevancy, and branching either to returning "irrelevant" if the argument is irrelevant, or trying to look up the value of the function with the argument evaluated.

**Comment by cheshire** [comment]
I've solved it on my side by checking whether the returned value is numerical/boolean.
Feel free to close, but an update to the documentation will be appreciated.

**Comment by NikolajBjorner** [comment]
yes, the documentation was missing a comment about what happens in when completion is disabled.
