### ISSUE TITLE
(horn) Soundness bug in QF_BVFP

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5423]
Hi,
For these cases, Z3 gives an incorrect answer with (check-sat-using horn):
[QF_BVFP.zip](https://github.com/Z3Prover/z3/files/6856897/QF_BVFP.zip)

OS: Ubuntu 18.04.5 LTS
Revision: [b84b5d](https://github.com/Z3Prover/z3/commit/b84b5d091e77724a3c842f7e5d7009be6552f041)

**Comment by agurfinkel** [comment]
As far as I can tell, this is a QF_BVFP instance to which horn tactic is manually applied. 
Horn tactic should only be applied to instances in HORN logic fragment.

In general, horn tactic does not support FP (reliably) and should not be used with this theory.

**Comment by merlinsun** [comment]
> As far as I can tell, this is a QF_BVFP instance to which horn tactic is manually applied.
> Horn tactic should only be applied to instances in HORN logic fragment.
> 
> In general, horn tactic does not support FP (reliably) and should not be used with this theory.

OK, I think I get it. Really thanks for your reply.

**Comment by merlinsun** [comment]
Maybe it is not a good question, but I wonder why does Z3 return “unsat” instead of “unknown” for this case that horn tactic doesn't support.

**Comment by agurfinkel** [comment]
Most tactics are best-effort. Instead of failing, they attempt to interpret unsupported features in some way and proceed with analysis. This is useful for advanced users that are pushing at the limit of what is possible / supported. In your example, you are specifically calling the horn tactic, thus, you are expected to known whether it is possible and what result to expect. 

You might want to enable `fp.validate=true` option to turn on validation in the horn solver. This way, the answers are validated before the result is produced.

**Comment by merlinsun** [comment]
> Most tactics are best-effort. Instead of failing, they attempt to interpret unsupported features in some way and proceed with analysis. This is useful for advanced users that are pushing at the limit of what is possible / supported. In your example, you are specifically calling the horn tactic, thus, you are expected to known whether it is possible and what result to expect.
> 
> You might want to enable `fp.validate=true` option to turn on validation in the horn solver. This way, the answers are validated before the result is produced.

I feel so grateful for your help!
