### ISSUE TITLE
python z3 gt expression flipped

### ISSUE THREAD

**Issue by batchenRothenberg** [Z3Prover/z3#5434]
I am using Python 3.8 with Z3 4.8.12 and I encountered a problem, which is exemplified in the following code:
```python
    from z3 import *
    if __name__ == "__main__":
        x = Int('x')
        y = x <= 0
        z = y.arg(0) > y.arg(1)
        print(z) # prints 0 < x
```
The problem is that although `0<x` is semantically equivalent to `x>0` (of course), the syntax was important to me. 
I wanted z to be built exactly as I asked: with ">" as the operator, and <x,0> as the arguments, in that order.
Can I somehow turn off whatever is causing z3 to flip my expression?
Thanks :)

**Comment by andrewvaughanj** [comment]
I think you're hitting a Python strangeness here, and nothing to do with Z3.

Consider this slight change to your code:

```python
from z3 import *

if __name__ == "__main__":
    x = Int("x")
    y = x <= 0
    a1 = y.arg(0)
    a2 = y.arg(1)
    z = a1.__lt__(a2)
    print(z)
    z = a2.__gt__(a1)
    print(z)
    z = a1 < a2
    print(z)
```

The last two give `gt` when you'd expect the first and the last to be the same (i.e., the first and last should be `lt`). If you debug in the Z3 API (e.g., put a print in `z3.py` around `__lt__`/`__gt__` on `ArithRef`), you'll see that Python is *directly* calling `__gt__` in `ArithRef` on the last one.

I believe the reason is as follows:

> If the operands are of different types, and right
> operand’s type is a direct or indirect subclass of the
> left operand’s type, the reflected method of the right
> operand has priority, otherwise the left operand’s method
> has priority.
> 

[https://docs.python.org/3/reference/datamodel.html#object.__gt__](https://docs.python.org/3/reference/datamodel.html#object.__gt__)

and this is likely because `a1` is `ArithRef`, while `a2` is `IntNumRef`, which then "takes precedence" because `IntNumRef` extends from `ArithRef`, so your operator gets flipped **by Python**.

**Comment by andrewvaughanj** [comment]
This demonstrates it quite nicely:

```python
class Base:
    def __init__(self):
        pass

    def __gt__(self, other):
        print("GT")

    def __lt__(self, other):
        print("LT")


class Derived(Base):
    def __init__(self):
        pass


x = Base()
print(x)
y = Derived()
print(y)

x < y  # GT
x > y  # LT

y < x  # LT
y > x  # GT
```

**Comment by NikolajBjorner** [comment]
Here is a minimal example:

```
x = Int('x')
>>> print(0 < x)
x > 0
```

Whether it is numerals or IntNumRef, the same comment applies: It is a Python feature.

**Comment by batchenRothenberg** [comment]
Thanks for a great explanation and a real fast reply!
And sorry for bothering you with a non-z3 issue.
