### ISSUE TITLE
Soundness bug in QF_IDL

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5456]
Hi,
For the following instance, Z3 returns `unsat` with `(check-sat-using (then nnf pb-preprocess der smt))`, but returns `sat` with `(check-sat)`:
[QF_IDL.zip](https://github.com/Z3Prover/z3/files/6930856/QF_IDL.zip)

Revision: [9398601](https://github.com/Z3Prover/z3/commit/939860148fdfe914b3832127fc190bc2a008e69f)

**Comment by NikolajBjorner** [comment]
It is likely much more suitable to name these bugs as issues with pb-preprocess. 
The pb-preprocess tactic is way out of mainstream and rarely if ever used and therefore as you have seen prone to bugs that haven't been found. It is even possible that I just remove this tactic because functionality is duplicated and thoroughly debugged as inprocessing.

**Comment by merlinsun** [comment]
> It is likely much more suitable to name these bugs as issues with pb-preprocess.
> The pb-preprocess tactic is way out of mainstream and rarely if ever used and therefore as you have seen prone to bugs that haven't been found. It is even possible that I just remove this tactic because functionality is duplicated and thoroughly debugged as inprocessing.

Thanks for your attention to each issue. 
In the future, I will report bugs in a targeted manner.
