### ISSUE TITLE
create fpa from three bit-vector

### ISSUE THREAD

**Issue by Taeyang123456** [Z3Prover/z3#5474]
Hello, I'm using z3 in C++, and I would like to create a 80bit float-point expression, with 1 bit sign,15 bit exponent and 64 bit significand. So I use 'Z3_mk_fpa_fp', with three bit-vector in the size of 1, 15 and 64, and their sort is ```(_ BitVec 1) (_ BitVec 15) (_ BitVec 64)```. However, this Api return a fpa with ```(_ FloatingPoint 15 65)```, and its significand's size is not what I want. Why this happened?

**Comment by wintersteiger** [comment]
The extra bit is the leading, hidden significand bit. I.e., a 64-bit significand is represented by a bit-vector of size 63, because the leading bit is always 1 (except for specials, but those are indicated by the exponent). See also `(fp (_ BitVec 1) (_ BitVec eb) (_ BitVec i) (_ FloatingPoint eb sb))` in the [FP theory specification](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml).

**Comment by Taeyang123456** [comment]
It really helps. Thank you!
