### ISSUE TITLE
How to simplify expression towards algorithmic complexity?

### ISSUE THREAD

**Issue by yaitskov** [Z3Prover/z3#5548]
Hi,

Can z3 simplify expressions with declared functions with defined algorithmic complexity for them?
Example of expression 
```
simplify(
  strlen(
    concat("123", "abc"))) => 
 strlen("123") + strlen("abc")
```

or

```
simplify(substring(upper("abcd"), 1, 2)) =>
 upper(substring("abcd, 1, 2))
```

**Comment by nunoplopes** [comment]
Nope, Z3 doesn't support anything of that kind. That's closer to what compilers do. Maybe check MLIR's rewrite framework: 
https://mlir.llvm.org/docs/DeclarativeRewrites/
https://mlir.llvm.org/docs/Tutorials/QuickstartRewrites/

It's not exactly what you want, but probably the closest. Otherwise, check stuff like equality saturation, such as egg (https://dl.acm.org/doi/10.1145/3434304).
