### ISSUE TITLE
int2bv trivially confused

### ISSUE THREAD

**Issue by Owlz** [Z3Prover/z3#555]
I'm working on creating a python script symbolic executor and using Z3 as the solver. I've run into a few issues, one of the bigger right now is that int2bv can apparently be trivially confused when the bitvec size is high enough. Here's an example:

```python
import z3

def z3_int_to_bv(x,size=64):
    assert type(x) in [z3.IntNumRef,z3.ArithRef]
    assert x.is_int()
    # Converts Int to BV
    return z3.BitVecRef(z3.Z3_mk_int2bv(x.ctx_ref(),size,x.as_ast()))


a,b = z3.Ints('a b')
c = z3.BitVec('c',64)

s = z3.Solver()

s.add(a == 1)
s.add(b == a)
s.add(c == z3_int_to_bv(b,64) ^ z3.BitVecVal(1,64))
```

For this, the size of 64 basically never returns. It starts getting slow at about a bit length of 16 even though there's only one assignment of this variable previously and it was to a static variable itself. I chose the value of 1 for the sake of demonstration, however it's obviously possible the value would be something else in practice.

How can I get by this problem? For various reasons I really do have to leverage the int2bv function and in some cases it works fine. The case mentioned above does come up a fair amount in practice.

**Comment by Owlz** [comment]
Still learning about Z3 and SMT things. I've recently discovered that using "z3.Then("simplify","solve-eqs","smt")" seems to fix many problems I have. It appears to fix this as well. Apologies for the lack of understanding on this. Perhaps that type of solver should be the default for those of us who don't understand the options?

**Comment by wintersteiger** [comment]
int2bv is a z3-specific extension to SMT and its semantics depend on the context. We usually tell people to assume int2bv is treated as uninterpreted. Further, in this context it forces Z3 to fall back to the slowest possible solver because that is the only solver that supports bit-vectors and integers in the same problem. If you can stick to only one of those two theories, chances are that the performance will be significantly better.
