### ISSUE TITLE
How do mod0 and div0 mean in the output?

### ISSUE THREAD

**Issue by lesshaste** [Z3Prover/z3#5565]
Take this toy example

```
from z3 import *
a, b, c, d = Ints('a b c d')
s = Solver()
s.add(a>0)
s.add(b>1)
s.add(c>0)
s.add(d>0)
s.add(a*b - c*d< 20)
s.add(d/a+b/d > 2)
s.add((a*c)/(b*d) > 3)
s.check()
print(s.model())
```

it outputs 

[d = 8,
 a = 4,
 c = 64,
 b = 8,
 div0 = [(8, 4) -> 2, (256, 64) -> 4, else -> 1],
 mod0 = [else -> 0]]

What do the div0 and mod0 lines mean? I tried to look in the documentation but couldn't find a relevant section.

**Comment by chansey97** [comment]
A related issue: https://github.com/Z3Prover/z3/issues/5553

**Comment by NikolajBjorner** [comment]
There are several functions that have partial specifications. They are fully specified on a subset of their domains, and outside of that subset they behave as uninterpreted functions. These functions include mod, div, rem, /, several floating point functions.
Specifically for mod, div, rem, / the functions are fully specified when the second argument is non-zero.
For example
```
                   q > 0 implies p = (p div q) * q + (p mod q) and 0 <= p mod q < q 
```

It uniquely defines p div q and p mod q whenever q > 0.
When q = 0, there is no defining axiom. We introduce div0 etc to indicate how div behaves when the second argument is 0.
Thus, the interpretation of (div p q) is integer division when q is != 0 and it is given by (div0 p q) otherwise.

**Comment by lesshaste** [comment]
Thank you. That is very informative.
