### ISSUE TITLE
Z3 ignores timeout

### ISSUE THREAD

**Issue by MohamedElgharbawy** [Z3Prover/z3#5568]
Hello,

I set a timeout in my code for 1 second, but Z3 seems to ignore this sometimes. I use `set_param("timeout", max_timeout)` in my function, but when I add too many constraints (~500) it just ignores the timeout. See the following graph:

![image](https://user-images.githubusercontent.com/30507689/134726631-9929784d-af24-47ac-9d9c-8aafef2a5d12.png)

Any idea if this is a bug, or am I using timeout wrong?

**Comment by NikolajBjorner** [comment]
Not all activities can be safely interrupted. Z3 internally polls for whether there is a cancelation/timeout/resource excess state. The polling is only performed safe places. For example, if it performs a "push", which can be in response to an internal or external action, it cannot be safely interrupted because the state is not safely backtrackable. Based on the high-level report I have to assume it is due to the solver being set into a state where it cannot be interrupted.

**Comment by MohamedElgharbawy** [comment]
The only thing I want to interrupt is solver.check(), is there no way to consistently do that?

**Comment by NikolajBjorner** [comment]
You can use solver.ctx.interrupt() from a different thread, but it could also not result in immediate termination.
