### ISSUE TITLE
pyZ3 crashing

### ISSUE THREAD

**Issue by Owlz** [Z3Prover/z3#559]
In ref to a previous ticket (https://github.com/Z3Prover/z3/issues/485), I've again stumbled into a situation that regularly causes python to completely crash. Here's how to reproduce:

git clone https://github.com/Owlz/pySym/tree/z3_crashing

Ensure you have z3 available for import (workon/virtualenv/etc).

Open ipython (v3)

```python
import logging
logging.basicConfig(level=logging.DEBUG,format='%(name)s - %(levelname)s - %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p')
from pyPath import Path
import ast
import Colorer
from pyPathGroup import PathGroup

source = """
a = 1
"""

b = ast.parse(source).body
p = Path(b,source=source)
pg = PathGroup(p)
pg.explore()
pg.errored[0].step()
```

You can also usually replace that last step command with simply attempting to exit out of the ipython interpreter. Usually you get a general core dump message or "corrupted double-linked list: 0x00000000015d7150" type message.

EDIT: This problem re-appeared when attempting to implement s.translate in my pyState/__init__.py:copy routine.

**Comment by Owlz** [comment]
Btw, this is with a Z3 version that I just compiled today from git. But it affected older versions as well.

**Comment by NikolajBjorner** [comment]
Would you be able to call "open_log(<logfile>.log)" prior to any other Z3 context creation to create a log file? Log files are often (but not always) very instrumental for reproducing crashes inside of Z3 in a way that only depends on the current API functions (log files stop running when we update the API functions, so it helps having the commit hash associated with the log file).
I downloaded your rather cool project, but I don't have pip, pip3 etc,, and I use Win10 (and I am not alpha testing the ubuntu features yet) so I am a bit afraid it would be a sinkhole to try to reproduce the bug. 

One thing I noticed: solvers that are created by composing tactics are not really incremental. push/pop would not help with internal incrementality. It may still be useful for how you manage external state and speed up the interaction altogether. You should assume that the only real incremental solvers is the default solver. This is probably not a real issue for you, but something that may be useful to know.

**Comment by Owlz** [comment]
Nikolaj,

Thanks for the feedback! Good to know on the push/pop. That'd actually explain why pop stopped working too, and as you pointed out it likely wouldn't change too much from how the program works currently.

I ran the log command you mentioned. I've pushed that back to the repo.

Theoretically this should work on Windows, but honestly I've never tried it. For now the targeted environment is indeed Ubuntu.

**Comment by NikolajBjorner** [comment]
The log runs through without crashing (but reports a little leakage). Note that you are creating new contexts (4 fresh contexts are created according to the log). You can't use expressions created in one context when accessing state owned by a different context. This is a most likely cause of crashes (and would explain the leakage as well) and it requires quite a bit of diligence on the caller to ensure that contexts are used properly. The C# and Java APIs, and the python APIs do check for proper context usage as far as we have been able to identify the proper places to check, but it could very well be that not everything is checked.

Multiple contexts are useful for multi-threading, otherwise they should not be required. If you just want to save solver state so that you can explore from that state later then it should be possible to use the same context when translating solvers. Of course, this code in Z3 could have bugs, especially as it is a very rarely used feature.

**Comment by Owlz** [comment]
Ahhh. Didn't realize that I could just keep the same context. Making that change it now works like a charm and has a noticeable speed improvement.

Thanks!

**Comment by NikolajBjorner** [comment]
great!
