### ISSUE TITLE
FPA remainder does not match SMT-FPA semantics

### ISSUE THREAD

**Issue by davemenendez** [Z3Prover/z3#561]
In Z3, if I do remainder(7,4) I get 3.

```
>>> simplify(fpRem(FPVal(7, Float32()), 4))
1.5*(2**1)
```

However, my reading of the [SMT-FPA theory](http://www.cprover.org/SMT-LIB-Float/smt-fpa.pdf) and IEEE 754 is that remainder(7,4) should be -1. Specifically, remainder(7,4) = 7 - 4 * n, where n is the integer nearest to 7/4 = 1.75, meaning n = 2.

Alternately, if the current semantics for `fpRem` are intentional, they should be documented somewhere.

**Comment by wintersteiger** [comment]
The document you cite is not the SMT FP standard, but an early draft/suggestion. The actual standard document is [here](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml) and the semantics are described in-depth in [this paper](http://smtlib.cs.uiowa.edu/papers/BTRW15.pdf).

That said, out of all the FP functions the remainder is the least tested (and few applications/people need it), so it's quite possible that it is still buggy for some inputs, but I think this particular case should be in accordance with the standard.

**Comment by davemenendez** [comment]
From the standard:

> remainder: x - y * n, where n in Z is nearest to x/y 

The integer nearest 7/4 = 1.75 is 2, so rem(7,4) = 7 - 4 * 2 = -1.

Table IX in the paper translates `fp.rem` to *remrne*, which is similarly defined on page 10.

**Comment by wintersteiger** [comment]
I've handed this case over to all the related FP people (who are free to respond here if they like). I currently think that Z3 may indeed be non-compliant to the SMT-FP standard, but at the same time the standard may not be worded as intended. 

As it turns out, my x87 FPU says -1.0, but my SSE2 FPU says +3.0. It looks like there may have been a change in semantics between the old IEEE754 and the new one, but this has not been considered in the SMT-FP standard.

**Comment by LeventErkok** [comment]
**From the hardware perspective:** There are two related instructions `FPREM` and `FPREM1` in the x86 instruction set. Former truncates towards zero (justifying the result `+3.0`), latter rounds to nearest (justifying the result `-1`).

For details, see here: http://www.intel.com/Assets/en_US/PDF/manual/253666.pdf
Volume 2A; pages: 3-398 thru 3-403.

**From the software perspective:** The C function `fmod` promises the result to have the same sign as the first argument, which suggests a `truncate-towards-zero` interpretation. See here: http://linux.die.net/man/3/fmod

I'll posit that the SMT-Lib standard models (i.e., `FPREM`/`fmod`) and hence `+3.0` is the correct answer in this case. Perhaps the most obvious thing to do would be to change the standard so that `fp.rem` actually takes the rounding-mode as an argument, allowing modeling both `FPREM` and `FPREM1` and whatever other rounding modes one might want.

**Comment by wintersteiger** [comment]
@LeventErkok: fmod is what I used when testing Z3 and to generate the SMT-LIB benchmark files, but it turns out that this function is not IEEE-compliant. Instead, I currently believe that [remainder(...) ](http://en.cppreference.com/w/cpp/numeric/math/remainder) will have the right behaviour, but I'm still fixing other (related) bugs before I can do any serious testing.

**Comment by wintersteiger** [comment]
BTW, we're trying to get a wiki on FP corner-case documentation running. Is [this](https://bitbucket.org/smt-lib/standard/wiki/Theory%20of%20floating%20point%20numbers%20(FloatingPoint)) accessible for you?

**Comment by LeventErkok** [comment]
@wintersteiger Yes, I can view the wiki..

So, looks like `FRPEM1` from the x86 instruction-set is the one being modeled by `fp.rem` then?

**Comment by wintersteiger** [comment]
Yes. If I'm not mistaken FPREM predates IEEE-754, so FPREM1 was added afterwards.

**Comment by wintersteiger** [comment]
Thanks again for the report, this has now been fixed. I replaced large chunks of old implementation with a new implementation, so there is of course a chance that I introduced new bugs. Further testing encouraged and much appreciated!
