### ISSUE TITLE
variable names of rules

### ISSUE THREAD

**Issue by KihongHeo** [Z3Prover/z3#5613]
Hi,

I declare variables and rules like 
```ocaml
let v1 = Z3.Arithmetic.Integer.mk_const_s z3ctx "Name1" in
let v2 = Z3.Arithmetic.Integer.mk_const_s z3ctx "Name2" in
let vars = [v1; v2] in
let cons = (* some expressions *)
let r =  Z3.Quantifier.mk_forall_const z3ctx vars cons None [] [] None None  in
Z3.Fixedpoint.add_rule solver r None
```

Although I give the names of `v1` and `v2` as `Name1` and `Name2`, the corresponding smt2 file has default names like
```smt2
(declare-var A Int)
(declare-var B Int)
(rule ... A ... B ...)
```

How can I get the names I give in the smt2 file?

**Comment by agurfinkel** [comment]
The names are cached at the quantifier during `mk_forall_const`, but the subsequent transformations in the fixedpoint object do not preserve them. Preserving the names is non trivial since name clashes may make the result unsound. Using fresh names each time is safer and easier. So that is what the code is doing.
