### ISSUE TITLE
Z3_get_lstring now adds escaping of some bytes.

### ISSUE THREAD

**Issue by carstimon** [Z3Prover/z3#5615]
For https://github.com/Z3Prover/z3/issues/2286 the function Z3_get_lstring was introduced, and its documentation says it returns an unescaped string. We use this in the C++ API via "get_string" which was introduced in a [second commit](https://github.com/Z3Prover/z3/commit/082a0f4df49ee06a28dd702448e6ef06b0ed927a). Our team uses this function to get the string in a C++ program, and we need to get the string to be exactly the string produced by z3 (e.g. if we are asserting the length is 3 we expect the length of the produced string to be 3). Furthermore, the result is now ambiguous: "\u{a}" could mean that Z3 found the one-character string "\n" or the 5 character string "\u{a}".

As of [this commit](https://github.com/Z3Prover/z3/commit/fc8dfe3e402d6407ac08d5bd3b2b5736b2e154bb) and [this commit](https://github.com/Z3Prover/z3/commit/90f98d5791a1c21a8804a26524df405d77c85ced) the function now does escaping. In particular `c.string_val("\n", 1).get_string() == "\n"` is no longer true. Is there a version to preserve the round-trip?

I don't have the context of the first commit that escaped non-ascii bytes, but I would expect that that round trip works for even unicode if that is now supported.

**Comment by NikolajBjorner** [comment]
I updated the C++ API by removing the "escaped" getter because they are both escaped (and there was another bug in one of the escape conversions to fix). There is a new function get_wstring() that returns a vector of unsigned. I am not sure if there is any more useful API (maybe one of the C++ versions for building Unicode strings works, but wchar definitely doesn't have enough bits with only 16).
