### ISSUE TITLE
[consolidated] issues in floating point

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#5621]
z3 4cfc73779adec4dc4d37b16
~~~~
(set-option :trace true)
(declare-fun fpv6 () Float32)
(assert (fp.leq fpv6 (_ +zero 8 24)))
(push)
~~~~
~~~~
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 414
UNEXPECTED CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

**Comment by alexanderjsummers** [comment]
Hi @NikolajBjorner,

I'm very sorry to read about the issues in the tracing code - I'm not sure I fully understand them yet, but would like to. I'll send you an email - hopefully we could set up a call about what would be most useful for maintaining this workflow in the future. I'm happy to contribute code personally if that would be useful!

I don't know much about the subsequent work in the diagram, but your support back when we were working on the Axiom Profiler was certainly critical to us in getting the necessary information reliably into the tool, and I really appreciate it. I know that a few people are using the Axiom Profiler with Z3 and have found it very helpful since, too.

Thanks, Alex

**Comment by NikolajBjorner** [comment]
The main issue is that the tracing code is brittle. Some blame can be cast on pre-existing z3 code, but I found it brittle to evolve when it requires two calls, as illustrated with the example above, for a single trace entity. There are ways in C++ to live with requirements of this form (not sure why it should have been a requirement in the first place to have these being/close entities given that enode creation just tells the tracer what node identifiers expand into). So I ended up introducing a scoped class to deal with many of the two-calls-to-tracing-sprinkled-across-many-lines occurrences. My shorthands are accumulated in smt_theory.h. Also, you decided to trace formulas, not in clausal form but at some higher level. For example, if z3 generates two clauses (a or !b), (b or !a), then you trace (a <=> b) in some cases. Maybe it looks better in your front end, but you put these transformations all the way into the leaves (the place where the clauses are produced). Again a brittle approach because you will just miss some other places where clauses encode more succinct formulas and then the trace functionality also ends up creating new expressions that are created only during trace mode. Creating new expressions influences search so z3 can behave differently with or without tracing. You don't want to push complexity down into the leaves. There has to be some software engineering curriculum that contains material along these lines.
A desired state would have characteristics, such as:
1. each trace entity uses a single call into a trace abstraction. 
2. the trace abstraction hides the tests whether tracing is enabled.
3. tracing does not introduce new expressions. 
4. tracing happens in fewer places (moving tracing from each theory to the single place that creates theory axioms?)
5. It is dumb and simple.
