### ISSUE TITLE
Wrong includedir returned by pkg-config on Fedora

### ISSUE THREAD

**Issue by torokati44** [Z3Prover/z3#5659]
On Fedora 35 (was already happening on 34), I get this:
```
$ pkg-config --cflags z3
-I/usr/usr/include/z3
```

That `/usr/usr` part is not right.

The `/usr/lib64/pkgconfig/z3.pc` file on my system starts with:
```
prefix=/usr
exec_prefix=/usr
libdir=${exec_prefix}/lib64
sharedlibdir=${exec_prefix}/lib64
includedir=${prefix}//usr/include/z3
```

And from the first and last lines of this snippet, it's understandable why.

I'm not sure if it's because of how Z3 is packaged for Fedora, or if the cause is in the sources themselves, so I started by reporting it here.

**Comment by NikolajBjorner** [comment]
Seems to be due to: 
https://github.com/Z3Prover/z3/commit/ed44a44579ff2ab3c08cf346a9516167333636fb#diff-460ae5d9a7423567b629f403bd6f017c325a0726e88c95a9e9b3c28be1a3159a

@FabianWolff

**Comment by FabianWolff** [comment]
`CMAKE_INSTALL_INCLUDEDIR` is set to `%{_includedir}` in the Fedora package, which [apparently](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch22s02s03.html) expands to an absolute path, i.e. `/usr/include`, while my change assumed that it would be _relative_ to the prefix, which is also what the CMake documentation [suggests](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html), although admittedly absolute paths are allowed there, too.

Therefore, one solution would be for the Fedora package to use a relative path instead. As you can see, it is already doing this for `CMAKE_INSTALL_LIBDIR`, because `libdir` and `sharedlibdir` are correct.

Otherwise, we could replace `${prefix}/@CMAKE_INSTALL_INCLUDEDIR@` with `@CMAKE_INSTALL_FULL_INCLUDEDIR@`, and similarly for the other variables in `z3.pc.cmake.in` (this most likely won't work if `DESTDIR` is set as an environment variable when `make install` runs, but the current `z3.pc.cmake.in` doesn't handle this either, I think).

**Comment by NikolajBjorner** [comment]
what is the next step to resolve this issue?

**Comment by NikolajBjorner** [comment]
I am not sure what to do with this given that it affects two different platforms that are only tested with the BVT. 
If you have a way to update azure-pipelines.yaml or nightly.yml with BVT tests or add a GitHub action that tests the installations on the relevant platforms it would be great.

**Comment by torokati44** [comment]
I was still able to reproduce this earlier today on Fedora 37, but no longer after updating to Fedora 38.
Whoever fixed it, thanks!
