### ISSUE TITLE
Assertion violation while using Z3 python libraries in multithreaded application

### ISSUE THREAD

**Issue by wburton-intel** [Z3Prover/z3#5666]
I received the following error message while solving several predominantly bitvector related expressions in different threads in my application:
ASSERTION VIOLATION
File: D:\a\1\s\src\ast/rewriter/rewriter_def.h
Line: 213
UNEXPECTED CODE WAS REACHED.
Z3 4.8.12.0
Each thread has a completely separate context and is working on solving a series of expressions generated automatically from a symbolic representation of a series of x86 instructions. This means I have no good way of triggering the issue on demand, so I am primarily reporting this for informational purposes as my fix will be to create separate processes for each solver instance.

The most recent logged state of my two solver instances was as follows:

Thread 1:
[Solver] Simple EQ: Not(Con_0xafafaf0cL == 3221225485)
[Solver]   Simple 1: Or(Not(Or(ULE(2239204, Con_0xafafaf0cL),
          And(Extract(31, 22, Con_0xafafaf0cL) == 0,
              ULE(Extract(21, 0, Con_0xafafaf0cL), 2239103)))),
   Con_0xafafaf0cL == 2239204)
[Solver]   Simple 2: Con_0xafafaf0cL == 2239104
[Solver]   Simple 3: Not(Mem_0xefefef00 == 17168)
[Solver]   Simple 4: Not(Con_0xafafaf0cL == 3221225485)

and thread 2:
[Solver] Simple EQ: Or(ULE(2239204, Con_0xafafaf0cL),
   And(Extract(31, 22, Con_0xafafaf0cL) == 0,
       ULE(Extract(21, 0, Con_0xafafaf0cL), 2239103)))
[Solver]   Simple 1: Or(ULE(2239204, Con_0xafafaf0cL),
   And(Extract(31, 22, Con_0xafafaf0cL) == 0,
       ULE(Extract(21, 0, Con_0xafafaf0cL), 2239103)))

Both threads are operating on identically named variables with very similar values as they are generated by different runs through the same source program. ULE is unsigned less than or equal, all variables are BitVectors of length 32 bits. According to the logs it appears that one thread was in the process of building an AST, while the other thread was in the process of logging a model that had been solved.

Hope that helps.

**Comment by NikolajBjorner** [comment]
It has to be because an expression got built based on a context not owned by the thread. 
For the python bindings, there is a _default_ global context for single threaded use. The global context is handy because it doesn't have to be passed in whenever building a base expression (expression without arguments). When building an expression with arguments, the various expression building functions should, unless they have been implemented incorrectly, inherit the context of the arguments (the arguments should all have the same context). 
The python bindings goes some way of checking these conditions, but maybe not all the way and this is where bugs in the client application end up only triggering deeper inside z3. There is no great way of debugging this. You can instrument your code to retrieve ctx_ref() from each of the expressions and solvers you create and check if they are the same within the thread.

**Comment by NikolajBjorner** [comment]
I will have to close it as a no-repro. You should double check the Context usage between your threads.
