### ISSUE TITLE
Z3 error "ASSERTION ERROR"

### ISSUE THREAD

**Issue by eagleman2** [Z3Prover/z3#5684]
I wrote a file to solve a magic square of size 6x6. I already have written and gotten correct results for a 3x3, 4x4 and 5x5 square. However, when I did the same thing for a 6x6 square, I received an error that I have no clue how to decipher. I attached the text file I ran with z3 and the error I received.
![z3Issue](https://user-images.githubusercontent.com/62881041/143462822-7380be9c-449d-4925-b0ad-c20c9f6e8dd9.png)
[6x6MagicSquare.txt](https://github.com/Z3Prover/z3/files/7603781/6x6MagicSquare.txt)

**Comment by NikolajBjorner** [comment]
@levnach - I was unable to reproduce this. Are you?

**Comment by levnach** [comment]
No, I could not reproduce it on Windows with the last version. It just runs for about an hour already.  @eagleman2, may I ask how long does it need to run until the repro?

**Comment by eagleman2** [comment]
@levnach, it took me about 2 hours before the error occurred. I tried it again and it didn't show up, so not sure what happened.
Thanks for the help anyways!

**Comment by levnach** [comment]
I let it run and I got a repro. I will try to catch the error in the visual studio debugger. It will probably will take a very long time!

**Comment by levnach** [comment]
It seems  get_freedom_interval_for_column() works correctly but it cannot find a free interval because one of the basic columns, has its low and upper bounds crisscrossed. It is column 505 with low bound 23/2 and upper bound 0. 
The column value is -21.
The bug takes a long time to reproduce, I think more than two hours with the release build. I tried the debug build but it is just too slow. I might try to search for a faster repro with different random seeds.

**Comment by NikolajBjorner** [comment]
it was fixed, 7758b519bc093e37f70b769f90e36e7d76163377
