### ISSUE TITLE
Regression in Optimization between Z3 version 4.8.10 and 4.8.11

### ISSUE THREAD

**Issue by kfriedberger** [Z3Prover/z3#5720]
We noticed a regression problem when updating the Z3 library in our project. We are using the Java-Native API.
The regression appears when querying the approximation value for a maximized symbol after an optimization query.

For example, we try to get the maximum value for `x` with the constraint `x < 1`.
In Z3 version `4.8.10` we got the result value `x:=1` and version `4.8.11/4.8.12/4.8.13` returns `x:=0`.

The following example program computes the value:
```
    long cfg = Native.mkConfig();
    long context = Native.mkContextRc(cfg);
    long optSolver = Native.mkOptimize(context);

    // assume (x < 1)
    long symbol = Native.mkStringSymbol(context, "x");
    long sort = Native.mkRealSort(context);
    Native.incRef(context, sort);
    long x = Native.mkConst(context, symbol, sort);
    Native.incRef(context, x);
    long one = Native.mkInt64(context, 1, sort);
    Native.incRef(context, one);
    long constraint = Native.mkLt(context, x, one);
    Native.incRef(context, constraint);
    Native.optimizeAssert(context, optSolver, constraint);

    // check satisfiability and maximize (x)
    int handle = Native.optimizeMaximize(context, optSolver, x);
    int status = Native.optimizeCheck(context, optSolver, 0, null);

    // get the approximation value
    long vector = Native.optimizeGetUpperAsVector(context, optSolver, handle);
    Native.astVectorIncRef(context, vector);
    long value = Native.astVectorGet(context, vector, 1);

    // the result value is 1 in version 4.8.10, and 1 in newer version.
```

**Comment by NikolajBjorner** [comment]
Note that there is no optimal value over the reals. 
Internally, it computes an optimal of the form 1 - epsilon. Then epsilon gets set to a positive real number. 
4.10 gives an incorrect result. x cannot be 1. The newest versions give the result 0.
Here is a self-contained repro:

```
(declare-const r Real)
(assert (< r 1))
(maximize r)
(check-sat)
(get-objectives)
```

**Comment by kfriedberger** [comment]
Is there a way to access the internal value `1-epsilon`? Can we set `epsilon` via an configuration option?
Would it be possible to provide a method like `upper(handle, epsilon)` that returns a maximum/minimum value for the given handle within the range of a given epsilon?

**Comment by kfriedberger** [comment]
Hi @NikolajBjorner : Any news on the last question?

**Comment by kfriedberger** [comment]
Hi @NikolajBjorner : Any news on the last question?

**Comment by NikolajBjorner** [comment]
The maximization routine used to return infinitesimals where the local maximization routine would find them. 
I am trying to resurrect this functionality with the caveat that it could expose bugs. 
The format with the objective value is now that it is either "infinity" or of the form (a + epsilon*b), where a, b are rationals.

**Comment by levnach** [comment]
## Reopening: the #10052 fix for this regression is unsound and has been reverted

This issue (`maximize r` s.t. `r < 1` returning `0` instead of the strict supremum `1 - ε`) was addressed by PR #10052, which **eagerly commits** the arithmetic (LP) optimization hint whenever it carries a non-zero infinitesimal, before `check_bound()` validation:

```cpp
// opt_solver::maximize_objective  (added by #10052)
if (val.is_finite() && !val.get_infinitesimal().is_zero() && val > m_objective_values[i])
    m_objective_values[i] = val;
```

The premise is *"a non-zero infinitesimal ⇒ an exact, unattainable strict optimum, so the LP hint is authoritative."* That is true for a **pure LP**, but **false when the objective is a shared symbol** with another theory (e.g. the auxiliary uninterpreted function used to encode a `distinct` with > 32 arguments). There the LP relaxation only produces a *hint* that can be a strict **over-estimate**, and #10052 commits it without validation — exactly the class of unsound bound that #10028 (`check_bound`) was introduced to reject.

### Counterexample

`bug.smt2` below: a 6-mark Golomb ruler over integers `x0..x5`, with the `distinct` padded to > 32 arguments so `x5` becomes a shared symbol; the objective is a real `obj` with `obj > x5`.

- Ground truth: `minimize x5` (integer) ⇒ **17**. Since `obj > x5`, the true optimum is **`17 + ε`**.
- With #10052, z3 reports **`(obj (+ 5.0 epsilon))`** — wrong, and **infeasible**: asserting `obj < 6` is `unsat`, and the returned model itself has `x5 = 35, obj = 49.5`, inconsistent with the reported optimum.

```smt2
; See ground truth: (minimize x5) over the same constraints => 17, so obj > x5 => optimum 17 + epsilon.
; With #10052's eager-commit, z3 reports (obj (+ 5.0 epsilon)) -- infeasible (obj < 6 is unsat),
; and inconsistent with its own model (x5 = 35, obj = 49.5).
(set-logic ALL)
(declare-fun x0 () Int)
(declare-fun x1 () Int)
(declare-fun x2 () Int)
(declare-fun x3 () Int)
(declare-fun x4 () Int)
(declare-fun x5 () Int)
(declare-fun d0 () Int)
(declare-fun d1 () Int)
(declare-fun d2 () Int)
(declare-fun d3 () Int)
(declare-fun d4 () Int)
(declare-fun d5 () Int)
(declare-fun d6 () Int)
(declare-fun d7 () Int)
(declare-fun d8 () Int)
(declare-fun d9 () Int)
(declare-fun d10 () Int)
(declare-fun d11 () Int)
(declare-fun d12 () Int)
(declare-fun d13 () Int)
(declare-fun d14 () Int)
(declare-fun d15 () Int)
(declare-fun d16 () Int)
(declare-fun d17 () Int)
(declare-fun d18 () Int)
(declare-fun d19 () Int)
(declare-fun d20 () Int)
(declare-fun d21 () Int)
(declare-fun d22 () Int)
(declare-fun d23 () Int)
(declare-fun d24 () Int)
(declare-fun obj () Real)
(assert (>= x0 0)) (assert (<= x0 50))
(assert (>= x1 0)) (assert (<= x1 50))
(assert (>= x2 0)) (assert (<= x2 50))
(assert (>= x3 0)) (assert (<= x3 50))
(assert (>= x4 0)) (assert (<= x4 50))
(assert (>= x5 0)) (assert (<= x5 50))
(assert (= x0 0))
(assert (< x0 x1))
(assert (< x1 x2))
(assert (< x2 x3))
(assert (< x3 x4))
(assert (< x4 x5))
(assert (distinct (- x1 x0) (- x2 x0) (- x3 x0) (- x4 x0) (- x5 x0) (- x2 x1) (- x3 x1) (- x4 x1) (- x5 x1) (- x3 x2) (- x4 x2) (- x5 x2) (- x4 x3) (- x5 x3) (- x5 x4) (+ 1000 d0) (+ 1000 d1) (+ 1000 d2) (+ 1000 d3) (+ 1000 d4) (+ 1000 d5) (+ 1000 d6) (+ 1000 d7) (+ 1000 d8) (+ 1000 d9) (+ 1000 d10) (+ 1000 d11) (+ 1000 d12) (+ 1000 d13) (+ 1000 d14) (+ 1000 d15) (+ 1000 d16) (+ 1000 d17) (+ 1000 d18) (+ 1000 d19) (+ 1000 d20) (+ 1000 d21) (+ 1000 d22) (+ 1000 d23) (+ 1000 d24)))
(assert (>= d0 0)) (assert (<= d0 100))
(assert (>= d1 0)) (assert (<= d1 100))
(assert (>= d2 0)) (assert (<= d2 100))
(assert (>= d3 0)) (assert (<= d3 100))
(assert (>= d4 0)) (assert (<= d4 100))
(assert (>= d5 0)) (assert (<= d5 100))
(assert (>= d6 0)) (assert (<= d6 100))
(assert (>= d7 0)) (assert (<= d7 100))
(assert (>= d8 0)) (assert (<= d8 100))
(assert (>= d9 0)) (assert (<= d9 100))
(assert (>= d10 0)) (assert (<= d10 100))
(assert (>= d11 0)) (assert (<= d11 100))
(assert (>= d12 0)) (assert (<= d12 100))
(assert (>= d13 0)) (assert (<= d13 100))
(assert (>= d14 0)) (assert (<= d14 100))
(assert (>= d15 0)) (assert (<= d15 100))
(assert (>= d16 0)) (assert (<= d16 100))
(assert (>= d17 0)) (assert (<= d17 100))
(assert (>= d18 0)) (assert (<= d18 100))
(assert (>= d19 0)) (assert (<= d19 100))
(assert (>= d20 0)) (assert (<= d20 100))
(assert (>= d21 0)) (assert (<= d21 100))
(assert (>= d22 0)) (assert (<= d22 100))
(assert (>= d23 0)) (assert (<= d23 100))
(assert (>= d24 0)) (assert (<= d24 100))
(assert (> obj (to_real x5)))
(minimize obj)
(check-sat)
(get-objectives)
```

### Effect of reverting #10052

| benchmark | with #10052 (current master) | after reverting #10052 |
| --- | --- | --- |
| `bug.smt2` (shared symbol) | `(obj (+ 5.0 epsilon))` ❌ infeasible | `(obj 18)` ✅ consistent |
| this issue (`max r < 1`) | `1 - epsilon` ✅ | `0` ❌ (regression returns) |

Reverting #10052 restores soundness on the shared-symbol case but **reintroduces this regression**, so the issue is reopened. A correct fix must preserve the strict single-objective supremum **without** trusting an unvalidated shared-symbol hint — e.g. gate the eager commit on `!has_shared` (pure LP only), or validate the rational part of the hint while keeping the infinitesimal, rather than accepting any non-zero-infinitesimal value outright. The same blind spot applies to the alternative guard proposed in PR #10051 (`check_bound` returning `true` for any non-zero infinitesimal).

**Comment by NikolajBjorner** [comment]
@levnach - is this addressed with latest merge?

**Comment by levnach** [comment]
@NikolajBjorner , yes, after the merge the example above gives 17+eps.
