### ISSUE TITLE
location of binaries in cmake build

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#573]
@delcypher: when building Z3 sources and python, I receive beinaries (and python scripts) in the build directory. When enabling dotnet (Microsoft.Z3.dll), the dll is placed under api\dotnet subdirectory. 
Is this by design?

**Comment by delcypher** [comment]
The code intentionally does that but there are ``FIXME``s there right now

https://github.com/Z3Prover/z3/blob/8ee49d16dfa15ba15e50cbbba5c9c5f79e3e5aed/contrib/cmake/src/api/dotnet/CMakeLists.txt#L206

https://github.com/Z3Prover/z3/blob/8ee49d16dfa15ba15e50cbbba5c9c5f79e3e5aed/contrib/cmake/src/api/dotnet/CMakeLists.txt#L150

The core of the issue is that I couldn't get things to work correctly for "multi-configuration generators" (i.e. Visual Studio) due to some limiations in CMake so in order to make the behaviour consistent between all CMake builds I just put the ``Microsoft.Z3.dll`` in ``src/api/dotnet`` in the build directory.

In hindsight that might not have been the best decision. Perhaps instead

* ``Microsoft.Z3.dll`` should go in the root build directory like ``libz3.so`` does for single configuration generators. For multi-configuration generators a problem will occur where it isn't possible to have multiple versions of ``Microsoft.Z3.dll`` (this means if you change the build type in Visual Studio the old version of ``Microsoft.Z3.dll`` will be overwritten) but we have that problem already in the code in the ``master`` branch. Note this isn't a problem for ``libz3.so`` which is put in its own directory (e.g. ``Debug``) depending on Visual Studio's build type but I currently can't replicate that behaviour for building ``Microsoft.Z3.dll`` in CMake.

* If on Windows and in a single configuration build pass the ``/linkresource:`` flag to mimic what the existing Python build system does. I didn't do this before because ``csc.exe`` is weird. It seems to require the the argument to ``/linkresource`` be a file name and not a path. If you give ``/linkresource:`` an absolute path it does not complain but when an attempt is made to link against a ``.NET`` application against ``Microsoft.Z3.dll`` the copy of ``libz3.dll`` fails...

If these seem like good ideas I can create a PR for them if you'd like.

**Comment by NikolajBjorner** [comment]
cool, thanks. So there is a reason. It took me less than a minute to find the location, so I would say, keep things simple as you find rational.
