### ISSUE TITLE
unexpected unknown result with mbqi/array property fragment

### ISSUE THREAD

**Issue by cp526** [Z3Prover/z3#5767]
Hello!

My understanding is that z3 with mbqi enabled should give reliable true/false answers for queries in the array property fragment. For the example below I am getting 'unknown', with version 4.8.13.

```
(set-option :smt.mbqi true)
(set-option :smt.ematching false)


(declare-datatypes ((|DT| 0)) (((|C1|) (|C2|)))) ;;1
(declare-datatypes 
  ((|R1| 0)) 
  (((|R1| 
      (|R1_unused| (Array Int |DT|)) ;;2
      (|R1_int| Int) 
    )))
)
(declare-const r1 |R1|)
(declare-const a1 (Array Int Int))

(assert 
  (forall ((i Int))
    (=> (<= i (|R1_int| r1))
        (= (select a1 i) 0))))

(assert (= (select a1 5) 0))

(push)
(check-sat)
```

Is this expected? I think this should be in the array property fragment.

The push command, I am guessing switches on a different solver. Is that solver one I should not expect to be powerful enough? Without `push` I get 'sat'.

Curiously, if I remove the record field `R1_unused` from the datatype definition (`;;2`), it also goes through. Same when I remove constructor `C2` from the definition of `DT` (`;;1`).

Thank you very much in advance!

**Comment by 11Tanik** [comment]
We encountered this problem today too. Just with mbqi disabled.
This is the smallest example I was able to produce:

```smtlib
(set-option :smt.mbqi false)
(push 1)
(assert (forall ((x Int)) (= x 42)))
(check-sat)
```
Z3 Version 4.8.13 shows 'unknown' for this file.
But if `(push 1)` is removed Z3 shows 'unsat'.

This has also implications for other tools like [boogie](https://github.com/boogie-org/boogie). Because boogie puts a `push` before assertions it is unable to verify the following file: (that is how we encountered this problem)

```bpl
procedure x() {
    assert (exists x:int :: x == 42);
}
```
Thanks in advance as well!

**Comment by NikolajBjorner** [comment]
assert exists x . x = 42 should translate into checking unsat of the negation, so forall x. x != 42.
Either way, the ematching engine is insufficient for formulas where the bound variables don't occur under (uninterpreted) functions. You will need mbqi. I now added an option calls 'smt.q.elim' that will apply light weight quantifier elimination as pre-processing for the solver so it doesn't depend on push/pop.

```
(set-option :smt.q.elim true)
(set-option :smt.mbqi false)
(push 1)
(assert (forall ((x Int)) (= x 42)))
(check-sat)
```

**Comment by cp526** [comment]
Thanks very much for the quick answer! Just to make sure it doesn't get lost: I guess, the two questions, 11Tanik's and mine, end up being different because of the choice of options: mbqi off vs mbqi on, respectively. 

So as far as I understand, the original question is still open.

Thanks again!

**Comment by NikolajBjorner** [comment]
these are different issues.

11Tanik's isn't a use case for Boogie. I tried to add smt.q.elim as an option to allow the same kind of simplification that makes it work in non-incremental mode yesterday but had to revert it.

Your issue is that MBQI isn't really for ADTs. MBQI as it is now can find models where functions have finite ranges. 
As ADTs get treated as functions, but their ranges are not finite, the setup loops. There are ways to address it/generalize mbqi, but this was never a feature so far.

**Comment by cp526** [comment]
Thanks for the quick answer!

Is any use of ADTs going to be problematic for MBQI, or are there "subsets" of the ADT functionality that are fine? In particular, if the only ADTs we used were (non-recursive) records/tuples (like R1 and unlike DT in my example), would that be OK, or is that not something we could reliably expect to work with MBQI in combination with arrays?

What about arbitrary combinations/nesting of records/tuples and arrays -- e.g. an array of records, where each of those records again contains arrays of some other record sort?

Thanks!

**Comment by NikolajBjorner** [comment]
Sounds like a mid-term test.
MBQI wasn't actually designed for the theory of arrays. It has since been retrofitted to handle main cases as it gets invoked a lot with formulas using arrays.
It works with "arrays" as encoded using first-order axioms.
Regarding ADTs: yes records and enumeration types and combinations that are non-recursive work and also along stratifications.
Arrays of finite ADTs with arrays: in principle. The bugs I see are about corner cases and the interaction matrix complexity not about the basic instantiation approach.
Note that if you have arithmetic variables under an ADT function it breaks some assumptions about finiteness of function ranges. It could work because the ADT function can then only be compared with the same ADT and not nested.

**Comment by cp526** [comment]
Thanks very much! 

Even though it wasn't designed for it, is it still true that MBQI is a decision procedure for the array property fragment as stated in
[Z3's release notes](https://github.com/Z3Prover/z3/blob/56d3718cde7260d54c34e1420ef11a3436671139/RELEASE_NOTES#L689) ? If so, is there a clearly defined subset of the SMT language that is guaranteed to be decided by z3 with mbqi?

Apologies, some small questions to understand your answer:
1. What does finiteness of ADTs mean here? For example, would a record sort with a single member/component of integer sort (Z) be finite in this sense?
2. RE: "It works with "arrays" as encoded using first-order axioms." Is this referring to a scenario where arrays are directly modelled as uninterpreted functions? Or does it also work with "arrays as values" (constants of array sort)?
3. I did not follow your remark about arithmetic variables, sorry. Are ADT functions the constructors/destructors/recognisers that are part of the data-type declaration?

**Comment by NikolajBjorner** [comment]
Not sure I can answer details of the questions without spending some time to ensure the answers are precise and accurate, 
but the main statement is that what is advertised as the array property fragment in papers and the essentially uninterpreted fragment are covered.

Your example from above uses an array of DT. It causes the instantiation engine to create a stream of instances. It wasn't designed for this class of formulas.

**Comment by cp526** [comment]
Thanks very much!  I will then investigate whether avoiding non-record type definitions on our end makes the problem go away.

Thanks!

**Comment by cp526** [comment]
For the following cut-down example I still get z3 returning unknown, now even without datatype definitions:

```
(set-option :auto_config false)
(set-option :smt.auto_config false)
(set-option :smt.arith.solver 2)
(set-option :smt.mbqi true)
(set-option :smt.ematching false)


(declare-const a (Array Int Int))
(assert (forall ((i Int)) (=> (>= i 0) (= (select a i) 0))))
(assert (= (store a 0 0) a))
(check-sat)
```
