### ISSUE TITLE
User propagator and arithmetic solver

### ISSUE THREAD

**Issue by imarmanis** [Z3Prover/z3#5768]
Hi, what is the correct way to specify the arithmetic solver when using a solver with a user propagator?

Following [this](https://stackoverflow.com/a/30356879), I have tried 
```
z3::context c;
z3::solver s(c, (struct z3::solver::simple) {});
z3::params p(c);
p.set("auto_config", false);
p.set("smt.arith.solver", (unsigned) 1);
s.set(p);
```
However, I doubt that the arithmetic solver parameter is respected, since
I see absolutely no difference in performance when trying different values.

I'm using z3 version 4.8.14.

**Comment by NikolajBjorner** [comment]
The user propagator only applies to bit-vectors and Booleans at this point. It does not propagate fixed values for arithmetic and it is not tested otherwise.

The reason it can't propagate fixed values for arithmetic is that in general very few integer/real variables are fixed to a value during search. Their values are opaque to the truth values of atoms, only their bounds are going to be fixed during search. So, designing a user propagator for fixed values with integers/reals means something different. Before I know of a good use case it isn't supported. It is possible the propagator can use the equality and disequality callbacks to tell the propagator when two variables are equal. It may also be possible to use the fixed-value callback in a final check where the arithmetic solver fixes values of all variables. Internally, the sequence solver uses this. So far this is not available.

**Comment by imarmanis** [comment]
I'm not adding any variables for the user propagator to track apart from bools.
My issue is that, additional to the variables tracked by my propagator,
my problem includes some integer variables that take part in constraints of the
form ```x < y```, and I would like to specify which arithmetic solver will be used
to solve them.

**Comment by NikolajBjorner** [comment]
try smt.auto_config=false?

**Comment by imarmanis** [comment]
Added ``` p.set("smt.auto_config", false)```, I'm still observing the same thing.

I don't know if this is relevant, but when I print the formula,
the ```x<y``` constraints are rewritten as ```(not (>= (+ x (* (-1) y)) 0))```.
Does this hint that the simplex solver is being used?

**Comment by NikolajBjorner** [comment]
This is how the formula looks like after pre-processing.
Suppose you want to track x < y and pre-processing rewrites it. There is no way to relate these two formulas.
You have to create a proxy variable that does not get rewritten and assert it is equivalent to what you want to track.

**Comment by imarmanis** [comment]
However, when I explicitly set the logic to IDL (```z3::solver s(c, "QF_IDL");```),
the ```x < y``` constraints are not rewritten (but the user propagator does not work in this case).

Regarding the issue, is there any reason that would lead to "smt.arith.solver=1" being disregarded
when the solver has a user propagator, and is initialized as ```z3::solver s(c, (struct z3::solver::simple) {})```,
given that auto_config=false, smt.auto_config=false are also set?

**Comment by NikolajBjorner** [comment]
The only safe approach is to use proxies. There are no contracts that say a theory term is not going to be changed.

**Comment by imarmanis** [comment]
In the end, what I was trying doesn't seem to be possible. Apart from the ```x<y``` constraints,
my problem also includes integer arithmetic constraints.
When I was explicitly specifying a logic, the smt.arith.solver=1 parameter
was respected and z3 was correctly returning UNKNOWN, it was not a problem with the user propagator.

The only issue, if any, is that when the logic is omitted (```z3::solver s(c, (struct z3::solver::simple) {})```),
the smt.arith.solver=1 parameter is disregarded, and the simplex solver is probably used to solve it.

Sorry for the confusion.

**Comment by NikolajBjorner** [comment]
You can't use arith.solver=1 to bypass this problem.
I might need to fix the user-propagator to introduce proxies on the fly instead of assuming the user manages them.
I don't have a test case for this, but the idea is similar to how we allow assumptions to be arbitrary formulas and can still track them.
