### ISSUE TITLE
Get some randomness with Java API

### ISSUE THREAD

**Issue by espresso-if** [Z3Prover/z3#5772]
Hi

I'm working with Kotlin and the Java API of z3 (version 4.8.14) to create a testbench that extract sample inputs using given predicates. I have found multiple posts indicating that z3 can provide some randomness regarding the variable values of the model.
- https://stackoverflow.com/questions/35352624/how-to-get-random-results-from-microsoft-z3
- https://stackoverflow.com/questions/24327987/z3-randomness-of-generated-model-values/24369051#24369051

The problem is that I constantly get the same result.

My test program is
``` kotlin
  println( Native.getFullVersion())
  val ctx = Context(mapOf("proof" to "true", "model" to "true"))
  val expr = ctx.mkLe(ctx.mkAdd(ctx.mkIntConst("x"),ctx.mkInt(1)),ctx.mkInt(4))
  println("Expr: $expr")
  val s = ctx.mkSolver()
  val p = ctx.mkParams()
  p.add("auto_config", false)
  p.add(":random_seed", 100)
  p.add(":sat.random-seed", 100)
  p.add("arith.random_initial_value", true)
  s.setParameters(p)
  s.add(expr)

  for (i in (1..5)) {
      println("iteration $i")
      p.add(":random_seed", i*100)
      p.add(":sat.random-seed", i*100)
      val q: Status = s.check()
      q shouldBe Status.SATISFIABLE

      println(s.model)
  }
```
The resulting out put is:

        Z3 4.8.14.0
        Expr: (<= (+ x 1) 4)
        iteration 1
        (define-fun x () Int
          3)
        iteration 2
        (define-fun x () Int
          3)
        iteration 3
        (define-fun x () Int
          3)
        iteration 4
        (define-fun x () Int
          3)
        iteration 5
        (define-fun x () Int
          3)

Even if I try to use the smt2 statements from the stackoverflow posts (using https://www.philipzucker.com/z3-rise4fun/), I get the same result for every `get-model` statement.

Is there a misunderstanding on my part or is this even expected behavior?

Thank you in advance

**Comment by NikolajBjorner** [comment]
The arithmetic solvers use dual simplex or other optimization algorithm. They set feasible values at the vertices of the simplex.

**Comment by espresso-if** [comment]
I'm sorry to bother you, but is there a way to get some randomness?
Honestly I am confused because the stack overflow posts indicated that there is way.

**Comment by wintersteiger** [comment]
What Nikolaj meant to say is that on this particular formula, the solver will always find the same solution.

In general, no, there is no way to get any form of numbers that satisfy any statistical randomness measures. The various solvers will sometimes make (pseudo) random decisions depending on the random seed, but there is no guarantee about the type of randomness you get from that at all and it is often trivial. In many cases it means that it takes a different branching decision, but not a different variable assignment. So, performance changes, but the models don't. Also, Z3 will often not even reach the point at which it has to make any decision at all, or where it will always chose zero instead of a random value, in which case it will always find the same model regardless of the random seed.

**Comment by espresso-if** [comment]
Ok thank you.
I have found the following article (maybe it is interesting for you or other readers)
https://alastairreid.github.io/tracing-smt3/
Linked papers:(https://www.cs.rice.edu/~vardi/papers/cav13.pdf, https://www.cs.rice.edu/~vardi/papers/cav16tk.pdf
