### ISSUE TITLE
Z3 build scripts assume there's a single ocamlfind path location

### ISSUE THREAD

**Issue by protz** [Z3Prover/z3#5814]
This assumes the output of `ocamlfind printconf path` is a single entry: https://github.com/Z3Prover/z3/blob/474949542e854b2286e09973d3357dbdcc024b45/scripts/mk_util.py#L1998

This is incorrect: the user may export OCAMLPATH to inform ocamlfind that there are multiple directories in which to find packages. For instance, on my machine:

```
jonathan@absinthe:~/Code/z3 (master) $ ocamlfind printconf path
/Users/jonathan/Code/everest/fstar/bin
/Users/jonathan/.opam/default/lib
```

This generates an incorrect `ocamlmklib` invocation:

```
ocamlmklib -o api/ml/z3ml -I api/ml -L. api/ml/z3native_stubs.o api/ml/z3enums.cmo api/ml/z3native.cmo api/ml/z3.cmo -lz3 -lstdc++ -ccopt -L/Users/jonathan/Code/everest/fstar/bin /Users/jonathan/.opam/default/lib/stublibs -dllpath /Users/jonathan/Code/everest/fstar/bin /Users/jonathan/.opam/default/lib/stublibs
```

which in turn makes the build fail:

```
ocamlmklib -o api/ml/z3ml  -I api/ml -L. api/ml/z3native_stubs.o api/ml/z3enums.cmo api/ml/z3native.cmo api/ml/z3.cmo  -lz3 -lstdc++  -ccopt -L$(ocamlfind printconf path)/stublibs -dllpath $(ocamlfind printconf path)/stublibs
Don't know what to do with /Users/jonathan/.opam/default/lib/stublibs
```

Proposed patch:

```diff
diff --git a/scripts/mk_util.py b/scripts/mk_util.py
index 042e6af46..e3319c257 100644
--- a/scripts/mk_util.py
+++ b/scripts/mk_util.py
@@ -1995,7 +1995,7 @@ class MLComponent(Component):
 
             LIBZ3 = LIBZ3 + ' ' + ' '.join(map(lambda x: '-cclib ' + x, LDFLAGS.split()))
 
-            stubs_install_path = '$$(%s printconf path)/stublibs' % OCAMLFIND
+            stubs_install_path = '$$(%s printconf path | tail -n 1)/stublibs' % OCAMLFIND
             if not STATIC_LIB:
                 loadpath = '-ccopt -L' + stubs_install_path
                 dllpath = '-dllpath ' + stubs_install_path
```

Thanks,

Jonathan

**Comment by NikolajBjorner** [comment]
Are you going to add a pull request or asking for more input?

**Comment by protz** [comment]
If you're ok with my analysis feel free to go ahead and commit the patch :-).

**Comment by NikolajBjorner** [comment]
@k4rtik - what do you think about the patch from this sketchy character?

**Comment by k4rtik** [comment]
I think we are really calling in @arbipher here to look at this.

**Comment by arbipher** [comment]
I agree this may cause problems. I didn't notice `ocamlfind printconf path` can have multiple result, as shown in your case.
I check with ocamlfind [manual](http://projects.camlcity.org/projects/dl/findlib-1.9.3/doc/ref-html/r17.html) and [src](https://github.com/ocaml/ocamlfind/blob/6c8438c13b68e5cbc48ea558906046e38a7f8d72/src/findlib/frontend.ml?_pjax=div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20%3E%20main#L2426) (`List.iter print_endline (Findlib.search_path())`). There is no argument to filter just one result for `ocamlfind printconf path`.

The fix uses the path to find `stublibs` and the path it's used for linking. I would also ask K4rtik's question and then I test it on my own (by export `OCAMLPATH` and see the result of the command).
I have spent some time to read its source of ocamlfind, the result of the command comes from `env_search_path @ sys_search_path` ([src](https://github.com/ocaml/ocamlfind/blob/6c8438c13b68e5cbc48ea558906046e38a7f8d72/src/findlib/findlib.ml?_pjax=div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20%3E%20main#L289)) where:
- `env_search_path` is set by reading `OCAMLPATH`
- `sys_search_path` is the path defined in the findlib config file. See this [comment].(https://github.com/ocaml/ocamlfind/blob/6c8438c13b68e5cbc48ea558906046e38a7f8d72/src/findlib/findlib.mli?_pjax=div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20%3E%20main#L66) 

The conf file can be found by `ocamlfind printconf conf`. I am thinking since the task is to get the `path`, maybe we could directly read from the config file instead of getting from the command. The source for the information is the same.

**Comment by k4rtik** [comment]
Perfect, `destdir` does seem like an appropriate solution. Excellent analysis, @arbipher!

**Comment by protz** [comment]
Thanks for the improved solution -- best not to trust patches from sketchy characters indeed!

**Comment by NikolajBjorner** [comment]
and meanwhile...

![image](https://user-images.githubusercontent.com/3085284/153057581-b97a1838-c3d7-4d70-8f10-c9a2d59e7ca2.png)

**Comment by arbipher** [comment]
lol, as the current maintainer of the z3-ocaml on opam, I know two faces in the photo!
