### ISSUE TITLE
Changing the inlining parameters results in the invalid model

### ISSUE THREAD

**Issue by AnzhelaSukhanova** [Z3Prover/z3#5913]
Hello!

For the instance
```
(set-logic HORN)

(set-option :fp.xform.inline_linear_branch true)
(set-option :fp.xform.inline_eager false)

(declare-fun P1 (Int Int) Bool)
(declare-fun P2 (Int Int Int) Bool)
(declare-fun P3 (Int) Bool)
(declare-fun P4 (Int Int) Bool)

(assert (forall ((v1 Int) (v2 Int))
  (=> (and (P4 v1 v2))
      (P3 v1))))

(assert (forall ((v1 Int) (v2 Int))
  (=> (and (= v2 0)) (P4 v2 v1))))

(assert (forall ((v1 Int) (v2 Int) (v3 Int))
  (=> (and (P1 v1 v3) (P4 v3 v2))
      (P2 v1 v3 v2))))

(assert (forall ((v1 Int) (v2 Int))
  (=> (and (P3 v2))
      (P1 v1 v2))))

(check-sat)
(get-model)
(exit)
```
z3 returns
```
sat
(
  (define-fun P3 ((x!0 Int)) Bool
    (= x!0 0))
  (define-fun P1 ((x!0 Int) (x!1 Int)) Bool
    true)
  (define-fun P4 ((x!0 Int) (x!1 Int)) Bool
    true)
  (define-fun P2 ((x!0 Int) (x!1 Int) (x!2 Int)) Bool
    true)
)
```
If in the first clause v1 != 0, this interpretation is incorrect.
With fp.xform.inline_eager in true or fp.xform.inline_linear_branch in false, z3 returns correct model.

**Comment by NikolajBjorner** [comment]
In this case, P3 is in-lined by the clause for P4 (v2 = 0). 
But P4 is sent to SPACER and set to true. 
SPACER does not see P3 or the dependency of P3 on P4.
Unclear if a "simple" patch is possible based on the implementation.
The model transformer has to ensure that when deleting a rule P3(x) :- P4(x,y), then the interpretation for P3 should contain P4.
It deletes the rule without ensuring this, it just in-lines P3(x) :- x = 0. And then ensures that P3(x) contains at least x = 0.
At this point, it serves possibly better as a use case for developing a formal account for model reconstruction than pointing to something immediately actionable in the code (because model reconstruction there was an after-thought I don't think it is the best idea to keep patching it).
In principle, model reconstruction takes a trail of deleted and added Horn rules and updates the interpretation for predicates in the head. In practice, all deleted rules have to be tracked correctly and rules that involve recursion would need to be accounted for. Shortcuts may be possible if predicates are guaranteed to be unreachable and therefore can be interpreted as "true".

**Comment by NikolajBjorner** [comment]
moved to #5920
