### ISSUE TITLE
Z3 C++ API fpEq

### ISSUE THREAD

**Issue by zwimer** [Z3Prover/z3#5948]
Is there a reason that the Z3 C++ API breaks `fpa_eq` out from normal equality? For other operators like `<=`, `>`, etc, it does not do this. Links:

Notice the lack of `Z3_mk_fpa_eq` in the `operator==`:
```
    inline expr operator==(expr const & a, expr const & b) {
        check_context(a, b);
        Z3_ast r = Z3_mk_eq(a.ctx(), a, b);
        a.check_error();
        return expr(a.ctx(), r);
    }
```

We instead define a separate function `.fp_eq`: https://github.com/Z3Prover/z3/blob/bd70c79b255d2c0e43bea6cb256a9251b9b9f5ea/src/api/c%2B%2B/z3%2B%2B.h#L1958

Yet in `operator<=` you can see everything is within one function:
https://github.com/Z3Prover/z3/blob/bd70c79b255d2c0e43bea6cb256a9251b9b9f5ea/src/api/c%2B%2B/z3%2B%2B.h#L1805

Is this intentional?

**Comment by NikolajBjorner** [comment]
Seems right:

smtlib defines fp.eq that has different semantics from equality: 

```
 "(fp.eq x y) evaluates to true if x evaluates to -zero and y to +zero, or vice versa.
  fp.eq and all the other comparison operators evaluate to false if one of their
  arguments is NaN.
 "
```

See http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml

So == is equality, and fp.eq is a separate relation.

The relations <, <= can be overloaded because there are no two different readings of them for floating points.
