### ISSUE TITLE
OCaml: GC tweaks are wrong

### ISSUE THREAD

**Issue by giltho** [Z3Prover/z3#5970]
Hello,

Following an update of Z3 from 4.8.7 to 4.8.15, the execution of our verification got around ***4 times slower***.
Given that calls to Z3 are around 30-40% of our execution, I'm expecting that means calls to Z3 got ~8 times slower.

I spent a few hours finding the issue, and I found out that [this is the PR that made everything slower](https://github.com/Z3Prover/z3/pull/5600).

Agreed our usage of Z3 is very suboptimal (non-incremental, having one solver that we reuse by resetting on every call), but such a slowdown means that the change is wrong.

@c-cube, any idea? This change leaves us unable to upgrade past 4.8.12
I'd be happy running our benchmark on any change you make

**Comment by c-cube** [comment]
Ah, interesting, yes. We also have a slowdown, but it did save a lot of RAM (:weary:). It was done with a 4.08 switch I think, and the GC has changed since in the ways it manages off-heap items. If you have time to tweak things yourself and see if it improves runtime I think it'd be very useful.

cc @Bronsa on that one, too :)
