### ISSUE TITLE
Deadlock in `scoped_timer`

### ISSUE THREAD

**Issue by bmourad01** [Z3Prover/z3#5990]
I seem to be encountering deadlock at this point in the `scoped_timer`

https://github.com/Z3Prover/z3/blob/ec57d3b15c0e0f3a7192bd3c0213a9ab3b8a7084/src/util/scoped_timer.cpp#L54

Looking through the history, I see a relevant PR (#5371). However, this issue still appears to be present in the upstream version.

For what it's worth, I'm using Z3 via the OCaml bindings.

**Comment by NikolajBjorner** [comment]
@nunoplopes - the appverifier allows to enable cuzz.

**Comment by nunoplopes** [comment]
@bmourad01 can you share a repro, please? Preferably without using ocaml bindings.
Otherwise I can't debug it.

**Comment by NikolajBjorner** [comment]
Have you run the existing unit tests using appverifier?

**Comment by nunoplopes** [comment]
I've never used appverifier. I don't have MSVC installed either. I'm a bit short on computing resources at the moment.

**Comment by NikolajBjorner** [comment]
It is either pre-installed as "appverif" or can be added.
https://www.microsoft.com/en-us/research/project/cuzz-concurrency-fuzzing/

**Comment by NikolajBjorner** [comment]
Maybe @bmourad01 has an easier time running this (it assumes Windows) directly from the ocaml app, and instrument some logging to the scoped_timer class to produce a trace that can help understanding what is going on.
4 decades of CAV, model checking, fuzzing, verification, concurrent separation logic, ...

**Comment by bmourad01** [comment]
I'm having a hard time coming up with a minimal example that reproduces the problem. Will update if that situation changes.

**Comment by nunoplopes** [comment]
Please reopen if you are able to provide more information. Thank you!

**Comment by fkohlgrueber** [comment]
I ran into the same issue yesterday and was able to reproduce it with a small example program (see [here](https://github.com/fkohlgrueber/z3/commit/eac7dfa1af9fc2a477fd53dbd8fda2a64b12b3f1)):

```c++
for (int i = 0; i< 1000000; i++) {
    if (i % 10 == 0) {
        std::cout << i << std::endl;
    }
    test_scoped_eh eh;
    auto delay = rand() % 20 + 1;
    scoped_timer sc(100, &eh);
    auto end = std::chrono::steady_clock::now() + std::chrono::milliseconds(delay);
    while (std::chrono::steady_clock::now() < end) {
    }
}
```

Running this example (debug compile) on my machine deadlocks quickly. Most of the time it just takes a couple of seconds.

I took a closer look at the implementation of `scoped_timer` and found the issue. When reusing an existing thread for a new `scoped_timer`, the following scheduling results in a deadlock:
- starting point: worker thread is before line 73, main thread on line 113
- worker thread sets `s->work` to `IDLE`
- main thread locks `workers`, completes destructor
- main thread enters `scoped_timer` constructor and executes until line 96
- worker thread starts with next loop iteration and executes until `s->work > IDLE` (which is false)
- main thread completes the constructor (setting `s->work` to `WORKING` and executing `s->cv.notify_one();`
- worker thread starts waiting on the condition variable

At this point, the worker thread is "stuck" as it has missed the notification from the main thread. The main thread will continue to run until it eventually busy-loops infinitely in the destructor of `scoped_timer` (line 113).

The root cause of the deadlock is that the value of `s->work` can change between the worker thread checking it and waiting again. For some more elaborate description of the issue, see this SO answer: [link](https://stackoverflow.com/a/17102100/19290937)

As far as I can see, the deadlock can be fixed by acqiuring the `workers` lock before updating `s->work` in the `scoped_timer` constructor. This should make sure that the value can't change while the worker thread is awake. After the main thread releases the lock on `workers`, the worker thread will see the updated value when it is woken up the next time. The main thread makes sure that that happens with the `s->cv.notify_one();` call.

```diff
diff --git a/src/util/scoped_timer.cpp b/src/util/scoped_timer.cpp
index e8a72e2..4d28e90 100644
--- a/src/util/scoped_timer.cpp
+++ b/src/util/scoped_timer.cpp
@@ -96,7 +96,9 @@ scoped_timer::scoped_timer(unsigned ms, event_handler * eh) {
     s->ms = ms;
     s->eh = eh;
     s->m_mutex.lock();
+    workers.lock();
     s->work = WORKING;
+    workers.unlock();
     if (new_worker) {
         s->m_thread = std::thread(thread_func, s);
     }
```

There's probably better ways to do this as the change above would acquire/release the `workers` lock twice. It's probably faster to simply extend the critical section in case of reusing a thread until the `scoped_timer_state`'s values have been set.

Btw: Is there a specific reason why each instance of `scoped_timer` is backed by a thread? Wouldn't it be possible to have a single thread that maintains a (sorted) list of all active tasks and triggers the event handlers at the right point in time? I could imagine that this would be easier and probably also more efficient.

Not sure whether you're getting notifications for comments on a closed issue, so... @nunoplopes @NikolajBjorner @bmourad01

**Comment by nunoplopes** [comment]
cc @regehr

**Comment by nunoplopes** [comment]
Interesting, I can reproduce the problem, but only in a debug build. The release build doesn't repro for me.
Trace:
```
#0  sched_yield ()
#1  __gthread_yield ()
#2  std::this_thread::yield ()
#3  scoped_timer::~scoped_timer (this=0x7ffe3bdf1a60, __in_chrg=<optimized out>)
    at ../src/util/scoped_timer.cpp:114
```

**Comment by nunoplopes** [comment]
FWIW, it's true we could have a single thread with a list of timers, etc. In practice, the users of multi-threaded Z3 are not that many, so most of the times we have a single timer thread. Or maybe 2 if the old timer thread is slow to get added back to the pool.

**Comment by fkohlgrueber** [comment]
Hi @nunoplopes, thanks for taking care of the issue so quickly!

I'm afraid your fix introduces another race condition though. You changed the order in which the fields of the `scoped_timer_state` are written in the `scoped_timer` constructor. As soon as `work` is set to `WORKING` and the `workers` mutex is released by the main thread, the worker thread can get past `cv.wait` (line 54). The race condition is that both threads can read/write the other fields of the state object and if the worker thread accesses the data first, it will see data from the previous usage of the state. This could lead to the worker thread using a wrong timout value (because it's read `s->ms` before the main thread wrote to it) or not waiting at all (if it locks `s->m_mutex` before the main thread does). 

I haven't created a repro for this, but I'm pretty sure about the finding.

I have created a PR that fixes the issue, see #6102.

**Comment by nunoplopes** [comment]
How can the thread go past `cv.wait`? It needs to wait for the `cv.notify_one()` call, which is the last thing we do.

**Comment by fkohlgrueber** [comment]
There's two situations in which this could happen:

#### 1. Predicate is checked before wait is executed for the first time

According to the [cppreference](https://en.cppreference.com/w/cpp/thread/condition_variable/wait), `void wait( std::unique_lock<std::mutex>& lock, Predicate stop_waiting );` is equivalent to:

```cpp
while (!stop_waiting()) {
    wait(lock);
}
```

This means that the condition (`stop_waiting`) is checked before the thread waits for the first time. If the condition is true already, we'll skip the wait and immediately continue executing the rest of the function.

#### 2. Spurious wakeups

> The thread will be unblocked when [notify_all()](https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all) or [notify_one()](https://en.cppreference.com/w/cpp/thread/condition_variable/notify_one) is executed. **It may also be unblocked spuriously**.

The implementation must assume that there may be wakeups at any point in time, not only when `notify_*` was called.
