### ISSUE TITLE
Potential ABI breaking change?

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#6030]
I guess a bit too late but:

Commit https://github.com/Z3Prover/z3/commit/c9fa00aec1442464c9cc2ab6f3d2e5c749232b6e changed `z3_api.h` adding a new enum element `Z3_OP_RECURSIVE` to `Z3_decl_kind` without being the last element.
It was released in 4.8.16. Wouldn't that be an ABI breaking change, and thus imply that the next release should be 4.9.0?

It showed as a breaking change in our case when our release binary linked with z3 4.8.14 (using headers from 4.8.14) using the dynamic library of z3 4.8.16 (with 4.8.16 headers) receives an AST node from z3 as `Z3_OP_RECURSIVE` but it has no idea what that is. The other case is also problematic, if you link with the headers from 4.8.16 and run with 4.8.14, when z3 returns a `Z3_OP_RECURSIVE` you actually read it as `Z3_OP_UNINTERPRETED`.

**Comment by NikolajBjorner** [comment]
Note that internal replay always breaks when a new method is added to C headers.

**Comment by leonardoalt** [comment]
I'm not sure I understand, what do you mean by internal replay?

**Comment by ekpyron** [comment]
And isn't this a huge problem in general? Any linux distribution is perfectly within it's rights to *not* rebuild dependent packages, as long as the SO-version indicates ABI compatibility, so won't a change like this randomly break all kinds of things using Z3 everywhere :-)?

**Comment by nunoplopes** [comment]
Z3 releases have never been binary compatible.
Maybe Z3 could be better with increasing .so version numbers, but in the end this is a research project and has no full-time developer looking after it. Downstream distros have to be flexible.

**Comment by ekpyron** [comment]
So what I'm trying to say: There's two things you can do: Either at least *try* to be ABI compatible across patch versions (with downstream of course being aware that with z3 being a research project this may not *always* work out perfectly) - *or* you can say that there is no ABI compatibility across patch versions at all - but then you should change the SO versioning scheme, because the current one is very much crying out that things *are* ABI compatible across patch versions... (and will result in z3 libraries being installed in a way that will have dependent software pick up new patch releases without rebuild - that's what so versioning is for after all)

**Comment by NikolajBjorner** [comment]
I will be using 4.9, 4.10, etc going forward

**Comment by ekpyron** [comment]
Just some additional information on this:

In the context of an issue reported to us wrt dynamic loading of Z3 (https://github.com/ethereum/solidity/issues/13073, although the details there are not important here), I had a look at the Debian Z3 packages and realized that the Debian package maintainers apparently decided to actually patch the SOVERSION when building Z3, i.e. they apply this patch:

https://sources.debian.org/patches/z3/4.8.12-1/01-soname.patch/

On the other hand, other distributions like Fedora or Archlinux seem to stay with the SOVERSION you define in the repository... which is a bit unfortunate, since we now cannot rely on any particular SOVERSION schema across distributions :-).

I'm not quite sure why Debian decided to go for this patch, but my guess is that they are aware that Z3's so-versioning scheme in the past did not actually indicate binary compatibility and decided to replace it (I assume they'll bump the SOVERSION in their patch to ``5`` once they update to the next binary-incompatible version of Z3).

I'm not sure, whether it makes sense for you to consider this, but the optimal solution to the underlying problem of binary compatibility and so-versioning would be for you to decouple the regular Z3 versions from the SOVERSION:

It makes a lot of sense to stay with 4.8, as long as Z3 stays *API*-compatible, i.e. as long as rebuilding from sources is expected to keep working. Ideally, though, the ``SOVERSION`` defined in https://github.com/Z3Prover/z3/blob/7497856dedd21c185e94caaf11f68be0bd847ae9/src/CMakeLists.txt#L131 would be completely independent of the Z3 version and just be an integer that is increased whenever a Z3 release is no longer ABI-compatible with the previous version.

As far as I'm aware, this would be the canonical way to handle SOVERSIONs. For example, ``glibc-2.35`` has its SOVERSION set to ``6``, i.e. it installs as ``libc.so.6`` - an increase from version ``2.35`` to ``3.0`` would indicate *API*-incompatibility, while an increase of the SOVERSION from ``6`` to ``7`` would indicate *ABI*-incompatibility.

I'm just mentioning this, since this would be the nicest way for you to handle so-versioning while keeping your previous versioning scheme with respect to API-compatibility. But this would mean that you'd have to evaluate ABI-compatibility at each release and correctly bump the SOVERSION at any binary-incompatible change, and I'm not sure if that's feasible for you.

**Comment by NikolajBjorner** [comment]
4.9.1
