### ISSUE TITLE
Trivial queries fail in Horn Clause extension

### ISSUE THREAD

**Issue by agurfinkel** [Z3Prover/z3#604]
Z3 fails on the following input
```(query false)```
The output is 
```(error "line 1 column 8: invalid function declaration reference, unknown function false")```

It appears that the constants `false` and `true` are not recognized as functions.

**Comment by NikolajBjorner** [comment]
The format of queries is the following:

      (query <relation-name>)

where <relation-name> is the name of a relation that is registered as a relation. 
It used to be that the format was:

      (query <formula>)

but then the mechanism for associating values to free variables was not transparent.
By using the name of a relation, the mechanism for returning values to free variables amounts
to supplying values to the arguments of the relation-name.

Whenver you have an old style query, you can obtain a new style query by specifying 
a relation that mentions the free variables you are interested in and asserting the rule

    (rule (=> <formula> (<relation-name> v1 .. vn))

**Comment by agurfinkel** [comment]
Is there a way to fix the error message or to accept `true` and `false` as special cases? 
Currently the error message is confusing since `false` and `true` are known builtin functions.

**Comment by NikolajBjorner** [comment]
you should not send built-in functions to query.
There is actually a different bug now: if you specify

         (declare-const x Bool)
        (query true)

you don't get an error, but the wrong answer "unsat".
The engine does not check that these functions are illegal (they are assumed user-defined, when they are in fact built in).
The behavior with different errors is due to how ast manager gets initialized when invoking "query" without any other declarations.
