### ISSUE TITLE
cmake request: mention how to generate symbols

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#612]
@delcypher : The default for VS seems to not generate symbols. This impedes debugging ninja generated code.
It would help if the readme-cmakefile mentions how to configure builds with symbols.

**Comment by delcypher** [comment]
@NikolajBjorner Unfortunately I'm not in a position where I can contribute code/docs to Z3 at this time. I will be from mid August onwards.

However I'll try to help you out. What precisely do you mean by symbols here? If you mean debug symbols then you need to pick the right build type which is documented at

https://github.com/Z3Prover/z3/blob/master/README-CMake.md#build-types

You can see the default which is ``RelWithDebInfo`` which is set at

https://github.com/Z3Prover/z3/blob/master/CMakeLists.txt#L107

Note because this is a cache variable changing the value in the ``CMakeLists.txt`` file with have no effect if the value is already set in your cache. Instead you can change it by running ``ninja edit_cache`` (this will launch cmake-gui or ccmake or cmake to let you change options. Once you have changed options you will need to configure again).

The ``RelWithDebInfo`` build type is supposed to have debug information though. If you take a look at 

https://github.com/Z3Prover/z3/blob/master/contrib/cmake/cmake/compiler_flags_override.cmake#L30

you can see the flags that are passed to MSVC in that build mode. The ``/Zi`` flag is supposed to tell MSVC to generate debug information.

**Comment by NikolajBjorner** [comment]
Thank you!
