### ISSUE TITLE
Install Z3 through PyPy

### ISSUE THREAD

**Issue by computereasy** [Z3Prover/z3#617]
Hello, 

I am working a `python` project which largely utilizes `z3` for some symbolic execution tasks. Currently, the code runs quite slow for large test cases, and I am thinking to leverage `pypy` to speed up the codebase. 

However, I am not able to `import z3` when using the `pypy` interpreter. Even if I installed some `z3` package through `pip`. I did the following steps:

    python
    >> import z3
    >>

    sudo python -m pip install z3   <--- successfully installed
  
    pypy
    >> import z3
    ImportError: No module named z3

Could anyone sled some lights on how to import z3 when using PyPy, or, in general, how to speedup `z3 + Python` code? say, using `CPython`?

Sincerely,
Shuai

**Comment by delcypher** [comment]
@computereasy There isn't an official Z3 pip package so you're using someone else's work. In this case you should have checked what the ``z3`` package on PyPi actually is

https://pypi.python.org/pypi/z3/

it is **not** this Z3 it is something different.

**Comment by computereasy** [comment]
@delcypher thank you for your reply. I am talking about `pypy`, http://pypy.org/. Are we talking about the same thing..?

**Comment by computereasy** [comment]
@delcypher  Thank you for your reply. So basically, if I want to speedup `z3` by using `PyPy` (http://pypy.org/), what should I do here?

**Comment by delcypher** [comment]
The Z3 python module is just a think wrapper to Z3's C API so I don't think you're going to get much improvement there.

To get started I think you need to build Z3 from source or take pre-built binaries and just try using the Z3 python module with pypy. I'm not sure what pypy's current state is so I have no idea how well this will work.

Really though if you're having performance problems you need to identify where your bottlenecks are and then focus on improving those.

**Comment by NikolajBjorner** [comment]
Following up on the last sentence of the previous comment: Z3's python wrapper does a bunch of coercions, assertion checking and creates python objects. Each of these factor into performance overhead. You can get rid of some of the assertions by using python with debug assertions disabled, but before that, try to use the python profilers. 
Note however, that the python API is for rapid prototyping, but isn't optimal for creating large benchmarks because in the end it creates python objects for each intermediary term. This carries overhead that is a cost.
