### ISSUE TITLE
ASSERTION VIOLATION at src/ast/ast.cpp, Line: 3036: is_or(f1)

### ISSUE THREAD

**Issue by zhendongsu** [Z3Prover/z3#6320]
```
[528] % z3release small.smt2
unknown
[529] % z3debug small.smt2
ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 3036
is_or(f1)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[530] % cat small.smt2
(set-option :rewriter.expand_nested_stores true)
(set-option :proof true)
(declare-fun b ((Array Int (Array Int Real)) Int) Bool)
(declare-fun a () (Array Int (Array Int Real)))
(declare-fun c () (Array Int (Array Int Real)))
(declare-fun d () (Array Int (Array Int Real)))
(assert (forall ((e (Array Int (Array Int Real)))) (= (b e 0) (forall ((f Int) (g Int)) (= (select (select a f) g) (select (e g) 1))))))
(assert (b c 0))
(assert (= c (store a 0 (select d 0))))
(assert (= d (store d 1 (select c 2))))
(check-sat-using qflra)
```

**Comment by NikolajBjorner** [comment]
While there is a patch for this in, I don't think it makes sense to take fuzz bugs on proof objects at this point.
The discrepancy is due to introducing lambdas, but on the other hand, I can't point to consumers of proof objects that would suffer. Spacer uses proofs, but they are for arithmetic. It makes more sense for me to spend energy on proof traces in the new core where the design takes lessons from the legacy core. So, spending bandwidth on finding, filing and fixing fuzz-bugs like these seems not well motivated.
