### ISSUE TITLE
Parallel execution for z3 and Translate() api in Golang.

### ISSUE THREAD

**Issue by CHZofCSU** [Z3Prover/z3#6428]
I am struggling with the parallel execution for z3 in Go. Here is my situation.
There are 4 contexts for 4 Goroutines. A State Object( which has some Bitvecs and Bools in it) in a go's channel.
Each Goroutine will get a state object _S_ from channel, and use Translate() api to translate the _S_  into its own context first. Then this Goroutine will use its context to create a optimize to solve the constraints in _S_. At last, it will produce a new State and push it in go's channel, so the other goroutine can get this state.
My question is: when the number of state in channel is small, it works fine. However, when the number becomes large, it will crash and report a z3 report.
![2DF355C9-7877-4e89-BADB-D64F37DC6BE4](https://user-images.githubusercontent.com/44314918/198815580-5ed8cfb7-660e-4d53-bb90-766961602f82.png)

Is it thread-safe for Translate() api ? Can I use it in different Goroutines ? 
Hope for your reply. Many thanks!

**Comment by NikolajBjorner** [comment]
> Is it thread-safe for Translate() api?

You cannot call Translate in one thread while a different thread operates on either the source or destination of translate.
The use case should be that you create a new context, then translate a solver state into the new context (such cloning a solver from an old context into a new context using the appropriate API function that lets you clone solvers). Then after a solver is cloned you can operate on the cloned solver in its own thread.

I am not sure how you use z3 from GO. It isn't a binding available from github.com/z3prover. 
The root cause of your problem could be any of the following (1) your own code (2) the go bindings (3) inside of z3.
For option (3) you would benefit from mixed-mode debugging; you would be on your own though as it isn't practical to support debugging multi-threaded applications on my end.

**Comment by CHZofCSU** [comment]
> > Is it thread-safe for Translate() api?
> 
> You cannot call Translate in one thread while a different thread operates on either the source or destination of translate. The use case should be that you create a new context, then translate a solver state into the new context (such cloning a solver from an old context into a new context using the appropriate API function that lets you clone solvers). Then after a solver is cloned you can operate on the cloned solver in its own thread.
> 
> I am not sure how you use z3 from GO. It isn't a binding available from github.com/z3prover. The root cause of your problem could be any of the following (1) your own code (2) the go bindings (3) inside of z3. For option (3) you would benefit from mixed-mode debugging; you would be on your own though as it isn't practical to support debugging multi-threaded applications on my end.

Thanks for your reply. 
1) We wrote a Go binding of z3 using Cgo, which could call C function in Go Apps.
2) The root cause of my program is my own code. It uses Translate(source, target) while the source and target contexts may do something else simultaneously. And I solve the problem by creating extra context as a bridge between sourceCtx and targetCtx: translate(sourceCtx, newCtx)  -> translate(newCtx, targetCtx). It seems work fine. 
But I am wondering:
     _If I create too many contexts with the same one config obj, will z3 report a out-of-memory error?_ (I get this error sometimes).
     _Can I use ctx.Close() api or create another config obj to solve this problem?_

**Comment by NikolajBjorner** [comment]
> If I create too many contexts with the same one config obj, 

Yes, contexts add to memory pressure. They include some hash-tables that are initialized with some spare capacity. They are also initialized with some factories for creating terms. Each factory has some pre-initialized state.
So even if they have no assertions, there will be overhead.
