### ISSUE TITLE
[Spacer] Stuck on some input with several optimizers disabled

### ISSUE THREAD

**Issue by panda2134** [Z3Prover/z3#6432]
The input as well as the debug output is provided [here](https://gist.github.com/panda2134/d52b195e4a7ad16f5c0e0006d23123ef).

When running spacer on the given case, its output is:

```
(error "query failed: Stuck on a lemma")
unknown
```

Setting random seeds to different values cannot alleviate the problem. However, when I comment out line 3, everything works and spacer gives unsat.

**Comment by hgvk94** [comment]
The instance has a non-linear operation `(= A (* D C))`. While solving, Spacer cannot validate a proof step because of this non-linearity. 

The instance doesn't really involve non-linearity since inlining assigns values to `C` and `D`. In fact, after inlining, the instance is trivially unsat. 

If you really want to stick with this encoding, you can try turning interpolation off `(fp.spacer.use_iuc=false)` or go with a different solver `(fp.spacer.arith.solver=6`). Both of them are workarounds. You probably will hit problems if you are using non-linear operations.

**Comment by panda2134** [comment]
Thanks a lot for your comments! BTW, spacer seems to lack some documentation, so where can I look up the meanings of such options? Are they present in the API docs?

**Comment by NikolajBjorner** [comment]
https://microsoft.github.io/z3guide/programming/Parameters#fp
