### ISSUE TITLE
Official Rust Z3 binding?

### ISSUE THREAD

**Issue by arnursabet** [Z3Prover/z3#6463]
I am aware of the unofficial Rust Z3 binding, but it doesn't implement all the desired features and has some problems with how they use Rust's ownership system. In addition, it is fairly difficult to get it running on M1 macs. I was wondering if you are planning/working on an official Rust Z3 binding. I am confident that it would be in high demand in the Rust community. Thanks.

**Comment by waywardmonkeys** [comment]
(I maintain the Z3 bindings)

I would like to rewrite the high level bindings to be more like the TypeScript / JavaScript.

I have been busy for the last two months. I will look into the M1 issue of there is a reported bug.

Either way, the low level unsafe `z3-sys` bindings should be usable as well. They haven’t been updated to use newer features from z3 since we need to update how we build things since a lot of systems don’t have packages for current Z3.

**Comment by NikolajBjorner** [comment]
FWIW, the README.md does not contain a link to these Rust bindings.
