### ISSUE TITLE
`unknown` result because constant is not propagated using assumptions

### ISSUE THREAD

**Issue by thpani** [Z3Prover/z3#6499]
We're experiencing an issue where an equality constraint is not propagated when using assumptions, resulting in `unknown`.
However, the same constraint _without_ assumptions is propagated just fine, and it does not seem to be an issue with the incremental solver per se:

### MWE

**Case 1 (working)**: The following correctly reports `unsat`:
```smt
(declare-const exp Int)

(assert (= exp 1))
(assert (not (= 2 (^ 2 exp))))

(check-sat) ;; unsat
```

**Case 2 (broken)**: However, adding an assumption around `(= exp 1)` reports `unknown`:
```smt
(declare-const ass Bool)
(declare-const exp Int)

(assert (=> ass (= exp 1)))
(assert (not (= 2 (^ 2 exp))))

(check-sat ass) ;; unknown
```

**Case 3 (working)**: This does not seem to be an inherent issue with the incremental solver. The following version uses assumptions, but correctly reports `unsat`:

```smt
(declare-const ass Bool)
(declare-const exp Int)

(assert (= exp 1))
(assert (=> ass (not (= 2 (^ 2 exp)))))

(check-sat ass) ;; unsat
```

### Questions

Is there something preventing the equality constraint on `exp` from being propagated in Case 2?
Possibly some preprocessing is omitted?

**Comment by NikolajBjorner** [comment]
It requires pre-processing.
It is a long-standing issue to integrate good pre-processing with incrementality and assumptions. It is not well solved in the current version of z3. The newer core deals with incremental pre-processing in a systematic way, though you have to prepare assumptions in a different way.

```
(set-option :unsat_core true)
;(set-option :sat.smt true)
(declare-const exp Int)

(push)
(assert (! (= exp 1) :named ass))
(assert (not (= 2 (^ 2 exp))))

(check-sat) ;; unknown
(get-unsat-core)
```

The legacy core return unknown. 
If you enable sat.smt it uses incremental pre-processing which works with tracked assertions but not (yet) with assumption literals (which may be nice to do as well since the next N support calls would likely point this out).

**Comment by NikolajBjorner** [comment]
hope this answers the question for now

**Comment by thpani** [comment]
Thanks for the quick response @NikolajBjorner!

> incremental pre-processing which works with tracked assertions but not (yet) with assumption literals (which may be nice to do as well since the next N support calls would likely point this out).

Indeed, incremental pre-processing with assumption literals would be great for [Apalache](https://github.com/informalsystems/apalache).
If that makes it onto the roadmap, we'd definitely use them!
