### ISSUE TITLE
Z3 failed to runtests due to run test-z3.exe smt2print_parse under amd64 mode

### ISSUE THREAD

**Issue by nnfdnkns** [Z3Prover/z3#6537]
**Description:**
Z3 failed to runtests due to run test-z3.exe smt2print_parse under amd64 mode. It was fixed https://github.com/Z3Prover/z3/issues/6535 two days ago in x86 mode. But the same problem again in amd64 mode. could you please look this issue? Thanks.

**Reproduction steps:**
1. open VS2019 x64 tools command
2. git clone https://github.com/Z3Prover/z3 F:\gitP\Z3Prover\z3
3. cd F:\gitP\Z3Prover\z3 &mkdir build_amd64 &cd F:\gitP\Z3Prover\z3\build_amd64
4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 .. 2>&1
5. set CL=/D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS
6. msbuild /m /p:Platform=x64 /p:Configuration=Release Z3.sln /t:Rebuild /p:BuildInParallel=true 2>&1
7. msbuild /m /p:Platform=x64 /p:Configuration=Release .\examples\c_example.vcxproj /t:Rebuild /p:BuildInParallel=true 2>&1
8. msbuild /m /p:Platform=x64 /p:Configuration=Release .\examples\cpp_example.vcxproj /t:Rebuild /p:BuildInParallel=true 2>&1
9. .\Release\test-z3.exe smt2print_parse 2>&1

**Expected behavio:**
Runtests successfully.

**Actual behavior:**
[test.log](https://github.com/Z3Prover/z3/files/10407359/test.log)
[test.log.62.log](https://github.com/Z3Prover/z3/files/10419379/test.log.62.log)

spec:
(declare-datatypes (T) ((list (nil) (cons (car T) (cdr list)))))
(declare-const x Int)
(declare-const l (list Int))
(declare-fun f ((list Int)) Bool)
(assert (f (cons x l)))
done parsing
spec1: benchmark->string
; test
(set-info :status unknown)
(declare-datatypes ((list 1)) ((par (k!00)((nil) (cons (car k!00) (cdr (list k!00)))))))
(declare-fun f ((list Int)) Bool)
(declare-fun l () (list Int))
(declare-fun x () Int)
(assert
(let (($x8 (f (cons x l))))
(and $x8)))
(check-sat)

attempting to parse spec1...
parse successful, converting ast->string
spec2: string->ast->string
(ast-vector
(and (f (cons x l))))
done printing
spec:
(declare-const x Int)
(declare-const a (Array Int Int))
(declare-const b (Array (Array Int Int) Bool))
(assert (select b a))
(assert (= b ((as const (Array (Array Int Int) Bool)) true)))
(assert (= b (store b a true)))
(declare-const b1 (Array Bool Bool))
(declare-const b2 (Array Bool Bool))
(assert (= ((as const (Array Bool Bool)) false) ((_ map and) b1 b2)))

**Comment by NikolajBjorner** [comment]
Steps

```
msbuild /m /p:Platform=x64 /p:Configuration=Release .\examples\c_example.vcxproj /t:Rebuild /p:BuildInParallel=true 2>&1
msbuild /m /p:Platform=x64 /p:Configuration=Release .\examples\cpp_example.vcxproj /t:Rebuild /p:BuildInParallel=true 2>&1
```
are irrelevant and a waste of time.

Does it repro in debug mode for you?
Release builds with your flags don't produce symbols so I could pinpoint the issue with a debug build.

If you reproduce the error with debug (symbols) it may be more productive use of round-tripping.
Also given that your use case is compiler testing and not really using z3 it would be useful to get more of a helping hand than being filed bugs against.
I don't have vs2019 on my laptop either.

**Comment by NikolajBjorner** [comment]
This doesn't repro. 
Can you identify where the crash is with a stack.

Your [test.log](https://github.com/Z3Prover/z3/files/10407359/test.log) log looks suspicious:

```
##[command] Command #0 (Output in "test.log.0.out"):  set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
##[debug] Command #0 exited with code [0].
##[command] Command #1 (Output in "test.log.1.out"):  cd F:\gitP\Z3Prover\z3\build_x86
```

It refers to a different architecture than the build

**Comment by erozenfeld** [comment]
@NikolajBjorner This does repro with the steps in the description (as you mentioned, steps 7 and 8 are unnecessary). I repro-ed it with `-G "Visual Studio 17 2022"` instead of `-G "Visual Studio 16 2019"` in step 4.

The symptom is that the exception thrown by `throwError` is not caught by `test_eval` with this call stack (in RelWithDebInfo build):

 	test-z3.exe!throwError(_Z3_context * c, Z3_error_code e) Line 97	C++
 	test-z3.exe!api::context::invoke_error_handler(Z3_error_code c) Line 324	C++
 	test-z3.exe!api::context::set_error_code(Z3_error_code err, std::string && opt_msg) Line 202	C++
 	test-z3.exe!Z3_eval_smtlib2_string(_Z3_context * c, const char * str) Line 255	C++
	test-z3.exe!test_eval(_Z3_context * ctx, const char * spec, bool shouldFail) Line 74	C++
 	test-z3.exe!test_repeated_eval() Line 156	C++
 	test-z3.exe!main(int argc, char * * argv) Line 210	C++

The root cause is that `Z3_eval_smtlib2_string` is declared as `extern "C"` and the code is compiled with `\EHsc`. When `/EHsc` is specified, the compiler assumes that functions declared as `extern "C"` never throw a C++ exception: https://learn.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170 If that function does throw an exception, it's undefined behavior. So, in this test the exception is caught in Debug but is not caught in Release.

The fix is either to compile with `/EHs` instead of `/EHsc` or to change the code so that `Z3_eval_smtlib2_string` can't throw exceptions.

**Comment by NikolajBjorner** [comment]
thanks, updated per updated understanding.
