### ISSUE TITLE
Mixed sum of Boolean variables and constants in Python

### ISSUE THREAD

**Issue by IgnaceBleukx** [Z3Prover/z3#6598]
I am encountering the following issue:

```python
import z3
a = z3.Bool("a")
b = z3.Bool("b")
z3.Sum([a,3,b])
>> Z3Exception: True, False or Z3 Boolean expression expected. Received 0 of type <class 'int'>
```

It seems using a python integer in a sum of boolean variables is not allowed by the Z3 Python API.
As this does work when using integer variables, I was wondering if there are any plans to support such a summation for boolean variables as well?

**Comment by LeventErkok** [comment]
Try:

```python
Sum([a,IntVal(3),b])
```

while this'll work, it's almost always a bad idea to mix integers/booleans in this way, from a programming perspective. If you really have to do it, wrap it in `IntVal` to indicate this is intentional. I think z3 is rightly refusing to mix these: In fact, I wish it rejected all coercions between types; but that's a different story.

**Comment by NikolajBjorner** [comment]
allowing Booleans within arithmetic context is a shorthand for wrapping them with if-then-else. The Python API allows for some other liftings of constants to expressions. This is what you ran into. Use expressions or use explicit coercions.
