### ISSUE TITLE
The real bottleneck of solvers

### ISSUE THREAD

**Issue by verifierlife** [Z3Prover/z3#6636]
I am verifying a large scale software production in 64bit OS with 32G RAM, 3.39GHz and 3.40G Hz processors.  It is beyond the ability of the z3. When I try the experiment in 64bit OS with 128G RAM with the same processors. The solver is still out of memory. So, the conclusion comes out: the memory is not the bottleneck for a large scale software.
  Another question appears: what is the real bottleneck of the solver? If a machine provide 1T RAM, whether it can increase the ability of formal verification?

Thanks

**Comment by nunoplopes** [comment]
Z3 is solving a NP-hard problem (or worse), so it's normal it's slow. CPUs with more cache are usually faster, since the cache hit in SMT solvers is usually slow.
But the solution to speed things up and reduce memory consumption lies in the frontend that produces these constraints. You've to optimize that. Z3 isn't magical. If you are verifying a large-scale production system I'm sure you've verification experts to help you with the tunning of the verification tool.
