### ISSUE TITLE
Questions on simplification

### ISSUE THREAD

**Issue by duytai** [Z3Prover/z3#6694]
I recently am trying out z3-solver to simplify expressions and have some questions about it.
According to my understanding, function `simplify()` and two other tactics including `ctx-simplify` and `ctx-solver-simplify` can be used to simplify an expression (https://microsoft.github.io/z3guide/programming/Example%20Programs/Formula%20Simplification/)
For example, given e = `Or(x >= 3, x >= 5)` where `x` is Int.

- `simplify(e)` returns `Or(x >= 3, x >= 5)`
- `Tactic('ctx-simplify').apply(e)`  returns `Or(x >= 3, x >= 5)`
- `Tactic('ctx-solver-simplify').apply(e)`  returns `Or(x >= 3, x >= 5)`

Since my expected result is `x >= 3`, I have the following questions:
1. Are there any better built-in functions ?
2. If there is no better built-in function, how to achieve the result: x >= 3 ?

Thanks in advance !

**Comment by NikolajBjorner** [comment]
For what you want to do you should roll your own to reduce clauses.
For example, if your formula is a set of clauses C1, C2, ..., Cn, you can simplify each clause C_i by checking equivalence under the remaining clauses when removing a literal. 

```
result = set(clauses)
for C in clauses:
      result = result - { C }
      assert is_or(C)
      literals = set(C.children())
      for lit in C.children():
            if result Implies Or(literals) <=> Or(literals - { lit }):
                 literals -= { lit }
      result = Or(literals)
```

**Comment by Nic30** [comment]
@NikolajBjorner

Do you have any advice how to deal with the cases where  expression AST is a mix of `And/Or/Not/Xor` with compares at the leafs?

(I would like to avoid normalizing to dnf/nnf, because my expression is very large (1k+ terms).)
Currently I am using object similar to a Value Lattice from Correlated Value Propagation from LLVM. In that lattice there is a cell for every term which stores ranges where formula is satisfied. This works well for And as adding next term to such table is simple. However inversion of such table on every Or/Not is computationally expensive.

I was thinking that z3 can do something similar. Is there any library which can do this reasonably fast enough?
