### ISSUE TITLE
rlimit-count depends on machine characteristics

### ISSUE THREAD

**Issue by yannickmoy** [Z3Prover/z3#6736]
We have cases in our testsuite where the value of `rlimit-count` used by the same executable of z3 (Z3 version 4.11.2 - 64 bit) on two different machines are different on the exact same file attached:

[post.txt](https://github.com/Z3Prover/z3/files/11573650/post.txt)

```
z3 -smt2 -st post.smt2 
unsat
(:rlimit-count 7284)
```

or

```
z3 -smt2 -st post.smt2                  
unsat
(:rlimit-count 13110)
```

This is a problem for us because we run such tests in a mode where we rely on the value of `rlimit-count` to bound the prover effort. Could you indicate what could be the reasons for such variability? In particular, the two machines have the same version of glibc (Ubuntu GLIBC 2.31-0ubuntu9.9) but very different characteristics in terms of memory and cores (a laptop versus a powerful server).

Thanks for your help!

**Comment by NikolajBjorner** [comment]
Iterators over stl unordered sets with limit inc inside loops over such iterators.

Some tactics, but they do not get used in incremental mode.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: yannickmoy ***@***.***>
Sent: Friday, May 26, 2023 10:25:57 AM
To: Z3Prover/z3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Z3Prover/z3] rlimit-count depends on machine characteristics (Issue #6736)


We have cases in our testsuite where the value of rlimit-count used by the same executable of z3 (Z3 version 4.11.2 - 64 bit) on two different machines are different on the exact same file attached:

post.txt<https://github.com/Z3Prover/z3/files/11573650/post.txt>

z3 -smt2 -st post.smt2
unsat
(:rlimit-count 7284)


or

z3 -smt2 -st post.smt2
unsat
(:rlimit-count 13110)


This is a problem for us because we run such tests in a mode where we rely on the value of rlimit-count to bound the prover effort. Could you indicate what could be the reasons for such variability? In particular, the two machines have the same version of glibc (Ubuntu GLIBC 2.31-0ubuntu9.9) but very different characteristics in terms of memory and cores (a laptop versus a powerful server).

Thanks for your help!

**Comment by yannickmoy** [comment]
Thanks! Is it possible to use ordered sets instead in those cases?

**Comment by NikolajBjorner** [comment]
I didnt see the attachement before. I was almost going to ask for it.
Would be better to investigate what actually goes on. The use of unordered collections interfering with rlimit is hypothetical. 
What you can see when running your example with -v:10 is that it uses a tactic. These tactics have open-ended ways to influence rlimit. Better to compile on two platforms and delta-debug into where the first discrepancy can be found.

**Comment by NikolajBjorner** [comment]
The cause is that the pre-processor uses a memory limit when bailing out of hoisting ite-expressions. Some platforms support a malloc with access to allocated memory size, others do not. The size of allocated memory will differ between platforms, but not within one platform.

**Comment by kanigsson** [comment]
Hello Nikolaj, thanks for your answer. Could you please clarify what you mean by different platforms? Do you mean different hardware (e.g. available RAM)? In Yannick's case I believe the two system are very close from a software point of view, running the same binary on an Ubuntu 20.4 with the same glibc. The binary is static with the exception of libc and libm I think.

**Comment by NikolajBjorner** [comment]
I tested windows vs Ubuntu. Ran -v:10 and it shows a discrepancy during pre-processing for lifting ite-terms. Digging in, it throws an OOM exception in one version and not the other (the exception is handled and just cancels the effect of the tactic). 
The configurations for memory bounds are the same in the Windows/Ubuntu version, but the estimate of allocated memory is different. The root cause is then in code like this:

https://github.com/Z3Prover/z3/blob/621f1f8a850f8875b511e35a03b80634f041f4cc/src/util/memory_manager.cpp#L276

You could check on your side whether this is consistent with your two different linking versions. The library defines allocation sizes.

**Comment by yannickmoy** [comment]
I confirm that the two logs with `-v:10` are identical (modulo values of `before-memory` and `after-memory`) until the line `cofactor-term-ite`. You mean that `malloc_usable_size` may not return the same value for the same call to  `malloc`? I see no way to control that, let us know otherwise. And thanks for the explanations.

**Comment by nunoplopes** [comment]
It may be different, depending on the kernel + libc versions.

You can disable the usage of `malloc_usable_size` and use the alternative implementation. It's slightly slower, but works fine.

**Comment by kanigsson** [comment]
I think `malloc_usable_size` is not the issue here, as (1) the two machines are very similar and should have the same kernel and glibc (2) The bug report was for z3 4.11.2 which doesn't even have this code.
Could the cause be just a regular out-of-memory event? That for some reason, malloc signals OOM on one machine and not the other?

**Comment by kanigsson** [comment]
[machine2.txt](https://github.com/Z3Prover/z3/files/11609909/machine2.txt)
[machine1.txt](https://github.com/Z3Prover/z3/files/11609911/machine1.txt)

You are right of course. I have attached log files which are a bit different from Yannick's situation, that is "machine 2" is the same in both situations, but "machine 1" is my computer, while Yannick did his experiments on his own laptop. Nevertheless we were hoping to have the same rlimit on such machines.
To my untrained eye the first diffs are just some memory sizes (could be the cause as well of course), but these lines look interesting:
```diff
-set m_config.m_eqs_threshold 1840
-set m_config.m_expr_size_limit to 58
-set m_config.m_expr_degree_limit to 6
+set m_config.m_eqs_threshold 3450
+set m_config.m_expr_size_limit to 30
+set m_config.m_expr_degree_limit to 4
```
Do you think this is related?

**Comment by kanigsson** [comment]
My previous log was completely wrong, I used an older version of z3 on machine2. I updated my comment now. Sorry for the trouble.

**Comment by NikolajBjorner** [comment]
current master will still show divergent behavior.
You can manually change the code in memory_allocator as Nuno says to remove OS dependent allocation and/or add pull request with compile time directive for your builds to make it a build option.

**Comment by kanigsson** [comment]
Thanks again for looking into this.
