### ISSUE TITLE
API request: force close on context

### ISSUE THREAD

**Issue by cheshire** [Z3Prover/z3#679]
Hi,

As far as I understand, `Z3_del_context` does not really delete the context if some formulas still reference it.
Is it possible to have `Z3_force_del_context` or similar which would _really_ delete the context and all the associated data no matter what?

It would be really handy from Java, if the client does not want to keep track of the used formulas, yet wants to enforce the fact that once all contexts are closed, no more memory is occupied by Z3.

**Comment by wintersteiger** [comment]
Take a look at `Z3_reset_memory` and `Z3_finalize_memory`, would one of those do the job?

**Comment by cheshire** [comment]
@wintersteiger I would like to do it per-context.

**Comment by NikolajBjorner** [comment]
I believe there is some miss-understanding: del_context does in fact deallocate the context. 
Any dangling references are invalid. This is innocent for dangling AST objects where 
the memory gets reclaimed, but not too good for dangling solver and ast_vector 
objects whose memory is not reclaimed 
(given the current architecture, which your question raises a good point about).

The Z3_resest_memory/finalize_memory reclaim memory allocated to symbols and big-num rationals. This is across contexts and helps so that you can unload Z3 dlls without leaving allocated memory around.

**Comment by cheshire** [comment]
I think as we have figured out in #245 closing the context does not free the memory for AST objects which were not explicitly closed.
Is it possible to have a function which would actually "force-kill" all such objects?

**Comment by NikolajBjorner** [comment]
It's possible, but more than a few lines: we would need to track all objects (Solver, Tactic, Goal, Ast-vectors, Optimize,) besides ASTs in a region owned by the context such that it can delete them on del_context. Then at the Java/.NET level have the dec-ref ooperations be no-ops after del_context is invoked.

**Comment by NikolajBjorner** [comment]
here you go.

**Comment by NikolajBjorner** [comment]
> I think as we have figured out in #245 closing the context does not free the memory for AST objects which were not explicitly closed.

Not quite: AST pointers are allocated in a special region. The region goes away when ~ast_manager() gets invoked. This is invoked when calling del_context.

**Comment by NikolajBjorner** [comment]
@arifogel, it is very possible that these recent changes make a difference for your setup.

**Comment by NikolajBjorner** [comment]
@Cheshire, let us know if this can be closed. Enjoy CAV/Toronto.

**Comment by cheshire** [comment]
@NikolajBjorner Actually I do not know, apparently there are performance issues when closing solvers.  @PhilippWendler ?
