### ISSUE TITLE
Inconsistent results of horn encodings

### ISSUE THREAD

**Issue by jx5c** [Z3Prover/z3#6821]
Hi, 

I try to reproduce some results from a research [paper](https://arxiv.org/pdf/2304.12588.pdf) on verifying relational properties with CHC encodings.  I have developed three slightly different files (attached zip) containing the same CHC encodings for the problem I try to verify (which is shown as comments at the bottom of the files). The files are different in how two functions `init()` and `Tr()` are defined syntactically, using either `declare-fun` or `define-fun`. _z3_ gives different results for the files: 

1. `horntestunsat.smt2`: it uses `define-fun` for the two functions, and _z3_  produces `unsat` result; 
2. `horntestsat.smt2`: it is identical to `horntestunsat.smt2`, except for a syntactic error: it uses `declare-fun` instead of `define-fun` in defining the two functions. But _z3_ gives a `sat` result and a model (after reporting syntactic errors). The model looks **valid** to me. And I believe the CHC encoding should be satisfiable. 
3. `horntestunknown.smt2`: it uses `declare-fun` first and then assertions to describe the functions, and _z3_  produces `unknown` result; 

How did I get the different results because of the different ways of definitions? I am not very family with z3, so any insights could be useful. Thanks a lot!  (z3 version: 4.12.3)

[horntest.zip](https://github.com/Z3Prover/z3/files/12101677/horntest.zip)

**Comment by yvizel** [comment]
Hello,

This is simply a misuse of the SMT2 format.
In the second example, you are using "declare-fun" but you also give an interpretation/definition of the function, so Z3 complains about the name of the variable not being a sort.
It of course continues to solve with "unknown constants" now, and the problem is SAT which is obvious because there is a trivial solution (the unknown constants are given "false", this makes the constraint false, which makes the CHC trivial). Z3 should probably behave differently because the returned model does not give any indication about the unknown constants being false.

For the third example, you give an input that is not really horn and verbosity shows an error that a recursive predicates occurs nested in the body of a rule.
I changed that file a bit, to be somewhat what you meant (transformed the definition of init into a fact, and explicitly define TR), Spacer runs on this modified file, but crashes at some point and returns unknown. This is something we should debug to understand why Spacer fails.

I hope this helps.

**Comment by jx5c** [comment]
That helps a lot! Thank you so much!

**Comment by yvizel** [comment]
If you have more questions about the paper - let us know.
