### ISSUE TITLE
dotnet API: "Unable to find an entry point named 'Z3_enable_concurrent_dec_ref'"

### ISSUE THREAD

**Issue by ndreuu** [Z3Prover/z3#6825]
I got the "Unable to find an entry point named 'Z3_enable_concurrent_dec_ref'" when tried to update Z3 to `4.12.2` from `4.11.2` version from nuget, also I tried to use nupkg from [release `4.12.2`](https://github.com/Z3Prover/z3/releases/tag/z3-4.12.2), but got same problem.

Ubuntu 22.04.2 LTS

**Comment by NikolajBjorner** [comment]
most likely your path environment causes linking with stale libraries/headers

**Comment by m-carrasco** [comment]
Hi,

I'm experiencing the same issue on Ubuntu 22.04 LTS, and Z3 4.12.2. I inspected the Nuget package, and the native libraries for Linux are not shipped. This has been happening since 4.12.0.

https://nuget.info/packages/Microsoft.Z3/4.12.2 -> `runtimes/linux-x64` is missing
https://nuget.info/packages/Microsoft.Z3/4.11.2 -> `runtimes/linux-x64` is present

Best,
Manuel
