### ISSUE TITLE
Refutational Soundness issue on QF_SLIA

### ISSUE THREAD

**Issue by fwangdo** [Z3Prover/z3#6855]
Greetings,
For this instance, a refutational soundness bug occurred. Also, we checked that this instance should be "SAT". We truly hope that this instance will be helpful for the z3 team.
```
$ ./z3 ./test.smt2
unsat

$ /solvers/z3-4.11.0/build/z3 ./test.smt2 model_validate=true
sat

$ cat ./test.smt2
(set-logic QF_SLIA)
(declare-fun x () String)
(declare-fun y () String)
(declare-fun z () Int)
(assert (not (distinct (re.comp re.all) (re.range "e" "x"))))
(check-sat)
(exit)
```
commit version: [b04e48f](https://github.com/Z3Prover/z3/commit/b04e48f374e1e8b1bba3fef5f2a13c4bf2f25f53)

**Comment by NikolajBjorner** [comment]
why should this instance be SAT?
It simplifies to
assert (= re.empty (re.range "e" "x"))
which is false.

The bug is in 4.11. Model validate is a self-validator. It doesn't help if it either skips validating some formulas (with quantifiers etc) or uses the same rewriting engine with the unsoundness bug.

**Comment by fwangdo** [comment]
@NikolajBjorner  Thanks for your answer. I was confused as well however, I reported this instance just because it was "SAT" under model_validate. Now that I saw your explanation, I can understand it's not a bug. Thanks again!
