### ISSUE TITLE
How to turn off generating ".z3-trace" file

### ISSUE THREAD

**Issue by foreverkenan** [Z3Prover/z3#6919]
![image](https://github.com/Z3Prover/z3/assets/41415508/fa855e1f-344e-4773-9231-ba006107a578)

    z3::config cfg;
    cfg.set("TRACE", false);
    z3::context c(cfg);
    z3::solver s(c);

I tried many methods but they didn't work(.z3-trace file still generated)

**Comment by NikolajBjorner** [comment]
You must be using a debug build where debug tracing is enabled. Release builds don't create trace files.
The "TRACE" configuration controls a different style of logging. It is not related to .z3-trace files.

**Comment by Naville** [comment]
> You must be using a debug build where debug tracing is enabled. Release builds don't create trace files. The "TRACE" configuration controls a different style of logging. It is not related to .z3-trace files.

Sorry for necromancing, from my understanding is that https://github.com/Z3Prover/z3/blob/6ecc7a2dd44df1c575d436d6c2e1bf8ae794d96f/src/util/trace.cpp#L43 always implicitly creates .z3-trace due to it's static global variable that's constructed with a filename.

I suspect a better way would be default construct ``tout``, and then ``open_trace`` and ``close_trace``  explicitly.

@NikolajBjorner

**Comment by NikolajBjorner** [comment]
yes, it always creates .z3-trace, but only for builds that are debug or for builds where tracing is enabled as a non-default build option.
So, this is a feature of non-release builds.
It therefore does not affect end-users. 
It can affect developers who create their own debug builds. 
If you are a developer and you create your own debug builds and you don't want .z3-trace you can modify the source code.
