### ISSUE TITLE
Segmentation fault when testing smt2 on linux

### ISSUE THREAD

**Issue by zhoum929** [Z3Prover/z3#6942]
Hello,

Thank you making the library open sourse.

We met some trouble when running two tests of smt2 on linux terminal with command "z3 -smt2 neos-799716.smt2" and "z3 -smt2 mod011.smt2". 

Both give "Segmentation fault (core dumped)".

Attached please find the two files of smt2.

It would be helpful if you can help us understand what kind of error this is.
[tests.zip](https://github.com/Z3Prover/z3/files/12886510/tests.zip)

Thanks again.

**Comment by NikolajBjorner** [comment]
Thanks for sharing the instances. Z3 runs out of memory: it isn't built for solving large MIP problems nor does it handle Gauss-Jordan elimination in any tuned way. Use a MIP solver. Your encoding is also better tailored for MIP as the 0-1 variables are reified within the inequalities instead of used to encode clauses.
