### ISSUE TITLE
Q: Enum sort numerals

### ISSUE THREAD

**Issue by wintersteiger** [Z3Prover/z3#7001]
We've seen a change in behaviour while trying to upgrade to a more recent version of Z3. I bisected it down to https://github.com/Z3Prover/z3/commit/b7169e2a41121a979072d3f17075b2f0604e30ba which changed `is_numeral_ext` to return true for enum-sort constructors, here: https://github.com/Z3Prover/z3/blob/1b6c7d65412fafa36a8c3a5fe0c8e195c1708c15/src/ast/dl_decl_plugin.cpp#L747

Is it intentional that this is considered a numeral, even if the user did not explicitly ask for an enum sort (but "accidentally" created one with 0-field constructors)?

**Comment by NikolajBjorner** [comment]
This change was made for aligning internal behavior for the datalog engine. The external behavior seems affected because the function for checking whether an AST is a numeral then returns true for an enumeration sort, but the function for retrieving the numeric value will fail. I have updated the API behavior.

**Comment by wintersteiger** [comment]
Awesome, many thanks!
