### ISSUE TITLE
Missing BitVec support in QF_FP

### ISSUE THREAD

**Issue by Heizmann** [Z3Prover/z3#709]
On the [attached script](https://github.com/Z3Prover/z3/files/405805/FP-bitvector-bug.smt2.txt) I get

    (error "line 2 column 21: unknown sort 'BitVec'")

However, [according to SMT-LIB](http://smtlib.cs.uiowa.edu/theories-FloatingPoint.shtml) all (_ BitVec m) sorts are implicitly supported by the FloatingPoint theory.

I am just reporting this issue for the sake of completeness. It is absolutely not important for us, in practise we always use QF_BVFP (because bitvector operations are *not* implicitly supported by the FloatingPoint theory).

**Comment by wintersteiger** [comment]
This is debatable and I lean toward the side of this being in line with the intention of the SMT theory. The theory definition itself requires BV sorts because FP literals are constructed from BV literals, but nothing else is imported into FP from the BV theory, i.e., sorts are there, but you can't use them in any functions. 

For full support of both theories we should specify (QF_)*BVFP and I think that's what most people would expect.
