### ISSUE TITLE
Negation bug in datalog

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#717]
In this program:

    (set-option :fixedpoint.engine datalog)
    (set-option :fixedpoint.xform.inline_eager false)
    (declare-rel r0 ())
    (declare-rel r1 ())
    (declare-rel r2 ())

    (rule (=> (not r0) r1))
    (rule (=> r1 r2))

    (query r0 :print-answer true)
    (query r1 :print-answer true)
    (query r2 :print-answer true)

z3 returns unsat, sat, unsat.  According to my mental model of how this should work, the answer for r0 and r1 are correct and r2 is thus a bug.

**Comment by NikolajBjorner** [comment]
@nunoplopes, could you check? It seems this is the Bottom-up dataflow engine. 
Just comment out the first two queries.

**Comment by nunoplopes** [comment]
Well, Datalog semantics go bottom-up, starting with facts.  The first rule "(=> (not r0) r1)" shouldn't even produce anything since the rule has no facts to start from.  Right now it sometimes works as a convenience I added to the Datalog compiler, but I wouldn't rely on that.

From a quick check, it seems it's the COI filter that is removing the rules, and it seems like the right behavior per se.
If we restrict ourselves to Datalog, then we were supposed to get unsat for all the queries.
@NikolajBjorner what do you think?

**Comment by NikolajBjorner** [comment]
@nunoplopes. 

There are no rules for r0, so r0 is false. 
Therefore r1 is true because of the rule r1 :- not r0. 
Therefore r2 is true because of the rule r2 :- r1.

**Comment by nunoplopes** [comment]
Ok. Just discussed semantics with @andrey-rybalchenko and we agree with that result.

**Comment by seanmcl** [comment]
@nunoplopes You agree with Nikolaj or with the result of the current implementation?

**Comment by nunoplopes** [comment]
with Nikolaj.

**Comment by NikolajBjorner** [comment]
As an added bonus, after my check-ins, the current implementation agrees with me, Nuno, Andrey, and Sean.
