### ISSUE TITLE
Add SA_ONSTACK flag to SIGINT signal handlers (required for CGO)

### ISSUE THREAD

**Issue by tiborschneider** [Z3Prover/z3#7305]
When including z3 from golang, we noticed that z3 registers `SIGINT` handlers without setting the `SA_ONSTACK` flag. This is required for CGO: https://pkg.go.dev/os/signal#hdr-Go_programs_that_use_cgo_or_SWIG. 

There seems to be lots of places in the code base where signal handlers are used. Fortunately, most are in `src/shell`, `src/api`, and `src/test`, all of which are not used in `z3.h`. The only file that would need changes is `src/util/scoped_ctrl_c.cpp`. Are there any plans to flag use `sigaction` with `SA_ONSTACK` instead of `signal` in that file?

**Comment by NikolajBjorner** [comment]
sounds like updating to using sigaction instead of signal is the way to go.
z3.h uses src/api, which depends on scoped_ctrl. This is to allow killing console applications built on top of z3's API.

**Comment by NikolajBjorner** [comment]
The issue is a good test case for github workspaces. Trying it out. I am not totally sure about whether the change preserves semantics, and it may be better to replace signal everywhere by sigaction. ctrl-c is used also from the shell.

**Comment by nunoplopes** [comment]
Is this a real problem or just theoretical?
Because the linked page from Go says that programs have limited stack. Which is fine.. Z3's signal handlers don't do much. The ctr-C one just terminates the program or sets some terminating flag. The amount of stack usage is minimal.

I suggest that unless there is proof that something doesn't work, we don't try to fix a problem that doesn't exist. These things are super tricky to get right..
