### ISSUE TITLE
WASM bindings are broken

### ISSUE THREAD

**Issue by NikolajBjorner** [Z3Prover/z3#7399]
Z3 now uses c++20. #7379
However, there is something amiss for more than a month now. The continuous build/test of WASM bindings is broken.
@pelikhan and I can confirm it remains broken when setting it up over codespaces (following the steps in the README.md and then running npm test).
Some observations:

- emsdk uses node 18, the current default is 20. Switching to node 18 mode doesn't seem to matter.
- it runs out of memory. 
- Commenting out the unit test (number 17) does not change the memory issue, it just runs out of memory later.
- Adding an early return before number 17 causes an exception.
- Adding console.log to calls like

```
    constructor(ptr: Z3_solver | string = Z3.mk_solver(contextPtr)) {
        this.ctx = ctx;
        let myPtr: Z3_solver;
        if (typeof ptr === 'string') {
          myPtr = check(Z3.mk_solver_for_logic(contextPtr, _toSymbol(ptr)));
        } else {
          myPtr = ptr;
        }
        this.ptr = myPtr;
        console.log("create solver");
        Z3.solver_inc_ref(contextPtr, myPtr);
        cleanup.register(this, () => { console.log("dec-ref-solver"); Z3.solver_dec_ref(contextPtr, myPtr);});
      }
```
suggests that the cleanup actions are never run.
I can see that cleanup is an instance of FinalizationRegistry, that is connected to GC. 

- Should the gc be forced? Global.gc, std.global.gc, std.gc?

@bakkot

**Comment by bakkot** [comment]
I can confirm the build worked at 3e518b9e8b387f1bb664a619e0aec45f4b62dfba and fails at bf34600f08d732680f7a9b3d85a257caf435418b. In fact it fails even when asking for 2GB rather than 1GB on [this line](https://github.com/Z3Prover/z3/blob/82eb18674b446f3a90992fc57cbb690ccd4cfa08/src/api/js/scripts/build-wasm.ts#L72).

I notice a new warning when building at the later commit, not present on the former:

```
../src/nlsat/nlsat_solver.cpp:2840:23: warning: binding reference member 'm_lit_num' to stack allocated parameter 'ln' [-Wdangling-field]
 2840 |             m_lit_num(ln) {
      |                       ^~
../src/nlsat/nlsat_solver.cpp:2837:31: note: reference member declared here
 2837 |             unsigned_vector & m_lit_num;
      |                               ^
```
Because emscripten has to do a lot of work to translate from C++'s arbitrary memory accesses to WASM's more restrained model, my best guess is that this is causing it to mess up its memory handling somehow.

I am too rusty with C++ to be able to immediately fix that warning, but maybe that would do it?

**Comment by NikolajBjorner** [comment]
Thanks. The warning was a bug, it was fixed. That bug is likely orthogonal.
So basically track down memory hogs / undo some changes from https://github.com/Z3Prover/z3/commit/bf34600f08d732680f7a9b3d85a257caf435418b

@levnach - you looked at this before: just changing build parameters seems not to address any root cause. 
The regression could be related to nlsat based on commit history.
