### ISSUE TITLE
Sat unknown for simple problem

### ISSUE THREAD

**Issue by ramsdell** [Z3Prover/z3#814]
I'm not sure this is a bug, but here is an example where z3 returns sat unknown for a simple problem.
----------- graph-color.smt2 -----------
;; Spec: 2-color a graph with no sinks
;; Dan Dougherty WPI 2016-11
(declare-sort A 0)
(declare-fun E (A A) Bool)
(declare-fun red (A) Bool)
(declare-fun green (A) Bool)

;; color the nodes
(assert (forall ( (x A) )
                (=  (red x) (not (green x)))))
(assert (forall ( (x A) (y A) )
                (=> (E x y) (red x) (not (red y)))))
(assert (forall ( (x A) (y A) )
                (=> (E x y) (green x) (not (green y)))))

;; no sinks
(assert (forall ((x A))
                (exists ((y A)) (E x y))))

(check-sat)
(get-info :version)
-----------
$ z3 graph-color.smt2
unknown
(:version "4.5.1")
$

**Comment by NikolajBjorner** [comment]
Sorry, the problem is easier solved if you tell Z3 it should look for a small finite domain solution.

(declare-datatypes () ((A x y z)))
(declare-fun E (A A) Bool)
(declare-fun red (A) Bool)
(declare-fun green (A) Bool)
;; color the nodes
(assert (forall ( (x A) )
(= (red x) (not (green x)))))
(assert (forall ( (x A) (y A) )
(=> (E x y) (red x) (not (red y)))))
(assert (forall ( (x A) (y A) )
(=> (E x y) (green x) (not (green y)))))
;; no sinks
(assert (forall ((x A))
(exists ((y A)) (E x y))))
(check-sat)
(get-model)

**Comment by ramsdell** [comment]
Right.  There is an even simpler two element solution too.  The question is why can't Z3 find it without resorting to enumerated types.

**Comment by NikolajBjorner** [comment]
It would be that the model-based projection implementation isn't complete for finite models. 
That is, a formula main have a finite model, but Z3 would not find it.
This is not really a bug, as quantifier reasoning is inherently undecidable.
