### ISSUE TITLE
Floating-point query doesn't terminate

### ISSUE THREAD

**Issue by ddcc** [Z3Prover/z3#834]
The following floating-point query doesn't terminate, after leaving it running for ~16 hrs.
```
(set-logic QF_FP)
(declare-const $0 (_ FloatingPoint 11 53))
(define-fun f ((x!1 (_ FloatingPoint 11 53)) (x!2 (_ FloatingPoint 11 53))) (_ FloatingPoint 11 53) (fp.add roundNearestTiesToEven
                   (fp.mul roundNearestTiesToEven x!1 x!1)
                   (fp.neg (fp.mul roundNearestTiesToEven x!2 x!2))))
(assert (not (fp.isNaN (f $0 (fp.add roundNearestTiesToEven $0 (_ +zero 11 53))))))
(assert (not (fp.leq (_ +zero 11 53) (f $0 (fp.add roundNearestTiesToEven $0 (_ +zero 11 53))))))
(check-sat)
(get-model)
```

**Comment by ddcc** [comment]
I retried with the latest changes (4c664f1c05786a479e016ffac0d0c6a2e00ab64d) since last night, and the behavior still seems be unchanged (at least, after running for 5 mins).

**Comment by wintersteiger** [comment]
This is converted to bit-vectors and then bit-blasted into SAT and the SAT solver then finds the resulting formula hard to solve. There will likely not be a quick/easy fix for this. 

Generally, `fp.mul` over otherwise unconstrained variables will frequently be hard to solve (over double precision numbers this produces 128-bit bit-vector multipliers plus a couple of adders).

**Comment by wintersteiger** [comment]
Closing this issue as there is no fix in the pipeline and the general issue of floating-point operations causing large and complex (sub-)problems is understood.
