### ISSUE TITLE
Z3 doesn't report the errors using `stderr`

### ISSUE THREAD

**Issue by asr** [Z3Prover/z3#859]
In my Ubuntu machine, given the following wrong program

```smt2
(declare-fun B⇒ () Bool)
```

running

```
$ z3 test.smt2 2> errors.txt
```

doesn't report the errors in the `errors.txt` file but in `stdin`. Is it the expected behaviour?

I'm using

```
$ z3 --version
Z3 version 4.5.0 - 64 bit
```

(Partially) blocking https://github.com/asr/apia/issues/64.

**Comment by wintersteiger** [comment]
The fact that no error is reported on stderr is fully expected; see [SMT Standard 2.5](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.5-r2015-06-28.pdf) section 3.9.1: "Regular output, **including error messages**, is printed on the **regular output** channel."

I can't tell whether your "B=>" contains special (unicode?) characters, but 

    (declare-fun B=> () Bool)

does not produce any errors, because `B=>` is indeed a legal function name; see same document, section 3.1: "A symbol ... letter and digit and ... = ... >".

**Comment by asr** [comment]
Thanks!

> I can't tell whether your "B=>" contains special (unicode?) characters,

Yes, it has a Unicode character.

**Comment by wintersteiger** [comment]
In that case I'm not sure whether the SMT standard makes any suggestions as to how to handle those characters/files, but Z3 should report an "unexpected character" (on stdout).

**Comment by asr** [comment]
> but Z3 should report an "unexpected character" (on stdout).

Yes, Z3 reports

```
$ z3 test.smt2 
(error "line 1 column 15: unexpected character")
(error "line 1 column 16: unexpected character")
(error "line 1 column 17: unexpected character")
```
