### ISSUE TITLE
Performance difference using assertion stack

### ISSUE THREAD

**Issue by seanmcl** [Z3Prover/z3#862]
The following program runs for at least 10s before I kill it:

    (declare-const v1 String)
    (declare-const v2 String)
    (declare-const v3 String)
    (declare-const v3_v4 String)
    (declare-const v3_v5 String)
    (assert (= v3 (str.++ v3_v4 ":" v3_v5)))
    (declare-const p1.0.v3 bool)
    (assert (= p1.0.v3 (or (str.prefixof "foo:" v3))))
    (declare-const p1.0.v10 bool)
    (declare-const p1.0.v1 bool)
    (assert (= p1.0.v1 true))
    (declare-const p1.0.v2 bool)
    (assert (= p1.0.v2 true))
    (declare-const p1.0.v6.v7 bool)
    (declare-const p1.0.v6.v8 bool)
    (assert (= p1.0.v6.v7 (and p1.0.v3 p1.0.v10 p1.0.v1 p1.0.v2)))
    (declare-const p1.1.v3 bool)
    (assert (= p1.1.v3 (not (or (str.prefixof "foo:bar" v3)))))
    (declare-const p1.1.v10 bool)
    (assert (= p1.1.v10 true))
    (declare-const p1.1.v1 bool)
    (assert (= p1.1.v1 true))
    (declare-const p1.1.v2 bool)
    (assert (= p1.1.v2 true))
    (declare-const p1.1.v6.v7 bool)
    (declare-const p1.1.v6.v8 bool)
    (assert (= p1.1.v6.v7 (and p1.1.v3 p1.1.v10 p1.1.v1 p1.1.v2)))
    (declare-const p1.v7 bool)
    (declare-const p1.v8 bool)
    (declare-const p1.v9 bool)
    (assert (= p1.v7 (or p1.0.v6.v7 p1.1.v6.v7)))
    (assert (= p1.v8 (or p1.0.v6.v8 p1.1.v6.v8)))
    (assert (= p1.v9 (and (not p1.v7) (not p1.v8))))

    (push)
    (assert p1.v9)
    (check-sat)
    (pop)
        

When I remove the `push` and `pop` z3 returns immediately with `sat`.

**Comment by wintersteiger** [comment]
I'm afraid this is half expected. As the problem is different, the order in which Z3 explores the search space is different, and in this case it looks like it's simply unlucky. For instance, adding `smt.random_seed=1` also makes it solve the problem instantaneously (for seeds 1 to 5, but not 0 and 6). 

(We may be able to improve that situation, but it will be some time until I'll have time to look at it.)
