### ISSUE TITLE
Sort mismatch at argument #1 for function "or" during solverCheck

### ISSUE THREAD

**Issue by PhilippWendler** [Z3Prover/z3#863]
I get the error
```
Sort mismatch at argument #1 for function (declare-fun or (Bool Bool) Bool) supplied sort is Int
```
during a call to `Native.solverCheck` from the Java API.

I checked my code and I could not find a place where I used an `Int` as argument to `or`. I also serialized the solver instance at the point where the error occurs and looked at the formula and could not see an erroneous use of `or`. So it seems this might be a bug in Z3 maybe?

Giving the string from the serialized solver to Z3 does not produce an error. The replay log however reproduces the `sort mismatch` error.

I have an [archive](http://students.fim.uni-passau.de/~wendler/z3-sort-mismatch.tar.bz2) that contains both the replay log as well as the serialized solver in SMTLIB2 format.

I saw the other two issues mentioning `sort mismatch`, but as my situation seems to be a little bit different, I opened another issue. Apologies if it is a duplicate.

**Comment by ntu-juking** [comment]
您好，
    您的来信我已收到，我将在稍晚的时候阅读您的来信。

----
Best Regards
Xiaolin JU
==========================================
School of Computer Science and Technology
Nantong University
==========================================
No.9 Seyuan Road,
Nantong,JiangSu Province, 226019
P.R.China

**Comment by wintersteiger** [comment]
The log file triggers the assertion at `ast.cpp:2934: SASSERT(is_or(f1));`. It looks like it tries to resolve one fact with itself (we have `f1 == f2)` at that point). This is related to #864, which crashes during conflict resolution because of the polarity of one of the literals being wrong. However, we need a new log file after the changes introduced for #864, because they introduced new API functions. @PhilippWendler could you extract a new one with the latest master?

Also, there is a problem with the `.smt2` log file; the .log file contains many calls to `Z3_solver_check` (`C 419`) while the .smt2 file contains only one `(check-sat)`. The variables that are involved in the bogus resolution are `|stopRequestedInDirection::__cil_tmp8@11|` and `|stopRequestedInDirection::__cil_tmp7@11|`, neither of which appear in the .smt2 file.

**Comment by PhilippWendler** [comment]
Yes, I will attempt to create a new replay log with current master.

The reason why the `.smt2` has less sat checks is because it it is not a log of the queries, but instead I just called `solverToString` on the solver instance directly after the problem. I have no idea why it has less variables though.

I do not know how to create an SMTLIB2 compliant log file of the queries with Z3. If you tell me how to do this with Z3 I would be glad to provide one (in fact, I would love to have such a feature, all other SMT solvers I use also have it).

**Comment by wintersteiger** [comment]
In many applications incremental SMT2 files are produced and then fed to the solver, so they are also easy to share. Does any other solver have a way to dump SMT2 files from an incremental use of their API (instead of SMT2 files)?

**Comment by PhilippWendler** [comment]
I tried to reproduce this problem with current master revision of Z3 on several of the test cases where it previously failed and could not reproduce it. So perhaps it has been solved by the same fix as #864. I will run the complete test suite in the next days and report back.

For the SMT2 log file I have opened another issue (#867).

**Comment by wintersteiger** [comment]
Fantastic, thanks a lot for testing this! I'll close this issue then, if anything else comes up we can re-open it.

**Comment by NikolajBjorner** [comment]
I also tested the old log on a locally fixed version. It also passes.
