### ISSUE TITLE
SMT Tactic slowness

### ISSUE THREAD

**Issue by dwoos** [Z3Prover/z3#914]
The tactic system seems to have pretty significant overhead. On average on a large set of benchmarks, using `(check-sat-using smt)` seems to be about twice as slow as using `(check-sat)`. I've attached ([z3-tactic-slowness.zip](https://github.com/Z3Prover/z3/files/800732/z3-tactic-slowness.zip)) a particularly egregious example. On my machine, the tactic version takes around 30s, while the version without tactic calls takes about 1s. I'm not sure how representative this is, since it might be the result of a specific bug rather than general slowness, but hopefully it's helpful. Please let me know if I can provide any other information.

**Comment by NikolajBjorner** [comment]
It seems that when running with different random seeds we get different running times.
z3 /st smt.random_seed=1 bug-tactic.smt2 finishes very quickly, but with the default smt.random_seed=0 it is slow. Similar for bug.smt2 the random seed influences running time. 

So it could mainly be an artifact of flickleness: sometimes Z3 gets trapped.

A workaround is to put your spare cores to use:

       (check-sat-using (par-or smt (with smt :smt.random_seed 1) (with smt :smt.random_seed 2)))

**Comment by NikolajBjorner** [comment]
Doug, can we close this?

**Comment by wintersteiger** [comment]
The [default tactic](https://github.com/Z3Prover/z3/blob/master/src/tactic/portfolio/default_tactic.cpp) (which is what you get via `(check-sat)`) first runs the simplifier (`simplify` tactic) and then tries to figure out which logic your benchmarks and then runs a tactic for that logic. If it doesn't find anything suitable, it will run the `smt` tactic. 

That means `(check-sat)` should (I think) in your case be the same as `(check-sat-using (then simplify smt))`, but it isn't. This is due to the `(push 1)` command, which is handled differently when using `check-sat-using` and possibly also due to bugs causing some parameters not passed on correctly through the tactic framework (we fixed a bunch, but I'm sure some are still in there).
