### ISSUE TITLE
Unexpected unsat when modifying constraint.

### ISSUE THREAD

**Issue by franco-maroni** [Z3Prover/z3#920]
Running Z3 on the big formula included in file
[smt_input_sat.txt](https://github.com/Z3Prover/z3/files/804521/smt_input_sat.txt), I observed a suspect behavior related to a specific variable and set of constraints.
Highlighted below are some constraints that are included in the end of [smt_input_sat.txt](https://github.com/Z3Prover/z3/files/804521/smt_input_sat.txt)
 and refer to variable **r_emit_urlcrawldeciderbolt**:

```lisp
(assert (<= (r_emit_urlcrawldeciderbolt 0) (zot-a887 0)))
(assert (<= (r_emit_urlcrawldeciderbolt 1) (zot-a887 1)))
(assert (<= (r_emit_urlcrawldeciderbolt 2) (zot-a887 2)))
(assert (<= (r_emit_urlcrawldeciderbolt 3) (zot-a887 3)))
(assert (<= (r_emit_urlcrawldeciderbolt 4) (zot-a887 4)))
(assert (<= (r_emit_urlcrawldeciderbolt 5) 1.0))
(assert (<= (r_emit_urlcrawldeciderbolt 6) (zot-a887 6)))
(assert (<= (r_emit_urlcrawldeciderbolt 7) (zot-a887 7)))
(assert (<= (r_emit_urlcrawldeciderbolt 8) (zot-a887 8)))
(assert (<= (r_emit_urlcrawldeciderbolt 9) (zot-a887 9)))
```
Z3 solves the formula, and the model returned ([output.1.txt](https://github.com/Z3Prover/z3/files/804312/output.1.txt)) has the following assignments for **r_emit_urlcrawldeciderbolt**:

```lisp
(define-fun r_emit_urlcrawldeciderbolt ((x!1 Int)) Int
    (ite (= x!1 0) 0
    (ite (= x!1 1) 0
    (ite (= x!1 2) 0
    (ite (= x!1 3) 1
    (ite (= x!1 4) 0
    (ite (= x!1 5) 0
    (ite (= x!1 6) 0
    (ite (= x!1 7) 1
    (ite (= x!1 8) 0
    (ite (= x!1 9) 24
      0)))))))))))
```
 
You can observe that the value of the function **r_emit_urlcrawldeciderbolt**  when **x!1=5** is **0** (which is OK with respect to `(assert (<= (r_emit_urlcrawldeciderbolt 5) 1.0))` ).
Now, if the big formula is modified just by constraining **r_emit_urlcrawldeciderbolt** to be less than or equal to 0 (as in the returned model), the result is **unsat** (full input file is [smt_input_unsat.txt](https://github.com/Z3Prover/z3/files/804314/smt_input_unsat.txt)).

```lisp
(assert (<= (r_emit_urlcrawldeciderbolt 0) (zot-a887 0)))
(assert (<= (r_emit_urlcrawldeciderbolt 1) (zot-a887 1)))
(assert (<= (r_emit_urlcrawldeciderbolt 2) (zot-a887 2)))
(assert (<= (r_emit_urlcrawldeciderbolt 3) (zot-a887 3)))
(assert (<= (r_emit_urlcrawldeciderbolt 4) (zot-a887 4)))
(assert (<= (r_emit_urlcrawldeciderbolt 5) 0.0)) 
(assert (<= (r_emit_urlcrawldeciderbolt 6) (zot-a887 6)))
(assert (<= (r_emit_urlcrawldeciderbolt 7) (zot-a887 7)))
(assert (<= (r_emit_urlcrawldeciderbolt 8) (zot-a887 8)))
(assert (<= (r_emit_urlcrawldeciderbolt 9) (zot-a887 9)))
```

I am not able to explain why the modified constraint leads to an unsat result, so I am wondering if this can be an issue of Z3.

Thanks in advance for your helpfulness.

**Comment by wintersteiger** [comment]
I just downloaded the two input files and it seems they are the same and Z3 tells me it's unsat. Could you update the files/links?

**Comment by wintersteiger** [comment]
Also `(repeat bit-blast)` in the custom tactic seems unnecessary. Do you have a use-case where bit-blasting multiple times is necessary?

**Comment by franco-maroni** [comment]
You are right, I uploaded the same file twice. Just updated it.
Thanks

**Comment by franco-maroni** [comment]
Regarding `(repeat bit-blast)`, let me forward this question to @mmpourhashem.

>Also  `(repeat bit-blast)` in the custom tactic seems unnecessary. Do you have a use-case where bit-blasting multiple times is necessary?

**Comment by mmpourhashem** [comment]
@franco-maroni 
Both models contain many invalid constraints and since Z3 is not SMT 2.0 compliant by default you, don't see the error messages.

If you add `(set-option :smtlib2-compliant true)` as the first line to any of your models you will get `(error "line 2815 column 55: Sort mismatch at argument #2 for function (declare-fun <= (Int Int) Bool) supplied sort is Real")`.
The reason is that you are comparing Int with Real. E.g you have
`(assert (<= (r_emit_urlcrawldeciderbolt 0) (zot-a887 0)))` while Z3 expects to see
`(assert (<= (to_real (r_emit_urlcrawldeciderbolt 0)) (zot-a887 0)))`.

Solution:
If you are extending my tool, add the proper casting wherever required. Note that you need to take care of constants as well. E.g. `(> realVar1 0)` must be `(> realVar1 0.0)`; otherwise, use the latest version.

@wintersteiger 
I remember repeating bit-blast (until not sub-goal is modified) was saving few seconds for some models (that I don't find now). Since it wasn't very expensive to repeat, I didn't rule it out from my configuration.

**Comment by franco-maroni** [comment]
thanks @mmpourhashem for pointing out the problem with casting.
We investigated more deeply and we found that the source of the issue lied in the starting model and in our procedure to automatically generate the formulae.
So nothing that concerns Z3.
