### ISSUE TITLE
Quantifier no longer instantiated if conjunct is added

### ISSUE THREAD

**Issue by mschwerhoff** [Z3Prover/z3#935]
The following program is expected to be yield `unsat`, and does. However, uncommenting the additional conjunct in the quantifier AX-1 changes the result to `unknown`.

```
(set-option :auto_config false)
(set-option :smt.mbqi false)

(declare-fun foo (Int) Bool)
(declare-const k Real)
(declare-fun p (Int) Bool)

(assert (forall ((i Int)) (!
  (and
    (< 0.0 k)
;    (p i) ;;; ---- uncomment this line ----
  )
  :pattern ((foo i))
  :qid |AX-1|)))

(assert (forall ((i Int)) (!
  (foo i)
  :pattern ((foo i))
  :qid |AX-2|)))

(declare-const j Int)
(assert (< j 0))

; (push) ;;; doesn't make a difference
(assert (not
  (ite
    (foo j)
    (< 0.0 k)
    false)))

; (set-option :smt.qi.profile true)
(check-sat)
; (get-info :all-statistics)
; (pop)
```

The quantifier instantiation statistics show that `AX-2` is instantiated in both cases, but `AX-1` is only instantiated if the additional conjunct is not included. My assumption is that in the latter case, Z3 eliminates the quantifier since the quantified variable doesn't occur in the body.

However, I find it surprising that the version with the additional conjunct - in which Z3 presumably doesn't eliminate the quantifier - yields unknown, since the trigger for the quantifier (`(foo j)`) should be available.

**Comment by wintersteiger** [comment]
Yes, this is a known problem (known by me anyways). It's similar to the problem you submitted to StackOverflow some time ago. Ultimately, it comes down to heuristics: It gets the crucial instances, but it does so _after_ making a decision and when it backtracks that decision, it also backtracks those instances without re-generating them. If you change some of the heuristic settings (e.g. smt.case_split, smt.phase_selection, smt.relevancy), some of them will make it give up and others won't. This is on my desk, but so are a thousand other things, so sorry, no ETA at the moment!

**Comment by mschwerhoff** [comment]
Original Stackoverflow question: http://stackoverflow.com/questions/39835199

**Comment by NikolajBjorner** [comment]
The bug is related to relevancy propagation. Z3 misses retaining relevancy of a unit literal that is learned from conflict analysis. This unit literal happens to be a pattern and then the quantifier guarded by that patter is not instantiated after backtracking. If it were instantiated Z3 would conclude unsat. 
The fix (above) attempts to address this bug by recording relevant literals prior to backjumping and then ensuring that those literals remain relevant after backjumping.

The scenario that this example exercises is in more detail as follows:

Initially, Z3 treats (foo j) as non-relevant in the following formula (which is compiled to the clause
(or (not (< 0 k)) (not (foo j)))

(assert (not
  (ite
    (foo j)
    (< 0.0 k)
    false)))

It then performs case split on (< 0 k). It assigns it to true. (actually, it converts (< 0 k) to (not (<= k 0)) and assigns (<= k 0) to false), so unit propagation sets (foo j) to true and it is marked as relevant.
This triggers quantifier instantiation with AX-2 and a backjump is forced. We learn (foo j), but the previous code did not remember to ensure that (foo j) should remain relevant. Without relevancy marked on (foo j) AX-1 would not be instantiated.

The bug is of course masked if we turn off relevancy propagation. The commit above addresses the forgotten relevancy of (foo j).

**Comment by wintersteiger** [comment]
Sweet! Thanks for fixing that so quickly, @NikolajBjorner !

**Comment by mschwerhoff** [comment]
I just built and tested the latest version and the example now works as expected. Thank you very much for the quick fix, @NikolajBjorner!
