### ISSUE TITLE
Timeout in z3::optimize

### ISSUE THREAD

**Issue by marcelwa** [Z3Prover/z3#974]
Hi at all,
I'm currently facing difficulties using C++'s z3::optimize. It seems that it does not support the "timeout" parameter of z3::params. I found a comment on stackoverflow about this topic [here](https://stackoverflow.com/questions/38674049/z3-timeout-for-optimize-in-c). It is suggested there to call `Z3_global_param_set("timeout", t);` where `t` is a CString. I invoke the function before creating my context and optimize. Nonetheless it seems to have no impact at all.

What am I missing? There must be an easy way to set a timeout. Any help is appreciated. A running example would be very helpful.

Thank you so much in advance!

**Comment by NikolajBjorner** [comment]
Your report indicates several usability issues.

By default, the C++ API may not flag errors as it used to. 
Since the change: 

        #if !defined(Z3_THROW)
        #if __cpp_exceptions || _CPPUNWIND
        #define Z3_THROW(x) throw x
        #else
        #define Z3_THROW(x) {}
        #endif
        #endif // !defined(Z3_THROW)

got in, it is likely that your application isn't detecting errors.
You should compile with _CPPUNWIND defined.
In this case, the following example will throw when adding timeout or rlimit to the optimization object:

     #include "z3++.h"

     using namespace z3;

     void main() {
        context ctx;
        optimize opt(ctx);
        params p(ctx);
        try {

            p.set("timeout", (unsigned)1ul);
            //        p.set("rlimit", (unsigned)2000);
            opt.set(p);
            opt.from_file("testfile.smt2");
            std::cout << opt.check() << "\n";
            std::cout << opt.statistics() << "\n";
        }
        catch (exception& e) {
           std::cout << e << "\n";
        }
     }

Optimization objects don't own "timeout" or "rlimit" attributes. They can be set on the context.
This is somewhat asymmetric to other objects, so I have added these two parameters to optimization objects.
With the change, the code will also throw an exception, except this time it will report that the check was cancelled.

**Comment by NikolajBjorner** [comment]
The issue should be addressed with the commit https://github.com/Z3Prover/z3/commit/e4b9080165dce794561f26d4008fd9c9a0eb9bde
