### ISSUE TITLE
Interpreting optimization objective

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#985]
For the following input (admittedly, the input is rather silly; but it comes from a much bigger example where such constraints do arise naturally):

```
(declare-fun x () Int)
(maximize x)
(maximize (+ x 1))
(check-sat)
```

z3 is producing:

```
sat
(objectives
 (x oo)
 ((+ x 1)  ((* (- 1) oo) oo))
)
```

I'm curious as to how to interpret the value of the second objective:

```
((* (- 1) oo) oo)
```

which seems to be type-incorrect: It's applying `-oo` to `oo`? In any case, shouldn't we simply get `oo` for the value of that objective as well?

**Comment by NikolajBjorner** [comment]
It produces the interval of the best lower and upper bound for the objective it could determine. In this case the interval goes from minus infinity to plus infinity. 
Perhaps the format of the output isn't intuitive to parse because it looks like a normal expression, but then one can't apply the value -oo to +oo. I could produce the textual output that says (interval (* -1 oo) oo), where "interval" is some hypothetical function.

**Comment by LeventErkok** [comment]
Thanks Nikolaj. Indeed, application of `interval` would make this a lot easier to use by up-stream tools, if you could put that in.

However, I'm still confused as to why z3 is giving the bound `-oo` to `oo` on the second objective. Since it already determined `x` to be maximized at `oo`, shouldn't the lexicographic optimizer make the second objective `oo` as well?

**Comment by NikolajBjorner** [comment]
Commit https://github.com/Z3Prover/z3/commit/a048d74bae705b38c9155cf9758b606704f00942 adds an interval designator

**Comment by LeventErkok** [comment]
Thanks! I already used the `interval` desginator and it works as advertised.

My question about the bounds on `x+1` remains, but perhaps the correct interpretation of intervals is "correct but not necessarily tight?"

**Comment by NikolajBjorner** [comment]
The background with x+1 is as follows. The lexicographic ordering is a don't care after the first unbounded objective. It simply stops evaluating any coordinate after the first unbounded objective. The remaining objectives have no lower/upper bounds calculated and becomes open intervals.

**Comment by LeventErkok** [comment]
I find that counterintuitive, especially if we have two completely independent objectives: 

```
(set-option :produce-models true)
(declare-fun x () Int)
(declare-fun y () Int)
(assert (< x 4))
(assert (< y 4))
(minimize x)
(maximize y)
(check-sat)
```

I indeed get:

```
sat
(objectives
 (x (* (- 1) oo))
 (y  (interval (* (- 1) oo) oo))
)
```

But `y` has a perfectly good optimal value of `3`, which I think would fit the definition of lexicographic.  Is there a reason why you stop after the first unbounded objective? Perhaps I don't understand what lexicographic means in this context.

**Comment by NikolajBjorner** [comment]
suppose I disable the code that bails out on unbounded objectives during lex, then I get funny answers because later objectives could recycle some of the same values. Take for instance:

    (set-option :produce-models true)
    (declare-fun x () Int)
    (declare-fun y () Int)
    (assert (< x 4))
    (assert (< y 4))
    (minimize x)
    (maximize y)
    (maximize x)
    (check-sat)

With the modified lex I get:
    sat
    (objectives
     (x  (interval (* (- 1) oo) (- 2)))
     (y 3)
     (x (- 2))
   )

Now, the value of x got set to -2 because this maximized the third objective. But it acted contrary to the first objective which is the lexicographically most significant. You could argue that it is wrong to skip the part that constrains the first objective in case it is unbounded. It should be "infinitely small" no matter what. So what does it mean to add this constraint? In one sense it means "whatever value x has it should not be a finite number". But this means that any assignment to x is infeasible, e.g., assert false.
So this behavior could be argued as even more counter-intuitive.

**Comment by LeventErkok** [comment]
According to https://en.wikipedia.org/wiki/Multi-objective_optimization#A_priori_methods it appears that the strategy is to solve for the first, then assert the results of the first objective, and continue with the next. But I guess that's easier said than done when you have `x = oo`. I suspect the underlying engine cannot do that as an assertion since `oo` is not a well-defined value in the domain? (Same comment, of course, applies for `epsilon`.)

**Comment by NikolajBjorner** [comment]
Right.
Epsilon tends to be easier because it is going to correspond to strict inequalities.
Having x = oo could be done in an extension field. The equality is false within the standard numeral fields. There is a version of the arithmetic solver for an extension field that admits infinities. It was used for box objectives, but I would rather not depend on it.

I suggest that a tool could repose queries for objectives after the first unbounded objective.

**Comment by LeventErkok** [comment]
I think that is a good compromise: Quite often it's not the value of the metric that I care about, but rather all the other variables in it anyhow. It seems if the objective value is not bounded, then I cannot query Z3 for reasonable values of the variables appearing in it anyhow. Is that correct?

**Comment by NikolajBjorner** [comment]
It is a compromise, we don't expose control over the extension fields and even then there would be questions of what that really means for lexicographic products. (say you maximize x and then 2*x and x is unbounded, should the result be oo, 2*oo or should it be 17*oo, 34*oo?).

The get-value is free to print 0: it prints whatever is determined by the latest model. The latest model happens to assign x to 0. The optimization component tells you that x is unbounded. It does not convey a particular value in this case

**Comment by LeventErkok** [comment]
Thanks Nikolaj. This discussion is very helpful to me. I'm going to close this ticket as I don't think any actionable item is left to do on it, but feel free to reopen if you think otherwise.
